README.md
```
updated readme to reflect acs-engine transition
```
=> updated readme to reflect acs-engine transition

packer/cleanup-vhd.sh, packer/feature-flagged.sh, packer/init-variables.sh, packer/install-dependencies.sh, pkg/engine/testdata/rename.sh, pkg/helpers/Get-AzureConstants.py, scripts/azure-const.sh, scripts/build-windows-k8s.sh, scripts/convert-lcg-lcl.sh, scripts/devenv.sh, scripts/update-enus-po.sh, scripts/update-translation.sh, scripts/validate-dependencies.sh, scripts/validate-generated.sh, test/cluster-tests/kubernetes/k8s-utils.sh, test/cluster-tests/kubernetes/test.sh, test/cluster-tests/utils.sh, test/common.sh, test/deploy.sh, test/e2e.sh, test/e2e/cleanup.sh, test/shunit/deploy_template.sh, test/shunit/generate_template.sh, test/shunit/scale_agent_pool.sh, test/shunit/validate_deployment.sh, test/step.sh
Extends #23 to add headers to shell scripts and the lone Python file in the repository.
(Also gives me a simple PR with which to ensure our CircleCI setup is working.)
**Which issue this PR fixes**:
Refs #12
```release-note
Add copyright header to source code that isn't Go
```
=> Add copyright header to source code that isn't Go

test/e2e/engine/template.go
**What this PR does / why we need it**: once I got rid of the nil dereference I got the actual error!
```
E2E: eliminate possible nil dereference
```
=> E2E: eliminate possible nil dereference

pkg/operations/deletevm.go
**What this PR does / why we need it**: Bringing this PR over here:
https://github.com/Azure/acs-engine/pull/4258
```
*string needs nil guard
```
=> *string needs nil guard

test/e2e/kubernetes/kubernetes_test.go
**What this PR does / why we need it**: When we run E2E tests immediately after a scale operation, the node could might still be converging towards the goal state, so we want to be able to tolerate that temporary inconsistency.
```
E2E: retry node count test
```
=> E2E: retry node count test

.circleci/config.yml, Makefile, makedev.ps1
See https://golang.org/doc/devel/release.html#go1.11.minor
and https://github.com/deis/docker-go-dev/releases/tag/v1.17.3
```release-note
Update go-dev tools image for go 1.11.2
```
=> Update go-dev tools image for go 1.11.2

parts/k8s/health-monitor.sh
**What this PR does / why we need it**: If you define a bash function omitting the `function` keyword, you need `()`
```
bash needs params for function definition
```
=> docker-health monitor doesn't work

docs/kubernetes/gpu.md, pkg/engine/params_k8s_test.go
**What this PR does / why we need it**: remove docs for docker-engine feature flag as it was removed.
```release-note
```
=> [docs] Remove docker-engine feature flag docs

cmd/scale.go, test/e2e/kubernetes/kubernetes_test.go
**What this PR does / why we need it**: The current `aks-engine scale` implementation does not persist changes to the apimodel.json in scale down scenarios. This change fixes that.
```
E2E: node count check is flaky after scale
```
=> scale: persist scale down in api model

packer/install-dependencies.sh, pkg/api/common/versions.go, pkg/api/k8s_versions.go
See https://github.com/kubernetes/kubernetes/releases/tag/v1.12.3
TODO:
```release-note
Add support for Kubernetes 1.12.3
```
=> Add support for Kubernetes 1.12.3

parts/k8s/containeraddons/ip-masq-agent.yaml
Fixing a bug when the YAML is rendered improperly. This can be reproduced when a user supplies a ClusterSubnet
=> Fix issues in ip-masq yaml render

pkg/api/apiloader.go, pkg/api/apiloader_test.go, pkg/api/convertertoapi.go, pkg/api/convertertoapi_test.go
**What this PR does / why we need it**: Carried over from here:
https://github.com/Azure/acs-engine/pull/4346
```
[BUG] orchestratorVersion should not get changed for ACS scale apiVersion 2017-07-01
```
=> [BUG] orchestratorVersion should not get changed for ACS scale apiVersion 2017-07-01

test/e2e/kubernetes/kubernetes_test.go
**What this PR does / why we need it**: Adds a simple `kubectl top nodes` check as a simple `metrics-server/heapster` validation.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #76
```
kubectl top nodes for metrics-server validation
```
=> kubectl top nodes for metrics-server validation

pkg/api/agentPoolOnlyApi/v20180331/doc.go, pkg/api/agentPoolOnlyApi/vlabs/doc.go, pkg/api/doc.go, pkg/api/v20160330/doc.go, pkg/api/v20160930/doc.go, pkg/api/v20170701/doc.go, pkg/api/v20170930/doc.go, pkg/api/vlabs/doc.go, pkg/operations/dcosupgrade/doc.go, pkg/operations/kubernetesupgrade/doc.go
Some legacy code remains in aks-engine to support the ACS service. Marking these packages as [deprecated](https://rakyll.org/deprecated/) clarifies their role and hopefully helps contributors avoid making changes to those files.
**Which issue this PR fixes**:
Fixes #93
```release-note
Add some Go package deprecation notices
```
=> Add some Go package deprecation notices

pkg/api/types.go
Adds a 'Scaling' constant to track a provisioning state where nodes are being scaled up or down. Matches a local modification expected by AKS.
```release-note
Add "Scaling" constant to provisioning states
```
=> Add "Scaling" constant to provisioning states

packer/install-dependencies.sh, pkg/api/common/versions.go, pkg/api/k8s_versions.go
See https://github.com/kubernetes/kubernetes/releases/tag/v1.13.0
Refs #73 and kubernetes/kubernetes#71736
fixes #140
TODO:
```release-note
Add support for Kubernetes 1.13.0
```
=> Add support for Kubernetes 1.13.1

examples/networkpolicy/README.md, examples/networkpolicy/kubernetes-calico-azure.json, examples/networkpolicy/kubernetes-calico-kubenet.json
updates documentation around how to configure Calico policy on the acs-engine deploy
=> update Calico network policy examples docs

parts/k8s/containeraddons/1.6/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/1.7/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/1.8/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesparams.t, pkg/api/addons.go, pkg/api/const.go, pkg/api/defaults_test.go, pkg/engine/artifacts.go, pkg/engine/const.go, pkg/engine/engine.go, pkg/engine/params_k8s.go, test/e2e/kubernetes/kubernetes_test.go
Fixes #126 
This PR does two things
Disable Heapster for k8s clusters with version 1.13.0 or greater. As per this document , https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md
Remove sed statements to apply heapster configurations and use the new addon pre-render flow instead.
=> disable heapster for kubernetes versions > 1.13

packer/install-dependencies.sh
VHD image didn't get bumped from k8s 1.13.0 to 1.13.1.
```release-note
Add 1.13.1 to VHD image
```
=> Add 1.13.1 to VHD image

pkg/api/defaults-kubelet.go
It fixes default value for non-masquerade-cidr for kubelet. 
According to https://github.com/kubernetes-incubator/ip-masq-agent#configuring-the-agent CIDR 0.0.0.0/0 should be used, not 0.0.0.0
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/Azure/acs-engine/issues/4353
Moved from https://github.com/Azure/acs-engine/pull/4356
```release-note
```
=> Fix default value for kublet's non-masquerade-cidr

docs/kubernetes/windows.md, examples/windows/kubernetes.json
AKS-Engine v0.27.0 deploys Windows Server 2019 by default, but the docs still reference 1803. This fixes it so the example will match the cluster created. It also clarifies what OS & K8s versions will be deployed at the top of the doc.
=> Docs: Update version strings and make examples match Windows version

docs/kubernetes/features.md, examples/kubernetes-config/kubernetes-keyvault-encryption.json, packer/install-dependencies.sh, parts/k8s/artifacts/kubernetesazurekms.service, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/types.go, pkg/api/vlabs/types.go, pkg/engine/params_k8s.go
=> Add HSM support for kms encryption

parts/k8s/kubernetesagentcustomdata.yml, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/types.go, pkg/engine/template_generator.go
Add toggle for switching ip-masq-agent logic for AKS. This way, the AKS-engine code can be checked in first. Later when AKS turn on the toggle, it should activate this feature.
=> Add toggle for switching ip-masq-agent logic for AKS.

pkg/api/defaults-kubelet_test.go
This PR is needed because of the CircleCI Master test failing.
How did this happen? : #154 changed`defaults_kubelet.go`.  So after merging #129 (which should have been ideally rebased. My bad), this test case failure was noticed.
Lesson learned: Rebase PRs even if GH doesn't explicitly ask you to .
=> Fix Failing Unit test

pkg/api/const.go, pkg/api/types.go, pkg/engine/artifacts.go
=> do not parse azure-cni monitor manifests if addon is disabled in the apimodel

test/e2e/config/config.go, test/e2e/config/config_test.go
**What this PR does / why we need it**: This canary-ish region has more trouble than other ones, let's stop using it in the blessed default list.
```
stop defaulting to westcentralus as a regional option for E2E
```
=> stop defaulting to westcentralus as a regional option for E2E

packer/install-dependencies.sh, pkg/api/k8s_versions.go
Bumps the cluster-autoscaler component version to the appropriate release for k8s 1.13.1.
See https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases for details of how cluster-autoscaler is released now.
```release-note
Update version of cluster-autoscaler for k8s 1.13.1
```
=> Update version of cluster-autoscaler for k8s 1.13.1

packer/install-dependencies.sh, pkg/api/common/versions.go, pkg/api/k8s_versions.go, test/e2e/kubernetes/kubernetes_test.go
See https://github.com/kubernetes/kubernetes/releases/tag/v1.12.4
Refs #73.
TODO:
```release-note
Add support for Kubernetes 1.12.4
```
=> Add support for Kubernetes 1.12.4

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Includes the following additions pre-baked into the image:
- Kubernetes v1.13.1
- Kubernetes v1.12.4
- Kubernetes v1.11.6
- cluster-autoscaler 1.13.1, 1.12.1
- microsoft/k8s-azure-kms v0.0.7
```
use latest VHD image: k8s 1.11.6, 1.12.4, 1.13.1
```
=> use latest VHD image: k8s 1.11.6, 1.12.4, 1.13.1

parts/k8s/kubernetesmasterresources.t
All network ARM resources must use `apiVersionNetwork`
=> using the correct apiVersion Private Cluster NICs

parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes.yaml, parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml
The default value `None` would lead to slow perf. And according to below doc: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching
default host cache should be `ReadOnly`, the reason why we use “cachingMode: None” by default in k8s is that there is a critical disk bug due to this cachingMode setting(`ReadOnly` & `ReadWrite`) which would lead to disk i/o error, and this issue has been fixed in the middle of this year by azure disk team. 
For more details, refer to …
=> change azure disk cachingMode to ReadOnly

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Enable AKS VHD images in mooncake cloud
```
enable AKS VHD images in mooncake
```
=> enable AKS VHD images in mooncake

pkg/helpers/pki.go
for more details about the issue please take a look at this:
https://medium.com/@cep21/gos-append-is-not-always-thread-safe-a3034db7975
=> fix: protect the slice for append operation in multi-thread scenario

pkg/operations/kubernetesupgrade/upgrader.go
**What this PR does / why we need it**: This change is aks-engine only, does not affect AKS (reviewer to validate).
Our 99th percentile 3 node cluster measurement is tracking at 13 mins, so 10 min timeout is probably too low in the real world.
```
increase vm upgrade timeout to 20 mins
```
=> fix: increase vm upgrade timeout to 20 mins

packer/install-dependencies.sh, parts/k8s/artifacts/kubernetesazurekms.service, parts/k8s/kubernetesagentresourcesvmas.t, parts/k8s/kubernetesagentresourcesvmss.t, parts/k8s/kubernetesbase.t, parts/k8s/kubernetesmasterresources.t, parts/k8s/kubernetesmasterresourcesvmss.t, parts/k8s/kubernetesmastervars.t, parts/k8s/kuberneteswinagentresourcesvmas.t, parts/k8s/kuberneteswinagentresourcesvmss.t
- Remove MSI Extension since it will be deprecated in Jan 2019 and it is not available in sovereign clouds
- Create separate apiVersionAuthorization to support both user assigned and system assigned identity for clouds that do not have the latest apis: `apiVersionAuthorizationUser` and `apiVersionAuthorizationSystem`
- Add VMs to dependsOn for each role assignment if it's system assigned identity
- Bump version of kms plugin to support instance metadata service identity endpoint 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #175
```release-note
Update MSI to remove …
```
=> fix: update MSI

docs/kubernetes.md
The issue described has been mitigated here:
https://github.com/kubernetes/kubernetes/pull/63492
**Notes**:
=> docs: remove obsolete "known issue"

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
Increases the tolerance for pod startup thrashing (i.e., ratio of Ready/NotReady count) during cluster startup in kube-system namespace. Also standardizes wait retry to 1 second for quicker reconciliation.
This intends to eliminate some E2E flakiness around kube-system pod readiness checks. E.g.:
```
"Pods from deployment (kube-addon-manager) in namespace (kube-system) have been checked out as all Ready 2 times, but NotReady 3 times. This behavior may mean it is in a crashloop"
```
By increasing the Ready count requirement to 6, we also tolerate more NotReady counts. See this code snippet for how this is currently implemented:
https://github.com/Azure/aks-engine/blob/bc250139f3f08ce7e63e42691c68282535bae216/test/e2e/kubernetes/pod/pod.go#L457 …
=> test: more tolerance for kube-system pod startup in E2E

Makefile
This commit makes it such that `make build` will compile aks-engine.exe
and aks-engine-test.exe for testing on Windows devices.
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
**Reason for Change**: This allows me to start contributing to the aks-engine project from a Windows device. I have not actually tested whether it'll work on Windows yet. :)
**Notes**: 👋
=> feat: support `make build` on Windows

.pipelines/pr-e2e.yaml
The Azure pipeline for E2E needs the codecov token set as an env var to upload results.
**Notes**:
=> fix: add codecov token env var to Azure pipeline

pkg/api/defaults-controller-manager.go, pkg/api/defaults.go, pkg/api/types.go, pkg/api/vlabs/types.go, pkg/api/vlabs/validate.go, test/e2e/kubernetes/kubernetes_test.go
Only checks `kubectl top nodes` if RBAC is enabled. Also includes the convenience addition of a `IsRBACEnabled` method.
If RBAC is not enabled on the cluster, kubectl top nodes checks are likely to fail. We first observed this yesterday when our tests upgrade to version 1.10 of kubectl.
**Notes**:
=> test: only check top nodes if RBAC is enabled

packer/install-dependencies.sh
`heapster:v1.3.0` was included in the VHD image, but it is only [needed by Kubernetes 1.6](https://github.com/Azure/aks-engine/blob/master/pkg/api/k8s_versions.go#L240) which is available for legacy ACS support.
**Notes**:
=> chore: remove Kubernetes 1.6 heapster version from VHD script

test/e2e/kubernetes/kubernetes_test.go
Observed some flakes in long-running cluster tests where ILB service was not deleted from a previous run. This change pre-emptively deletes the svc + deployment before running.
**Notes**:
=> test: pre-delete ILB stuffs before running

parts/k8s/containeraddons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-smb-flexvolume-installer.yaml, test/e2e/kubernetes/kubernetes_test.go
use kube-system namespace instead of flex, kv:
When enableRbac and enablePodSecurityPolicy are both set to true, default pod security policies are created. The restrictive policy is applied to all pods that either don't have a service account with a role binding to a less restrictive policy or a policy bound to the namespace. This results in pods in the kv and flex namespaces being unable to start.
I decided to use kube-system for all flexvolume drivers since those daemonsets only installs the flexvol driver like what other daemonset in kube-system namespace does, e.g. network-monitor, switch to use kube-system makes the maintanance more easily.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> fix: use kube-system namespace instead of flex, kv

parts/k8s/addons/coredns.yaml, parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
This allows the cluster-autoscaler to evict the pods of the concerned deployments.
**Notes**: Add pod disruption budgets
=> feat: add pod disruption budgets

packer/install-dependencies.sh, pkg/api/defaults_test.go, pkg/api/k8s_versions.go
See https://github.com/kubernetes/dashboard/releases/tag/v1.10.1
**Notes**:
=> chore: update kubernetes-dashboard to v1.10.1

pkg/operations/kubernetesupgrade/upgradecluster.go
The upgradable() function in upgrade checks if a node is upgradable by checking if its current version is contained in a list of upgrade versions. The list of upgrade versions is determined using the list of supported Kubernetes version for aks-engine. However, this does not apply to hosted master clusters (AKS) that have their own list of supported versions and perform upgrade validation already. This allows distinct version support for AKS (as long as the versions supported in aks-engine are a superset).
Fixes #235
**Notes**:
=> fix: remove VM upgrade version check for AKS

pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
Clone of https://github.com/Azure/acs-engine/pull/4271
=> fix: do not check agent & master pool size when using availability zones

.github/stale.yml
Adds [stale app](https://github.com/probot/stale) configuration yaml, a GitHub App built with Probot that closes abandoned Issues and Pull Requests after a period of inactivity.
**Notes**:
=> feat: add stale app yaml

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/namespace/namespace.go
Calico and Azure NetworkPolicy-backed clusters aren't able to be E2E-tested in long-running scenarios (soak/upgrade/scale) because the test was not implemented to be re-used in the same cluster across multiple runs.
**Notes**:
=> test: NetworkPolicy E2E tests cleanup for soak

parts/k8s/addons/coredns.yaml
Improve resilience of the coredns service with anti-affinity.
Those will try to spread coredns pods across `failure-domain zones` and `nodes` at scheduling.
See:
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
**Notes**:
=> feat: add anti affinity to coredns deployment

.pipelines/pr-e2e.yaml
`make validate-commit-msg` only looks at the most recent non-merge commit, which can be [less than optimal](https://github.com/Azure/aks-engine/pull/237#issuecomment-451593876). This removes that check from our Azure DevOps pipeline.
Instead let's try the probot [semantic pull requests](https://github.com/probot/semantic-pull-requests) GitHub service. I enabled it and will test it with this PR.
**Notes**:
=> chore: remove commit check from Azure DevOps pipeline

parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
The cluster-autoscaler needs permission to list replicasets.apps resources.
Fixes #261 
**Notes**:
@tariq1890 I created the PR as you suggested, however my issue was for k8s 1.13.1. Will this fix work with previous k8s versions?
=> fix: Give cluster-autoscaler permission to list replicasets.apps

docs/kubernetes/deploy.md, parts/k8s/kubernetesagentresourcesvmas.t, parts/k8s/kubernetesmasterresources.t, parts/k8s/kubernetesmasterresourcesvmss.t, parts/k8s/kuberneteswinagentresourcesvmas.t, parts/masterparams.t, pkg/engine/params.go, pkg/engine/template_generator.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgrader.go
This is a leftover "acs-engine" to "aks-engine" transition item. The tag that is added to every VM deployed with aks-engine is now "aksEngineVersion" instead of "acsengineVersion". Also changed variables in the code that referred to acsengineVersion.
**Notes**:
=> fix: Rename acsengineVersion tag to aksEngineVersion

pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/helpers/pki.go
There are some cases where we have pods on master nodes who needs to communicate with the API server (e.g.: cluster-autoscaler) but it cannot use the `kubernetes.default` service cause it will intermittently fail due to the fact that, if the request is forwarded by the service to the apiserver on the **same node** as it originated from, the request will never come back due to `Martian source` network error.
The way around that is to use host network and send request to localhost:443 but localhost is currently not part of the default domains in the certificates generated.
**Notes**:
=> feat: add localhost and 127.0.0.1 to certificates

parts/k8s/addons/coredns.yaml, parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
I forgot the `addonmanager.kubernetes.io/mode: EnsureExists` label when I made the original PR.
Without it the addond manager will not create the resource.
**Notes**:
=> fix: addon manager pod discruption budgets

test/e2e/azure/cli.go, test/e2e/engine/template.go, test/e2e/runner/cli_provisioner.go
In practice, lots of folks segment their vnet into subnets per agent pool. The purpose of this PR is to add that configuration pattern to "custom VNET" scenarios automatically, to ensure that this known working operational scenario does not decay into an edge case over time due to lack of test coverage.
**Notes**:
=> test: enable multiple subnets per agent pool

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
Updates our linter tool `golanci-lint` to the current release. See https://github.com/deis/docker-go-dev/releases/tag/v1.18.3
**Notes**:
=> chore: update go-dev image for newer golangci-lint

packer/install-dependencies.sh, pkg/api/common/versions.go
See the [v1.13.2 changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#changelog-since-v1131) and https://github.com/kubernetes/kubernetes/releases/tag/v1.13.2
Several Azure-specific fixes in this patch release--some may correlate to aks-engine issues...
**Notes**:
=> chore: add support for Kubernetes 1.13.2

packer/install-dependencies.sh
Noticed that Tiller 2.11.0 and blobfuse-flexvolume addon container images were missing from the VHD install script. This PR adds them.
**Notes**:
=> fix: add missing container images in VHD

test/e2e/kubernetes/kubernetes_test.go
As we do for `kubectl get nodes -o wide`, let's do for pods in all namespaces.
**Notes**:
=> test: print all pods at beginning of E2E test run

parts/k8s/addons/coredns.yaml, parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
In practice these are negatively impacting single master cluster cordon/drain scenarios (upgrade/scale)
Recently introduced `PodDisruptionBudget` definitions were preventing scale/upgrade scenarios for (at least) single master node cluster configurations:
```
time="2019-01-11T00:53:15Z" level=info msg="Node k8s-agent2-13795059-2 has been marked unschedulable." source="scaling command line"
time="2019-01-11T00:53:15Z" level=info msg="2 pods need to be removed/deleted" source="scaling command line"
time="2019-01-11T00:53:15Z" level=info msg="1 pods need to be removed/deleted" source="scaling command line"
time="2019-01-11T00:53:15Z" level=info msg="metrics-server-69b44566d5-vnqzx pod successfully evicted" source="scaling command line"
time="2019-01-11T00:53:15Z" …
```
=> fix: revert PodDisruptionBudget definitions

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
To help debug flakes (e.g., `kubectl top nodes`), we should be printing out the pod logs when errors occur)
**Notes**:
=> test: print pod logs when errors occur

docs/topics/clusterdefinitions.md
update default value of smb-flexvolume in clusterdefinitions.md to false, make it consistent with actual behavior.
Fixes #322 
=> docs: update default value of smb-flexvolume in clusterdefinitions.md

parts/agentparams.t, parts/k8s/kuberneteswinagentresourcesvmas.t, parts/k8s/kuberneteswinagentresourcesvmss.t, parts/windowsparams.t
Cleanup text.
Windows pool description was showing "Linux OS image"
Extension profile "Compute.AKS-Engine.Windows.Billing" was named '-computeAksLinuxBilling'
**Notes**:
=> fix: use correct OS Type in description text

packer/install-dependencies.sh
Improve cluster CRUD resiliency for flannel cluster configuration scenarios
See here for image sizes to evaluate add'l VHD storage overhead:
https://quay.io/repository/coreos/flannel?tag=latest&tab=tags
**Notes**:
=> feat: pre-pull flannel images

parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesmasterresourcesvmss.t, parts/k8s/kubernetesmastervars.t, pkg/api/common/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
- Add internal loadbalancer for masters when `availabilityProfile` is `VirtualMachineScaleSets` and `MasterProfile.Count > 1`
- New internal IP assigned to `kubernetesAPIServerIP` derived from `"[concat(variables('masterFirstAddrOctets')[0],'.',variables('masterFirstAddrOctets')[1],'.255.', variables('masterInternalLbIPOffset'))]"` e.g. `10.240.255.10`
- Add master node's primary IP to ILB's backend pool
Fixes #304 
**Notes**:
- Also fixes few style issues in e2e
=> fix: Add ILB for vmss masters

parts/k8s/kubernetesagentresourcesvmas.t, parts/k8s/kubernetesmasterresources.t, parts/k8s/kuberneteswinagentresourcesvmas.t
`computername` is the wrong name and it is not recognized by the RP schema. `computerName` should be used instead
=> fix: Fix the incorrect computername parameter

docs/tutorials/quickstart.md, docs/tutorials/quickstart.zh-CN.md
The link is broken.
**Notes**:
=> docs: fix a broken link and rename ACS to AKS

docs/topics/clusterdefinitions.md, examples/ipvs/kubernetes-msi.json, parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/kubernetesmastercustomdata.yml, pkg/api/const.go, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/types.go, pkg/api/vlabs/types.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
adds ipvs support to clusters created by `aks-engine`. The default mode is still iptabales, the user have to opt-in via setting `KuberentesConfig.kubeProxyMode = "ipvs"` in api-model
> I do believe there was a long standing feature request on acs-engine, maybe we lost it in the move? (I could be wrong)
Fixes #344
=> enable ipvs + samples

parts/k8s/kubernetesmasterresourcesvmss.t, pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json, pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json, pkg/engine/transform/transformtestfiles/k8s_scale_template.json, pkg/engine/transform/transformtestfiles/k8s_template.json, pkg/engine/transform/transformtestfiles/k8s_vnet_scale_template.json, pkg/engine/transform/transformtestfiles/k8s_vnet_template.json
This PR sets `publicIPAllocationMethod` as static for master node, this is for doing AKS whitelist feature which requires all master nodes uses static public ip.
cc @feiskyer @ritazh 
**Notes**:
set `publicIPAllocationMethod` as static for master node
=> set publicIPAllocationMethod as static for master node

pkg/api/vlabs/validate.go
Fix misleading validation message for DNSServiceIP / ServiceCidr configuration combinations.
Fixes #349
**Notes**:
=> fix: ServiceCidr + DNSServiceIP validation error message

pkg/api/types.go, pkg/api/types_test.go, pkg/engine/template_generator.go
Adding helper methods to increase reuse of code.
=> fix: add getter methods for managed identity

parts/k8s/kubernetesagentresourcesvmss.t, parts/k8s/kubernetesmasterresourcesvmss.t, parts/k8s/kuberneteswinagentresourcesvmss.t
location is not a valid parameter  in VMSS extension profiles. Extension profiles are a field within the VMSS object and the VMSS object specifies the location :)
=> fix: remove invalid parameter location from vmss extension profiles

parts/k8s/kuberneteswinagentresourcesvmss.t
Why should windows miss out on the fun  ;)
cc @asw101
=> fix: Add support for low pri scalesets in windows agents

pkg/engine/template_generator.go
Enable billing extension for AzureChinaCloud
Compute.AKS-Engine.Linux.Billing & Compute.AKS.Linux.Billing are deployed in mooncake.
Moved from https://github.com/Azure/acs-engine/pull/4144
**Notes**:
=> fix: Enable billing extension for AzureChinaCloud

docs/topics/kubernetes-developers.md
Update kubernetes-developers.md to reflect the fact that "distro" needs to be set for master and agent nodes in order to get the kubelet from the custom hyperkube image passed.
Addresses issue: https://github.com/Azure/aks-engine/issues/342
=> docs: Update kubernetes-developers.md

parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
Without this toleration, a v1.12 aks-engine cluster using flannel as its
network plugin will be unable to come up, as the cni plugin will never
start running on the nodes.
Currently when an v1.12 `aks-engine` cluster comes up, the nodes start out with a not-ready taint. The flannel daemonset does not tolerate this taint, so flannel can not come up. This in turn prevents the nodes from ever going ready.
**Notes**:
I'm not super sure how we could document or unit test this, but feel free to let me know how we could add that to this PR.
=> fix: add toleration to run flannel on not-yet-ready nodes.

docs/topics/upgrade.md, examples/addons/cluster-autoscaler/README.md
Document current issues and limitations of `aks-engine upgrade` and `cluster-autoscaler`
**Notes**:
=> docs: upgrade + cluster-autoscaler notes

parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
When a cluster is bootstrapped with cilium nodes do not become ready because of a missing CNI plugin which is installed by this daemonset. Allow it to schedule pods on non-ready nodes actually fixes the CNI configuration and the nodes turn into a Ready state.
=> fix(cilium): Allow the daemonset to deploy regardless of node status.

parts/k8s/kubernetesagentresourcesvmss.t, parts/k8s/kuberneteswinagentresourcesvmss.t
VMSS agent VMs are missing the "aksEngineVersion" : "[parameters('aksEngineVersion')]", tag that VMAS VMs have (https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesmasterresourcesvmss.t#L415-L416).
Fixes #411 
**Notes**:
=> feat: add the aksEngineVersion tag

.github/PULL_REQUEST_TEMPLATE.md
When opening a PR I like to have a visual of all the different commit types available, especially for the ones that aren't as obvious as "fix" and "feat". The list I added is a comment so it won't show in PR descriptions, just in the template when someone creates a PR.
**Notes**:
=> chore: add commit message categories to PR template

.pipelines/e2e-step-template.yaml
Always collect artifacts. We want to collect deployment logs even (and especially if) e2e failed.
**Notes**:
=> ci: always collect logs in pipeline

pkg/helpers/pki.go
For folks not submitting their own certificates, let's increase the expiration of the auto-generated certs we provide for them. In practice, expired certs render a cluster 100% inoperable.
@qike-ms @thomas1206 @jwilder @sauryadas @seanmck FYI
**Notes**:
=> chore: increase auto-generated cert expiration to 30 years

pkg/armhelpers/utils/util.go, pkg/armhelpers/utils/util_test.go, pkg/operations/kubernetesupgrade/upgrader.go
Remove the agentpool index usage from upgrade code path.
Remove agentpool index usage from function which gets agent VM name
**Notes**:
=> refactor: Remove agentpool index usage from function which gets agent VM name

pkg/api/types.go, pkg/api/types_test.go, pkg/armhelpers/compute.go
- Add per agentpool level kubernetes version and provisioning state.
- Add calls to delete an entire vmss.
Required work towards multi agentpool operations.
These will start getting used by AKS multi agent pool work initially and then used in aks-engine multi agentpool operations - like delete, scale, upgrade.
**Notes**:
=> chore: per-agent pool k8s versions and provisioning state

parts/k8s/kubernetesinstalls.sh
I've noticed some cluster deployments fail because etcd fails to download (no outbound on the VM) but the CSE times out instead of returning an error code because the etcd retries take too long. Reducing retries to 120 and sleep to 5s between retries.
**Notes**:
=> fix: reduce etcd download retries to avoid timeouts

pkg/api/mocks.go, pkg/api/types.go, pkg/api/types_test.go
Add agentpool resource(used for agentpool level operations) and UT
Agentpool resource definition is required for operating on agentpool as a resource. This is in preparation to the AKS multiagentpool work. There is no usage in aks-engine yet. AgentPoolProfile  is used to represent the agentpool in a cluster. This is included in the AgentPoolResource as its properties field. 
**Notes**:
=> chore: Add agentpool resource(used for agentpool level operations) and UT

parts/k8s/kubernetesinstalls.sh
Checks for the existence of containerd binary before downloading
reverts some of the changes introduced in https://github.com/Azure/aks-engine/pull/183
**Notes**:
=> fix: containerd downloads every time

pkg/api/apiloader.go, pkg/api/convertertoapi.go, pkg/api/convertertoapi_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
This PR runs the orchestrator version validation logic when running deploy before it is mistakenly being reset to the default value. This is mostly a workaround until we reach a better solution
Fixes #191 
**Notes**:
The fix is implemented with a workaround. Comment in the code describes the root cause/ideal fix.
=> fix: Fail deployCmd when orchestrator version is invalid

pkg/engine/engine.go
change azure disk host cache to ReadOnly
The default value `None` would lead to slow perf. And according to below doc: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage-performance#disk-caching, default host cache should be `ReadOnly`
Fixes #418
**Notes**:
=> set caching mode of data disks as ReadOnly by default

parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes.yaml
Due to [k8s upstream PR](https://github.com/kubernetes/kubernetes/pull/67483), default azure disk storage class has been changed to managed disk, this PR explicitly specify unmanaged disk class kind as `shared`, otherwise it will always create managed disk which is incorrect.
Fixes #419
**Notes**:
@jackfrancis 
cc @DonMartin76
=> fix: specify "shared" for unmanaged disk class

cmd/scale.go, pkg/operations/kubernetesupgrade/upgradecluster.go
`Next()` is deprecated and is soon to be removed. `NextWithContext` forces good practices so that we use the existing parent context and not spawn a new one.
=> fix: remove the use of deprecated Next() method

cmd/get_versions.go, cmd/get_versions_test.go, cmd/orchestrators.go, cmd/root.go, cmd/root_test.go, cmd/upgrade.go, docs/topics/clusterdefinitions.md, docs/topics/upgrade.md, docs/tutorials/quickstart.zh-CN.md
The `aks-engine orchestrators` command is still generic and returns DCOS versions, for example, although aks-engine is Kubernetes-only.
This hides the `orchestrators` command and adds a `get-versions` command that calls the same code with the orchestrator argument hard-coded as `Kubernetes`.
There wasn't a consensus in #339 as to the name of the new command, so this is just my proposal, but I'm happy to change it based on your feedback.
Fixes #339
**Notes**:
I tried to use Cobra's "alias" feature to avoid writing any code, but it didn't quite fit since the commands don't expose the same arguments. Hiding the `orchestrators` command but otherwise leaving it intact seems like the most polite way to replace it with a new command.
=> feat: add "get-versions" command to replace "orchestrators"

CODE_OF_CONDUCT.md
Brings the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/) directly into the project so that GitHub considers this [community standard](https://github.com/Azure/aks-engine/community) met. 
See https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/ for more info.
**Notes**:
=> docs: add a "code of conduct" file where GitHub can see it

docs/tutorials/custom-vnet.md
Issue #475 as ACS is being deprecated
Removed ACS, added AKS to documentation. Except for line 209, which is still hyperlinked to ACS documentation yet to be marked as deprecated
**Notes**:
=> fix: updated acs to aks

docs/topics/clusterdefinitions.md, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
Enable configurable `--enforce-node-allocatable` kubelet flag to unblock scenarios such as described in #507.
Fixes #507 
**Notes**:
=> feat: enable configurable --enforce-node-allocatable

cmd/get_versions.go, cmd/get_versions_test.go, cmd/orchestrators.go, cmd/orchestrators_test.go, cmd/version.go
The `aks-engine get-versions` command added in #448 defaults to JSON output that is hard to read. This adds the `--output=human` argument which acts similarly to `az aks get-versions --output table`:
```sh
$ ./bin/aks-engine get-versions -o human
Version        Upgrades
1.14.0-alpha.1 
1.13.3         1.14.0-alpha.1
1.13.2         1.13.3, 1.14.0-alpha.1
1.12.5         1.13.2, 1.13.3
1.12.4         1.12.5, 1.13.2, 1.13.3
1.11.7         1.12.4, 1.12.5
1.11.6         1.11.7, 1.12.4, 1.12.5
1.10.13        1.11.6, 1.11.7
1.10.12        1.10.13, 1.11.6, 1.11.7
1.9.11         1.10.12, 1.10.13
1.9.10         1.9.11, 1.10.12, 1.10.13
1.6.9          1.9.10, 1.9.11
```
Fixes #520
**Notes**:
Should we make the table output the default?
=> feat: add human-readable output option to "get-versions" command

test/e2e/kubernetes/kubernetes_test.go
Intermittent `kubectl top nodes` failure test signal due to possibly transient metrics-server issues. Adding more retry time here to be more tolerant to Azure.
This PR will wait 10 minutes (1 retry per minute) to get a successful `kubectl top nodes` result.
Fixes #533
**Notes**:
=> test: wait longer between kubectl top nodes retries

.codecov/codecov.yml
Some files under the `test/` directory are being included in aks-engine's [code coverage report](https://codecov.io/gh/Azure/aks-engine/tree/master/test). Additionally, the `pkg/armhelpers/mockclients.go` should be excluded, as it is also test code.
Here are the [codecov docs](https://docs.codecov.io/docs/ignoring-paths) for configuring the `ignore:` directive.
**Notes**:
The proof for this PR will be in the codecov comment that gets posted.
=> ci: ignore test files in code coverage

docs/community/developer-guide.md, test/cluster-tests/kubernetes/k8s-utils.sh, test/cluster-tests/kubernetes/test.sh, test/common.sh, test/e2e/kubernetes/config.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/namespace/namespace.go, test/e2e/kubernetes/networkpolicy/networkpolicy.go, test/e2e/kubernetes/node/node.go, test/e2e/kubernetes/persistentvolume/persistentvolume.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/storageclass/storageclass.go, test/e2e/runner/cli_provisioner.go, test/e2e/runner/ginkgo.go
Uses the [`k`](https://github.com/jakepearson/k) script in the [go-dev](https://github.com/deis/docker-go-dev) image to fetch the right version of `kubectl` just-in-time for E2E tests.
Fixes #557
Unblocks #435
**Notes**:
This is just one approach to fixing this recurrent problem: other ideas are welcome. It worked fine for me running E2E tests locally (but requires the `k` script to be in your path of course).
=> test: use "k" script to fetch the right kubectl just-in-time

pkg/api/common/versions.go, pkg/api/defaults-apiserver.go, test/e2e/kubernetes/workloads/dns-liveness.yaml
Adds support for Kubernetes v1.14.0-alpha.2. See:
https://github.com/kubernetes/kubernetes/releases/tag/v1.14.0-alpha.2
**Notes**:
=> feat: enable 1.14.0-alpha.2 support

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, docs/community/developer-guide.md, makedev.ps1, scripts/k
See https://github.com/deis/docker-go-dev/releases/tag/v1.18.5
Closes #567
Should fix issues we are seeing in Jenkins E2E upgrade tests. I've already set `${GO_DEV_IMAGE}` to v1.18.5 there and it looks like we are 💚 again.
**Notes**:
=> fix: silence `k` script

docs/topics/clusterdefinitions.md, pkg/engine/artifacts.go, pkg/engine/engine.go
=> fix: allow for gzip and b64 encoding of the raw Addon data by decoding the input beforehand

pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/types.go, pkg/api/types_test.go, pkg/api/vlabs/const.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/const.go, pkg/engine/template_generator.go
`cilium` network plugin does its own masquerading, so `ip-masq-agent` should never be used.
Also commiting several const conveniences so we don't ever accidentally mistype the "cilium" val.
**Notes**:
=> chore: disable ip-masq-agent when using cilium networkPlugin

pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgrademasternode.go
To fix some ugly trailing `\n` when I run `aks-engine upgrade`. Like:
```
time="2019-02-25T17:18:03+08:00" level=info msg="Upgrading to Kubernetes version 1.13.3\n"
```
**Notes**:
=> fix: remove extra \n in log messages

pkg/api/defaults-kubelet.go
This removes the configuration for `--eviction-hard` for windows.  Although the values are subtracted from `NodeAllocatable` there is [no enforcement for `--eviction-hard` in windows currently](https://github.com/kubernetes/kubernetes/issues/73417#issuecomment-465806482).
The default linux configuration was being passed to Windows which was causing the error message "eviction manager: no observation found for eviction signal nodefs.inodesFree" show up in error logs.
https://github.com/kubernetes/kubernetes/issues/73792
**Notes**:
Could remove just the `inodesFree` from configuration to fix issue above but I thought it was clearer to remove settings that do not work for windows.
I didn't see any unit tests the test overloaded …
=> fix: eviction-hard is not implemented in windows

.pipelines/vhd-builder.yaml, packer.mk
Add cleanup to VHD pipeline to avoid running out of quota.
**Notes**:
=> ci: add storage account cleanup to VHD pipeline

pkg/armhelpers/compute.go, pkg/armhelpers/interfaces.go, pkg/armhelpers/mockclients.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go
This is extracting the vmss interfaces and mocks from the `upgrade --force PR` to reduce its footprint.
One test is carried over, which I just marked as skipped here as it lacks the implementation to pass
=> test: add VMSS client interfaces and mocks to make upgrade testable

.pipelines/vhd-builder.yaml, packer.mk
Azure pipelines treats the variable DRY_RUN as a string (did not find a way to specify it as a bool), so using string comparison. Previously `not('False')` was evaluating as `False`.
**Notes**:
=> ci: DRY_RUN variable is a string not a bool

pkg/api/const.go
Over the next period I will be PRing some changes to limits and allocation to aks-engine covering
1. (this PR) - Eviction Hard Thresholds 
100Mi (original) is too little. Here is why
1. kubelet (or rather cadvisor) calculation of free memory is `free` + `cached` by looking at `cat /sys/fs/cgroup/memory/memory.stat`. The problem with this the server can be under sever memory pressure but kubelet will not see that because it sees cached memory (memory that the kernel is unable release back for `free` pool. 
Here is a simple test 
1. Run two SSH to any aks-cluster nodes. 
2. on session #1 run `journalctl -fu kubelet` 
3. on session #2 run `apt update && apt install stress && stress --vm-bytes $(awk '/MemAvailable/{printf "%d\n", $2 * 0.99;}' < /proc/meminfo)k --vm-keep -m 1
` basically …
=> chore: modify eviction to memory.available.750Mi

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/util/util.go
Enable setting an upper bound time limit on E2E test commands. The specific use-case is ensuring that simple pod-to-pod networking operations are consistently quick and don't fall victim to, for example, occasional > 5 second DNS lookup operations.
**Notes**:
=> test: enable timeouts for running E2E commands

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesmastervars.t, parts/k8s/system.conf, pkg/engine/const.go, pkg/engine/template_generator.go
This configuration was recently removed because of systemd release notes announcing deprecation of JoinControllers starting with version 240:
https://lists.freedesktop.org/archives/systemd-devel/2018-December/041852.html
However, Ubuntu 16.04-LTS (current default OS SKU) version of systemd is not using that version:
```
$ systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```
Here is the recently reverted PR:
https://github.com/Azure/aks-engine/pull/410
**Notes**:
=> chore: add system.conf with static JoinControllers configuration

parts/k8s/windowskubeletfunc.ps1
Fix CNI lock file names and kill the processes before
getting rid of the config files
On restart of Kubelet Azure CNI would leak a lock file. The kubelet start script had incorrect lock file names which is causing the lock files to be left behind when kubelet starts.
**Notes**:
cc: @ashvindeodhar @PatrickLang
=> fix: Fix the CNI lock file names

packer/install-dependencies.sh
=> chore: enable 1.11.8 in VHD, deprecate 1.11.6

cmd/upgrade.go, cmd/upgrade_test.go, pkg/armhelpers/mockclients.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go
**Is this a request for help?**:  
No
---
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature Proposal
---
**description**:
We want to be able to force the upgrade process on a cluster without changing the kubernetes version. This will ensure that all components of the cluster are healthy and using the latest validated version for a given kubernetes version.
**proposed cli**: 
For an existing kubernetes `1.12.5` cluster, we want the following command to go through each nodes of the cluster and "refresh" them if necessary (update to latest valid version).
```bash
> aks-engine upgrade --force --location westus --resource-group rg --subsctiption $sub --upgrade-version 1.12.5
```
**Open questions**: 
- What should the behavior of the `--force` flag be for a usual next k8s version …
=> feat: add force parameter to the upgrade command

docs/topics/windows-and-kubernetes.md, examples/windows/kubernetes-windows-automatic-update.json, parts/k8s/kuberneteswinagentresourcesvmas.t, parts/k8s/kuberneteswinagentresourcesvmss.t, pkg/api/const.go, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/types.go, pkg/api/types_test.go, pkg/api/vlabs/types.go, pkg/engine/template_generator.go
This pull request should fix #402.
Add functionality to disable automatic windows update
Fixes #402 - Disable windows auto update
Add ability to disable automatic Windows updates. An entry for _windowsConfiguration_ will now be added under _osProfile_. This will default to true if the user does not provide a value. 
**Notes**: 
This is one of a few approaches I thought of when adding this functionality. Interested to hear if this is acceptable or not. I went with implementation of always adding the entry for  _windowsConfiguration_  under _osProfile_. I thought that explicitly setting this value would be better for consumers.
I wasn't sure if the changes should be put under _api_ or _vlabs_.
=> feat: Azure #402 - Disable windows auto update

pkg/api/types_test.go
Fixes a `make test-style` problem that somehow crept in with #627, at least for me. It also fails inside `make dev`, so I assume this will be a problem for CI in general:
```console
==> Running static validations and linters <==
pkg/api/types_test.go:852:5: should omit comparison to bool constant, can be simplified to !update (megacheck.{unused,gosimple})
if update != true {
^
Makefile:126: recipe for target 'test-style' failed
make: *** [test-style] Error 1
```
**Notes**:
=> fix: simplify comparison to satisfy linter

pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrader.go
PR #570 introduced some code issues. This fixes that.
```
pkg/operations/kubernetesupgrade/upgradecluster_test.go:485:8: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
ctx, _ := context.WithTimeout(context.Background(), 90*time.Minute)
^
pkg/operations/kubernetesupgrade/upgrader.go:634:6: S1009: should omit nil check; len() for nil slices is defined as zero (gosimple)
if vms != nil && len(vms) > 0 {
```
=> fix: address govet and gosimple issues

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesinstalls.sh, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesprovisionsource.sh
Use the -proposed systemd xenial package to get needed required systemd patch to address the following:
https://github.com/kubernetes/kubernetes/issues/57345
**Notes**:
=> chore: install -proposed systemd package

docs/topics/upgrade.md, pkg/operations/kubernetesupgrade/upgrader.go
The custom node properties are retained automatically for aks-engine master nodes, we don't need our special logic to do so. 
The custom node properties are retained automatically for aks-engine master nodes, we don't need our special logic to do so. 
**Notes**:
=> fix: Remove retaining custom properties logic for master nodes

.pipelines/vhd-builder.yaml, packer.mk, packer/install-dependencies.sh, packer/vhd-image-builder.json
Log which components are installed during the VHD script as part of the the VHD build pipeline to generate a text file of notes. For now, the file is published as an artifact of the pipeline and can be easily copy/pasted into a PR that adds the new image version. In the future, the goal is to automate adding the file to the the repo when the pipeline runs for publishing.
Side-fix: `set -o pipefail` when running packer to make sure the Build VHD step fails if the script returns non-zero.
#427 
**Notes**:
=> ci: generate release notes for component versions installed in VHD build

cmd/upgrade.go, cmd/upgrade_test.go
**Reason for Change**:  
This fixes a bug that did not assign the target version on the containerService object when `--force` was applied to the upgrade command.
issue wasn't raised
**Notes**:
The fix is implemented with the simplest change possible (move the assignment out of the if block) and does not refactor the upgrade command logic to make it less prone to such errors.
related to #525
=> fix: always assign target version on upgrade

test.mk
This allows to pass `SKIP_TEST=true` down to `make test-kubernetes` which effectively just builds a test cluster.
=> test: pass in skip_test env variable down to the test container

test/e2e/kubernetes/pod/pod.go
We regularly see pod deletes succeeding just above the current timeout threshold of 1 minute. E.g.:
```
2019/03/06 10:34:42 #### $ k delete po -n default iis-azurefile completed in 1m23.84830648s
```
There is no strict reason to enforce a 1 minute timeout generally for all pod delete operations. Let's increase to 5 mins to account for normal operational variance.
**Notes**:
=> test: increase e2e pod delete timeout tolerance to 5 mins

test/e2e/kubernetes/kubernetes_test.go
Found this while debugging E2E tests for ubuntu 18.04... The test actually failed but the error wasn't checked.
**Notes**:
=> test: check error returned when checking outbound connection of pod

pkg/engine/armvariables.go, pkg/engine/virtualmachinescalesets.go
Follow-up from #324
- Fixes a typo the `creationSource` value of master VMSS object (missing closing param)
- Fixes conditional logic regression for non-hosted master / non-custom VNET scenarios
- See the reference here for what needs to be implemented:
- https://github.com/Azure/aks-engine/blob/master/parts/k8s/kubernetesmastervars.t#L206
Addresses some of https://github.com/Azure/aks-engine/issues/685
**Notes**:
=> fix: master vmss cluster configuration errors in template refactor

pkg/engine/armvariables.go, pkg/engine/armvariables_test.go
Based on the current implementation, we always need these variables for composition by the ARM template.
Follow-up from #677 
The added Azure Stack variables are implemented in a way that requires them to exist.
**Notes**:
=> fix: 2 Azure Stack vars are obligatory

pkg/engine/networkinterfaces.go, pkg/engine/networkinterfaces_test.go
A small change to agentpool NIC logic in new template implementation to achieve parity with existing template implementation.
**Notes**:
=> fix: agentpools have their own “is custom vnet” logic

pkg/engine/armvariables_test.go
"allocateNodeCidrs" var reference needs to be removed from TestK8sVarsMastersOnly unit test
**Notes**:
=> test: remove obsolete allocateNodeCidrs var

cmd/scale.go, pkg/operations/kubernetesupgrade/upgrader.go
Add appropriate err != nil checks to avoid panics when a json string isn't unmarshalled succesfully.
=> fix: add err != nil checks for json Unmarshal in scale and upgrade ops

.pipelines/pr-e2e.yaml
Reason:
Linting rules in the CI depend on fully-working and compiled code to run. In cases where dependencies are completely in sync with their manifests and go imports, linting rules will fail.  This is why we would need to `dep check` to precede `test-style`
=> ci: run dep check before linting in the pr-e2e pipeline

Makefile
Uses the [`upx`](https://upx.github.io/) tool to compress the `aks-engine` and `aks-engine.exe` binaries.
Since `upx` knows tricks specific to each binary format, it compresses better than `zip` or `tar` in this case. This makes our commonly-downloaded artifacts a bit smaller:
```sh
$ git co master && make clean dist && akse-dist-sizes
...
-rw-r--r--  1 matt  staff    19M Mar  8 14:05 _dist/aks-engine-2f96b59c2-darwin-amd64.tar.gz
-rw-r--r--  1 matt  staff    19M Mar  8 14:05 _dist/aks-engine-2f96b59c2-darwin-amd64.zip
-rwxr-xr-x  1 matt  staff    49M Mar  8 14:05 _dist/aks-engine-2f96b59c2-darwin-amd64/aks-engine
-rw-r--r--  1 matt  staff    11M Mar  8 14:05 _dist/aks-engine-2f96b59c2-linux-amd64.tar.gz
-rw-r--r--  1 matt  staff    11M Mar  8 14:05 …
```
=> build: compress aks-engine binaries

pkg/engine/template_generator.go
omitting err in multi-valued contexts is considered bad practice. It also makes it harder to debug issues without it.
=> fix: add err check while JSON marshalling the ARM template

parts/k8s/kubernetesmasterresources.t, parts/k8s/kubernetesmasterresourcesvmss.t, pkg/engine/virtualmachines.go, pkg/engine/virtualmachinescalesets.go
Allow masters with custom images to use data disks for etcd
Fixes #496 
- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
**Notes**:
Tested with a custom ubuntu 16.04 image. And this model:
```
{
"apiVersion": "vlabs",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"kubernetesConfig": {
"etcdDiskSizeGB": "256"
}
},
"masterProfile": {
"count": 1,
"dnsPrefix": "",
"vmSize": "Standard_DS2_v2",
"imageReference": {
"name": "ubuntu-16-04",
"resourceGroup": "test-images"
},
"availabilityProfile": "AvailabilitySet"
},
"agentPoolProfiles": [
{
"name": "agent",
"count": 1,
"vmSize": "Standard_DS2_v2",
"storageProfile" : "ManagedDisks",
"imageReference": {
"name": "ubuntu-16-04", …
```
=>  fix: Allow masters with custom images to use data disks for etcd

pkg/engine/armresources.go
This should fix a bug in a scenario where system assigned MSI role assignments are used in the agent pool profiles.
=> fix: add the system role assignment object as the resource instead of the function pointer

pkg/armhelpers/utils/util.go, pkg/operations/kubernetesupgrade/upgradecluster.go
Currently the upgrade operaton upgrades the entire cluster, even if the 'AgentPoolsToUpgrade' is specified in the upgrade operation. This change adds the relevant code to skip agentpools which are not specified in the AgentPoolsToUpgrade, thus providing agentpool level upgrade support. This change only supports VMSS.
**Notes**:
=> feat: add selective agentpool upgrade support - VMSS

test/e2e/kubernetes/pod/pod.go
Adds some additional pod introspection foo in the service of debugging #679. This will have general value, so "kubectl pod describe" has been added to the error gathering implementation for the various "wait for all pods to become ready" tests.
**Notes**:
=> test: describe pod object in error scenario

cmd/deploy.go, cmd/deploy_test.go, cmd/generate.go, cmd/generate_test.go, cmd/get_versions_test.go, cmd/orchestrators_test.go, cmd/root.go, cmd/root_test.go, cmd/scale.go, cmd/scale_test.go, cmd/upgrade.go, cmd/upgrade_test.go, cmd/version.go, cmd/version_test.go, main.go
Many places in the `cmd` module were calling `log.Fatalf` which makes that code untestable since it calls `os.Exit`. (This also meant that errors in a couple commands would have a return code of 0.)
This refactors commands so errors are returned all the way to the caller in `main.go` where they can be handled consistently. This also add some basic test coverage at that level, although there is more that can be done in that respect.
Fixes #536
Fixes #518
**Notes**:
=> fix: commands return errors rather than exit

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesbase.t, pkg/engine/armvariables.go
We currently configure docker as GPU-enabled only if the particular nvidia addon that we deliver is enabled. This is problematic in the event that someone wants to disable *out* addon and configure their own. In that event, we should *always* configure the container runtime for GPU in an N series context.
Also cleaned up an unused taints variable.
**Notes**:
=> fix: always configure the container runtime for GPU in an N series context

cmd/scale.go
Always check for err != nil :)
=> fix: add err!=nil check when loading an ARM template during scale ops

cmd/scale.go
=> fix: correct typo in err message in scale when unmarshaling ARM params

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/types.go, pkg/api/types_test.go
AKS windows agent pool support needs a few changes
1. Windows VM name prefix should not include agent pool index since AKS agent pool can be dynamically added and deleted. The new naming prefix get rid of the clusterId and agent pool index. It is now "k8s"+agentpoolname. It is up to AKS code to ensure the agent pool name can't be more than 6 chars.
2. Included a new flag NewWindowsNaming in agent pool profile data model to indicate new naming. Right now, this flag is NOT exposed to AKS-engine users. Only AKS can set this flag.
2. The generation of kubelet config for windows agent pool assumes kubernetes config being null for windows agent pool definition. This might not always be the case for AKS.
3. The two kubelet flags removed for linux agent pool when secure …
=> feat: windows agentpool support for AKS

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go, test/e2e/kubernetes/workloads/nginx-master.yaml, test/e2e/runner/cli_provisioner.go
Follow up from #570
Add E2E test coverage for node labels and annotations.
**Notes**:
=> test: add node label and annotation validation

parts/k8s/kubernetesagentcustomdata.yml
This reverts commit 76720109c4bd418dc0c73d2465413d91f8ed402b.
The sysctl files are basically just for show. The kubelet will override the panic_on_oom toggle on process start every time.
This file are deceptive for anyone debugging kernel parameters on the nodes.
**Notes**:
Bug filed with the Kubernetes project: [74151](https://github.com/kubernetes/kubernetes/issues/74151)
=> Revert "fix: set nodes to panic and reboot on oom (#503)"

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesconfigs.sh, parts/k8s/kubernetescustomscript.sh, parts/k8s/kubernetesmastercustomdata.yml
By not marking walinuxagent for "hold" (i.e., do not modify via apt) during CSE, even VHD scenarios, we risk walinuxagent being updated via CSE, which will never finish, because walinuxagent updates require a non-active CSE operation.
Additionally, we were releasing the hold too early, as apt system.daily operations are able to update waagent, and despite the invocation being sent to the background, the fact that it is a child process of the parent CSE runtime process in practice means we see these symptoms.
Fixes #768 Fixes #758 
**Notes**:
=> fix: actually apt-mark hold walinuxagent during all CSE runs

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesconfigs.sh, parts/k8s/kubernetescustomscript.sh, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesprovisionsource.sh
Follow-up of #771
Testing against the changes in #771 revealed that cloud-init itself is invoking `apt` to install some packages:
```
2019-03-15 19:26:12,725 - helpers.py[DEBUG]: Running update-sources using lock (<FileLock using file '/var/lib/cloud/instances/3557FA54-5097-654B-9116-21C59991226E/sem/update_sources'>)
2019-03-15 19:26:12,726 - util.py[DEBUG]: Running command ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold', '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'update'] with allowed return codes [0] (shell=False, capture=False)
2019-03-15 19:26:25,480 - util.py[DEBUG]: apt-update [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet update] …
```
=> fix: mark walinux for hold in cloud-init

pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/types.go
**Reason for Change**: The AKS billing extensions are now available in the Azure Government cloud. This change allows aks-engine to include that extension when generating templates for that cloud.
=> chore: Include billing extensions for AzureUSGovernmentCloud

packer/cleanup-vhd.sh
When we look at the logs such as /var/log/kern.log on VM created from AKS VHD, we see logs from when the VHD was created. For example, I only booted up the VM once, but I saw it twice in kern.log.
#664 
**Notes**:
=> fix: move /var/log/ during VHD build to a vhd specific directory

pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
This fixes a bug in VMSS scenarios for windows agents.
=> fix: add missing parameter ComputerNamePrefix for VMSS agents using Windows

pkg/engine/engine.go, pkg/engine/engine_test.go
This is a more resilient and consistent version of PR #787. 
This has test cases that are resilient to non-deterministic order of map key-value pairs
=> test: add tests for pkg/engine/engine.go

pkg/engine/armresources.go
This addresses cases when GenerateTemplate is called with `containerService` objects wil nil `kubernetesConfig`
=> fix: add nil checks for more resilience in template refactor

packer.mk
The output of the DevOps pipelines isn't always as serial as it should be, remove all shell commands that accidentally show up in the release notes artifacts.
**Notes**:
=> fix: remove shell output from VHD release notes

parts/k8s/kubernetesagentresourcesvmas.t, parts/k8s/kubernetesagentresourcesvmss.t, parts/k8s/kubernetesmasterresources.t, parts/masterparams.t, pkg/engine/networkinterfaces.go, pkg/engine/params.go, pkg/engine/template_generator.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachinescalesets.go
Is there such a thing called "too many nil checks"?
=> fix: add extra nil guard checks for LinuxProfiles

test/e2e/kubernetes/kubernetes_test.go
Remove flakes due to dns-liveness pods not being ready in 2 mins, especially on cluster configurations where a bunch of pods are scheduled in a short period of time and there's only one schedulable node.
**Notes**:
=> test: wait the regular, configurable time for dns-liveness pod readiness

pkg/api/defaults_test.go
Adds a couple unit test cases to `assignDefaultAddonVals()` to validate `nil` `Enabled` property behavior.
**Notes**:
=> test: add test case for assignDefaultAddonVals to deal with nil Enabled property

test/e2e/kubernetes/pod/pod.go
It is bad practice to use a loop variable in a go-routine without locking it. This PR fixes that.
=> style: fix go_vet issues in the code

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/namespace/namespace.go
Follow-up from #638
This PR guards new NetworkPolicy tests added in the above PR to reflect that you need a 1.11 or greater versioned cluster to execute the new tests.
Also, reduces the wait time to validate NetworkPolicy enforcement, and enables re-use scenarios by enabling the label creation statement to be idempotent (`--overwrite=true`).
Here is an example of the errors you get running these tests against a 1.10 cluster:
```
$ k create -f workloads/policies/backend-policy-allow-ingress-pod-label.yaml
2019/03/21 16:57:56 Error trying to create NetworkPolicy backend-allow-ingress-pod-label:The NetworkPolicy "backend-allow-ingress-pod-label" is invalid: spec.ingress[0].from[0]: Forbidden: may not specify more than 1 from type
``` …
=> test: fix NetworkPolicy tests for pre-1.11 cluster configurations

cmd/get_versions.go, cmd/version.go, pkg/api/vlabs/validate.go, pkg/operations/kubernetesupgrade/upgrader.go, test/e2e/kubernetes/util/util.go
Apparently `pkg/errors` is also artisanal.
https://github.com/pkg/
=> style: use errors.Errorf instead of fmt.Errorf as it's more idiomatic

parts/k8s/kubernetesconfigs.sh
Increase the timeout to 10 mins for nvidia drivers installation.
We have suggestions that nvidia drivers installation is being interrupted before it has time to finish:
```
+ timeout 120 sh /usr/local/nvidia/nvidia-drivers-396.26 --silent --accept-license --no-drm --dkms --utility-prefix=/usr/local/nvidia --opengl-prefix=/usr/local/nvidia
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 396.26.......................................................................................................................................................................................................................................................................................................................................... …
```
=> fix: increase timeout tolerance for nvidia drivers installation

parts/k8s/containeraddons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
Realized while testing another change that we were pulling the blobfuse-flexvol-installer image every time since  `imagePullPolicy` was set to `Always`. We pre-pull the image in the AKS base image so no need to re-pull it for every deployment.
**Notes**:
=> fix: change blobfuse-flexvol-installer imagePullPolicy to IfNotPresent

pkg/api/converterfromagentpoolonlyapi.go, pkg/api/converterfromagentpoolonlyapi_test.go, pkg/api/convertertoagentpoolonlyapi.go, pkg/api/convertertoagentpoolonlyapi_test.go, pkg/api/convertertoapi_test.go, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/defaults_test.go, pkg/api/mocks.go, pkg/api/types.go, pkg/api/types_test.go
These constants already exist. This just ensures consistent usage. (Go already interns strings at compile time so this probably isn't an optimization.)
**Notes**:
=> style: use constants consistently in pkg/api

parts/k8s/kubernetesconfigs.sh
https://icm.ad.msft.net/imp/v3/incidents/details/108362084/home
OMS agent relies on auth.log for getting ssh logs for security monitoring purposes. https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-data-sources-syslog#configure-syslog-on-linux-agent
https://github.com/Azure/acs-engine/pull/1956 disabled `ForwardToSyslog` which broke this scenario. See for additional context: https://github.com/Azure/acs-engine/pull/1956#issuecomment-382822102
**Notes**:
=> fix: fix sshd logging to auth.log for OMS

pkg/engine/keyvaults.go, pkg/engine/keyvaults_test.go, pkg/engine/masterarmresources.go, pkg/engine/virtualmachinescalesets.go
We have some identified regressions based on this api model input:
```
{
"apiVersion": "vlabs",
"location": "westus",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"orchestratorRelease": "1.13",
"kubernetesConfig": {
"enableRbac": true,
"useManagedIdentity": true,
"useInstanceMetadata": true,
"cloudProviderBackoff": true,
"cloudProviderBackoffRetries": 6,
"cloudProviderBackoffJitter": 1,
"cloudProviderBackoffDuration": 6,
"cloudProviderBackoffExponent": 1.5,
"cloudProviderRateLimit": false,
"cloudProviderRateLimitQPS": 3,
"cloudProviderRateLimitBucket": 10,
"etcdDiskSizeGB": "4000",
"networkPlugin": "azure",
"enableEncryptionWithExternalKms": true,
"keyVaultSku": "Premium",
"controllerManagerConfig": {
"--route-reconciliation-period": …
```
=> fix: address regressions from v2 template refactor

packer/install-dependencies.sh
Organizes the versions in the VHD creation script so each is on its own line to make merge conflicts less likely. Also lists versions consistently in descending order.
Kubernetes releases tend to appear in groups, as they did on Monday. Creating more than one PR to add version support basically guarantees `git` merge conflicts since changes are made to different sections of the same line. This should avoid that problem. I think it's a bit easier to read as well.
**Notes**:
I only did this for components that actually have more than one version. We could expand it to all such variables, even those with a single value, for consistency if we prefer. Although in practice it's only the k8s versions and cluster-autoscaler that often …
=> refactor: put each version on its own line in VHD script

packer/install-dependencies.sh, pkg/api/const.go
See https://github.com/containernetworking/plugins/releases/tag/v0.7.5
This should have been included with #876 since it is mentioned in the Kubernetes v1.14.0 [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#external-dependencies):
> CNI has been updated to v0.7.5 (kubernetes/kubernetes#75455)
**Notes**:
=> chore: update CNI plugin to v0.7.5

.pipelines/pr-e2e.yaml
Removes Kubernetes 1.10 from Azure DevOps end-to-end testing.
Kubernetes 1.10 is [now unsupported](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) with the release of 1.14. This will save some testing resources.
*Edit*: actually, Kubernetes 1.11 is now unsupported according to the policy, and 1.10 has been unsupported since 1.13 was released. That's a stronger argument for removing 1.10.
**Notes**:
It's not impossible that Kubernetes 1.10 still could get a patch release in the event of an earth-shattering CVE, but it's not likely given the stated policy. Let me know if you think this is premature.
=> chore: remove Kubernetes 1.10 from e2e testing

pkg/armhelpers/azurestack/kubeclient.go, pkg/armhelpers/kubeclient.go
The default `Policy()` is [deprecated](https://github.com/Azure/aks-engine/blob/master/vendor/k8s.io/client-go/kubernetes/clientset.go#L320) (and is gone in current versions of kubernetes/client-go). AKS Engine should be using `PolicyV1beta1()`.
**Notes**:
=> chore: use V1beta1 Policy client, not the deprecated default

packer/install-dependencies.sh
Follow up from #459. We pre-pull gcr.io/google-containers/ip-masq-agent-amd64:v2.0.0 onto our VHDs but the default addon spec for ip-masq-agent specifies "k8s.gcr.io/ip-masq-agent-amd64:v2.0.0".  This PR updates the VHD script to pre-pull the both images. We keep the gcr.io/google-containers for now because AKS uses it. In the future, we will update AKS to use the same image as AKS Engine and remove the old image from the VHD.
#910
**Notes**:
=> fix: ip-masq-agent container image has a different repo base in VHD

extensions/prometheus-grafana-k8s/v1/prometheus-grafana-k8s.sh
The prometheus-grafana (and cadvisor) extension use an extensionParameter to customize its  deployment, as documented here. 
https://github.com/Azure/aks-engine/tree/master/extensions/prometheus-grafana-k8s#configuration
This is nice, but I noticed the cAdvisor deployment was not namespaced when using it. 
**Notes**:
=> fix : prometheus-grafana extension : cAdvisor deployment is not namespaced

parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/kubernetesconfigs.sh, parts/k8s/kubernetesmastercustomdata.yml, pkg/api/addons.go, pkg/engine/const.go
- Upgrade calico to v3.5
- Allow calico to work with azure CNI by setting 
```NetworkPolicy: "calico" , NetworkPlugin: "azure"```
In this case, calico per-host daemon works with azure CNI plugin and azure IPAM to support network policy. 
- Continue support kubenet network plugin by setting
```NetworkPolicy: "calico" , NetworkPlugin: "kubenet"```
**Notes**:
=> chore: Update calico to 3.5 and allow calico to work with azure CNI

pkg/armhelpers/utils/util.go, pkg/armhelpers/utils/util_test.go, pkg/engine/transform/transform.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrader.go
Upgrade windows nodes's kubernetes version requires keeping the custom data of the windows profile because the kubernetes version is fixed in the custom data.
Also added retry with a 5 minutes timeout for copying node properties because windows node takes a little bit longer to show up.
**Notes**:
=> fix: AKS VMSS windows agent pool upgrade

parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsazurecnifunc.ps1
For windows node provisioned in custom vnet with CNI, we should include VNETCIDR in the outbound NAT exception list. Otherwise VMs in different subnet won't be able to reach the windows pods.
**Notes**:
=> fix: include vnet CIDR in windows node CNI outbound NAT exception list

pkg/engine/vmextensions.go, pkg/engine/vmextensions_test.go
The AADClientSecret needs to be escaped in case it contains a special character such as `)`
Fixes #926 
**Notes**:
Not tested, relying on automation to test it
=> fix: #926 Escape servicePrincipalClientSecret in Windows custom script block

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetescustomscript.sh, parts/k8s/kubernetesinstalls.sh, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesprovisionsource.sh
Reverts Azure/aks-engine#870
Following this change, we're seeing regressions in CSE performance. Let's consider discrete changes here for re-introduction (especially the "disable unattended upgrades during first boot", as that may increase the stability of purposeful apt operations).
=> revert: improve CSE script

pkg/operations/kubernetesupgrade/upgradeagentnode.go, pkg/operations/kubernetesupgrade/upgrader.go
There are cluster configuration scenarios (e.g., vms that have lots of persistent volumes) for which a 1 minute cordon/drain timeout isn't sufficiently long. Let's unblock these quickly by increasing the timeout to 20 mins. A // TODO for later is to make this a user-configurable timeout.
Fixes #930 
**Notes**:
=> fix: increase cordon/drain timeout to 20 mins during upgrade

pkg/engine/virtualmachines.go, pkg/engine/virtualmachines_test.go
Addresses a regression introduced in #682. With the strongly typed representation of a vm, we now need to evaluate just a string to include inside the strongly typed array. Using the pre-template refactor ARM expression was resulting in an array inside an array, breaking the type req's.
Fixes #902
**Notes**:
=> fix: zones values for VMAS masters is an array of a single string

pkg/api/defaults.go, pkg/api/defaults_test.go
For a period of time, there was a bug in default assignment w/ respect to `enableAggregatedAPI` and `enableRBAC`. Specifically: `enableAggregatedAPI` configuration depends upon `enableRBAC` (the former can only be `true` if the latter is also `true`).
Proper default enforcement was implemented here:
https://github.com/Azure/acs-engine/pull/3813
Prior to that it was possible to create a cluster w/ a pathological config (primarily because CSE was permissive to `enableAggregatedAPI` being set to true without RBAC, see https://github.com/Azure/acs-engine/pull/3751 for when that started to change).
The purpose of this PR is to detect pathological configurations in upgrade scenarios, and to fix them via defaults enforcements flow.
Fixes #905 …
=> fix: fix disable rbac + enable aggregated API upgrade bug

parts/k8s/addons/coredns.yaml, test/e2e/kubernetes/kubernetes_test.go
Mounts an emptyDir at /tmp in the coredns container and reenables the dns-liveness test, in hopes that this works around a container restart issue as suggested [here](https://github.com/kubernetes/kubernetes/issues/75414#issuecomment-479905336).
**Notes**:
=> fix: mount tmp emptyDir to stop CoreDNS restarts

parts/k8s/kubernetesconfigs.sh
Enables calico 3.5 for the AKS / hosted masters code path by calling `configureCNIIPTables` unconditionally. Basically reverting #952.
Fixes #993
**Notes**:
=> feat: enable calico 3.5 for AKS

pkg/api/types.go, pkg/api/types_test.go, pkg/engine/armoutputs.go, pkg/engine/armvariables.go, pkg/engine/masterarmresources.go, pkg/engine/storageaccounts.go, pkg/engine/template_generator.go
Noticed that some isPrivateCluster assignments were missing nil checks and got carried away... This makes sure the function is in one central place and is unit tested.
**Notes**:
=> refactor: move isPrivateCluster to types.go

.pipelines/e2e-step-template.yaml, packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/api/types.go, pkg/api/types_test.go, test.mk, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/util/util.go
Assigns a root password if none exists. Doing this via the cis.sh interface, which will be invoked by VHD and base OS image creation flows.
Also, as a point of hygiene, moving the `installDeps` above `installEtcd`, as the former should be done prior to the latter.
Includes E2E test coverage, which required that we shore up ssh-agent forwarding. For now this test is only enabled on ubuntu distro cluster configurations (as the enforcement isn't present on VHDs yet).
Fixes #964
**Notes**:
=> chore(CIS): assign root pw

parts/k8s/cloud-init/artifacts/cse_main.sh
#892 introduced a regression by using by checking `if [[ $FULL_INSTALL_REQUIRED ]]` which always evaluates to true since that var is assigned as a string. The correct way to check if it is true is with `[ "$FULL_INSTALL_REQUIRED" == "true" ]`. Also change the `OS` check to only run these lines for `UBUNTU since that's more explicit (and allows us to add more OSes later on without breaking this flow.
**Notes**:
=> fix: only run installDeps in non-VHD scenarios

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
In some upgrade tests we're seeing the `k get nodes` return list of nodes after scale in. This change should allow us to further filter out non-Ready nodes to ensure we don't do e.g., ssh to node tests against nodes in a state of deletion that don't actually have functional VMs behind them.
**Notes**:
=> test: ensure node is ready before running validations

packer/install-dependencies.sh, packer/vhd-image-builder.json, parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Follow-up from PRs #1024 and #1031 to include validation tests; and to only pave files via cloud-init in non-VHD flows.
**Notes**:
=> chore: backport tests + cloud-init usage for CIS changes

pkg/engine/armvariables.go
The parameter for  ScaleSetEvictionPolicy is defined as `"{{.Name}}ScaleSetEvictionPolicy"`. This fixes a regression from the template refactor which referenced a param `<agentName>EvictionPolicy` that doesn't exist.
https://github.com/Azure/aks-engine/blob/master/parts/agentparams.t#L30
Fixes #1058 
**Notes**:
=> fix: fix parameter name for ScaleSetEvictionPolicy

parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_main.sh
Looking at the VHD build logs, I found that the chmod commands were always failing because the directory part of the path was missing. I fixed the path and also fixed error handling in the script so we actually exit on errors from now on.
**Notes**:
=>  fix: error handling in CIS bash script

parts/k8s/cloud-init/artifacts/cse_config.sh
This has been fixed:
https://github.com/kubernetes/kubernetes/pull/67478
**Notes**:
=> fix: no longer need 1.12 kubelet start workaround

parts/k8s/cloud-init/artifacts/kubelet.service, test/e2e/kubernetes/scripts/net-config-validate.sh
Works around a [TCP reset bug](https://github.com/kubernetes/kubernetes/issues/74839) in Kubernetes by setting the value of kernel parameter `net.netfilter.nf_conntrack_tcp_be_liberal` to `1` (true) before starting `kubelet`. 
Also piggy-backs on the `net-config-validate.sh` script to test this parameter as well as`net.ipv4.tcp_retries2` (which was also set by `kubelet.service`).
See [Debugging an Intermittent Connection Reset](https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/) for a good explanation of the issue.
Fixes #1068 
**Notes**:
=> fix: make conntrack more liberal on packets

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
Evolving our "log onto node vms and run tests" pattern so that we always only log onto a "Ready" node. This is to accommodate long-running test scenarios, e.g., running a battery of E2E tests immediately after a "scale in" operation. In such scenarios, there is a high likelihood that a "NotReady" node will be in a delete reconciliation state, and won't be backed by a VM; and so an remote ssh command onto that vm will fail.
This is a follow-up from #1045. This PR is more general.
**Notes**:
=> test: add nodes.GetReady() method for E2E tests

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/scripts/time-sync-validate.sh
Add ubuntu host OS time sync validation to regular E2E tests.
**Notes**:
=> test: add ubuntu time sync E2E validation

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/scripts/host-os-dns-validate.sh
This simplifies the Linux host OS DNS E2E tests a bit.
1. consolidates all tests into a single shell script
2. runs this validation earlier in the E2E run as later tests will not work if host DNS (for example) is not healthy; in such cases we want to fail on the actual failure, which is host OS DNS
3. adds additional vm DNS resolution coverage: now all node vms will be validated against being able to resolve all nodes (previously we were just checking that the master could resolve node vns)
4. adds retry tolerance
**Notes**:
=> test: single host OS DNS test script

packer/install-dependencies.sh
Alert in release notes when a VHD build takes more than 75% space. Error when it's more than 90%.
#1064 
**Notes**:
=> ci: Add alert on VHD space greater than 75%

parts/k8s/cloud-init/artifacts/cse_helpers.sh
To prevent scripted apt operations from stalling waiting for interactive input, we should always ensure that `apt` executions have a `DEBIAN_FRONTEND=noninteractive` env context.
**Notes**:
=> chore: always ensure apt runs non-interactively

test/e2e/kubernetes/scripts/net-config-validate.sh
Restores a bonus test from #1093 that was unrelated to the problem with setting `net.netfilter.nf_conntrack_tcp_be_liberal`.
**Notes**:
=> test: check net.ipv4.tcp_retries2 kernel parameter

cmd/scale.go, docs/topics/scale.md, pkg/api/types.go, pkg/api/types_test.go, pkg/armhelpers/utils/util.go, pkg/engine/armvariables.go, pkg/engine/template_generator.go
The scale code sets the container service to only have 1 agent pool, the one that is being scaled, https://github.com/Azure/aks-engine/blob/master/cmd/scale.go#L346.
When we generate the new template to deploy, we get the VM name prefix using https://github.com/Azure/aks-engine/blob/master/pkg/api/types.go#L835, which calculates the pool index according to the pool's position in the agent pool array - thus, new VMs always have an agent pool index of 00.
This is especially an issue because if there are 2 Windows pools:
3831k8s010
3831k8s011
3831k8s020
3831k8s021
And I scale pool 1, it will add a node named 3831k8s002. If I scale pool 2 after first scale, it will create a node named 3831k8s002 again, which will conflict with the existing one.
Fixes …
=> fix: use the actual pool index in the VM prefix for windows scale operations

pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go
Adds `WindowsProfile` into the standard defaults enforcement code flow. We retain the existing ARM parameters defaults to ensure back-compat defaults enforcement for pre-existing clusters.
This PR delivers the following opinionated defaults, which are subject to review:
```
// DefaultWindowsPublisher sets the default WindowsPublisher value in WindowsProfile
DefaultWindowsPublisher = "MicrosoftWindowsServer"
// DefaultWindowsOffer sets the default WindowsOffer value in WindowsProfile
DefaultWindowsOffer = "WindowsServerSemiAnnual"
// DefaultWindowsSku sets the default WindowsSku value in WindowsProfile
DefaultWindowsSku = "Datacenter-Core-1809-with-Containers-smalldisk"
// DefaultImageVersion sets the default ImageVersion value in WindowsProfile
DefaultImageVersion = …
```
=> feat: enable WindowsProfile in defaults enforcement code flow

pkg/api/converterfromagentpoolonlyapi.go
In master there is some (old) code that fails `govet` with golangci-lint v1.16.0. This removes a redundant nil check to satisfy it. Look at the code just above the diff to see why it's redundant.
```
==> Running static validations and linters <==
pkg/api/converterfromagentpoolonlyapi.go:148:8: nilness: tautological condition: non-nil != nil (govet)
if kc != nil && kc.EnableRbac != nil && *kc.EnableRbac {
^
Makefile:138: recipe for target 'test-style' failed
make: *** [test-style] Error 1
```
Unblocks #1088 
**Notes**:
I'm not sure how this made it into master without us noticing. The code hasn't been changed, and the linter version changed a while ago...
=> style: remove unneeded nil check

parts/k8s/cloud-init/artifacts/cis.sh
Adds `/var/log/landscape/sysinfo.log and /var/log/unattended-upgrades/unattended-upgrades-dpkg.log` to `assignFilePermissions`. Fixes E2E with Ubuntu 18.04-LTS distro.
**Notes**:
=> chore: add two missing /var/log files for 18.04 in CIS script

test/e2e/kubernetes/kubernetes_test.go
We need to *only* test `Ready` nodes for DNS records, as in scale in scenarios the k8s API may report back nodes that have been deleted (including associated DNS recordse). E.g. in the below test output `k8s-agentpool1-17958128-vmss000001` was recently deleted due to a scale in:
```
+ cat /etc/resolv.conf
nameserver 168.63.129.16
search imudjfrnoytevm05fafjnpihzc.lx.internal.cloudapp.net
+ set +x
++ dig +short +search +answer k8s-agentpool1-17958128-vmss000000
+ '[' -s 10.240.0.4 ']'
+ '[' 1 -eq 0 ']'
+ set +x
++ dig +short +search +answer k8s-agentpool1-17958128-vmss000001
+ '[' -s ']'
+ '[' 0 -eq 0 ']'
+ success=no
+ break
+ [[ no == \y\e\s ]]
+ '[' 1 -eq 1 ']'
+ exit 1
```
**Notes**:
=> test: only test Ready nodes for DNS

pkg/engine/armresources.go, pkg/engine/roleassignments.go, pkg/engine/roleassignments_test.go
Background: there is an upcoming feature in AKS: support authenticating to Azure using MSI. In the implementation, agent nodes will use an auto-generated user assigned identity and master components won't use this identity to authenticate. In this case, it enough to grant the generated user assigned identity only "Reader" role in the created resource group. 
**Notes**:
=> feat: grant user assigned identity 'Reader' role for hosted cluster

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go
This PR reduces the ARM template overhead in non-ubuntu distro (i.e., VHD) scenarios. The vars that we deliver to populate cloud-init are only needed when cloud-init will actually consume them.
**Notes**:
=> chore: reduce cloud-init var overhead for VHD scenarios

parts/k8s/cloud-init/artifacts/cis.sh
#1111 included a bug in VHD `/etc/default/grub` enforcement
Follow up from #1111
**Notes**:
=> fix: /etc/default/grub VHD enforcement

parts/k8s/cloud-init/artifacts/cis.sh
#1112 ommitted the step necessary to allow VHD CI script to pave `/etc/pam.d/su`
Follow-up of #1112
**Notes**:
=> fix: enable VHD enforcement of /etc/pam.d/su

pkg/engine/const.go
I'm seeing a linter error in master with the correct version of golangci-lint:
```shell
$ make test-style
==> Running shell script validator <==
==> Running static validations and linters <==
pkg/engine/const.go:155:2: U1000: const `kubernetesKubeletMonitorSystemdTimer` is unused (unused)
kubernetesKubeletMonitorSystemdTimer     = "k8s/cloud-init/artifacts/kubelet-monitor.timer" // TODO enable
^
make: *** [test-style] Error 1
```
**Notes**:
=> style: comment out unused constant

packer/install-dependencies.sh
AKSe assumes that both `hyperkube` and `pause` share the same repository prefix.
In the past, the Azure Stack team re-tagged the official pause image and re-pushed to docker hub to satisfy this requirement.
For disconnected instances, we need to pre-pull or re-tag during the VHD provisioning process.
Fixes #990
=> feat: pre-pull Pause from Azure Stack's docker repo

parts/k8s/addons/kubernetesmasteraddons-elb-svc.yaml, pkg/engine/loadbalancers.go, pkg/engine/loadbalancers_test.go, pkg/engine/masterarmresources.go
Azure Standard Load Balancers do not grant outbound access by default to backend VMs by default. This PR adds a UDP LB rule to the Standard LB spec to enable UDP outbound internet access on master VMs behind a Standard LB.
Additionally, added a UDP svc spec to enable UDP outbound for nodes.
Fixes #1099 
Fixes #1125
**Notes**:
=> fix: add UDP Standard LB rule to enable outbound access

pkg/operations/kubernetesupgrade/upgrader.go
When testing changes from PR #938 I found that the [`WaitForDelete`](https://github.com/Azure/aks-engine/blob/c2229858c671013388bd2e14776d357fc9edc386/pkg/armhelpers/kubeclient.go#L144) call to delete/evict a pod was still using a 10s timeout. This caused some pods to not evict in time and the upgrade to fail. To quickly address this I have updated the getKubernetesClient to allow the `cordonDrainTimeout` to be passed in. 
Fixes #930 
**Notes**:
=> fix: use cordon/drain timeout for pod eviction timeout during upgrade

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
```
[INFO] 2 Worker Node Security Configuration
[INFO] 2.1 Kubelet
[FAIL] 2.1.12 Ensure that the --rotate-certificates argument is not set to false (Scored)
[FAIL] 2.1.13 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
2.1.12 If using a Kubelet config file, edit the file to add the line rotateCertificates: true.
If using command line arguments, edit the kubelet service file /etc/systemd/system/kubelet.service
on each worker node and add --rotate-certificates=true argument to the KUBELET_CERTIFICATE_ARGS variable.
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload
systemctl restart kubelet.service
2.1.13 Edit the kubelet service file /etc/systemd/system/kubelet.service
on each worker node and set …
```
=> chore(CIS): add rotate kubelet certs flag

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
Tests show that the change introduced in #1052 breaks k8s clusters < 1.11. Disable "--rotate-certificates" kubelet config flag for those versions.
**Notes**:
=> fix: --rotate-certificates failing in k8s versions prior to 1.11

.golangci.yml, .pipelines/pr-e2e.yaml, pkg/engine/loadbalancers.go, scripts/validate-go.sh, scripts/validate-shell.sh
The `golangci-lint` tool [doesn't return an error](https://github.com/golangci/golangci-lint/issues/276) if it can't do its job because the Go source code won't compile. This fixes that by returning an error if the command output includes `skipped due to error`. Hopefully this closes the loophole that has allowed a couple of linter errors to make it into master.
This also removes some dead Go code that was causing `govet` to complain, and adds the output of the `--version` command to the script for both the Go and shell linters to help users reproduce any failures.
**Notes**:
=> ci: return error if Go linter can't compile source code

.codecov/codecov.yml
Adds a mock implementation to codecov's exclusion list.
Refs #1160
**Notes**:
This will probably drop our coverage a bit, since it was artificially boosting it before. 😞
=> ci: exclude a test mock file from coverage report

parts/k8s/cloud-init/masternodecustomdata.yml
not setup-etcd.sh
For master vmss scenarios, kubelet configuration needs to be applied at runtime to direct apiserver communications to the local IP address. And this enforcement was incorrectly being done via etcd bootstrap script instead of general kubelet bootstrap script, which breaks cosmos etcd + master vmss scenarios
Fixes #1181
**Notes**:
=> fix: kubeconfig enforcement via kubelet.sh

pkg/engine/keyvaults.go, pkg/engine/keyvaults_test.go
Restore `CreateKeyVaultVMSS` to the behavior it had before the template refactor for `enableEncryptionWithExternalKms`. Compare with:
https://github.com/Azure/aks-engine/blob/release-v0.31.0/parts/k8s/kubernetesmasterresourcesvmss.t#L76
Fixes #1034
**Notes**:
=> fix: enableEncryptionWithExternalKms with master VMSS missing objectID

test/e2e/kubernetes/kubernetes_test.go
#1188 and #1195 were not in fact the correct way to address failing E2E tests since the additional (CIS-influenced) OS validation tests were introduced. This PR re-introduces them for all scenarios, simply using the correct master SSH port for depending on whether vmss or vmas.
**Notes**:
=> test: enable all ssh to master tests for vmss masters

.chglog/config.yml
Some commits didn't show up in the [v0.35.0](https://github.com/Azure/aks-engine/releases/tag/v0.35.0) changelog initially because their message contained a scope field. This was because the `git-chglog` config file was generated initially with the simplified option. Updating the regex to the `msg(scope):` form fixes it.
**Notes**:
=> ci: permit optional scope field when generating changelog

packer/install-dependencies.sh, pkg/api/const.go, pkg/api/converterfromapi_test.go
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.21
**Notes**:
=> chore: update Azure CNI version to v1.0.22

parts/k8s/addons/kubernetesmasteraddons-managed-azure-storage-classes-custom.yaml, parts/k8s/addons/kubernetesmasteraddons-unmanaged-azure-storage-classes-custom.yaml, pkg/engine/artifacts.go
Remove azurefile as a valid storage class for Azure Stack deployments
#1220
**Notes**:
=> feat: remove azurefile storage class for Azure Stack

pkg/engine/masterarmresources.go, pkg/engine/masterarmresources_test.go, pkg/engine/networkinterfaces.go, pkg/engine/networkinterfaces_test.go, pkg/engine/networksecuritygroups.go, pkg/engine/networksecuritygroups_test.go, pkg/engine/virtualmachinescalesets.go
Private clusters do not currently deploy due to mixing of jumpbox and master resources, leading to variables absent or resources duplicated in the ARM templates. This PR separates and dedupes in the appropriate places, and fixes the corresponding tests to account for the behavior.
**Notes**:
=> fix: private cluster with VMSS masters, jumpbox

test/e2e/engine/template.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/util/util.go, test/e2e/kubernetes/workloads/ingress-nginx-elb.yaml, test/e2e/kubernetes/workloads/validate-dns-linux.yaml, test/e2e/kubernetes/workloads/validate-dns-windows-tcp.yaml, test/e2e/kubernetes/workloads/validate-dns-windows.yaml
Includes several modifications to E2E test implementations, especially to accommodate soak test scenarios:
- detect pre-existing resources that may have been left around from a prior run, and delete them
- Windows-specific changes to aid in reliable test signal
- now testing Windows DNS discretely
- "outbound internet access" test is literally that — validate 8.8.8.8 TCP 43
- configures HPA to more responsively upscale and downscale; this saves 3-4 minutes per test run on average
- combines the "ILB" and "nginx" test into a single "LoadBalancers validation" test
- removes an unnecessary "deploy IIS" test, as the "deploy and scale IIS" test includes everything in it
- reduces retry time for pod Readiness waiting to 10 seconds from 1 minute …
=> test: idempotent e2e changes for soak test scenarios

pkg/api/defaults-kubelet.go
Undefined Kubelet config values are populated from the Orchestrator profile,
which is always a Linux profile. Unsupported config keys for Windows must
be deleted after that step.
Fixes #1049 
**Notes**:
=> fix: Windows Kubelet issues error due to unsupported config

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
There are some open issues relating to kubelet flags defaults, let's get unit test coverage complete so that we can safely address these.
This PR uses empty string values to mark options as "not used", and then before rendering the final kubelet config map, we delete any keys that have `""` values. Unit tests should tell the story for expected default configuration functionality for all kubletConfig instances.
**Notes**:
=> fix: default kubelet flags windows/linux reconciliation w/ unit tests

pkg/engine/virtualmachinescalesets.go, pkg/engine/vmextensions.go
If I deploy to a disconnected Azure Stack instance, I would like to skip outbound connectivity validations.
Fixes #1249 
**Notes**:
I do not think we currently have a way of telling if the target Azure Stack is connected or disconnected.
For now, I am disabling the validation for all Azure Stack deployments. A subsequent PR will fix this.
=> fix: remove outbound connectivity check on disconnected Azure Stacks

parts/k8s/cloud-init/jumpboxcustomdata.yml
The cloud init yml for the jumpbox VM in private clusters resulted in root permissions for the default user. Fixed this in a foolproof way to ensure correct permissions.
Fixes #725
**Notes**:
No unit test, as in general testing on the jumpbox in private clusters is currently lacking some testing and this PR is not going to cure that.
=> fix: Proper permission on the HOME dir for user on jumpbox VM

pkg/api/defaults-kubelet_test.go
Follow-up from #1244 
We need to enumerate through the actual kubelet config keys to ensure that our expected set doesn't *exclude* anything. In other words, this change will fail unit tests if there's an additional config key that we aren't expecting.
**Notes**:
=> test: test for missing kubelet configs as well

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
chore(CIS):enable protect-kernel-defaults
PR(https://github.com/Azure/aks-engine/pull/999) does not enable `--protect-kernel-defaults` completely, this PR fixes this issue since below latest Ubuntu image has already enabled the required kernel flags in the VHD image:
```
"agentpoolosImageSKU": {
"value": "aks-ubuntu-1604-201904"
},
"agentpoolosImageVersion": {
"value": "2019.04.24"
},
```
/assign @jackfrancis 
**Notes**:
/hold
=> chore(CIS):enable protect-kernel-defaults

docs/tutorials/quickstart.md
If you try to run as per the documentation inside the container, it errors out because of auth-method as CLI when running it inside the linux container on windows.
Two probable solutions:
Either don't set the authentication method here
Or set the auth-method to client-secret 
Fixes the tutorial documentation for the case if running it inside the linux container on windows 
#1108 & #773 partially
**Notes**:
=> docs: aks-engine deploy tutorial errors out for auth method as CLI for linux container on windows

cmd/root.go, docs/topics/scale.md
Just a couple of typo fixes.
**Notes**:
=> docs: correct "--auth-method" arguments in help

parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml, parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml, parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml, parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
In k8s 1.15 this PR : https://github.com/kubernetes/kubernetes/pull/76953
removed aliases for k8s binaries in hyperkube ( i.e proxy alias for kube-proxy ).
This PR changes the commands in all manifests that invoke hyperkube
to use the full name of the binaries.
PR https://github.com/kubernetes/kubernetes/pull/76953 in kubernetes/kubernetes removed aliases for hyperkube binaries ( apiserver, proxy etc. ), thus the binaries have to be invoked by their full name ( kube-apiserver, kube-proxy etc. ).
This issue has been observed in upstream windows testing for k8s ( https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master ).
NOTE: 
- It does not affect aks-engine as it is now, as it only supports k8s 1.15.0-alpha.3 ( Change merged after this ) however it may …
=> Update hyperkube command in manifests for k8s components.

cmd/upgrade.go, cmd/upgrade_test.go, pkg/operations/kubernetesupgrade/upgradeagentnode.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrader.go
Make the cordon drain timeout value configurable in `--upgrade` command.
Fixes #950
**Notes**:
=> feat: Make cordon drain timeout configurable with --upgrade

pkg/operations/kubernetesupgrade/upgrader.go
Increase the time out for upgrade operation to 180 mins. 90 mins is not enough for agentpool with 18+ nodes.
**Notes**:
=> fix: increase upgrade timeout to 180 minutes

parts/k8s/cloud-init/artifacts/cis.sh, pkg/engine/templates_generated.go, test/e2e/kubernetes/scripts/CIS-files-validate.sh
All Linux E2E started failing today on `should validate all CIS VHD-paved files [It]` because the grub.cfg file is getting overwritten by something external.
**Notes**:
=> fix: remove grub file permissions enforcement

pkg/engine/masterarmresources.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachines_test.go
In cosmos etcd scenario we should not add a data disk for local etcd.
Fixes #1311
**Notes**:
=> fix: don’t add etcd data disk in cosmos etcd scenario

pkg/armhelpers/mockclients.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrader.go
Get VMSS node version from K8S API for instances with old model. Also adding back a missed lower case conversion
All instances in Azure VMSS share the same tags. So in case of partial agent pool upgrade failures, we will end up with nodes on both new model and old model. Yet, the tags of all nodes are of the new model. So retry upgrade in this situation ends up doing nothing. With this fix we will check whether each instance has the latest model applied before checking the tags. If not, we will use K8s API to get node version.
Also, adding back toLower to newnode name when copying node properties. 
**Notes**:
=> fix: Get VMSS node version from K8s API instead of tags for old instances

.pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.22.1
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.5
**Notes**:
~~I updated `$DEIS_GO_DEV_IMAGE` on Jenkins to match this change.~~
=> chore: update go toolchain to 1.12.5

pkg/api/common/helper.go, pkg/api/common/helper_test.go, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
```
"IsAzureStackCloud",
"IsMasterVirtualMachineScaleSets",
"IsHostedMaster",
"IsIPMasqAgentEnabled",
"IsKubernetesVersionGe",
"IsKubernetesVersionLt",
"GetMasterKubernetesLabels",
"GetAgentKubernetesLabels",
"GetKubeletConfigKeyVals",
"GetKubeletConfigKeyValsPsh",
"GetK8sRuntimeConfigKeyVals",
```
**Notes**:
=> test: getTemplateFuncMap unit tests part 1

docs/tutorials/quickstart.md
aks-engine deploy command fails as written.  client-id and client-password flags are required.
**Notes**:
=> fix:Update quickstart.md

scripts/validate-shell.sh, test/common.sh, test/deploy.sh, test/e2e.sh
Warns about exiting with a return code that isn't between 0 and 255.
See https://github.com/koalaman/shellcheck/wiki/SC2242
Refs #953 
**Notes**:
=> style: shell commands can only exit with status 0-255

pkg/api/common/helper.go, pkg/api/common/helper_test.go, pkg/api/const.go, pkg/api/defaults-apiserver.go, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/armvariables.go, pkg/engine/const.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/masterarmresources.go, pkg/engine/networkinterfaces.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachinescalesets.go
```
"HasPrivateRegistry",
"IsSwarmMode",
"IsKubernetes",
"IsPublic",
"IsAzureCNI",
"HasCosmosEtcd",
"GetCosmosEndPointUri",
"IsPrivateCluster",
"ProvisionJumpbox",
"UseManagedIdentity",
"NeedsKubeDNSWithExecHealthz",
"GetVNETSubnetDependencies",
"GetLBRules",
```
**Notes**:
=> test: getTemplateFuncMap unit tests part 2

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/engine/templates_generated.go
Backwards compatibility is broken in master because the moby install function is trying to install moby-cli 3.0.4 for clusters that were deployed with previous versions of aks-engine that had mobyVersion `3.0.4`.
#1355 
**Notes**:
=> fix: never use 3.0.4 for moby-cli and update moby on upgrade

pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/engine/templates_generated.go
The distro value needs to be set to `Ubuntu` for Azure clouds that don't support the VHD distros yet. Overriding the image value does not suffice since we do introspection on the distro value in the code to determine other cluster configurations (for example --protect-kernel-defaults kubelet flag).
#1291 
**Notes**:
=> fix: do not set distro to VHD for US Gov and German cloud

parts/dcos/bstrap/bootstrapparams.t, parts/dcos/bstrap/bootstrapresources.t, parts/dcos/bstrap/dcosmasterresources.t, parts/dcos/dcosagentresourcesvmas.t, parts/dcos/dcosagentresourcesvmss.t, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/engine_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
```
"GetProbes",
"GetSecurityRules",
"GetUniqueNameSuffix",
"GetVNETAddressPrefixes",
"GetVNETSubnets",
"GetDataDisks",
"HasBootstrap",
```
Also removed the entirely unnecessary `HasBootstrapPublicIP` and `IsHostedBootstrap` static `return false` template functions.
**Notes**:
=> test: getTemplateFuncMap unit tests part 3

pkg/api/defaults.go, pkg/api/defaults_test.go
When a cluster is upgraded or scaled currently, the etcd version and containerd version in. the apimodel get persisted instead of getting bumped to the latest. This PR changes the behavior to match other components by updating the version of etcd and containerd during update operations.
**Notes**:
=> fix: update etcd and containerd versions during upgrade

pkg/engine/transform/apimodel_merger.go, pkg/engine/transform/apimodel_merger_test.go
This fix enables configuring `etcdPeerCertificates` using `--set certificateProfile.etcdPeerCertificates[0]="aaa" --set certificateProfile.etcdPeerCertificates[1]="aaa"`
minor: It also fixes diagnostic formatting to use decimal numbers instead of binary numbers
**Notes**:
=> feat: added support for direct array assignment using --set

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
This PR remove `--allow-privileged` in kubelet config from k8s v1.15.0, since `--allow-privileged` is removed in this k8s upstream PR: https://github.com/kubernetes/kubernetes/pull/77820
Fixes#1368
**Notes**:
=> fix: remove "allow-privileged" in kubelet 1.15.0

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1150-alpha3
**Notes**:
~~Requires #1369 to merge before this will pass.~~ *Merged*
CoreDNS was bumped to 1.5.0, but I think this may require configuration changes. I'll take a look at that next.
=> feat: add support for Kubernetes 1.15.0-beta.1

pkg/engine/cosmosdb.go, pkg/engine/cosmosdb_test.go
multiple cosmosdb regions for a single customer is not currently supported by cosmosdb
See:
https://azure.microsoft.com/en-us/resources/videos/azure-cosmosdb-global-distribution/
Fixes #1400
**Notes**:
=> fix: disable redundant cosmosdb regions

pkg/api/addons.go, pkg/api/addons_test.go
Currently, we only set default addon values for addons when they are enabled but we still populate the defaults if the addon itself was omitted from the apimodel and is disabled by default. Although this has no functional impact, it is counter intuitive. As a user, when upgrading I would expect my addon Images to be refreshed, even if an addon is disabled or wasn't included in my input apimodel (since it will be included in the expanded apimodel). See #1372 for more details.
Steps to repro
- Deploy a cluster without specifying an addon that is disabled by default (eg. cluster-autoscaler)
- Note that the addon is added to the Addons section of the generated apimodel with `Enabled: false`.
- Upgrade the cluster with a more recent aks-engine version where the default …
=> fix: prune addon defaults if the addon is disabled

docs/topics/azure-stack.md
Deploying the sample extensions fails on Azure Stack because of a CRP version mismatch.
Adding a few lines to the Azure Stack doc to explain the situation and offer a workaround.
=> docs: sample extensions workaround for Azure Stack

Gopkg.lock, pkg/armhelpers/azurestack/kubeclient.go, pkg/armhelpers/interfaces.go, pkg/armhelpers/kubeclient.go, pkg/armhelpers/mockclients.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrader.go, vendor/github.com/sirupsen/logrus/alt_exit.go, vendor/github.com/sirupsen/logrus/entry.go, vendor/github.com/sirupsen/logrus/exported.go, vendor/github.com/sirupsen/logrus/hooks/test/test.go, vendor/github.com/sirupsen/logrus/json_formatter.go, vendor/github.com/sirupsen/logrus/logger.go, vendor/github.com/sirupsen/logrus/logrus.go, vendor/github.com/sirupsen/logrus/terminal_check_aix.go, vendor/github.com/sirupsen/logrus/terminal_check_bsd.go, vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go, vendor/github.com/sirupsen/logrus/terminal_check_unix.go, vendor/github.com/sirupsen/logrus/text_formatter.go
Pauses cluster-autoscaler during `aks-engine upgrade` to avoid problems, then resumes it after upgrade completes. Also uses the VMSS `Capacity` field for the agentpool `Count` to avoid off-by-N errors.
Fixes #401 
See also #881 and kubernetes/autoscaler#860
**Notes**:
=> fix: pause cluster-autoscaler and use VMSS capacity when upgrading

parts/agentparams.t, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go, pkg/helpers/azureconst.go, pkg/helpers/azureconst_test.go, pkg/helpers/generate_azure_constants.py
```
"GetMasterAllowedSizes",
"GetDefaultVNETCIDR",
"GetKubernetesAllowedVMSKUs",
"GetSizeMap",
"WriteLinkedTemplatesForExtensions",
"GetSshPublicKeysPowerShell",
"GetWindowsMasterSubnetARMParam"
```
`GetKubernetesAllowedVMSKUs` is a rename of `GetAgentAllowedSizes` to more clearly express what it is.
Also includes unit test coverage of extention convenienc functions.
**Notes**:
=> test: getTemplateFuncMap unit tests part 4

cmd/scale.go, pkg/api/types.go, pkg/api/types_test.go, pkg/armhelpers/azureclient.go, pkg/armhelpers/azureclient_test.go, pkg/armhelpers/azurestack/azureclient.go, pkg/armhelpers/azurestack/compute.go, pkg/armhelpers/azurestack/compute_test.go, pkg/armhelpers/azurestack/httpMockClient.go, pkg/armhelpers/azurestack/httpMockClientData/getAvailabilitySet.json, pkg/armhelpers/compute.go, pkg/armhelpers/interfaces.go, pkg/armhelpers/mockclients.go, pkg/engine/armresources_test.go, pkg/engine/armtype.go, pkg/engine/armtype_test.go, pkg/engine/availabilitysets.go, pkg/engine/availabilitysets_test.go, pkg/engine/engine_test.go, pkg/engine/masterarmresources_test.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, scripts/fault_domains_expr.py
Changes the hard-coded default of `2` for an availability set's `platformFaultDomainCount` to an ARM expression that will calculate the available number of fault domains in the deployment location. Also respects the current availability sets' value during scale and upgrade.
Fixes #671
**Notes**:
There is definitely some weirdness in here, so I'm looking for feedback. ~~There are no tests yet, but~~ I have tested it thoroughly by hand.
=> feat: use all VMAS fault domains in a region

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#changelog-since-v1136
**Notes**:
=> feat: add support for Kubernetes 1.13.7

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1142
**Notes**:
=> feat: add support for Kubernetes 1.14.3

parts/k8s/addons/1.15/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml, parts/k8s/addons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml, pkg/api/common/versions.go, pkg/engine/templates_generated.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1150-beta1
and kubernetes/kubernetes#78242
**Notes**:
Is it ok to add this new `ClusterRole[Binding]` in general, or should it be scoped to k8s 1.15+?
=> feat: add support for Kubernetes 1.15.0-beta.2

cmd/deploy.go, cmd/deploy_test.go
This is a simpler method of running cluster configuration validation during `aks-engine deploy`
**Notes**:
=> refactor: run full validation for aks-engine deploy

examples/e2e-tests/kubernetes/windows/hybrid/definition.json
`VirtualMachineScaleSets` has been the recommended default for k8s > 1.10 per https://github.com/Azure/aks-engine/blob/windows-vmss/docs/topics/clusterdefinitions.md#L530 , but the PR test passes are using `AvailabilitySet`
=> test: Switch Windows test passes to VMSS by default to match AKS

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/engine/templates_generated.go
This PR fixed the following CIS failure:
```
[FAIL] 2.1.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Scored)
== Remediations ==
2.1.10 If using a Kubelet config file, edit the file to set tlsCertFile to the location of the certificate
file to use to identify this Kubelet, and tlsPrivateKeyFile to the location of the
corresponding private key file.
If using command line arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf on each worker node and
set the below parameters in KUBELET_CERTIFICATE_ARGS variable.
--tls-cert-file=<path/to/tls-certificate-file>
file=<path/to/tls-key-file>
Based on your system, restart the kubelet service. For example:
systemctl daemon-reload …
```
=> chore(CIS): generate kubelet server cert in aks-engine

parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
We apt-mark hold walinuxagent in cloud init but there is no guarantee that that code will execute before apt-get upgrade and apt-get dist-upgrade run in CSE. 
Partly reverts https://github.com/Azure/aks-engine/pull/778.
**Notes**:
=> fix: fix race condition between cloud init walinuxagent hold and CSE

parts/k8s/cloud-init/artifacts/apt-preferences, pkg/engine/templates_generated.go
Why remove this?
- This was added in https://github.com/Azure/aks-engine/pull/778 to "to further protect against runtime changes to the walinuxagent". #1471 proved that this does not actually work. 
- Different clouds/regions might different walinuxagent versions rolled out so pinning to one version might break sovereign clouds that don't have the latest version available.
- Having this setting introduces friction to have the latest walinuxagent version as we are not actively monitoring agent releases, which might lead us to run into bugs in the future that would have otherwise been fixed in the latest version. I would argue we should delegate walinuxagent version updates to the linux agent team and not override it.
**Notes**:
=> fix: remove walinuxagent version pin

test/e2e/azure/cli.go, test/e2e/runner/cli_provisioner.go
As a convenience, add subnets to route table in E2E "custom VNET" test scenarios.
**Notes**:
=> test: add subnets to route table in E2E for custom vnet + kubenet

test/e2e/engine/template.go
Two things:
- `--horizontal-pod-autoscaler-downscale-stabilization` and `--horizontal-pod-autoscaler-cpu-initialization-period` were introduced in k8s 1.12, so we can only set that value if the cluster is >= 1.12
- the way the runner is setting the config is only if the api model `KubernetesConfig` is empty, which in practice it rarely is
**Notes**:
=> test: HPA scale down config only works if k8s >= 1.12

Gopkg.lock, pkg/engine/engine.go, vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go
After https://github.com/Azure/aks-engine/pull/506 was closed/merged it's still not possible to upgrade clusters with AAD support enabled. During the upgrade or scaling operation the error
`FATA[0377] Error upgrading cluster: No Auth Provider found for name "azure"`
still appears. This PR fixes that.
=> fix(auth): Explicitly import the AAD library to allow cluster upgrades

packer/install-dependencies.sh
Adds hyperkube support for Kubernetes 1.14.1 on Azure Stack to the VHD image script.
This was prompted by the docs changes in #1482.
**Notes**:
=> chore: add k8s 1.14.1 for Azure Stack to VHD script

packer/install-dependencies.sh
There is a mismatch between the [pre-pulled flannel image](https://github.com/Azure/aks-engine/blob/master/packer/install-dependencies.sh#L349) and [flannel's DS template](https://github.com/Azure/aks-engine/blob/bf4861fe098ab5114c892cbe09122574f0b972a9/parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml#L93)
This is breaking air-gapped deployments that rely on the VHD containing all dependencies.
=> fix: vhd pre-pulls expected flannel images tag

parts/k8s/addons/coredns.yaml
Upgrading clusters from previous versions to the current CoreDNS version break when this ConfigMap isn't also updated
/cc @mboersma
=> chore: CoreDNS configmap is not updated during upgrades

pkg/engine/templates_generated.go
#1493 was merged without including the output of `make generate` because the project still doesn't have a way to check. See #1318 for the continuing sad story.
**Notes**:
=> chore: update templates_generated.go

docs/topics/clusterdefinitions.md, pkg/api/const.go
This updates the last-known-good image to the latest Windows patch release. There were some issues that could break DNS in April/May cumulative updates. 
**Notes**:
/hold
I was expecting this to have a date on or after the 2nd Tuesday which is June 10, not June 4. I need to make sure this is the right one before merge.
=> chore: Change Windows default image to Jun 2019

docs/topics/clusterdefinitions.md, examples/windows/kubernetes-windows-1903.json, parts/k8s/windowsinstallopensshfunc.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go, test/e2e/engine/template.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/workloads/validate-dns-windows.yaml
This adds support for Windows Server version 1903, along with a sample and brief update to clusterdefinition.md. I also cleaned up the container version references and added comments to help identify what containers to use with the next Windows OS version change.
resolves #1462
**Notes**:
=> feat: Adding Windows Server version 1903 support

.pipelines/pr-e2e.yaml
The `Check if generated code is up to date` Azure DevOps task would always succeed because `make generate` had just been run in the previous `Run linting rules` task. This swaps them as a simple workaround.
Seems to work, as proved by #1406. 😅 
Fixes #1318
**Notes**:
=> ci: swap ensure-generated and test-style tasks

examples/kubernetes-releases/kubernetes1.14.json, examples/kubernetes-releases/kubernetes1.15.json, packer/install-dependencies.sh, pkg/api/common/versions.go, pkg/api/defaults_test.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md
**Notes**:
=> feat: add support for Kubernetes 1.15.0

docs/topics/clusterdefinitions.md
There's a new document describing what Windows Server images have been published to Azure. Let's link to it!
They're planning to add more details (offer/sku/version) to this doc over time so maybe people won't have to run `az vm list ...` and guess on which one to use in the future :)
=> docs: Link to more details on Windows images

pkg/api/types.go, pkg/api/types_test.go
Adds a `nil` check to fix upgrading with no masters and a test to prevent regression. Verified that the test panics without the fix.
**Notes**:
This bug was found by an AKS unit test when vendoring in the aks-engine v0.37.1 release.
=> fix: check for nil masterProfile when setting FD count

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/defaults.go, pkg/api/defaults_test.go
When upgrading to 1.14 from older AKS Engine versions, the api model will declare a `--pod-max-pids` kubeletConfig value of 100. Because the required feature flag to actually enforce that setting was disabled by default *until* 1.14, in practice this means that upgraded clusters will suddenly have a reduced PIDs/pods operational configuration, which will likely break many workload scenarios.
Fixes #1270
**Notes**:
=> fix: --pod-max-pids upgrade to 1.14 scenarios

pkg/api/addons.go, pkg/api/addons_test.go
For a very brief period of time we shipped a calico addon with functional configuration, but with a misleading `Enabled` value of `false`. See:
https://github.com/Azure/aks-engine/pull/1089/files#diff-d42c7f77841d06173c357c09c3ccbbf9R269
This PR anticipates this in an update scenario, sets the value of `Enabled` to true if `networkPolicy` == `calico`, and applies the appropriate defaults.
Fixes #1492
**Notes**:
=> fix: ensure calico is properly enabled during upgrade

parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
Since the mount content that we're including here is gzipped we need
this flag to cloud-init to gunzip it as it is being put in
place. Without this the file is still gzipped and systemd ignores it.
Fixes #1393
**Notes**:
=> fix: Set encoding:gzip on cilium BPFFS mount unit

docs/topics/azure-stack.md, packer/install-dependencies.sh
Adding 1.13.7 and 1.14.3 K8s images to be supported on Azure Stack.
Fixes #1373 
**Notes**:
=> chore: Add support for Kubernetes 1.13.7 and 1.14.3 on Azure Stack

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
A PR in-flight has an odd issue w/ nodes not getting upgraded to the expected version. Unfortunately that didn't generate an E2E error.
This PR expects the api model k8s version will be reflected in the node version, for every node in every agent pool, including master nodes.
**Notes**:
=> test: validate expected nodes version during E2E

parts/k8s/cloud-init/artifacts/etcd.service, pkg/engine/templates_generated.go
There is currenlty no ordering specified that the disk
`/var/lib/etcddisk` is available before etcd starts.
Predominately this is the case but on a hypervisor crash that disk
gets fscked and may not be available until later. Etcd will try for a
little while but will give up eventually leaving the master node
offline :-(
This patch tells systemd to add the ordering commands such that
etcd.service won't start till the disk is mounted.
Fixes #1515 
=> fix: Ensure etcd starts after disk is mounted (#1515)

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go
GPU install intermittently fails because unattended upgrades are running in the background resulting in:
```
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it
````
**Notes**:
=> fix: wait_for_apt_locks before GPU driver install

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
--anonymous-auth and --client-ca-file kubelet configuration enforcement is not responding to disabled EnableSecureKubelet properly
**Notes**:
=> fix: --anonymous-auth and --client-ca-file in insecure kubelet config

pkg/operations/kubernetesupgrade/upgradeagentnode.go, pkg/operations/kubernetesupgrade/upgrader.go
Tests suggest that AKS upgrade implementation is failing after client-go update to v10 because the k8s api client object isn't aware that its apiserver is listening on SSL + TCP 443
**Notes**:
=> chore: include https://fqdn:443 for AKS upgrade

docs/community/release-checklist.md
We should run `make build && make clean` before cutting a release to validate that the release branch we're cutting from has rationalized generated files.
**Notes**:
=> docs: make build before make clean in release docs

pkg/api/defaults.go, pkg/api/defaults_test.go
Currently fault domain count value is set using location condition based on the region. 
But in Azure Stack location value is not constant so we can't derive based on that.
Hence we setting PlatformFaultDomainCount value in SetAzureStackCloudSpec
Fixes #1528 
**Notes**:
=> feat: Set PlatformFaultDomainCount value as 3 for Azure Stack

examples/e2e-tests/kubernetes/release/default/definition.json
This PR proposes to update the cluster configuration definition used to validate basic Kubernetes on Azure functionality across k8s versions:
- changes from AvailabilitySet-backed VMs to VirtualMachineScaleSets-backed VMs
- removes the agent pool that tests non-managed disk
- enables cluster-autoscaler addon
- E2E tests covering this addon to be added later
- enables aad-pod-identity addon
- E2E tests covering this addon to be added later
- removes the addon configuration overrides for tiller, dashboard, and rescheduler
- we should be regularly testing the default configuration to validate the configuration that we are delivering to most users, not using this cluster configuration definition to validate user-configurable addon functionality …
=> test: update e2e api model definition

docs/topics/azure-stack.md, pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/engine/armvariables_test.go
PR update defaults to false for useInstanceMetadata and AcceleratedNetworkingEnabled on Azure Stack as both Instance service and Accelerated Networking are not supported yet.
Fixes #1378 #1380 
**Notes**:
=> feat: Add defaults for useInstanceMetadata and AcceleratedNetworkingEnabled on Azure Stack

parts/k8s/cloud-init/artifacts/cse_helpers.sh, pkg/engine/templates_generated.go
Distributions like Flatcar Linux sets `ID_LIKE=coreos` in `/etc/os-release` file.
This PR changes the way we set OS variable.
`sort -r` is used to always prefer ID_LIKE over ID, since `gawk` only
prints first line.
`/^ID(|_LIKE)=(.*)/` matches both `ID=` and `ID_LIKE=` and extracts the
value after `=` sign.
`print toupper(a[2]); exit` prints uppercased value and exits, so only
first line is always printed.
Closes #1559 
**Notes**:
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> feat: support CoreOS-like Linux distributions

examples/addons/appgw-ingress/README.md, examples/addons/appgw-ingress/kubernetes-appgw-ingress.json, parts/k8s/kubernetesparams.t, pkg/api/addons.go, pkg/api/const.go, pkg/api/defaults_test.go, pkg/api/types.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/applicationgateway.go, pkg/engine/applicationgateway_test.go, pkg/engine/armoutputs.go, pkg/engine/armoutputs_test.go, pkg/engine/armresources.go, pkg/engine/armtype.go, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/const.go, pkg/engine/ipaddresses.go, pkg/engine/ipaddresses_test.go, pkg/engine/masterarmresources.go, pkg/engine/params_k8s.go, pkg/engine/roleassignments.go, pkg/engine/roleassignments_test.go, pkg/engine/templates_generated.go, pkg/engine/userassignedidentities.go, pkg/engine/userassignedidentities_test.go, pkg/engine/virtualnetworks.go, pkg/engine/virtualnetworks_test.go
This PR adds support to deploy `Application Gateway` with the Kubernetes cluster to provide `ingress` support.
1) Azure `Application Gateway` is Azure's native layer-7 loadbalancer which additionally provides support for SSL Offload, WAF, Autoscaling, Private Ip, Redirects, etc.
2) [**Skipping adding ingress controller section, as discussed with Sean**] Ingress Controller is a controller that looks for `Ingress/Service/Endpoint/Pod` related changes on the cluster and configures the loadbalancer with the updated routing rules.
Ref: [Application Gateway Ingress Controller](https://github.com/Azure/application-gateway-kubernetes-ingress).
**Add-on Description**
This add-on will deploy an Application Gateway and dependency resources with your new Kubernetes cluster. …
=> feat: support for Application Gateway Ingress Controller

examples/kubernetes-config/kubernetes-accelerated-network.json
Due to Standard_D2_v3 not being supported with accelerated network due to 2 vCPUs, the example should use standard_D4_v3 instead.
Standard_D2_v3 is not supported with accelerated networking due to 2 vCPUs, changing to D4_v3 on the example makes the example valid. 
Fixes #1531 
**Notes**:
=> docs: changed accelerated networking example VMs

pkg/api/vlabs/const.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
On Azure Stack we dont support certain flags and expected to be in certain value or range.
This change add validation so that proper error is returned early and fail fast.
Fixes #1563 
**Notes**:
=> feat: Add checks for Metadata, AcceleratedNetworking and etcdDiskSizeGB on Azure Stack to fail fast.

pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go
Azure Stack only supports max disk size to be 1023GB. So in case when the number of nodes increases
we cant increase the size to 1024 or 2048GB.
Fixes #1557 
**Notes**:
=> feat: Set EtcdDiskSizeGB max default size to 1023 if target platform is Azure Stack

pkg/api/defaults.go, pkg/api/defaults_test.go
PR update defaults to false for AcceleratedNetworkingEnabledWindows on Azure Stack as Accelerated Networking are not supported yet on linux or windows.
Fixes #1567 
**Notes**:
=> feat: default AcceleratedNetworkingEnabledWindows to false if target platform is Azure Stack

parts/k8s/cloud-init/artifacts/cse_helpers.sh, pkg/engine/templates_generated.go
This reverts commit 31e804520e2839b823485ec8975a7a7da8b5722e.
#1560 broke Ubuntu distro deployments.
Repro steps:
- deploy cluster with `"distro": "ubuntu"`: `{   "apiVersion": "vlabs",   "properties": {     "orchestratorProfile": {       "orchestratorType": "Kubernetes",       "orchestratorRelease": "1.14",   "kubernetesConfig": {         "networkPlugin": "azure", "addons": [           {             "name": "tiller",             "enabled": false           },           {             "name": "aci-connector",             "enabled": false           },           {             "name": "blobfuse-flexvolume",             "enabled": false           },           {             "name": "smb-flexvolume",             "enabled": false           },           {             "name": …
=> revert: Revert "feat: support CoreOS-like Linux distributions (#1560)"

pkg/engine/params.go
azuredeploy.json
"vnetCidr": {
"defaultValue": "10.0.0.0/8",
"metadata": {
"description": "Cluster vnet cidr"
},
"type": "string"
},
azuredeploy.parameters.json overrides this with the empty string which results in an empty vnetCidr.
#1550 
**Notes**:
=> fix: do not override vnetCidr param when empty string

pkg/engine/armvariables.go
The kubeconfig generated in azuredeploy.json is incorrectly escaped which makes config invalid in jumpbox when doing `kubectl get pods` for example
Fixes #1552 
**Notes**:
=> fix: kubeconfig incorrectly escape characters for azuredeploy.json

packer/install-dependencies.sh
clear-containers has been replaced by Kata and is not used by AKS. After this PR, it will still be supported as an option but won't be pre-installed on the base image anymore.
Related to #1580 
**Notes**:
=> fix: do not install clear containers runtime on the VHD

test/e2e/kubernetes/kubernetes_test.go
Provides a temporary workaround for #1597 so we don't miss other failures that might be occurring in CI. cluster-autoscaler restarting several times on Linux but coming up `Ready` is still something to investigate, but the overall test is useful, so this disables testing for just that specific and logs it instead.
Refs #1597
**Notes**:
=> test: temporarily allow 10 CA restarts

parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/containeraddons/1.16/ip-masq-agent.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-tiller-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml, pkg/engine/templates_generated.go
Adds an explicit `selector:` to Deployment and DaemonSet manifests using apps/v1 (not -beta). This is no longer implicit in Kubernetes 1.16.
Fixes #1573 
**Notes**:
Most `apps/v1` manifests already had an explicit selector, so this just updates those that didn't.
=> fix: use explicit spec.Selector with apps/v1 api manifests

.gitignore, Makefile, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/kubernetes_test.go
A new pause image is needed to make `kubectl port-forward` work for Windows pods in 1.15. This won't fix it for <= 1.14.
resolves #1461 
cc @jchauncey
=> feat: Support kubectl port-forward with k8s 1.15 on Windows nodes

pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
Old VMSS AKS cluster cannot be upgraded after April 2
AKS-Engine changed AKS billing extension type from Compute.AKS-Engine.Linux.Billing to Compute.AKS.Linux.Billing in this PR (https://github.com/Azure/aks-engine/commit/bc462f1c49d5fc9bd93b9b7910504019853e4db9). The change was vendored into AKS on Apr. 2nd.  So any VMSS cluster created before the change will hit this problem during upgrade. New clusters should be fine.
Rename the billing extension to make the ARM deployment happy
**Notes**:
=> fix: old VMSS AKS cluster cannot be upgraded after April 2

parts/k8s/addons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/containeraddons/1.16/azure-cni-networkmonitor.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.1.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.1.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml, pkg/engine/templates_generated.go
Commit https://github.com/kubernetes/kubernetes/pull/79554 in
kubernetes/kubernetes removed the ExperimentalCriticalPodAnnotation feature
in kubernetes 1.16.
This PR aligns aks-engine with those changes, removing the feature-gate from
kube-proxy daemonset and the pod-critical annotations from any manifest that
uses it.
Fixes: https://github.com/Azure/aks-engine/issues/1617
=> fix: Remove pod-critical annotations in 1.16 manifests.

packer/install-dependencies.sh, pkg/api/common/versions.go
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1150
Closes #1641 
**Notes**:
=> feat: add support for Kubernetes 1.15.1

.pipelines/pr-e2e.yaml, examples/kubernetes-ubuntu-distro.json
Expand the functional test area of the "default" k8s cluster E2E job to include a non-VHD implementation. This will give advance notice of environmental flakiness that VHD-backed cluster configurations can protect against, in order to more effectively maintain our CustomScriptExtension (and other cluster bootstrapping areas) implementations.
The downside to this change are the following:
- slightly longer test runs for this job (depends upon network I/O to retrieve cluster components needed during bootstrapping)
- slightly higher false positives (environmental network I/O flakiness)
**Notes**:
=> test: replace “vanilla” E2E cluster test with non-VHD cluster test

CODE_OF_CONDUCT.md
Azure published [standard markdown](https://github.com/Azure/.github/blob/master/CODE_OF_CONDUCT.md) for `CODE_OF_CONDUCT.md`, so let's use it in place of our artisanal, hard-crafted version.
**Notes**:
=> docs: use Azure's standard code of conduct for GitHub

docs/topics/azure-stack.md, packer/install-dependencies.sh
See
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#downloads-for-v1151
Fixes #1647 
**Notes**:
1.15 Azure Stack version CNCF certification is approved.
=> feat: add support for Kubernetes 1.15.1 on Azure Stack

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/armresources_test.go, pkg/engine/loadbalancers.go, pkg/engine/loadbalancers_test.go, pkg/engine/networkinterfaces.go, pkg/engine/networkinterfaces_test.go, pkg/engine/templates_generated.go, pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
- Add ipv6 nic config to vmss for dualstack support
- Rename default ipv4 default backend pool name to match cluster name to support backward compat
- Add `ip6_tables` module
**Notes**:
=> fix: add ipv6 nic config for vmss [IPv6DualStack]

pkg/api/defaults.go
Currently we erroneously state that we're upgrading certain components (e.g., moby) during a scale operation if we're using a newer version of the `aks-engine` binary, or if the user has manually updated the generated apimodel.json to a newer component version:
```
aks-engine scale --subscription-id <sub_id> ----api-model _output/kubernetes-uksouth-52692/apimodel.json --location uksouth --resource-group kubernetes-uksouth-52692 --master-FQDN kubernetes-uksouth-52692.uksouth.cloudapp.azure.com --node-pool agent1 --new-node-count 1 --auth-method client_secret --client-id **** --client-secret ****
INFO[0000] validating...                                
INFO[0006] Name suffix: 20965292                        
WARN[0006] Moby will be upgraded to version 3.0.6       
... …
```
=> fix: distinct component update messages for upgrade/scale

test/e2e/kubernetes/kubernetes_test.go
Skips testing for the presence of the `kubernetes.azure.com/role` label on all nodes.
After committing #1626 the AKS Engine soak tests on Jenkins began to fail because the `kubernetes.azure.com/role` label was absent. This occurs because a cluster was created before the change that introduced that label, but is being tested with master code.
This new label can be considered an implementation detail really, since its only use is to know that the `kubernetes.io/role` and `node-role.kubernetes.io` labels need to be applied. So it should be safe to omit it from this e2e test spec.
**Notes**:
=> test: don't check for kubernetes.azure.com/role label

test/e2e/kubernetes/kubernetes_test.go
In practice it takes 5 minutes for the SIGINT signal to terminate the background kubectl port-forward process, making each test run 5 minutes longer.
**Notes**:
=> test: use kill instead of interrupt signal to terminate kubectl port-forward

pkg/api/convertertoapi.go, test/e2e/engine/template.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/runner/cli_provisioner.go
Based on pre-existing architectural debt, we are validating the `OrchestratorProfile` input data during the data marshalling flow, in particular in order to validate OrchestratorVersion for aks-engine deploy operations. See: #355
This PR modifies that vlabs hack a bit so that we only do this during create operations. The specific scenario that this fixes is scaling a pre-existing cluster with a pre-existing apimodel.json that was generated using an older version of aks-engine with a different (breaking) versions support matrix.
Also fixed up the E2E implementation a bit so when we marshall this data during an E2E run, we pass in the appropriate "update" context to skip validation, so that we can do back-compat style tests more easily (e.g., create from old branch, …
=> fix: only include OrchestratorProfile validation during data marshalling for create

docs/topics/azure-stack.md
Document supported K8s version when deploying to a air-gapped Azure Stack.
=> docs: supported versions for disconnected Azure Stacks using VHD 2019.07.10

packer/install-dependencies.sh
Make sure the "registered" version of docker registry is delivered
Fixes: #1625
=> fix: lock docker distribution version for Azure Stack

Makefile
=> chore: use HAS_GOLANGCI value if defined

examples/dualstack/README.md
Cleans up the Kubernetes dual stack example README:
- Use "dual stack," not "DualStack"
- Use "AKS Engine", not "AKS-Engine"
- Capitalize "Kubernetes"
- Use "IPv4" and "IPv6" 
- Clean up Mardown linter warnings
- [] includes documentation
**Notes**:
=> docs: clean up IPv4/v6 dual stack README

parts/k8s/addons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/containeraddons/1.16/azure-cni-networkmonitor.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml, pkg/api/common/versions.go, pkg/engine/templates_generated.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1160-alpha1
**Notes**:
This also implied a (manual) revert of #1621. See kubernetes/kubernetes#80277. cc: @adelina-t.
=> feat: add support for Kubernetes 1.16.0-alpha.2

scripts/build-windows-k8s.sh
`make build-windows-k8s` began failing since the website https://nssm.cc is not accessible, so let's fetch it from a stable archive instead.
**Notes**:
I used this change to create the Windows archive for #1694, so it has been tested. ✔️
=> chore: use k8s test infra archive for nssm.exe

packer/install-dependencies.sh
Fix VHD CI release notes omission for `registry` container image pre-pull.
**Notes**:
=> fix: document registry container image pull in VHD release notes

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201907_2019.07.30.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201907_2019.07.30.txt
This VHD is built with `registry:2.7.1` pre-pulled. This VHD CI operation wasn't persisted to the release notes, filed #1699 to address that going forward.
Manually validated that `registry:2.7.1` was pre-pulled during these VHD image generations.
**Notes**:
=> chore: update VHDs to 2019.07.30

packer.mk
Azure Devops changed console output lines from starting with 5 spaces to starting with "==>  ". This updates the regexp we use to parse the VHD pipeline output in order to extract release notes.
**Notes**:
=> ci: fix VHD release notes Azure DevOps log parsing

Gopkg.lock, Gopkg.toml, cmd/rotate_certs.go, cmd/rotate_certs_test.go, cmd/scale.go, docs/community/example-launch.json, docs/topics/certificaterotation.md, docs/topics/scale.md, docs/tutorials/day2-operations.md, examples/azure-cni/k8s-scale.sh, pkg/armhelpers/azurestack/kubeclient.go, pkg/armhelpers/deployments.go, pkg/armhelpers/interfaces.go, pkg/armhelpers/kubeclient.go, pkg/armhelpers/mockclients.go, pkg/engine/transform/transform.go, pkg/operations/cordondrainvm.go, pkg/operations/deletevm.go, pkg/operations/k8sapi_ops.go, pkg/operations/k8sapi_ops_test.go, pkg/operations/kubernetesupgrade/upgradeagentnode.go, pkg/operations/kubernetesupgrade/upgrademasternode.go, vendor/github.com/mgutz/ansi/LICENSE, vendor/github.com/mgutz/ansi/ansi.go, vendor/github.com/mgutz/ansi/doc.go, vendor/github.com/mgutz/ansi/print.go, vendor/github.com/x-cray/logrus-prefixed-formatter/LICENSE, vendor/github.com/x-cray/logrus-prefixed-formatter/formatter.go
Let's tag some of our scale log messages to "debug" from "info", and generally make them clearer and more human readable.
This PR:
- Changes "debug" messages to "debug" level, from "info"
- Deprecates `--master-FQDN` arg in favor of `--apiserver` for commands that need to connect to the k8s API (`--master-FQDN` still works, but will output a deprecated message)
- updates the cert rotation command as well to be consistent
- Connects the the k8s API during scale operation to give the user real-time feedback about the before/after effects of scale operations against their cluster node pools
- Added a warning message for VMSS scale in operations: targeted VMSS instance and thus purposeful cordon/drain is not yet supported
Fixes #1353 …
=> refactor: simplify scale operation CLI output

test/e2e/engine/template.go, test/e2e/kubernetes/kubernetes_test.go
Related to #1579 
In practice, crashing or not ready pods immediately after a cluster or node comes online is within the normal range of operational behavior for Kubernetes. This PR retains the test implementation to detect those behaviors, but makes it opt-in behind the env var `DEBUG_CRASHING_PODS=true`. By default we will not set that to false, skipping this test.
**Notes**:
=> test: make crashing pods test opt-in (debug only)

pkg/api/common/const.go, pkg/api/defaults.go, pkg/api/types.go, pkg/api/types_test.go
This PR changes the cloudprovider-enforced rate limiter configuration for VMSS scenarios to allow for more "burstability". Specifically, for Kubernetes LoadBalancer reconciliation, VMSS instance Get() calls are made during backend pool creation; one Get() call per VMSS instance. Because we can't anticipate in advance exactly how many VMSS instances will be served by an AKS Engine control plane (and because we don't currently have any functionality to update control plane cloudprovider configuration in response to scale up/down events), we need to configure the control plane so that it can handle the maximum number of supported VMSS instances. At present, we support up to 100 nodes per pool, and so we configure the "burstability" of the rate limit to be a factor of …
=> feat: enable smart cloudprovider rate limiting

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
This is possibly tech debt inherited from change over time? We should be simply configuring docker + systemd to do this:
`ExecStartPost=/sbin/iptables -P FORWARD ACCEPT`
In the `exec_start.conf` file itself via cloud-init. And not echo + stdout redirecting it to the file after it lands on disk via CSE.
**Notes**:
=> chore: configure docker ExecStartPost config in file

parts/k8s/cloud-init/artifacts/cse_helpers.sh, pkg/engine/templates_generated.go
Disable interactive for dpkg configure
Using 0.35.3 and observed following:
```
Setting up base-files (9.4ubuntu4.8) ...
Configuration file '/etc/issue'
==> Modified (by you or by a script) since installation.
==> Package distributor has shipped an updated version.
What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
D     : show the differences between the versions
Z     : start a shell to examine the situation
The default action is to keep your current version.
*** issue (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package base-files (--configure):
end of file on stdin at conffile prompt
Errors were encountered while processing:
base-files
E: Sub-process …
```
=> Fix 'dpkg --configure -a' interactive config update issue

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#v1152
**Notes**:
=> feat: add support for Kubernetes 1.15.2

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/defaults_test.go, pkg/engine/templates_generated.go
Update calico to v3.8.0
The major change from current version v3.7.2 is `Calico v3.8.0 includes several improvements to its integration with Istio for application layer policy enforcement. Calico now supports Istio v1.1, and includes the necessary drivers and volumes in calico-node by default`
Please refer to https://docs.projectcalico.org/v3.8/release-notes/
**Notes**:
=> chore: Update calico to v3.8.0

pkg/api/common/versions.go, pkg/api/k8s_versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1160-alpha2
**Notes**:
=> feat: add support for Kubernetes 1.16.0-alpha.3

pkg/api/const.go
Version catch-up. The Windows default images come with 18.09.7, so don't downgrade to 18.09.2.
The Docker release notes don't seem to have anything relevant but downgrading costs time & reboot. https://docs.docker.com/engine/release-notes/#18097
=> chore: Update to Docker EE 18.09.7 by default

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.09.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.09.txt
Adds the following pre-downloaded hyperkube images to support Kubernetes versions for both Azure and Azure Stack:
- v1.13.9
- v1.14.5
- v1.15.2
Removes the following deprecated Kubernetes version for both Azure and Azure Stack:
- v1.13.7
Adds the following pre-downloaded Kubernetes component images:
- k8s.gcr.io/kube-addon-manager-amd64:v9.0.2
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.2
- k8s.gcr.io/cloud-controller-manager-amd64:v1.14.5
- k8s.gcr.io/cloud-controller-manager-amd64:v1.13.9
**Notes**:
=> chore: rev VHD versions to 2019.08.09

.devcontainer.json, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
Updates the `go-dev` toolbox image to be based on Ubuntu 18.04.
See https://github.com/deis/docker-go-dev/releases/tag/v1.23.0
Provides a fresher version of `curl`, among other things.
**Notes**:
I updated `DEIS_GO_DEV_IMAGE` to use this on the Jenkins instance.
=> chore: update go-dev image to v1.23.0

parts/k8s/addons/kubernetesmasteraddons-scheduled-maintenance-deployment.yaml, pkg/engine/templates_generated.go
The `scheduled-maintenance` addon in #1575 didn't have `addonmanager.kubernetes.io/mode` labels on its manifests, so enabling it didn't actually create the "drainsafe-system" namespace and associated objects.
**Notes**:
=> fix: label scheduled-maintenance manifests for addon-manager

docs/topics/azure-stack.md
Document supported K8s versions when deploying to a air-gapped Azure Stack.
=> docs: supported versions for disconnected Azure Stacks using VHD 2019.07.30

test/e2e/kubernetes/kubernetes_test.go
This does 3 things to improve reliability:
1. Log stderr for kubectl port-forward if it doesn't give anything on stdout
2. Retry on failure starting kubectl port-forward
3. Properly kill child processes. It forks and the child process holds the port
=> test: improve kubectl port-forward tests

parts/k8s/cloud-init/artifacts/kubelet.service, pkg/engine/templates_generated.go
- avoid DNS reverse lookup when starting kubelet
- in some case custom dns server used in vNet, quality of their DNS is not guaranteed, which could block kubelet service start.
I did compare impact of this change, only different is it displays **0.0.0.0/0** instead of **anywhere**, for a clean aks cluster.
**Notes**:
=> chore: use numeric address to avoid DNS reverse lookup

.devcontainer.json, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.23.1
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.8
**Notes**:
I updated Jenkins to use this image already.
=> chore: update go toolchain to 1.12.8

pkg/api/defaults-scheduler.go
fix: race condition which causes concurrent map writes during tests
Occasionally when running tests, I will run into the following which is caused by a shared reference to a map of default values. This change will cause an empty map to be created and populated with the entries from the default values map.
```
fatal error: concurrent map writes
goroutine 612 [running]:
runtime.throw(0x1822cd0, 0x15)
/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0000c57e8 sp=0xc0000c57b8 pc=0x102f482
runtime.mapassign_faststr(0x1752a80, 0xc00023db60, 0x181ab9b, 0xc, 0x0)
/usr/local/Cellar/go/1.12.7/libexec/src/runtime/map_faststr.go:291 +0x40f fp=0xc0000c5850 sp=0xc0000c57e8 pc=0x1014f3f
github.com/Azure/aks-engine/pkg/api.(*ContainerService).setSchedulerConf …
```
=> fix: race condition which causes concurrent map writes during tests

docs/topics/clusterdefinitions.md, pkg/api/const.go
- This switches from Windows Server 1809 to Windows Server 2019. They are the same thing, but 2019 is supported longer.
- Use the latest available Windows cumulative update for security fixes
=> chore: Change Windows default to Windows Server 2019 LTSC, July patch

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
Simplify containerd kubelet config implementation: do this during cloud-init template generation instead of via sed at the last mile.
Also remove some deprecated "if less than k8s 1.8" logic to make the above more maintainable/expressive.
Fixes #1786 
**Notes**:
=> fix: set kubelet config for containerd in templates

examples/azure-stack/kubernetes-azurestack.json
Based on PM comment we need to keep the OS disk size as small as possible.
Fixes #1812 
**Notes**:
=> docs: Move master and agent node OS vhd size to default value i.e 30GB

packer/init-variables.sh
Fixes an access issue the storage container used to capture the image during VHD build pipeline is created with public access. The rest of the pipeline uses URLs with SAS tokens so public access is not needed.
**Notes**:
=> fix: Remove public access from vhd storage container

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#v11310
**Notes**:
Addresses CVE-2019-9512 and CVE-2019-9514.
=> feat: add support for Kubernetes 1.13.10

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#v1146
**Notes**:
Addresses CVE-2019-9512 and CVE-2019-9514.
=> feat: add support for Kubernetes 1.14.6

cmd/deploy_test.go, cmd/generate.go, cmd/generate_test.go
feat: autofill client Id and client secret for generate command
**Notes**:
=> feat: autofill client Id and client secret for generate command

parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml, pkg/engine/templates_generated.go
Ensure that upgrade operations always reconcile to the latest `kube-proxy` addons implementation. Also follow existing "critical addons" patterns.
Uses this as a reference:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/kube-proxy/kube-proxy-ds.yaml
Fixes #1817
**Notes**:
=> fix: kube-proxy addon not critical, doesn't reconcile

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.15.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.15.txt
Bump VHD references to 2019.08.15.
Includes the following changes:
- Kernel update: `Linux version 4.15.0-1055-azure`
- etcd 3.3.13 pre-baked
- etcd 3.2.26 no longer pre-baked
- Azure CNI 1.0.25 pre-baked
- Azure CNI 1.0.22 no longer pre-baked
**Notes**:
=> chore: rev VHD references to 2019.08.15

.pipelines/vhd-builder.yaml, packer.mk
azcopy was removed from the latest go dev image. Move to use azcopy-preview which is the newest version of azcopy. Once the new go dev image is published, we will replace azcopy-preview with azcopy.
Also declare an in code variable for the container image instead of using a devops variable to allow us to move the image version forward with the rest of our pipelines.
**Notes**:
=> fix: use azcopy-preview in VHD pipeline

pkg/api/types.go, pkg/api/types_test.go
PR changes the cloudprovider-enforced rate limiter configuration for VMAS scenarios as well to allow for more "burstability". For large cluster on Azure Stack, app deployment which requires LoadBalancer reconciliation either NicGet call or NicUpdate call is failing. Updating the code to support "burstability" on VMAS as well.
Fixes #1806 
**Notes**:
=> feat: update cloud provider rate limit for vmas.

docs/topics/azure-stack.md, packer/install-dependencies.sh
Add support for Kubernetes 1.13.9, 1.14.5, 1.15.2 on Azure Stack
Fixes #1809 
Fixes #1810 
Fixes #1811 
**Notes**:
=> feat: add support for Kubernetes 1.13.10, 1.14.6, 1.15.3 on Azure Stack

parts/k8s/addons/1.16/kubernetesmasteraddons-cilium-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-flannel-daemonset.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-dns-deployment.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/containeraddons/1.16/azure-cni-networkmonitor.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-azure-npm-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-heapster-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-kube-rescheduler-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml, pkg/api/common/versions.go, pkg/engine/templates_generated.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1160-alpha3
**Notes**:
We may still need to follow up on this:
> scheduler.alpha.kubernetes.io/critical-pod annotation is removed. Pod priority (spec.priorityClassName) should be used instead to mark pods as critical.
=> feat: add support for Kubernetes 1.16.0-beta.1

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.23.2
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.9
**Notes**:
Restores a working (old) `azcopy` to the go-dev image:
```shell
$ docker run quay.io/deis/go-dev:v1.23.2 azcopy
------------------------------------------------------------------------------
azcopy 7.3.0-netcore Copyright (c) 2018 Microsoft Corp. All Rights Reserved.
------------------------------------------------------------------------------
...
$ docker run quay.io/deis/go-dev:v1.23.2 azcopy-preview
AzCopy 10.2.1
Project URL: github.com/Azure/azure-storage-azcopy
...
```
=> chore: update go toolchain to 1.12.9 (#1789)

test/e2e/kubernetes/kubernetes_test.go, test/e2e/remote/ssh.go, test/e2e/runner/cli_provisioner.go
This PR generalizes the "ssh to master and run commands on all nodes" pattern, and enables 3 retries. Ditto for "scp files to master and to nodes".
Specifically: we were establishing ssh connections for every test, and running `ssh-add` inline for every ssh operation. And little of that was being retried. So now we're establishing a re-usable ssh connection (to the first master node), and then every remote ssh execution on that connection is allowed 3 retries.
The idea is that the above will remove undesired flakiness due to network I/O flakiness that we're not in control over.
**Notes**:
=> test: retry all ssh-dependent E2E tests

packer/configure-windows-vhd.ps1
I ran into some stability issues when trying to move the Windows VHD to start with the August images where winrm was not always reconnecting.
Hyper-V messes with networking on the reboot following it being enabled and delaying the winrm service start allows for windows to finish the reconfiguration before allowing packer to attempt connecting back to the machine.
**Notes**:
=> ci: Windows VHD winrm delay start

pkg/api/types.go, pkg/api/types_test.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
Low-priority scalesets will unexpectedly delete (and not restore) VMSS instances, which means we aren't able to predict node counts for such cluster configuration scenarios ahead of time.
For above scenarios let's fall back to testing for 100% node readiness (which should be reconcilable within reasonable E2E test timeouts following a VMSS instance delete).
**Notes**:
=> test: only check for static n node count if not using low pri VMSS

test/e2e/kubernetes/kubernetes_test.go
kubectl port forward E2E test depends upon an nginx pod to do its thing, but currently that pre-check is a static "check for one pod", not allowing for any pod creation reconciliation wait time.
This PR adds that tolerance.
**Notes**:
=> chore: wait for pod readiness in port forward test

docs/topics/coredns.md, parts/k8s/addons/coredns.yaml, pkg/engine/templates_generated.go
This resolves one piece of #1541. The change to setting
`ConfigMap/coredns` to addon mode `reconcile` in #1493 made it so that
operators can't customize CoreDNS with stub domains anymore.
This patch adds a second volume mount from the configmap
`coredns-custom` (optional) that appends configuration to what is
shipped with aks-engine.
**Notes**:
=> feat: Allow customization of coredns (#1541)

test/e2e/kubernetes/kubernetes_test.go, test/e2e/remote/ssh.go
3 retries is not enough to absorb potential environmental flakes :(
```
$ ssh -A -i /__w/1/s/gopath/src/github.com/Azure/aks-engine/_output/kubernetes-southeastasia-78856-ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no azureuser@kubernetes-southeastasia-78856.southeastasia.cloudapp.azure.com -p 22 scp -o StrictHostKeyChecking=no /tmp/auditd-validate.sh k8s-pool1-18623296-vmss000001:/tmp/auditd-validate.sh
2019/08/23 18:47:40 Error output:
Authorized uses only. All activity may be monitored and reported.
ssh: connect to host k8s-pool1-18623296-vmss000001 port 22: Connection timed out
lost connection
$ ssh -A -i /__w/1/s/gopath/src/github.com/Azure/aks-engine/_output/kubernetes-southeastasia-78856-ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no …
```
=> test: allow 20 retries for ssh-dependent tests

pkg/api/convertertoapi.go, pkg/api/convertertoapi_test.go
This PR changed vlabs-unversioned api model conversion logic to only set a default "azure" networkPlugin value if both networkPolicy and networkPlugin are "":
https://github.com/Azure/aks-engine/pull/1823
However, there are pre-established assumptions that "networkPolicy": "calico" should also get a networkPlugin value of "azure" during conversion, so we restore this behavior to protect pre-existing, known-working api model workflows.
**Notes**:
=> fix: restore working calico networkPolicy vlabs conversion logic

pkg/engine/networkinterfaces.go, pkg/engine/networkinterfaces_test.go, pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
Follow up from #1872, more guards against referring to the `agentLbID` template var in hosted master cluster configurations.
Now with Unit Tests!
**Notes**:
=> fix: more aks guarding against agentLbID template var

pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
fix: set streaming-connection-idle-timeout as 4h
Per https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#options, streaming-connection-idle-timeout means `Maximum time a streaming connection can be idle before the connection is automatically closed. 0 indicates no timeout. Example: '5m' (default 4h0m0s)`, we should set as `4h`, there is user complaining about the original `5m` value:
`when user run kubectl exec , then session terminated after 5 idle minutes.`
**Notes**:
/assign @jackfrancis @CecileRobertMichon
/azp run pr-e2e
=> fix: set streaming-connection-idle-timeout as 4h

packer/install-dependencies.sh, packer/vhd-image-builder.json, parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
Running waagent –deprovision cleans up the contents of /var/lib/waagent, removes user authentication credentials, (usually) removes user home directories, etc. When preparing a cloud-init based VM for clean reuse, you also need to tell cloud-init to reset itself. The command cloud-init clean -logs will remove cloud-init artifacts from /var/lib/cloud so cloud-init will re-run all stages as it did on first boot, and it cleans up the cloud-init log files so the next boot of the VM gets a clean log.
https://www.packer.io/docs/builders/azure.html#deprovision
Fixes #1720
#1717 
**Notes**:
=> fix: add deprovision step to packer script

packer/configure-windows-vhd.ps1
Manually triggering update of Windows Defender signatures as part of Windows VHD build.
These images are configured to periodically check for new Defender signatures updates automatically. This just helps unsure signatures are fresh on first boot.
**Notes**:
=> feat: Windows VHD update defender signatures

Jenkinsfile, test.mk, test/e2e/build.sh, test/e2e/cluster.sh, test/e2e/jenkins_reown.sh, test/e2e/kubernetes/kubernetes_test.go, test/e2e/test_cluster_configs/availabilityset.json, test/e2e/test_cluster_configs/base.json, test/e2e/test_cluster_configs/flannel/containerd.json, test/e2e/test_cluster_configs/flannel/docker.json, test/e2e/test_cluster_configs/gpu.json, test/e2e/test_cluster_configs/kubnet.json, test/e2e/test_cluster_configs/network_policy/azure.json, test/e2e/test_cluster_configs/network_policy/calico.json, test/e2e/test_cluster_configs/network_policy/cilium.json, test/e2e/test_cluster_configs/rbac_disabled.json
We are moving from one Jenkins cluster to another and it would be nice to tidy up our collection of jobs. In the longer term, I suspect we'll move over to DevOps or Actions, but for the short term, hopefully, this will work.
This PR is `wip` as I would like to use it to gather feedback and incorporate it into the design of the job.
The [Jenkinsfile](https://github.com/Azure/aks-engine/compare/master...devigned:jenkins-pipeline?expand=1#diff-58231b16fdee45a03a4ee3cf94a9f2c3) does the following:
- sets up default parameters for the build
- produces a matrix of jobs; [orchestrator versions] x [api models]
- _lots of jobs_
- looks for api models, actually job_config.json, under the ./test/e2e/test_cluster_configs dir
- job configs consist of `{"env":{}, "options":{}, …
=> chore: create parallel Jenkins pipeline for e2e tests

parts/k8s/cloud-init/artifacts/dhcpv6.service, pkg/engine/templates_generated.go
https://github.com/Azure/aks-engine/pull/1719 introduced `#EOF` in the files for `wait_for_file`. However this file has been missed because of which creating dualstack cluster fails after that change. This PR fixes that issue.
**Notes**:
=> fix: add #EOF for dhcpv6 service

pkg/helpers/filesaver.go
This fixes the blind mkdir which fails if it is empty.
Fixes #1048 
**Notes**:
=> fix: Remove the blind mkdir when writing outputs (#1048)

Jenkinsfile
Add an easier way to exclude jobs from the runner.
**Notes**:
=> chore: add job exclusion regex to jenkinsfile

docs/topics/azure-stack.md, pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.10.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.10.txt
Updates VHD reference to 2019.09.10 in preparation for incoming v0.41.0 release.
Changes:
- Delivers the `4.15.0-1057-azure` Ubuntu 16.04-LTS kernel
- Delivers the `5.0.0-1018-azure` Ubuntu 18.04-LTS kernel
- Pre-downloads Azure CNI version 1.0.27
- No longer pre-downloads Azure CNI 1.0.24
- Pre-install `apache2-utils` apt package for Azure Stack
- Pre-pulls the following container images:
- k8s.gcr.io/coredns:1.6.2
- mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:v0.0.13
- no longer pre-pulling mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:v0.0.7
**Notes**:
=> chore: rev VHD image references to 2019.09.10

test/e2e/kubernetes/kubernetes_test.go
We are running docker crash simulations against a list of nodes whose length we determine at the time the test runs. We also need to do all validations against that common list.
**Notes**:
=> test: crash docker and validate against common node count

test/e2e/azure/cli.go
The current soak test implementation persists the `_output/` directory to az storage for re-use across multiple runs/environments. However, there's a bug in our E2E code in that `az storage file download-batch` requires the `--destination` option to be a pre-existing directory.
This PR creates the `_output/` directory for cases where it doesn't already exist (e.g., a jenkins job configuration that cleans up its workspace directory for every job run).
**Notes**:
=> test: az storage file download-batch --destination must exist

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/kubernetes_test.go
Allow for retry tolerance when doing basic deployment resource operations.
**Notes**:
=> test: more resilience when k get deployment

test/e2e/config/config.go, test/e2e/config/config_test.go
This PR replaces the default `southcentralus` region with `uksouth`.
Seeing lots of this in recent tests:
```
Error from deployment for kubernetes-southcentralus-99368 in resource group kubernetes-southcentralus-99368:exit status 1
2019/09/13 16:51:48 Command Output: ERROR: Deployment failed. Correlation ID: 555bd6ee-8688-4088-bcc6-37caa0157810. {
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"details": [
{
"code": "AllocationFailed",
"message": "Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"
}
]
}
}
```
**Issue …
=> test: s/southcentralus/uksouth

Jenkinsfile
When upgrade / scaling, the test pipeline was passing even though the upgrade version was always the last one in the list (v1.16.rc1) due to the upgrade version var being captured in a closure enclosed in a loop. This change properly capture the upgrade version.
**Notes**:
=> chore: fix closure capture for UPGRADE_VERSIONS

parts/k8s/containeraddons/1.10/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.11/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.12/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.13/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.14/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.15/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/1.9/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/k8s_versions.go, pkg/engine/templates_generated.go, test/e2e/kubernetes/kubernetes_test.go
This PR upgrades metrics server from `v0.2.1` to `v0.3.4`
BTW, we cannot disable `--read-only-port` now since AKS also depends on this port and metrics server on AKS is still v0.2.x
metric server(v0.2.1) is still using KubeletReadOnlyPort(10255), we cannot switch to KubeletPort(10250) now, after upgrade to metric server v0.3.4, it uses 10250 port instead, then we could move on to merge PR [fix: disable ReadOnlyPort ](https://github.com/Azure/aks-engine/pull/975)
This PR only applies for k8s v1.16.0:
- upgrade metric server to v0.3.4
Tested on k8s v1.16.0-beta.1, test result:
```
$ kubectl top no
NAME                        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
6133k8s010                  56m          2%     445Mi           8%
k8s-linuxpool1-61339693-0   54m …
```
=> feat: upgrade metrics server to v0.3.4

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/api/azenvtypes.go, pkg/engine/templates_generated.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.13.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.13.txt
New VHD includes the following pre-downloaded artifacts for both 16.04-LTS and 18.04-LTS:
- etcd v3.3.15
Includes the following pre-downloaded versions:
- k8s.gcr.io/cluster-autoscaler:v1.16.0
Also this VHD includes a "file fingerprint" at the new `/opt/azure/vhd-install.complete` location, which CSE has been updated to check to validate that the underlying VM OS does not need to download system package pre-requisites.
**Notes**:
=> chore: rev vhd to 2019.09.13

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
Our current implementation was evaluating the duration time to execute a `kubectl` command, rather than actually introspecting a pod container's status to determine the duration of the container runtime execution lifecycle.
Also fixed some bugs around "Waiting for pods to complete".
**Notes**:
=> test: fix "run multiple commands in succession" implementation

parts/k8s/kubernetesparams.t, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/params_k8s.go, pkg/engine/templates_generated.go
For hosted master, we do not want to overwrite service principal with "msi" even if `useManagedIdentity` is `true`, that's because some addons running on agent nodes may not support authenticating using managed identity, so even managed identity is used, we still want to provide a service principal, which is dedicated to be used by addons.
**Notes**:
=> fix: not overwrite service principal profile for hosted master

cmd/scale.go
Instead of printing:
`time="2019-09-18T18:42:36Z" level=info msg="Nodes in pool pool1 cluster after scaling:"`
We should print:
`time="2019-09-18T18:42:36Z" level=info msg="Nodes in pool 'pool1' after scaling:"`
Also updated the message we print before the scale operation to surround the name of the pool in single quotes to anticipate that the name of the pool might include the word pool, and thus "stutter" in the context of the message clause.
**Notes**:
=> fix: correct scale message after scale operations

examples/azure-stack/kubernetes-azurestack.json
Update network plugin value to kubenet in Azure Stack example file as moby + flannel is not supported.
**Notes**:
=> chore: update network plugin value to kubenet in Azure Stack example file

pkg/operations/kubernetesupgrade/upgrader.go
The upgrade operation did not properly check if the nodes of all agentpools have been upgraded.
Fixes #1794
**Notes**:
=> fix: check the nodes of all agentpools during upgrade

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go, test/e2e/runner/cli_provisioner.go
Our most common E2E flake at present is node get operations returning unexpected results. This PR tolerates transient node get responses within a given retry timeout period.
**Notes**:
=> test: retry’able node get

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml
Ubuntu 18.04-LTS has a known symptom of regularly taking a long time (> 30 mins) to achieve time synchronization. Until we root cause and fix that, let's skip the time sync test on 18.04-LTS as a way of continuing to gather additional functional signal from Kubernetes + Azure + 18.04-LTS, without the annoying flaky test runs.
**Notes**:
=> test: skip time sync test for 18.04

.pipelines/vhd-builder-windows.yaml, packer/windows-vhd-builder.json, packer/write-release-notes-windows.ps1
Logging info about the git commit/branch/repo and azure devops build used to produce Windows VHDs
**Notes**:
=> ci: Adding provenance info in Windows VHD release notes

test/e2e/test_cluster_configs/base.json, test/e2e/test_cluster_configs/container_monitoring.json, test/e2e/test_cluster_configs/flannel/containerd.json, test/e2e/test_cluster_configs/flannel/docker.json, test/e2e/test_cluster_configs/gpu.json, test/e2e/test_cluster_configs/kubenet.json, test/e2e/test_cluster_configs/network/cilium.json, test/e2e/test_cluster_configs/network_policy/azure.json, test/e2e/test_cluster_configs/network_policy/calico.json, test/e2e/test_cluster_configs/network_policy/calico_azure.json, test/e2e/test_cluster_configs/network_policy/cilium.json, test/e2e/test_cluster_configs/no_outbound.json, test/e2e/test_cluster_configs/not_in_vhd.json, test/e2e/test_cluster_configs/rbac_disabled.json, test/e2e/test_cluster_configs/storage_profile.json, test/e2e/test_cluster_configs/vmss_master.json, test/e2e/test_cluster_configs/windows/accelerated_networking.json, test/e2e/test_cluster_configs/windows/custom_image.json, test/e2e/test_cluster_configs/windows/custom_vnet.json, test/e2e/test_cluster_configs/windows/image_reference.json, test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json, test/e2e/test_cluster_configs/windows/shared_image_gallery.json, test/e2e/test_cluster_configs/windows/vhd_url.json
Standardize E2E test config for Standard_D2_v3 VM SKUs, and low-pri VMSS where appropriate
**Notes**:
=> test: Use Standard_D2_v3 and low pri VMSS in E2E test configs

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go, test/e2e/kubernetes/persistentvolume/persistentvolume.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/storageclass/storageclass.go, test/e2e/kubernetes/util/util.go
1. validate service URLs w/ retries
2. don’t enforce “shell out command” timeouts everywhere
3. standardize Linux stability tests timeout to 3 secs per test
4. standardize some Windows stability tests timeout to 1 minute per test
**Notes**:
=> test: address 4 E2E test flakes

packer/configure-windows-vhd.ps1, packer/write-release-notes-windows.ps1, parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsinstallopensshfunc.ps1, pkg/engine/templates_generated.go
Caching content on the Windows VHDs can help improve reliability and shorten the duration of CSEs used to configure the Windows nodes by reducing the amount of files downloaded during their execution.
Addresses some of the work required for https://github.com/Azure/aks-engine/issues/1927
**Notes**:
=> feat: Windows vhd artifact caching

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml
Enable stability tests on PR E2E now that those tests have stabilized.
This PR:
- enables 10 successive tests for the 18.04-LTS job to help provide signal as we decide whether or not to cut over to 18.04-LTS as the default OS version
- enables 3 successive tests for all Linux k8s version-specific test jobs
- no stability tests for Windows nodes as those haven't yet stabilized
**Notes**:
=> test: enable stability tests for PR E2E

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
To prevent non-needed apt artifacts from interrupting with apt operations generally, we need to do package cleanup as the first step in bootstrap provisioning.
**Notes**:
=> fix: cleanup apt artifacts before running apt

docs/topics/clusterdefinitions.md, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go
`read-only-port`(default: `10255`) is only for heapster, while our aks-engine and aks has now switched to use metric server which uses `10250` by default.
This PR disabled `read-only-port` by set it as 0, here are the k8s ports definitons:
https://github.com/kubernetes/kubernetes/blob/b8b7ab39ec457b11caffbe0d31bd527cc8aa6f09/pkg/master/ports/ports.go#L38-L43
https://github.com/Azure/acs-engine/pull/2091
461
Original CIS conformance test result:
```
[FAIL] 2.1.4 Ensure that the --read-only-port argument is set to 0 (Scored)
== Remediations ==
2.1.4 If using a Kubelet config file, edit the file to set readOnlyPort to 0 .
If using command line arguments, edit the kubelet service file
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf on each worker …
```
=> [CIS conformance] fix: disable ReadOnlyPort since it's only for heapster

pkg/operations/kubernetesupgrade/upgrader.go
Doesn't return an error that occurs while draining a node during upgrade, just log it.
The idea here is that "cordon and drain" is the polite, best-effort way to upgrade, but that if it fails, upgrade can still delete the node and things will succeed with a bit more disruption to workloads.
Fixes #1919
**Notes**:
=> fix: continue upgrading after node drain error

pkg/operations/cordondrainvm.go, pkg/operations/kubernetesupgrade/upgrader.go
Ensures that `SafelyDrainNodeWithClient` uses the lowercase version of a VM's name to avoid disagreement between node name and machine name.
Fixes #1982 
**Notes**:
=> fix: lowercase vm name before calling drain node

test/e2e/kubernetes/node/node.go
Observed this E2E flake which this PR will address:
```
04:55:44  Unable to connect to the server: dial tcp 51.144.98.96:443: i/o timeout
04:56:05  2019/09/24 11:56:04 Error trying to run 'kubectl get nodes':
04:56:05   - exit status 1
04:56:05  2019/09/24 11:56:04 
04:56:05   - {
04:56:05      "apiVersion": "v1",
04:56:05      "items": [],
04:56:05      "kind": "List",
04:56:05      "metadata": {
04:56:05          "resourceVersion": "",
04:56:05          "selfLink": ""
04:56:05      }
04:56:05  }
04:56:05  Unable to connect to the server: dial tcp 51.144.98.96:443: i/o timeout
04:56:05  panic: runtime error: invalid memory address or nil pointer dereference
04:56:05  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b3d90]
04:56:05  
04:56:05 …
```
=> test: ensure we don’t dereference nil node List

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
This PR tweaks the way we validate that a pod or common set of pods is in a persistent, reliable "Ready" state. Instead of tracking and incrementing "successful" checks, and comparing to "unsuccessful" checks, we instead try to detect "flaps", which are in fact normal Kubernetes pod behaviors, and ensure that the transitions between Ready and non-Ready (i.e., a flap) are within a tolerable spectrum.
Specifically:
Once we get a positive Ready signal, we continue attempting to accumulate the desired success count until we detect a non-Ready signal. A ready --> non-ready transition counts as a single "flap". We then wait for the re-occurrence of a successive Ready signal, which then counts towards the targeted number of successes. Rinse, repeat.
We will return …
=> test: more resilient “wait for successful pod readiness checks”

packer/install-dependencies.sh
Add support for Kubernetes 1.16.0 on Azure Stack
Fixes #1989 
**Notes**:
We will update documentation to support 1.16.0 when new aks-vhd is generated.
=> feat: add support for Kubernetes 1.16.0 on Azure Stack

pkg/engine/transform/transform.go
Fix the possible nil pointer panic in transform logic.
Someone named an agentpool "master", and triggered nil pointer panic in transform.
**Notes**:
=> fix: nil pointer check for data disks in transform

packer/configure-windows-vhd.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
Skip downloading of pause image if image already present in windows vhd
Fixes #2039 
**Notes**:
=> feat: Skip downloading of pause image if image already present in windows vhd

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go
This PR addresses some observed flakes in E2E tests where resources take a long time to delete. This classification of error implemented by the `RunAndLogCommand` func doesn't make sense:
1. If it wrapped by "retry a bunch of times" orchestration and
2. If it implements a delete operation
Because, a "delete took too long to complete" error is not retry'able: the resource no longer exists to "re-delete"!
**Notes**:
=> test: don’t timeout k8s resource deletes in E2E

packer/write-release-notes-windows.ps1
Powershell does not add a file encoding by default which is results in github treating the text file as a binary file which checking in release notes generated for windows VHD images.
**Notes**:
=> fix: updating windows release notes script to set a file encoding

parts/k8s/cloud-init/artifacts/sysctl-d-60-CIS.conf, pkg/engine/templates_generated.go, test/e2e/kubernetes/scripts/net-config-validate.sh
Links:
- https://linux.die.net/man/7/inotify
- https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
Signed-off-by: Junaid Ali <junaidali.yahya@gmail.com>
**Notes**:
=> fix: Increasing inotify limit to 1048576 from the default 8192

examples/dualstack/kubernetes.json, parts/k8s/addons/1.16/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/cloud-init/masternodecustomdata.yml, pkg/api/defaults.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/ipaddresses.go, pkg/engine/ipaddresses_test.go, pkg/engine/loadbalancers.go, pkg/engine/loadbalancers_test.go, pkg/engine/masterarmresources.go, pkg/engine/networkinterfaces.go, pkg/engine/networkinterfaces_test.go, pkg/engine/templates_generated.go, pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
Adds support for creating a dualstack cluster with phase2 changes
- Support for dual stack service cidrs
- Currently only kube-proxy ipvs mode supported for dualstack
Sample api model used for testing - https://gist.github.com/aramase/19c1179641ca8e8d507244029d1f6146
cc @khenidak @lachie83 
**Notes**:
=> IPv6 dualstack phase2

pkg/api/addons.go, pkg/api/addons_test.go, test/e2e/test_cluster_configs/container_monitoring.json, test/e2e/test_cluster_configs/flannel/docker.json, test/e2e/test_cluster_configs/network/cilium.json, test/e2e/test_cluster_configs/network_policy/azure.json, test/e2e/test_cluster_configs/network_policy/cilium.json
Several cluster configs are consistently failing in 1.16 tests. While we triage, let's disable them so that we can get more readable test signal for configurations that do work more consistently.
While triaging 1.16 breakage for Azure NetworkPolicy addon, I determined that the issue was not practical (i.e., the addon was installed correctly on the cluster) but rather that we were adding superfluous api model configuration for >= 1.16 for this addon, which was causing the E2E test runner to panic. Because the changes are in order to fix our test signal, I've included those changes in this PR.
Fixes #2069
**Notes**:
=> test: disable 1.16 tests for various cluster configs

test/e2e/kubernetes/kubernetes_test.go
Requiring no pod container restarts in for IIS in all scale up scenarios doesn't address any specific operational scenario. Pods may restart for a variety of reasons within the boundaries of acceptable operational behaviors.
**Notes**:
=> test: don’t test for iis pod restart

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
To address observed E2E flakes in "get pods that match a prefix substring" usages, this PR converts all of those to async/retry implementations.
**Notes**:
=> test: retry “get pods by prefix substring match”

test/e2e/kubernetes/config.go, test/e2e/kubernetes/kubernetes_test.go
This PR addresses observed E2E flakes grabbing the kubectl config.
**Notes**:
=> test: retry “kubectl get config”

test/e2e/azure/cli.go, test/e2e/runner.go, test/e2e/runner/cli_provisioner.go
To address observed flakes, we'll retry the commonly used "shell out to az" invocations during E2E tests.
**Notes**:
=> test: retry az commands in E2E tests

cmd/deploy.go, parts/k8s/containeraddons/1.16/kubernetesmasteraddons-omsagent-daemonset.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml, pkg/api/addons.go, pkg/armhelpers/azurestack/loganalytics.go, pkg/armhelpers/loganalytics.go, pkg/engine/templates_generated.go
Container monitoring addon supported AzureChinaCloud and AzureUSGovernmentCloud in addition to Azure Public cloud. This PR has all required changes to work in AzureChinaCloud and AzureUSGovernmentCloud environments.
**Notes**:
=> feat: container monitoring addon supports other Azure clouds

packer/configure-windows-vhd.ps1, packer/windows-vhd-builder.json
As part of windows VHD preparation certain Azure agents gets install which should be removed from VHD so that VHD can be consumed across platform (Azure, Azure Stack)
Fixes #2086 
**Notes**:
=> fix: remove Azure agent specific artifacts from windows vhd

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1160
**Notes**:
Still waiting on publishing of k8s.gcr.io/hyperkube:v1.16.1. *Update*: published now.
=> feat: add support for Kubernetes v1.16.1

test/e2e/kubernetes/kubernetes_test.go, test/e2e/remote/ssh.go, test/e2e/runner/cli_provisioner.go
Add retries to SSH connection establishment foo in E2E
**Notes**:
=> test: retry establishing ssh connection for e2e

examples/dualstack/README.md, examples/dualstack/kubernetes.json, pkg/api/const.go
- Updates docs with changes in dual-stack phase2
- Update default ipv6 cluster cidr to `fc00::/8`
/cc @lachie83
=> chore: update default IPv6 subnet for dual stack, update docs

parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, pkg/engine/templates_generated.go
cluster-autoscaler 1.16+ wants to get, list, and watch [v1beta1.CSINode](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#csinode-v1beta1-storage-k8s-io) objects. Without this permission it logs errors:
```console
I1003 16:46:17.597992       1 scale_down.go:554] 2 nodes found to be unremovable in simulation, will re-check them at 2019-10-03 16:51:17.596782704 +0000 UTC m=+2433.908749086
I1003 16:46:17.598160       1 scale_down.go:785] No candidates for scale down
I1003 16:46:18.587192       1 reflector.go:158] Listing and watching *v1beta1.CSINode from k8s.io/client-go/informers/factory.go:134
E1003 16:46:18.588987       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is …
```
=> fix: add read perms for CSINodes to cluster-autoscaler role

pkg/api/azenvtypes.go, pkg/api/defaults.go, pkg/api/defaults_test.go
Use aks windows vhds by default for Azure Stack
Fixes #2107 
**Notes**:
=> feat: use aks windows vhds by default for Azure Stack

packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/masternodecustomdata.yml, pkg/engine/templates_generated.go
Some on-prem users dislike the idea of cloud-init reaching out to the internet before they have the chance to configure a proxy by running a pre-provision script.
=> chore: move cloud-init's apt commands to cse script

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
In most (but not all) instances, when we want to get all pods that match a prefix substring, we want the "Running" pods. A specific example is when we want to validate that a specific deployment replica count is met: in such validations we need to filter out only "Running" pods, so that we don't accidentally pick up an extra pod in a "Terminating" state (if, for example, a transient error caused a pod to be recycled, there will be a brief period of time where a simple `kubectl get pods` yields a set that is greater than the desired replica count).
**Notes**:
=> test: get Running pods by prefix in most cases

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
Observed this E2E flake:
```
$ k get nodes -o json
Failure [30.437 seconds]
2019/10/07 21:04:48 Error trying to run 'kubectl get nodes':
- exit status 1
2019/10/07 21:04:48 
- {
"apiVersion": "v1",
"items": [],
"kind": "List",
"metadata": {
"resourceVersion": "",
"selfLink": ""
}
}
Unable to connect to the server: dial tcp 13.81.26.234:443: i/o timeout
[BeforeSuite] BeforeSuite [0m
/go/src/github.com/Azure/aks-engine/test/e2e/kubernetes/kubernetes_test.go:71
Expected error:
<*exec.ExitError | 0xc0003cbc40>: {
ProcessState: {
pid: 3198,
status: 256,
rusage: {
Utime: {Sec: 0, Usec: 150474},
Stime: {Sec: 0, Usec: 22361},
Maxrss: 37936,
Ixrss: 0,
Idrss: 0,
Isrss: 0,
Minflt: 3460,
Majflt: 0,
Nswap: 0,
Inblock: 0,
Oublock: 8,
Msgsnd: 0,
Msgrcv: 0,
Nsignals: 0, …
```
=> test: retry "get nodes that match regex" test

packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/api/types.go, pkg/api/types_test.go, pkg/api/vlabs/validate.go, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/const.go, pkg/engine/templates_generated.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/test_cluster_configs/everything.json
This PR addresses auditd cruft left on vms that are built without the auditd flag enabled:
If `auditDEnabled` is not true in the cluster configuration, we should clean up the auditd apt package so that folks don't try and use it (we only deliver a working configuration *if* `auditDEnabled` is set to true.
This PR adds best-effort (i.e., it runs in the background and failures are ignored) `apt-get purge auditd`.
This PR also enables auditd for non-VHD distros.
Finally, this PR adds `"auditDEnabled": true` configuration for the "everything" test config to validate that we protect this feature with regular tests.
Fixes #2077 
**Notes**:
=> fix: auditd improvements

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
Follow-up from #2114. We can't change he `prod.list` apt URL until we backport all previously supported versions of moby to the new URL.
**Notes**:
=> fix: restore original moby apt prod.list URL

pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
This PR addresses an unresolved collision between `imageReference` configuration and our curated OS images (which are delivered via the `distro` configuration property). Specifically, unknown outcomes will occur if we associate any specific `distro` value with a cluster spec that includes a custom `imageReference` configuration.
Includes additional validation to fail fast when `imageReference` + `distro` configurations are used.
**Notes**:
=> fix: don’t assign distro if image ref is provided

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
This PR re-orders the "do I have the 'created by AKS VHD CI' OS signature?" and the "does my cluster configuration explicitly declare a VHD distro?" checks in order to enable AKS VHD re-use scenarios. E.g.:
- create a new managed image / shared gallery image / VHD _from_ the AKS VHD
Specifically, the boolean variable `FULL_INSTALL_REQUIRED` in our CSE implementation is functionally coupled with the VHD CI implementation that pairs with that CSE implementation at that commit of aks-engine. In practice, this means that for folks who want to re-use the AKS VHD as a base for creating their own Kubernetes node OS images can (1) take advantage of the optimized CSE code paths (e.g., don't execute unnecessary `apt` operations) and (2) implement the proper cleanup …
=> feat: enable re-use of VHD

test/e2e/kubernetes/kubernetes_test.go
Print out a bunch o' cluster logs after running E2E tests to help diagnose issues.
**Notes**:
=> test: print logs after E2E tests

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.09.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201910_2019.10.09.txt
Includes the following pre-downloaded components for both Ubuntu 16.04-LTS and 18.04-LTS AKS VHDs:
- moby 3.0.7 (was: moby 3.0.6)
- apt traceroute
Adds the following pre-pulled docker images:
- k8s.gcr.io/metrics-server-amd64:v0.3.5
**Notes**:
=> chore: rev AKS VHDs to 2019.10.09

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
We have a bizarre DNS issue that I think is caused by this #2053. 
Reverting until we figure out what's going on.
=> fix: revert 'trust Azure Stack's CA cert before pre-provision extensions'

Jenkinsfile, test/e2e/test_cluster_configs/windows/cse_benchmark_aks_vhds.json, test/e2e/test_cluster_configs/windows/cse_benchmark_win_vhds.json, test/e2e/test_cluster_configs/windows/custom_image.json, test/e2e/test_cluster_configs/windows/image_reference.json, test/e2e/test_cluster_configs/windows/shared_image_gallery.json, test/e2e/test_cluster_configs/windows/vhd_url.json
This change 
- Fixes some of the test configs by moving allowedOrchestratorRelease to options instead of env
- Adds the abililty to target a 'latest released' k8s version for jobs that do not benefits from running against multiple k8s versions
- Updates some additional test configs to use the 'latestReleasedVersion' allowedOrchestratorRelease
Addresses issue #2072 
**Notes**:
=> test: Add 'latestReleasedVersion' target to Jenkins jobs

packer/configure-windows-vhd.ps1, packer/install-dependencies.sh
Support 1.16.1 version on Azure Stack
Fixes #2142 
**Notes**:
We will update doc once the new VHD is cut.
=> feat: Support 1.16.1 version on Azure Stack

pkg/engine/const.go, pkg/engine/engine.go, pkg/engine/engine_test.go
Same reason as #2053 (then reverted here #2135). Downloading pre-provision extensions fails if the scripts are hosted on the local Azure Stack instance. Pass the 'cacert' option to curl fixed the problem and does not cause the unintended side-effects.
=> fix: pass 'cacert' option to curl pre-provision scripts on Azure Stack

parts/k8s/windowsazurecnifunc.ps1, pkg/engine/templates_generated.go
Fixes an issue where invalid cni conf json is generated when route exception lists contain a single value by forcing powershell function to return an array even for single values in GetBroadestRangesForEachAddress function 
This should fix failing windows/custom_vnet jenkins test jobs
**Notes**:
=> fix: fix cni conf json for single exception address

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1161
**Notes**:
I'm planning to make a separate VHD update PR after all the patches land, to avoid rebase conflicts.
=> feat: add support for Kubernetes v1.16.2

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.15.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201910_2019.10.15.txt
This PR delivers a PR w/ pre-downloaded hyperkube images for the following Kubernetes versions:
- v1.16.2
- v1.16.1 Azure Stack
- v1.15.5
- v1.14.8
- v1.13.12
No longer includes pre-pulled hyperkube images for these versions:
- v1.16.0
- v1.16.0 Azure Stack
- v1.15.3
- v1.15.3 Azure Stack
- v1.14.6
- v1.14.6 Azure Stack
- v1.13.10
- v1.13.10 Azure Stack
Pre-pulls the following container images:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.5
- mcr.microsoft.com/k8s/core/pause:1.2.0
These images no longer pre-pulled:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.3
- k8s.gcr.io/cloud-controller-manager-amd64:v1.14.6
- k8s.gcr.io/cloud-controller-manager-amd64:v1.13.10
**Notes**:
=> chore: rev VHD images to 2019.10.15

test/e2e/runner/cli_provisioner.go
Instead of the E2E test runner building /22 subnets to emulate custom VNET scenario, let's build /20 subnets to accommodate larger pool sizes + Azure CNI (these require a lot of IP addresses).
**Notes**:
=> test: build larger subnets for E2E custom VNET scenario

test/e2e/config/config.go, test/e2e/kubernetes/kubernetes_test.go
Allow skipping all e2e test that require an SSH connection when the cluster VMs do not have an open SSH port.  Set environment variable `BLOCK_SSH` to `true` to skip all tests that rely on ssh.
**Notes**:
=> test: add e2e test parameter for skipping all ssh tests

parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
Fixes a connectivity issue we see intermittently in AKS.  After the external network is created, it may take "some time" for the network adapter to get an IP address.  It will have a 169.254.0.0 address.  It is best to wait for the network adapter to get a proper IP address before continuing.
In the repro we looked at, HNS used the 169.254 address for many VFP rules.  This means we created containers before the network adapter got its proper ip address.
Fixes ICM 147788786.  I do not think we have a public GitHub issue on this.
**Notes**:
=> fix: Wait for management IP after creating ext network.

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
apt-get purge operations should only run on Ubuntu clusters.
Fixes #2180 
**Notes**:
=> fix: don't run CSE apt purge operations on coreos

parts/k8s/cloud-init/artifacts/cse_helpers.sh, pkg/engine/templates_generated.go
PR #1719 prevented CSE from running twice, which some folks rely upon via `az vmss update|update-instances`.
This PR keeps the improvements in file wait from #1719, but keeps track of files once they have been validated as delivered by cloud-init.
**Notes**:
=> fix: CSE file wait is idempotent

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
In order to improve the average CSE run, we should not block apt-get purge operations (which include waiting for apt locks that can be held by other concurrent processes)
**Notes**:
=> fix: run all CSE apt-get purge operations in background

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
Make sure that the "Custom script finished successfully" log is printed at the very end of CSE.
**Notes**:
=> fix: move CSE endcustomscript log to very end of CSE

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, makedev.ps1
See https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
and https://github.com/deis/docker-go-dev/releases/tag/v1.23.5
and https://github.com/deis/docker-go-dev/releases/tag/v1.23.6
Contains special `k` from jakepearson/k#5.
**Notes**:
I updated `DEIS_GO_DEV_IMAGE` on upstream Jenkins. 🤞
=> chore: update go toolchain to 1.12.12

test/e2e/azure/cli.go, test/e2e/runner.go, test/e2e/runner/cli_provisioner.go
This reverts commit 133cb46c420e6c35483c77babd594a7bbd053ee0.
#2039 doesn't work well with the current soak test implementation. Revert until we're able to re-introduce it in a more resilient way.
**Notes**:
=> Revert "test: retry az commands in E2E tests (#2089)"

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/armresources_test.go, pkg/engine/templates_generated.go
In #2050 I pulled together two if statements in the custom data templates to make the code more concise. Unfortunately, I didn't test `if` the `and` statement short circuits or if it executes both side of the statement. This PR replaces the concise `and` with the less concise, but functionally correct double `if` statement.
I also added a test to ensure no one else will ever have this happen to them.
/cc @Bhuvaneswari-Santharam
=> fix: go template and does not short circuit causing nil ptr

pkg/engine/engine.go, pkg/engine/engine_test.go
This resolves an issue where the Windows extensions parameters were not being passed to the VM correctly.
**Notes**:
We were manually making this change in our ARM templates, but that didn't persist when running a cluster upgrade. This fix worked when upgrading that cluster from 1.15.4 -> 1.15.5.
Credit to @sylus for doing the research as to what the fix was.
=> fix: Resolve incorrect Windows extension params

cmd/deploy.go, cmd/deploy_test.go
Ensures that in cases where the cloud profile in the api model has not specified an identity system, the identity system passed in the cli will be used before using defaults. Issue only happens in deploy command. 
Fixes #2054
**Notes**:
=> fix: Ensured identity system passed from cli is propagated to api model

packer/install-dependencies.sh
Removing 1.10.x hyperkube images from the VHD should have been part of removing 1.10 support in  #2234.
**Notes**:
=> chore: remove k8s 1.10 from VHD

pkg/api/const.go
Change Azure CNI default version for windows vhd
Fixes #2270 
**Notes**:
=> fix: Change Azure CNI default version to match latest windows vhd

packer/configure-windows-vhd.ps1
Add 1.0.28 Azure CNI zip file into windows vhd to get align with linux vhd
Fixes #2267 
**Notes**:
=> fix: Add 1.0.28 Azure CNI zip file into windows vhd

hack/tools/Makefile, scripts/validate-go.sh
- Lock the version of the golangci-lint to a specific version for more build stability
- Specify vendor modules only
**Notes**:
=> chore: lock the golangci-lint to 1.21.0 and use vendored modules

pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/defaults.go
We are unnecessarily re-configuring the api model addons spec on both scale _and_ upgrade operations. We should only be doing this for upgrade operations, as scale operations do not affect the master vms, and thus do not change the control plane implementation.
**Notes**:
=> fix: addons "update config" is upgrade-only

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
Issue #2220 documents a case where the CSE failed to pull the pause image but reported success which led to a bunch of problems. This change adds checks around key docker commands and will fail the CSE if they do not run successfully (after a specified amount of retires)
Fixes #2220
**Notes**:
=> fix: add retry/logging/validation around docker command for windows

pkg/api/types.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachines_test.go, pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
Detailed background can be found in #2233 
Fixes #2233 
**Notes**:
- Though AKS will only generate agent nodes' ARM template, I associate addons' identity to master VM(SS) to keep consistent with agent nodes' behaviror.
=> feat: support using existing identity for addons

packer/install-dependencies.sh, parts/k8s/containeraddons/1.17/kubernetesmasteraddons-cloud-node-manager.yaml, parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/const.go, pkg/api/defaults-cloud-controller-manager.go, pkg/api/defaults-cloud-controller-manager_test.go, pkg/api/defaults-controller-manager.go, pkg/api/defaults-controller-manager_test.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/k8s_versions.go, pkg/api/k8s_versions_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/artifacts.go, pkg/engine/const.go, pkg/engine/params_k8s.go, pkg/engine/templates_generated.go, pkg/engine/testdata/key-vault-certs/kubernetes.json, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/workloads/storageclass-azurefile-external.yaml
Switches to the [out-of-tree cloud provider components](https://github.com/kubernetes/cloud-provider-azure/releases) if `useCloudControllerManager` is enabled and the Kubernetes version is 1.16.x or later. These components are considered alpha status currently but intended to become the default by 1.17 final release (early December!).
Fixes #1915
**Notes**:
The cloud-controller-manager is deployed as a [static pod manifest](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/) as it already was, and the cloud-node-manager is deployed as an addon. This is odd but I would argue the best we can do, but I'm open to feedback.
=> chore: use Azure CCM for k8s 1.16 and later

pkg/engine/artifacts.go, pkg/engine/const.go, pkg/engine/engine_test.go
Follow-up of #2290 
We are also interpreting Kubernetes manifest file artifacts w/ go templating + `ContainerService` data context. Until we actually use that data context, we need to ensure that this traversal doesn't change the file contents.
**Notes**:
=> test: ensure manifests aren't change by go template processing

docs/topics/sgx.md, test/e2e/kubernetes/workloads/sgx-test.yaml
The documentation for SGX was wrong
Error message i got when i tried to apply the pod configuration documented here
https://github.com/Azure/aks-engine/blob/master/docs/topics/sgx.md
The Pod "XXX" is invalid: spec.containers[0].volumeDevices[0].name: Invalid value: "dev-sgx": can only use volume source type of PersistentVolumeClaim for block mode
Fixes #2286 
**Notes**:
=> docs: Working way to use SGX

packer/install-dependencies.sh, parts/k8s/addons/1.17/kubernetesmasteraddons-kube-proxy-daemonset.yaml, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/kubernetesparams.t, parts/k8s/manifests/1.17/kubernetesmaster-kube-apiserver.yaml, parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml, parts/k8s/manifests/1.17/kubernetesmaster-kube-scheduler.yaml, pkg/api/k8s_versions.go, pkg/api/k8s_versions_test.go, pkg/engine/params_k8s.go, pkg/engine/templates_generated.go
Hyperkube is no more as of Kubernetes 1.17.0-alpha.2, so AKS Engine needs to provision its core `kube-` components and binaries from other official builds.
Fixes #1842
Unblocks #2158 (yes, I tested)
Related to #2161 (`UseCloudControllerManager=true` is broken for k8s 1.16+)
**Notes**:
Still TODO:
TODO in another PR, let's keep this one simple:
=> refactor: install kube- components without hyperkube for k8s 1.17+

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1170-alpha1
**Notes**:
This is blocked until #2191 merges.
- ~~k8s.gcr.io/hyperkube:v1.17.0-alpha.2 is not published (yet?).~~ See #1842.
=> feat: add support for Kubernetes v1.17.0-beta.1

docs/topics/azure-stack.md
=> docs: supported versions for disconnected Azure Stacks using VHD 2019.10.24

parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
The userAssignedIdentity property in azure.json for windows does not have quotes around the values. So when the value is empty string, you will get the following line in the json:
"userAssignedIdentityID": ,
That is a syntax error. 
**Notes**:
=> fix: userAssignedIdentityId in windows azure.json missing quotes

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1170-beta1
**Notes**:
=> feat: add support for Kubernetes 1.17.0-beta.2

packer/install-dependencies.sh
The kernel version may be updated by `apt-get dist-upgrade -y` during VHD CI, so we need to output the kernel version to our release notes artifact at the end of the VHD CI script instead of at the beginning, or we may note a version of the kernel that is not the actual version on the VHD OS.
**Notes**:
=> fix: VHD release notes should output the kernel version at end

releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201910_2019.10.24.txt
VHD release notes printed the Linux kernel version present at the beginning of the VHD CI run, but didn't take into account a newer version that was installed by apt-get dist-upgrade.
The above symptom has been fixed in #2338
**Notes**:
=> docs: fix bad Linux kernel info on 16.04 vhd 2019.10.24

pkg/api/addons.go, pkg/api/addons_test.go
Enables the cloud-node-manager addon if appropriate during `aks-engine upgrade`.
Fixes #2337
**Notes**:
=> fix: enable cloud-node-manager addon on upgrade when appropriate

.pipelines/pr-e2e.yaml
These two versions have been out of Kubernetes' support matrix (and AKS Engine's) for a while now, so let's reduce the load each PR requires in Azure DevOps. (We still have a Jenkins 1.12 job for now.)
See also #2276
**Notes**:
=> ci: stop testing k8s 1.11 and 1.12 on PRs

.pipelines/pr-e2e.yaml, examples/e2e-tests/kubernetes/release/default/definition.json, test/e2e/kubernetes/kubernetes_test.go
Rather than test Windows by creating entirely new clusters, let's just add a Windows node pool to every cluster configuration we test across Kubernetes versions.
This PR adds a Windows node pool to the "standard" cluster configuration we use for our current "Linux" Kubernetes version tests, effectively making them OS-agnostic (or more appropriately: OS-generic, as they will cover both OS flavors).
This PR also removes 1.11 and 1.12 from our PR test matrix to reflect that 1.13-->1.17 are the versions of Kubernetes that are actively under development upstream.
Fewer tests for the same amount of coverage!
**Notes**:
=> test: remove windows-specific tests, use windows node pools

cmd/generate_test.go
The unit test `TestExampleAPIModel` wasn't updated after Kubernetes 1.15.
**Notes**:
=> test: add k8s 1.16 and 1.17 to TestExampleAPIModel unit test

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
To better determine flakes, and specifically the validate DNS test flakes
**Notes**:
=> test: resilient print pod logs during E2E, print more pod logs

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1170-beta2
**Notes**:
=> feat: add support for Kubernetes 1.17.0-rc.1

pkg/api/defaults-kubelet.go, pkg/api/defaults.go, pkg/api/defaults_test.go
This fixes a regression that landed w/ #2274 
The IPAddressCount values in MasterProfile and each AgentPoolProfile depend (in part) upon the kublet configuration `--max-pods`; essentially these values are related and need to be configured in concert according to a deterministic ordinality.
This PR moves the IPAddressCount default enforcement for both masters and pools to occur after the kubelet defaults codeflow.
The primary fix here is missing UT. :(
**Notes**:
=> fix: correct defaults order for setting IPAddressCount

test/e2e/azure/cli.go, test/e2e/runner/cli_provisioner.go
The most common `az` CLI flake during E2E runs is doing an operation against a resource group that was created just moments earlier:
```
$ timeout 60 az group create --name kubernetes-westeurope-71037 --location westeurope --tags now=1574462830
$ timeout 60 az network vnet create -g kubernetes-westeurope-71037 -n kubernetes-westeurope-71037CustomVnet --address-prefixes 10.239.0.0/16
2019/11/22 22:47:15 Error while trying to create vnet with the following command:
az network vnet create -g kubernetes-westeurope-71037 -n kubernetes-westeurope-71037CustomVnet --address-prefixes 10.239.0.0/16
Output:ERROR: error retrieving default location: Resource group 'kubernetes-westeurope-71037' could not be found.
```
This PR does an `az group show` until it gets a successful …
=> test: resilient az group create during E2E provisioning

test/e2e/kubernetes/config.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go, test/e2e/kubernetes/persistentvolume/persistentvolume.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/storageclass/storageclass.go
In response to observed E2E flakes in the kubectl portforward test, putting more of the "kubectl run" E2E conveniences behind async/retry interfaces.
**Notes**:
=> test: more resilient kubectl run interfaces
