examples/e2e-tests/kubernetes/release/default/definition.json
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/workloads/nginx-master.yaml
test/e2e/kubernetes/workloads/pod-pvc.yaml

This PR adds SLB-appropriate config to the cluster configuration used in PR E2E tests. Also updates some test manifests, where appropriate.
**Notes**:

test: use SLB in E2E cluster configs

---

pkg/api/addons.go
pkg/api/addons_test.go

Follows up on #2345 to fix the enabling csi-azuredisk-* and csi-azurefile-* components on upgrade. Also addresses a [review comment](https://github.com/Azure/aks-engine/pull/2345#discussion_r349354611) on the previous PR.
Refs #2337
**Notes**:

fix: enable CSI addons on upgrade when appropriate

---

test/e2e/kubernetes/kubernetes_test.go

This change fixes some of our upgrade/scale and back-compat test flows, which by convention scale down node pools before upgrading them. In the scale down case, we need to skip cluster-autoscaler tests because the out-of-band (from the perspective of cluster-autoscaler) scaling operation sort of turns the cluster-autoscaler enforcement vector into a no op (i.e., the node count changes in our tests don't currently manually update the cluster-autoscaler configs as well).
**Notes**:

test: ensure cluster-autoscaler tests don't run if min-nodes is > nodes in pool

---

Makefile
hack/tools/Makefile

The local container and the build system have out of sync tools leading to different versions of generated code and linting errors sneaking into master.
This PR will install all dev tools local to the repo in `./hack/tools/bin`. The top level Makefile will then add the `./hack/tools/bin` dir to the head of `$PATH`. After that, the scrips execute as they normally would, but using the local bin directory, rather than the `$GOBIN`, which could be changed by any number of other projects.
Also of note:
- added tools clean up to `make clean`
- added an echo to generate to be absolutely clear what version of go-bindata is being used
**Notes**:

fix: install tools bins locally and add to PATH

---

scripts/build-windows-k8s.sh

Removes code specific to Kubernetes 1.8 and earlier from the script called by `make windows-k8s`.
**Notes**:

style: remove dead code from Windows build script

---

pkg/api/common/versions.go

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1170-rc1
~~Also updates cluster-autoscaler to 1.17.0, see https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.17.0~~
See also #2390 
**Notes**:

feat: add support for Kubernetes 1.17.0-rc.2 

---

parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml
pkg/api/addons_test.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go

Defaults `useCloudControllerManager` to false for Kubernetes 1.17, and restores e2e tests that were being skipped.
Fixes #2369 
**Notes**:

fix: default useCloudControllerManager to false for 1.17

---

docs/design/custom-container-images.md

From the problem statement in the doc:
The existing AKS Engine Kubernetes component container image configuration surface area presents obstacles in the way of:
1. quickly testing/validating specific container images across the set of Kubernetes components in a working cluster; and
2. using Azure Container Compute Upstream-curated MCR container images instead of Kubernetes SIG-Release-curated k8s.gcr.io container images.
**Notes**:

docs: configurable component images design doc

---

packer/configure-windows-vhd.ps1
packer/install-dependencies.sh
parts/k8s/cloud-init/masternodecustomdata.yml
pkg/api/common/versions.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md
**Notes**:
This will fail until Kubernetes 1.17.0 is actually released (presumably on or after 12/9), and until the Windows support .zip is mirrored.

feat: add support for Kubernetes 1.17.0

---

pkg/api/common/versions.go

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#changelog-since-v1156
**Notes**:
I'll collect the VHD-related changes into a separate PR so we can focus discussion on those changes.

feat: add support for Kubernetes 1.15.7

---

pkg/api/common/versions.go

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#changelog-since-v1163
**Notes**:
I'll collect the VHD-related changes into a separate PR so we can focus discussion on those changes.

feat: add support for Kubernetes 1.16.4

---

pkg/api/addons.go
pkg/api/addons_test.go

Follow up from #2393 and #2416. UT was not fully engaged, and thus the back-compat was not implemented exactly right. This PR fixes UT, and implements back-compat according to the following recipe:
- If you are in an upgrade context and your cluster version is >= 1.12 (when coredns support first landed in aks-engine):
- Ensure that coredns addon is set to enabled if there is no coredns addon entry in the addons array
- The absence of coredns in the addons array indicates a "legacy" cluster config, i.e., a cluster config built using aks-engine prior to coredns being added as a user-configurable addon
- Ensure that kube-dns addon is set to disabled
- This is statically done, essentially to mimic the legacy implementation, which statically disables kube-dns and …

fix: kube-dns and coredns addons UT, back-compat

---

pkg/api/common/versions.go

https://github.com/Azure/aks-engine/issues/2312
v1.14.10 doesn't have this fix:
https://github.com/kubernetes/kubernetes/pull/86006
So we don't want to support it.
**Notes**:

chore: remove 1.14.10 support

---

parts/k8s/cloud-init/artifacts/kubelet.service
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/scripts/net-config-validate.sh
test/e2e/kubernetes/util/util.go
test/e2e/test_cluster_configs/large-vm-sku.json

For nodes with more CPU/Memory, the default kernel settings for  ubuntu is not big enough for high-performance server scenarios.
We changed the values for ARP table, network connections. These optimizations are applied widely in the industry.
- [X ] includes documentation
**Notes**:

fix: change kernel settings based on number of cores

---

pkg/api/addons_test.go

The `node-problem-detector` addon should have been part of the `TestSetAddonsConfig` unit test.
**Notes**:

test: include node-problem-detector in addons config test

---

test/e2e/kubernetes/event/event.go
test/e2e/kubernetes/kubernetes_test.go

Adds an e2e test spec that creates a kernel message which node-problem-detector should turn into a Kubernetes event, if everything is wired up properly.
Follows up on #2371
Refs #2389, #2411
**Notes**:

test: check k8s events to see if node-problem-detector works

---

pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go
pkg/api/defaults.go
pkg/api/types.go
pkg/api/vlabs/types.go
pkg/engine/armresources_test.go
pkg/engine/armtype_test.go
pkg/engine/availabilitysets.go
pkg/engine/availabilitysets_test.go
pkg/engine/masterarmresources_test.go

Allow user-overridable `platformUpdateDomainCount` to accommodate Azure regions that are unable to accommodate the static default `3` (e.g., `centraluseuap`).
This PR essentially keeps the static `3` configuration in place (via defaults enforcement), i.e., it does not auto-configure the platform update domain count value based on region.
**Notes**:

feat: enable user-configurable platformUpdateDomainCount

---

test/e2e/kubernetes/kubernetes_test.go

Part of the master/agent node labels test was skipped on Windows, but should have been restored after #1660 was closed.
**Notes**:

test: restore Windows node labels spec

---

cmd/upgrade.go
docs/topics/keyvault-secrets.md
docs/topics/upgrade.md
hack/tools/vendor/gopkg.in/tomb.v1/tomb.go
pkg/engine/template_generator_test.go

This PR accounts for my second strategy to solve the limitation
described in #2396. Rather than introduce the KeyVault client, so we can
run `GetSecret` and fetch our certs and keys, I read a local config file
based on what's passed into the command line.
This is not a complete PR, because I think the same stuff would need to
be done anywhere else `GenerateKubeConfig` is called.
See #2396 
See #2396  
**Notes**:

feat: Adds kubeconfig option to upgrade cmd

---

pkg/engine/vmextensions.go
pkg/engine/vmextensions_test.go

fix: fix ARM dependency issues with vm user-specified extensions on node pools

---

cmd/scale.go

fix: If K8s cluster deployed with microsoft-aks windows vhd then scale up scenario fail with error "resource name was missing from identifier" because current code is only checking for MicrosoftWindowsServer based publisher.
Fixes #2482 
**Notes**:

fix: Check microsoft-aks based os publisher for windows in scale scenario.

---

parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsconfigfunc.ps1
pkg/engine/templates_generated.go

Windows nodes are configured with no log rotation and this can lead to disks filling up for long running clusters.
This PR sets the log rotation setting to be the same as what is set as default for linux machines.
Fixes issue #373
**Notes**:

feat: Configuring docker log rotation for Windows nodes

---

scripts/collect-windows-logs.ps1

The previous method I used to create an array of files would sometimes end up creating a two-dimensional array. Allocating it separately as an empty array and always using += avoids this and is easier to read

fix: Fix some path handling in collect-windows-logs script

---

pkg/helpers/helpers.go
pkg/helpers/helpers_test.go

according to [Accelerated Networking doc](https://azure.microsoft.com/en-us/blog/maximize-your-vm-s-performance-with-accelerated-networking-now-generally-available-for-both-windows-and-linux/), DSv2 supports accelerated networking feature, "DS3 v2" is one of the [DSv2 SKU](https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/#d-series), this change is to add this SKU in to the supported list.
Fixes #2508
**Notes**:

fix: add "Standard_DS3_v2" to "AcceleratedNetworking" supported list

---

test/e2e/test_cluster_configs/flannel/docker.json

#2517 removed the restriction on testing >= 1.16 against flannel + docker scenarios. Probably because #2067 was overlooked.
#2067 re-opened and the >= 1.16 testing restriction re-introduced with this PR.
**Notes**:

test: don't test non-working >= 1.16 flannel + docker

---

pkg/api/common/helper.go
pkg/api/common/helper_test.go
test/e2e/kubernetes/kubernetes_test.go

To preserve the existing behavior of the deprecated `node-role.kubernetes.io/master`, future versions of Kubernetes will use these two [more targeted labels](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-07-16-node-role-label-use.md#instructions-for-deployers).
Fixes #2265
**Notes**:
These do no harm to apply to earlier versions of Kubernetes, so this is the simplest implementation.
The added e2e spec will fail eventually in upgrade testing, which builds clusters with earlier versions of AKS Engine but may run tests from master. To fix that, we can skip that part of the test unless the k8s version is 1.17.1 (not released yet) or greater.

fix: apply new master node labels for k8s v1.18+ compatibility

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowskubeletfunc.ps1
parts/k8s/windowslogscleanup.ps1
pkg/engine/const.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

Fixes #2470 
**Notes**:
This change increases the size of kubelet.err.log/kubeproxu.err.log to 10Mb and adds a scheduled task to keep the 5 most recent rotated logs.

feat: cleaning up old kubelet/kubeproxy logs for Windows nodes

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
pkg/api/defaults.go
pkg/api/types.go
pkg/api/types_test.go

As part of PR #2393, the following change was made to move addon configuration after setting kubelet config - https://github.com/Azure/aks-engine/commit/691e3d3c3a837abbb4f607d5e6b040b517af0f2a#diff-fd43f080184ed15731e5d7e0d917d6e1L486-L490. This change breaks setting kubelet config as kubelet configuration checks for addon configs while setting defaults. For instance `--non-masquerade-cidr` in kubelet is set to cluster subnet if `ip-masq-agent` is not enabled. But since the addon was configured after, kubelet assumes masq-agent is not enabled and sets the `--non-masquerade-cidr` to cluster subnet. This results in `ip-masq-agent` and `kubelet` both configuring iptables which could possibly break things.
**Notes**:
cc @lachie83

fix: configure addons before setting kubelet config

---

test/e2e/engine/template.go

This PR injects the `LOCATION` env var in an E2E test run into the api model for convenient cloud-specific template generation value add.
**Notes**:

test: use LOCATION env var for api model in E2E tests

---

parts/k8s/addons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.16/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
parts/k8s/addons/1.16/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
parts/k8s/addons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.17/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
parts/k8s/addons/1.17/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
parts/k8s/addons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.18/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
parts/k8s/addons/1.18/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
pkg/engine/templates_generated.go

This PR updates blobfuse-flexvolume and keyvault-flexvolume daemonsets to the `system-cluster-critical` PriorityClass to ensure that they are properly prioritized during pod scheduling.
For the `nmi` daemonset in the aad-pod-identity addon, we migrated the namespace to `kube-system`, as `system-cluster-critical` isn't allowed in the default namespace.
Specifically, during scale up events in response to more pods than available scheduleable nodes (e.g., cluster-autoscaler), we want to ensure that system daemonsets are scheduled first of all on new nodes, so that nodes don't reach pod capacity w/ non-system-critical pods before these daemonsets have a chance to be scheduled.
https://github.com/Azure/aad-pod-identity/issues/471
Fixes #2532
Fixes #2531 …

fix: promote system addons to system-cluster-critical

---

test/e2e/test_cluster_configs/byok.json

BYOK support is available in northeuerope, so let's prefer that over canary for testing.
**Notes**:

test: use northeurope for byok testing

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go

Due to https://github.com/kubernetes/kubernetes/pull/86210,  deploying kubelet built from k8s master branch will have the following error:
```
unrecognized feature gate: PodPriority
```
We should remove `PodPriority` feature gate since it's already enabled by default since k8s 1.11.
@aramase this PR should fix the timeout issue in https://testgrid.k8s.io/provider-azure-on-call#dualstack-azure-e2e-master
**Notes**:

fix: Remove PodPriority feature gate

---

pkg/api/azenvtypes.go
releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.10.txt
releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.10.txt
test/e2e/test_cluster_configs/no_outbound.json

This PR updates VHD references for Ubuntu 16.04-LTS and 18.04-LTS images.
- Updates the 16.04-LTS kernel to:
- `Linux version 4.15.0-1066-azure (buildd@lgw01-amd64-023) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #71-Ubuntu SMP Thu Dec 12 20:35:32 UTC 2019`
- Delivers etcd v3.3.18 (was: ~~v3.3.15~~)
- Adds Azure CNI 1.0.30
- Adds CNI plugin 0.7.6
- Adds Azure Stack VHD support for v1.15.7 hyperkube:
- `mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.15.7-azs`
- Changes the following container image references:
- `mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v0.3.0`
- instead of ~~mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.3.0~~
- `mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager:v0.3.0`
- …

chore: update VHD references to 2020.01.10

---

pkg/helpers/helpers.go
pkg/helpers/helpers_test.go

Updates the list of VM SKU types with the `acceleratedNetworkingEnabled` capability set to `True`, and adds the commands necessary to update it in the future.
Fixes #2562
Fixes #2519
Refs #1894
**Notes**:
This stops well short of automating this process, but if we think it needs more polish or a one-liner `make` target, please offer that feedback.

fix: update list of SKUs with accelerated networking support

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

Removes the random password configuration for the `etcd` user, so it has an empty password. Since we don't intend any Linux account to log in with username and password, adding a random one here is just confusing things. This makes /etc/passwd and /etc/shadow look consistent for the passwd field.
Refs #2569
**Notes**:

fix: don't configure password for "etcd" user

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR sets default WindowsSku and WindowsVersion when upgrading a VMSS.
**Notes**:

feat: Set the default Windows sku and version when upgrading a VMSS

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

Moves the download source for the `img` utility to our preferred production blob storage.
This is the first baby step in an effort to move off of the `acs-mirror` blob storage (and replace manual steps with automated pipelines).
Refs #2545
**Notes**:

build: fetch img tool from upstreamartifacts storage

---

test/e2e/cluster.sh

More resilient cluster.sh implementation when ADD_NODE_POOL_INPUT var is unset 
**Notes**:

test: fix unset ADD_NODE_POOL_INPUT var in cluster.sh test script

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/util/util.go

Skip storage class e2e test when ephemeral disk is used since storage classes aren't deployed. 
**Notes**:

fix: Skip storage class e2e test when ephemeral disk is used

---

vhd/packer/install-dependencies.sh

This PR modifies the comment suggesting we want to remove the `registry` container image from our VHD pre-pulled set of container images, as air-gapped environments will continue to need this image indefinitely.
Fixes #2307 
**Notes**:

docs: remove VHD code comment suggesting registry is temporary

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1171
**Notes**:
This is considered a ["no-op" release](https://groups.google.com/forum/#!topic/kubernetes-dev/Mhpx-loSBns/discussion) to work out a build issue, so we may want not want to bother merging this since 1.17.1 wasn't actually affected in our CI pipeline.

feat: add support for Kubernetes 1.17.2

---

test/e2e/cluster.sh
test/e2e/config/config.go
test/e2e/kubernetes/kubernetes_test.go

Until we make the E2E test runner more intelligent so that it is able to introspect the modified api model after a `addpool` operation, we should not check for a static node count in the E2E test job (because we are not correctly calculating the static count of nodes in the cluster in this context).
**Notes**:

test: don't test for static node count if add node pool context

---

test/e2e/config/config.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/everything.json

This PR modifies the PVC E2E test implementation so that it only runs if a `TEST_PVC` env var is set to `true` (in addition to other, pre-existing conditional criteria).
We will ship this change w/ a change to the "everything" test cluster configuration, so that that cluster config gets PVC test coverage.
**Notes**:

test: configurable pvc E2E tests

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/everything.json

It seems that due to this issue our increase of node pools has revealed a bug in HPA, where it doesn't scale down if pods are Pending:
https://github.com/kubernetes/kubernetes/issues/85506
This PR only calculates cluster-autoscaler-engaged node pools when determining how to configure HPA for scale up, so that there aren't Pending pods when we stop load.
**Notes**:

test: HPA/cluster-autoscaler fixes so we don't scale up too many pods

---

test/e2e/test_cluster_configs/everything.json

This PR grants cluster-autoscaler more tolerance to scale up pool1 on the "everything" test config.
**Notes**:

test: allow cluster-autoscaler more nodes in everything test config

---

parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml
pkg/engine/templates_generated.go

Custom kube-controller-manager template should reference hyperkube

fix: custom kube-controller-manager template should reference hyperkube

---

pkg/engine/networkinterfaces.go
pkg/engine/networkinterfaces_test.go

This PR fixes a regression introduced in #2572 where multiple master VM + private cluster scenarios have an empty ILB backend pool when LB type is basic.
Fixes #2645
**Notes**:

fix: private cluster + multiple masters in backend ILB pool

---

pkg/helpers/azureconst.go

Adds four new VM SKUs picked up by the `pkg/helpers/generate_azure_constants.py` script:
- Standard_DC1s_v2
- Standard_DC2s_v2
- Standard_DC4s_v2
- Standard_DC8_v2
**Notes**:
According to the [accelerated networking query](https://github.com/Azure/aks-engine/blob/master/pkg/helpers/helpers.go#L118-L119) these VM types do not support accelerated networking, so they weren't added to that list.

feat: add new Standard_DC[x]s_v2 VM SKUs

---

parts/k8s/kubernetesparams.t
pkg/api/azenvtypes.go
pkg/api/const.go
pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
pkg/armhelpers/httpMockClientData/deployVMRequest.json
pkg/armhelpers/httpMockClientData/deployVMResponse.json
pkg/engine/templates_generated.go
pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Moves the download source for `azure-cni` archives to our preferred production blob storage.
This is second step in an effort to move off the `acs-mirror` blob storage (and replace manual steps with automated pipelines).
Refs #2545
**Notes**:
Note that the cni-plugins archive is a different beast not tamed in this PR. This is just azure-vnet-cni.

build: fetch azure-vnet-cni from kubernetesartifacts storage

---

pkg/engine/virtualmachinescalesets.go

Addresses breaking change in Azure SDK for Go that causes the struct nesting in vmss extensions to not work properly anymore as the `Type` field is now both present in `VirtualMachineScaleSetExtensionProperties`  and `VirtualMachineScaleSetExtension`. See https://github.com/Azure/azure-rest-api-specs/pull/7724#issuecomment-576961394 for more details.
Fixes #2605 
**Notes**:

refactor: stop using type nesting in billing extensions 

---

examples/kubernetes.json
pkg/engine/armresources_test.go
pkg/engine/loadbalancers.go
pkg/engine/loadbalancers_test.go

This PR sets the `AllocatedOutboundPorts` configuration to `0`, as this is a preferred default configuration for LB outbound rules.
`0` is equivalent to "automatic", which means is preferable to the Azure-provided default of `1024` , which essentially caps SNAT ports at that number.
See here for more info:
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-rules-overview
Fixes #2558
**Notes**:

fix: default LB AllocatedOutboundPorts to 0

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/kubernetesparams.t
pkg/api/azenvtypes.go
pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
pkg/armhelpers/httpMockClientData/deployVMRequest.json
pkg/armhelpers/httpMockClientData/deployVMResponse.json
pkg/engine/templates_generated.go
pkg/engine/transform/transformtestfiles/k8s_slb_scale_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_vmss_scale_template.json
pkg/engine/transform/transformtestfiles/k8s_slb_vmss_template.json
vhd/packer/install-dependencies.sh

Moves the download source for `cni-plugins` archives to our preferred production blob storage.
This is third step in an effort to move off the `acs-mirror` blob storage (and replace manual steps with automated pipelines).
Refs #2545
**Notes**:

build: fetch cni-plugins from kubernetesartifacts storage

---

cmd/addpool.go

This PR properly persists the additional node pool after a successful `aks-engine addpool` operation, so that subsequent operations (e.g., scale, upgrade) will be able to know about the new pool via the canonical api model JSON.
**Notes**:

fix: persist new pool after addpool operation

---

cmd/upgrade.go
cmd/upgrade_test.go

This PR evolves the CLI upgrade functionality so that we include a `IsVMSSToBeUpgraded` method spec to the `UpgradeCluster` struct object. This method spec will ensure that the upgrade operationa is able to determine at runtime whether or not a VMSS present in the cluster resource group is actually a VMSS that correlates with an `AgentPoolProfile` of type `"VirtualMachineScaleSets"` in the cluster spec.
At present (passing in no method spec), the `aks-engine upgrade` operation is subject to edge case scenarios where VMSS instances in the resource group *not* created by `aks-engine` are evaluated as Kubernetes nodes.
**Notes**:

chore: use IsVMSSToBeUpgraded func to validate vmss pools in upgrade

---

parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
pkg/engine/templates_generated.go

Script `setup-custom-search-domains.sh` is passing an unexpected param to `systemctl_restart`.
Same change-set as #1562

fix: remove extra param from 'systemctl_restart' invocation

---

pkg/api/vlabs/validate.go
pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json
pkg/armhelpers/httpMockClientData/deployVMRequest.json
pkg/armhelpers/httpMockClientData/deployVMResponse.json
pkg/engine/transform/transformtestfiles/k8s_template_jumpbox.json
pkg/engine/transform/transformtestfiles/k8s_upgrade_template_jumpbox.json

Changes references to the deprecated acs-mirror storage to point to the approved locations.
Refs #2545 
**Notes**:

docs: refer to kubernetesartifacts storage in examples and comments

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.30.txt
vhd/release-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.30.txt

This PR brings in the `2020.01.30` VHD for both Ubuntu 16.04-LTS and 18.04-LTS.
Includes a new kernel version for 18.04-LTS:
- `Linux version 5.0.0-1028-azure (buildd@lcy01-amd64-028) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019`
Includes the following changes:
- includes moby v3.0.10
- changed from moby v3.0.8
- k8s.gcr.io/kube-apiserver:v1.17.2
- k8s.gcr.io/kube-controller-manager:v1.17.2
- k8s.gcr.io/kube-proxy:v1.17.2
- k8s.gcr.io/kube-scheduler:v1.17.2
- k8s.gcr.io/hyperkube-amd64:v1.16.6
- k8s.gcr.io/hyperkube-amd64:v1.15.9
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.9
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.15.9-azs
- …

chore: rev Linux VHDs to 2020.01.30

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Removes password expiration for the Linux `adminUser` account, since it uses only public key auth. Same for the non-interactive `etcd` account. Leaves the default rotation policy intact for accounts that may be created with passwords.
```shell
$ sudo cat /etc/shadow  # before
root:*LOCK*:14600::::::
daemon:*:18268:0:99999:7:::
bin:*:18268:0:99999:7:::
sys:*:18268:0:99999:7:::
...
statd:*:18277:0:99999:7:::
azureuser:!:18292:7:90:7:30::
etcd:!:18292:7:90:7:30::
$ sudo cat /etc/shadow  # after
root:*LOCK*:14600::::::
daemon:*:18268:0:99999:7:::
bin:*:18268:0:99999:7:::
sys:*:18268:0:99999:7:::
...
statd:*:18277:0:99999:7:::
azureuser:!:18292:0:99999:7:::
etcd:!:18292:0:99999:7:::
```
Closes #2569 
Fixes #2277
**Notes**:

fix: don't expire adminUser or etcd accounts

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

Follow-up from #2613. Now that we are delivering a `+azure` suffix w/ the internal Azure builds moby, we need to strip that from the version substring fetcher in CSE.
**Notes**:

fix: update CSE moby version substring match

---

test/e2e/cluster.sh
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/node/node.go

Use `Ready` as a required node status before determining to test it. This is more sane in general, and specifically, should help improve test flakes when running E2E immediately after running `aks-engine upgrade`, which may finish before all deleted vms have been unregistered as nodes in the cluster.
**Notes**:

test: wait for "Ready" nodes, where appropriate

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This PR doesn't add an unused `KUBELET_IMAGE` env var in the `/etc/default/kubelet` config file if the Kubernetes version is >= 1.17.0, because we don't support hyperkube starting with that version of k8s.
**Notes**:

chore: don't refer to hyperkube in template if > 1.16

---

pkg/armhelpers/utils/util.go
pkg/armhelpers/utils/util_test.go

Unknown ostype when getting an index should probably create an error
Today it just returns zero. Not sure if this is a real problem but popped up in our unittests that consume this package. 
Can create an issue but my face was already in the code :)
- [fix ] uses [conventional commit messages](https://www.conventionalcommits.org/)
**Notes**:

fix: unknown ostype when getting an index should probably create an error

---

Makefile
docs/topics/telemetry.md
go.mod
go.sum
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/api/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/engine/armvariables.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go
pkg/telemetry/telemetry.go
scripts/ginkgo.coverage.sh
test/e2e/Makefile
test/e2e/go.sum

This pull request enables users and aks-engine to have Application Insights telemetry keys. 
The telemetry key is now injected into the build rather than being hard coded as a const. This should allow us to override the ldflags for a release build to inject a telemetry key upon release.
fixes #2575

feat: multi AI telemetry keys

---

scripts/collect-windows-logs.ps1

When running this script remotely via ssh, Compress-Archive will fail because of the progress bar which can't be displayed.
This adds $ProgressPreference="SilentlyContinue" to logs collector script for Windows so that the script won't error out.

fix: add ProgressPreference=SilentlyContinue to disable progress bar

---

test/e2e/azure/cli.go
test/e2e/runner.go

This fixes creating soak clusters from scratch (before a rg exists).
**Notes**:

test: don't get vms before resource group exists

---

test/e2e/cluster.sh

need a default val for `$LB_TEST_TIMEOUT`
**Notes**:

test: add LB_TEST_TIMEOUT default

---

test/e2e/engine/template.go

unblocking e2e tests by hardcording iis image

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/testdata/azurestack/kubernetes.json

Block Azure Stack deployments if apimodel contains unsupported features.
Warn users if they enabled/selected preview features.  

feat: abort/warn if apimodel contains properties not supported by Azure Stack

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202002_2020.02.12.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202002_2020.02.12.txt

Revs AKS Engine Linux VHDs to `2020.02.12`. The new reference is to new SKUs `aks-engine-ubuntu-1604-202002`, and `aks-engine-ubuntu-1804-202002`, allowing AKS to manage its own VHD using the existing `aks-ubuntu-1604-<YYYYMM>` format, as the AKS VHD spec has diverged from the AKS Engine VHD Spec.
Compared to the existing AKS Engine VHDs, the new VHDs bring the following changes:
Adds the following pre-downloaded container images:
- k8s.gcr.io/kube-apiserver:v1.17.3
- k8s.gcr.io/kube-controller-manager:v1.17.3
- k8s.gcr.io/kube-proxy:v1.17.3
- k8s.gcr.io/kube-scheduler:v1.17.3
- k8s.gcr.io/hyperkube-amd64:v1.16.7
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.10
- mcr.microsoft.com/containernetworking/azure-npm:v1.0.32
No longer includes these container images:
- …

chore: rev AKS Engine Linux VHDs to 2020.02.12

---

docs/topics/clusterdefinitions.md
pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go

Updates a kube-apiserver flag to its non-experimental name, which has been in effect since k8s 1.13.
Fixes #2720
**Notes**:

fix: update apiserver encryption provider config flag

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/api/defaults_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This PR adds base layer of bpf debugging tools to aks-engine vhd + and cse install script. We'd like every cluster we bootstrap to have these tools available to do deep performance analysis and debugging, both ad-hoc and via automation. While we'd ultimately like to get bpftrace binaries on the system, we can immediately get benefit by using the lower-level bcc tools now. These also have much quicker install time, so it's easy to add them into the normal install path.
update: added bpftrace binary! for automation use cases and programmable interaction with the data, we will still want to keep the bcc libs installed. so this change can be purely additive.
n/a
**Notes**:

feat: install bpftrace + bcc by default

---

parts/k8s/cloud-init/artifacts/kubelet.service
pkg/engine/templates_generated.go
test/e2e/kubernetes/scripts/net-config-validate.sh

We should apply the large IPv4 neigh GC settings for all nodes (instead of just nodes with more than 8 cores). This is needed because we have seen many cases where CoreDNS is only working intermittently due to this issue. CoreDNS may not run on a large node but still has to handle many connections to it from many other pods.
**Notes**:

fix: apply large ipv4 neigh GC settings to nodes of all sizes

---

pkg/armhelpers/azureclient.go

While adding new Azure client support to our `AzureClient`, I noticed that not all client objects are being initialized the same way. This appears to be an oversight, so I fixed it.
**Notes**:

fix: init Azure clients consistently

---

pkg/engine/params.go
pkg/engine/params_test.go

Fix #2712 
Set vnetCidr by the address space of the vnet
**Notes**:

fix: Set vnetCidr by the address space of the vnet

---

pkg/engine/params.go
pkg/engine/params_test.go

Fix #2712
Set vnetCidr by the address space of the vnet
**Notes**:

fix: Set vnetCidr by the address space of the vnet (#2725)

---

.pipelines/pr-e2e.yaml
Jenkinsfile

Kubernetes 1.13 has been off the support matrix for a while, so in advance of disabling it, let's stop using CI resources to test it.
AKS is dropping support for 1.13 on [Feb. 28th](https://github.com/Azure/AKS/releases/tag/2020-02-03).
**Notes**:

ci: stop testing k8s 1.13

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR fixes an anomolous invocation of `configAddons` during CSE, which only exists according to a particular set of conditions. E.g.:
```
+ time_metric ConfigAddons configAddons
+ local name start end diff tags
+ name=ConfigAddons
+ shift
++ apmz time unixnano
+ start=1582571554614609524
+ configAddons
/opt/azure/containers/provision.sh: line 69: configAddons: command not found
```
**Notes**:

fix: only configAddons if addons enabled

---

parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/templates_generated.go

fix: apiserver broken due to incorrect kms cachesize
When enabling KMS feature on aks-engine, apiserver could not start up due to incorrect kms cachesize
original error is like following:
```
I0222 14:21:26.635590       1 services.go:51] Setting service IP to "10.0.0.1" (read-write).
I0222 14:21:26.635604       1 server.go:596] external host was not specified, using 10.255.255.5
I0222 14:21:26.635609       1 server.go:639] Initializing cache sizes based on 0MB limit
I0222 14:21:26.635886       1 server.go:150] Version: v1.18.0-alpha.5
Error: error while parsing encryption provider configuration file "/etc/kubernetes/encryption-config.yaml": error while parsing file: resources[0].providers[0].kms.cachesize: Invalid value: 0: cachesize should be a positive value, or …
```

fix: apiserver broken due to incorrect kms cachesize setting

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go

This PR prints more debug info to stdout if linux pod DNS validation fails.
**Notes**:

test: get pod network info if dns validation fails

---

pkg/api/components.go
pkg/api/components_test.go

This PR makes the new components interface work w/ Azure Stack. There is nothing Azure Stack-specific about how it defines the `KubernetesImageBase` configuration, and this change removes the assumption that Azure Stack uses the `AzureCloudSpecEnvMap` map to define it.
**Notes**:

fix: components works with Azure Stack

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go

Most of the exit codes used by the bpf download scripts are reserved. We should avoid using any reserved codes in our scripts. This PR changes all reserved codes to unreserved values.
n/a
**Notes**:

fix: use non-reserved exit codes for bcc/bpf install

---

vhd/packer/install-dependencies.sh

Azure Stack will be using images hosted in MCR instead of `k8s.gcr.io`. In order to make this work on air-gapped environments, we need to pre-pull MCR addons as well.
**Notes**:
~~I did not check how much extra disk space this requires.~~
~~I will be checking the CI output.~~
As far as I can tell, disk usage percentage did not change

chore: pre-pull addon images hosted in MCR

---

pkg/api/addons.go
pkg/api/addons_test.go

The kube-proxy addon always references the regular hyperkube image regardless of the target cloud. This PR makes sure that Azure Stack's custom hyperkube image is used when appropriated.

fix: kube-proxy uses custom hyperkube on Azure Stack

---

pkg/api/components.go
pkg/api/components_test.go

This PR enforces component command configuration override during upgrade, which is documented here:
https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md#components
Specifically:
> this configurable vector is designed for cluster creation only. Using aks-engine upgrade on a cluster will override the original, user-configured settings during the upgrade operation, rendering an upgraded cluster with the AKS Engine defaults for kube-controller-manager, cloud-controller-manager, kube-apiserver, kube-scheduler, and kube-addon-manager.
We would be true to the above documentation to statically override all configuraiton key/vals in an upgrade flow, but in the event that we want to enable some subset of the components container configuration to …

fix: override components command config during upgrade

---

go.mod
hack/tools/Makefile
vendor/gopkg.in/yaml.v2/encode.go
vendor/modules.txt

Updates `make build` and friends for the go 1.14 toolchain.
Note that we're still using go 1.13.8 in CI for now, so this *should* work with both versions. I have tested locally with go 1.14.
Fixes #2812
**Notes**:

fix: update yaml.v2 and golangci-lint for go 1.14 compatibility

---

pkg/api/const.go
pkg/api/defaults-controller-manager.go
pkg/api/defaults-controller-manager_test.go
pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
pkg/api/defaults.go
pkg/api/types.go
pkg/api/types_test.go

Default AKSe settings do not play well with Azure Stack limits. This PR changes defaults for Azure Stack to reduce the load to ARM.

chore: default to large cluster settings on Azure Stack

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/sgx.json

Update sgx driver download urls
Fixes #2743

fix: Updated sgx driver download urls. Fixes issue 2743

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

The latest `kubectl` built from k/k master branch causes `/usr/local/bin/kubectl cluster-info` in CSE to time out due to a new validation logic introduced in https://github.com/kubernetes/kubernetes/pull/86173/commits/b19ad9e7a78fea0ecdffe7aa53bbe309d9d346ee. This PR explicitly set kubeconfig when using kubectl to avoid this problem.
**Issue Fixed**: https://github.com/Azure/aks-engine/issues/2845
**Notes**:

fix: explicitly set kubeconfig when using KUBECTL in CSE

---

scripts/collect-windows-logs.ps1

feat: collect Windows CSE logs during log collection

---

parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/templates_generated.go

Update `EncryptionConfig` resources to `EncryptionConfiguration` using the stable API server encryption configuration as `EncryptionConfig` is deprecated.
Ref: https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#encrypting-your-data-with-the-kms-provider
fixes: #2777 
**Notes**:

fix: update EncryptionConfiguration

---

examples/azure-stack/kubernetes-azurestack.json
examples/azure-stack/kubernetes-windows.json
pkg/api/const.go

Reason for Change:
Default AKSe settings do not play well with Azure Stack limits. This PR changes defaults for Azure Stack Hub to reduce the retry load to ARM.
Fixes #2860 
**Notes**:

chore: update default to recommended cluster settings on Azure Stack

---

pkg/api/const.go

update to docker EE 19.03.5. 
**Notes**:
The latest Windows VHD `17763.1075.200227` has contained docker EE 19.03.5..

feat: Update to docker EE 19.03.5

---

pkg/api/const.go
pkg/api/defaults.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/testdata/azurestack/kubernetes.json

PR #2717 made master.availabilityProfile a required field.
#2855

fix: make master availabilityProfile an optional field for Azure Stack

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go
pkg/engine/vmextensions.go

Because commandToExecute changes with every upgrade (since the kubernetes version env variable changes) CSE are run when AKS tried to do an instance upgrade then reimage (which vmss is recommending as preferred over creating and deleting repeatedly). 
Rerunning the CSE's seems to hit a file watch timeout maybe 1:8 or 1:16 times. I have not found the file responsible just the error code.
However it seems like the CSE's were not made to be idempotent and maybe shoudl just abort if they've already run to completion. So maybe it's a good idea in general to check the provision.complete sentinal file that already gets emited at the end of the script?
**Notes**:

chore: don't re-run provision.sh if already called. 

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202003_2020.03.10.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202003_2020.03.10.txt

This PR references a new `2020.03.10` VHD for both Ubuntu 16.04-LTS and 18.04-LTS.
Includes the following apt packages pre-installed:
- dbus
- bpftrace
- bcc-tools
- libbcc-examples
Update apmz (telemetry) component to v0.5.0 (from v0.4.0).
Adds Azure CNI 1.0.33 pre-installed, and no longer includes the following versions of Azure CNI pre-installed:
- 1.0.28
Adds CNI plugin version 0.8.5, and no longer includes the following versions of CNI pre-installed:
- 0.7.1
- 0.7.5
- 0.7.6
No longer includes any pre-downloaded versions of containerd (previously included 1.2.4, 1.1.6, and 1.1.5).
Includes the following additional pre-downloaded container images:
- mcr.microsoft.com/oss/kubernetes/kubernetes-dashboard:v1.10.1
- …

chore: rev Linux VHDs to 2020.03.10

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

AKS uses patched hyperkube images for some versions hence we don't want to remove those images. The current grep logic is too strict and will remove any hyperkube image tag not ended with the kubernetes version(e.g. 1.15.7).
grep -v "${KUBERNETES_VERSION}$" | grep "hyperkube"
mcr.microsoft.com/oss/kubernetes/hyperkube:v1.17.3_f0.0.1
mcr.microsoft.com/oss/kubernetes/hyperkube:v1.16.7_f0.0.1
mcr.microsoft.com/oss/kubernetes/hyperkube:v1.15.10_f0.0.1
mcr.microsoft.com/oss/kubernetes/hyperkube:v1.14.8_f0.0.4
mcr.microsoft.com/oss/kubernetes/hyperkube:v1.17.0
Will not remove the patched hyperkube image from the node.
**Notes**:

fix: Do not remove patched hyperkube image in cleanUpContainerImages

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This includes a handful of bug fixes as well as another mitigation for an edge case discovered for [CVE-2019-14271](https://nvd.nist.gov/vuln/detail/CVE-2019-14271).
Reference: https://github.com/moby/moby/issues/40211

chore: Bump moby to 3.0.11

---

examples/dualstack/README.md
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

- `iptables` proxier support for dualstack has been added in 1.18.0-alpha.2. The PR allows using `iptables` proxy mode in 1.18+ versions.
- Set different cluster subnet for 1.16 dualstack cluster
- Update dualstack docs
fixes https://github.com/Azure/aks-engine/issues/2868
**Notes**:

feat: allow iptables mode for dualstack 1.18+

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/no_outbound.json

fix: Windows no outbound fixes

---

cmd/upgrade.go
pkg/operations/kubernetesupgrade/upgradecluster.go
pkg/operations/kubernetesupgrade/upgradecluster_test.go
pkg/operations/kubernetesupgrade/upgrader.go

This PR adds a `--control-plane-only` option to the `upgrade` command, to enable upgrade operations to target **only** the master vms.
Fixes #2134 
**Notes**:

feat: upgrade control plane only

---

parts/k8s/cloud-init/artifacts/label-nodes.service
pkg/engine/templates_generated.go

This PR fixes missing configuration data in the label-nodes systemd service so that it can be enabled for automatic start upon reboot.
**Notes**:

fix: ensure label-nodes systemd service can be enabled

---

parts/k8s/kubernetesparams.t
pkg/api/addons.go
pkg/api/addons_test.go
pkg/api/components.go
pkg/api/components_test.go
pkg/engine/params_k8s.go
pkg/engine/templates_generated.go

`customKubeAPIServerImage`, `customKubeControllerManagerImage`, `customKubeSchedulerImage`, and `customKubeProxyImage` have no effect after https://github.com/Azure/aks-engine/pull/2540 was merged. We should honor them when specified.
**Notes**:

fix: honor custom{component}Image fields

---

cmd/scale.go
test/e2e/test_cluster_configs/availabilityset.json

Scaling fails if the target pool is a VMAS pool of VHD-based linux nodes.
VM `osPublisher` is not enought to distinguish between Linux and Windows.
**Notes**:

fix: scale cannot find VM index for the VMAS+VHD+Linux case

---

cmd/addpool.go
pkg/engine/transform/transform.go
pkg/engine/transform/transform_test.go
pkg/engine/transform/transformtestfiles/k8s_addpool_vmas.json
test/e2e/test_cluster_configs/availabilityset.json

Template normalization broke for `addppols` operations that try to create a VMAS pool.
The normalization function is removing VMAS resources.
Pushing a new normalization function that does not remove VMAS resources.
**Notes**:

fix: do not remove VMAS resources from template when adding a VMAS pool

---

test/e2e/test_cluster_configs/no_outbound.json

This PR uses the minimum necessary node count (1) to determine whether or not locked-down clusters are deployable, and removes the spot configuration as that makes things more difficult to validate.
**Notes**:

test: only use 1 node per pool in no outbound test

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

When intel-sgx driver upgrades, old url would become invalid, thus breaking provision process. This change tries to determine what's the latest driver version by paring the checksum file.
Prevent future issues as of #2743
**Notes**:
Tested on both Ubuntu 16.04 and 18.04

fix: parse SGX driver url and compare checksum

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go
pkg/engine/vmextensions.go
pkg/engine/vmextensions_test.go

Sometimes agent nodes can not reach k8s api server due to custom network settings. It will cause "nodenotready" failures during create/scale/upgrade. This pr will check the connection from node to k8s api and raise error code if can't connect.
**Notes**:

fix: check network from node to k8s api server in CSE

---

parts/k8s/cloud-init/artifacts/label-nodes.sh
pkg/engine/templates_generated.go

Fixes this script so it works in Kubernetes 1.18.0-rc.1 (and others), now that `kubectl` doesn't find a default config as we assumed before.
See #2923
See kubernetes-sigs/windows-testing#141
**Notes**:
This change to `label-nodes.sh` isn't actually being tested in this PR since it's skipped over in VHD deploys, but the hacky commits in #2923 did test and validate this change.

fix: use explicit kubeconfig in label-nodes.sh

---

examples/e2e-tests/kubernetes/kubernetes-config/rbac-disabled.json
pkg/api/common/const.go
pkg/api/defaults_test.go

This PR sets the default Kubernetes version (if not explicitly provided) to 1.15 for both Linux and Windows.
**Notes**:

chore: rev default Kubernetes version to 1.15

---

cmd/root.go
cmd/root_test.go

CLI error message should indicate that the `--client-id` format is invalid instead of implying that the value may be missing.
**Notes**:

chore: improve --client-id flag validation message

---

.pipelines/pr-e2e.yaml
pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202003_2020.03.19.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202003_2020.03.19.txt

This PR revs Linux VHDs to 2020.03.19. This VHD includes these fixes to the label-nodes systemd job:
https://github.com/Azure/aks-engine/pull/2915
https://github.com/Azure/aks-engine/pull/2929
In addition, we are pre-installing the following packages for 18.04-LTS:
- ntp
- ntpstat
Going forward, 18.04-LTS will use ntp for time synchronization instead of systemd-timesync.
**Notes**:

chore: rev Linux VHDs to 2020.03.19

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

- make the retries, sleep timeout, and command timeout options static in the func (these options were common across all usages)
- do the "is this package already installed?" validation before purging in the func itself
- support multiple packages
**Notes**:

chore: optimize apt_get_purge CSE func

---

test/e2e/kubernetes/kubernetes_test.go

This PR skips the E2E test validating a particular released version of k8s if the cluster config includes a `customWindowsPackageURL` value.
**Notes**:

test: don't test version if customWindowsPackageURL

---

parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsinstallopensshfunc.ps1
parts/k8s/windowskubeletfunc.ps1
pkg/engine/templates_generated.go

Get WindowsVersion more efficiently.
Fix #2946
**Notes**:

fix: Get WindowsVersion from registry instead of calling Get-ComputerInfo

---

test/e2e/runner/cli_provisioner.go

ps output may contain secrets
**Notes**:

test: don't grab ps logs during E2E operation

---

test/e2e/config/config.go
test/e2e/runner/ginkgo.go

Runs all e2e test specs to completion by default, instead of ending tests after the first failure. The behavior can be overridden by adding `GINKGO_FAIL_FAST=[1|true]` to the environment.
**Notes**:

test: promote --failFast to an e2e flag, defaulting to false

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

Changes the URL for `apmz` to reference the Azure CDN, for consistency and also to facilitate locking down egress rules. (We reference the upstreamartifacts.azureedge.net URL consistently otherwise, so this looks like an oversight.)
**Notes**:
cc: @palma21

fix: use upstreamartifacts CDN URL for apmz

---

pkg/api/common/versions.go
pkg/api/components_test.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.18.md
Closes #2923
**Notes**:
This will fail until Kubernetes 1.18.0 is actually released ~today~ *tomorrow* and our pipeline does its thing.

feat: add support for Kubernetes 1.18.0

---

pkg/api/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go

Default to Basic LB SKU on Azure Stack even if the default for Azure is the Standard SKU.
Fixes #2972
Related to #2952
**Notes**:

chore: force Basic LB SKU on Azure Stack

---

pkg/api/k8s_versions.go

For Kubernetes 1.18, cluster-autoscaler was using the v1.17.0 tag in MCR, but the v1.18.0 in GCR. This looks like just an oversight.
```console
% docker pull mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.18.0
v1.18.0: Pulling from oss/kubernetes/autoscaler/cluster-autoscaler
9ff2acc3204b: Pull complete 
2beb2eb0dad4: Pull complete 
Digest: sha256:bb4d5b62e4716f736c2c5376498dd763dc2e12648416b34d6760c4c2ca8c1250
Status: Downloaded newer image for mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.18.0
mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.18.0
```
**Notes**:

fix: use same cluster-autoscaler version in MCR

---

parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/workloads/busybox-master.yaml

This PR sets the advertise address of the apiserver process to the local IP address, instead of the internal LB IP address of the cluster-wide apiserver.
Fixes #622
Fixes #2948
**Notes**:

fix: each apiserver process listens on its own IP address

---

pkg/api/addons_test.go

This PR adds a unit test to prove that when you upgrade to 1.16, your custom ip-masq-agent addon image value will be overridden to use the aks-engine default.
**Notes**:

test: UT for addons ip-masq-agent image override

---

parts/k8s/addons/kubernetesmasteraddons-secrets-store-csi-driver-daemonset.yaml
pkg/engine/templates_generated.go

- Adds nodeSelector for csi-secrets-store daemonset to ensure pods land only on linux nodes.
**Notes**:

fix: add node selector for csi-secrets-store addon ds

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go

Adding Windows defender process exclusions for kubelet.exe and csi-proxy-server.exe to reduce unnecessary cpu load on Windows nodes
This is an ask from @MikkelHegn from AKS team
**Notes**:

feat: adding  windows defender process exclusions

---

examples/dualstack/kubernetes.json
examples/e2e-tests/kubernetes/release/default/definition.json
pkg/api/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/mocks.go
pkg/engine/armvariables_test.go
pkg/engine/testdata/mastersonly/mastersonly.json
pkg/engine/virtualmachinescalesets_test.go
test/e2e/test_cluster_configs/everything.json
test/e2e/test_cluster_configs/zones.json

This PR changes default cluster configuration enforcement so that Standard is the LoadBalancer SKU type if the user does not declare a `loadBalancerSku` value in the `kubernetesConfig` configuration object.
`"Basic"` LoadBalancer configuration is no longer appropriate as a default for cluster configurations, as it precludes running LoadBalancer-backed Kubernetes services behind multiple node pool-enabled clusters.
Folks who want to continue using the legacy `"Basic"` LoadBalancer type will have to explicitly declare so in their api model:
```
{
"apiVersion": "vlabs",
"properties": {
"orchestratorProfile": {
"orchestratorType": "Kubernetes",
"kubernetesConfig": {
"loadBalancerSku": "Basic",
...
```
Fixes #2952 
**Notes**:

chore: use Standard LoadBalancer as default

---

scripts/collect-windows-logs.ps1

Updating behavior for collect-windows-logs.ps1 to check if collectlogs.ps1 is present on disk before trying to download it.
Fixes #2986 
**Notes**:

fix: don't download collectlogs.ps1 if it exists

---

parts/k8s/cloud-init/artifacts/cis.sh
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_customcloud.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/artifacts/enable-dhcpv6.sh
parts/k8s/cloud-init/artifacts/generateproxycerts.sh
parts/k8s/cloud-init/artifacts/health-monitor.sh
parts/k8s/cloud-init/artifacts/mountetcd.sh
pkg/engine/templates_generated.go

Formats shell scripts under ./parts/k8s to use 2-space indentation and to simplify some `bash` syntax. This should save some valuable bytes in AKS Engine's CSE payload.
**Notes**:
I ran `shfmt -s -i 2 -w` and then reverted any changes that looked risky or controversial. (It would be easy to enforce this format style in `make test-style` in the future if we revisit those changes.)

style: format CSE scripts consistently

---

pkg/api/converterfromapi.go
pkg/api/convertertoapi.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/api/vlabs/types_test.go

This PR is actually a place holder, it's mainly for AKS to support  EncryptionAtHost(Enable Encryption at Host support for VM/VMSS) (JEDI requirement) which is going to be in private preview late this month.
EncryptionAtHost functionality actually does not work by this PR since it depends on
- go sdk ready and upgrade to supported go sdk version
- EncryptionAtHost feature on public regions ready
- subs whitelist
Will make it work when the above 3 requirements are fullfilled.
**Notes**:

feat: EncryptionAtHost support

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go

This PR removes superfluous "wait for no held apt locks" *after* apt operations have already completed. Instead we are waiting only *before* attempting an apt operation. This configuration in concert will promote good apt race condition avoidance without unnecessarily blocking CSE progression (for example, the next operation after an apt operation is probably not _another_ apt operation, and so waiting for apt locks to be released means we're delaying that next operation unnecessarily).
**Notes**:

fix: remove unnecessary apt lock waits

---

.pipelines/pr-e2e.yaml
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1180
**Notes**:
This includes a commit to make CI test with 1.18.1, but that could be dropped before merging.
Pipeline build is still in progress, so this won't pass testing yet.

feat: add support for Kubernetes 1.18.1

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR ensures that clusters upgraded via `aks-engine upgrade` are built with componentry that references standard MCR images.
This is a follow-on PR of #3046 
**Notes**:

chore: ensure upgraded clusters use MCR images

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR sets the VMSS SinglePlacementGroup configuration to false if using Standard LB.
**Notes**:

chore: SinglePlacementGroup=false if VMSS + SLB

---

pkg/api/defaults.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

To support a scenario in air-gapped cloud where you need to manually upload an "official" distro image and refer it as ImageRef but STILL be treated as an official distro in aks-engine.
This change is required for treating these manually uploaded "official" distro images exactly same as official Distros VHDs in aks-engine flow, especially passing "{{- if HasVHDDistroNodes}}" variant checks in cse_main.sh to be treated as a "golden image":
https://github.com/Azure/aks-engine/blob/51bde0dbbec2bf90a18ad3fda5bdf3b127c94c3a/parts/k8s/cloud-init/artifacts/cse_main.sh#L71
Also, the semantic makes sense. When you specify Distro and ImageRef at the same time, Distro value is only used as a "hint" in various places. It still outputs ImageRef as an os image in the ARM …

feat: Allow specifying Distro and ImageRef at the same time to support air-gapped cloud

---

pkg/api/azenvtypes.go
test/e2e/test_cluster_configs/no_outbound.json
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202004_2020.04.09.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202004_2020.04.09.txt

This PR brings in new Linux VHDs. Of especial import: these VHDs now explicitly back MCR image-originating (mcr.microsoft.com) cluster image references to support https://github.com/Azure/aks-engine/pull/3046.
Other changes:
Includes a new pre-installed etcd version:
- etcd v3.3.19
Includes new cluster-autoscaler versions:
- mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.18.1
- mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.17.2
- mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.16.5
- mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.15.6
- mcr.microsoft.com/oss/kubernetes/autoscaler/cluster-autoscaler:v1.14.8
New Azure CNI componentry:
- …

chore: rev Linux VHDs to 2020.04.09

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

when we testing the gpu package installation.
even we have wait_for_apt_locks, the racing can still happen. especially when the unattended upgrade is turned on, and the unattended upgrading may takes 10 min to finish the installation, and we use the 1 second just to try to get the lock more aggressively.

fix: retry more aggressively when install the gpu deb package.

---

parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

* fix: disable unattended upgrades during CSE execution
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
* style: remove comments to save CSE bytes
Co-authored-by: Matt Boersma <Matt.Boersma@microsoft.com>
**Notes**:

fix: disable unattended upgrades during CSE execution (#1681)

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

fix: retry more aggressively when install the gpu deb package. (#3065)

---

examples/e2e-tests/kubernetes/release/default/definition.json
pkg/api/defaults.go
pkg/api/defaults_test.go
test/e2e/test_cluster_configs/everything.json

This PR moves default Linux OS forward from 16.04-LTS to 18.04-LTS. 18.04 has been supported for a long while and lots of folks are using it in production, so there's no reason to continue a conservative default configuration going forward.
**Notes**:

chore: use Ubuntu 18.04-LTS as default

---

pkg/api/converterfromapi.go
pkg/api/convertertoapi.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/api/vlabs/types_test.go

Ported from PR: https://github.com/Azure/aks-engine/pull/3041
This PR is actually a place holder, it's mainly for AKS to support  EncryptionAtHost(Enable Encryption at Host support for VM/VMSS) (JEDI requirement) which is going to be in private preview late this month.
EncryptionAtHost functionality actually does not work by this PR since it depends on
- go sdk ready and upgrade to supported go sdk version
- EncryptionAtHost feature on public regions ready
- subs whitelist
Will make it work when the above 3 requirements are fullfilled.
**Notes**:
/assign @xuto2
cc @jluk

feat: EncryptionAtHost support(cherry-pick to branch aks-release-v0.47.0-1)

---

docs/topics/sgx.md
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go
test/e2e/kubernetes/workloads/sgx-test.yaml

Azure Ubuntu images is now shipped with Intel SGX driver by default. We skip the driver installation if "/dev/sgx" is detected. We keep the installation code in case of a custom image is used.
NA
**Notes**:
None

refactor: skip sgx driver installation if already exists in OS

---

pkg/api/k8s_versions.go

https://github.com/Azure/aks-engine/pull/2982 added support 1.19 but the csi-secrets-store image references missed out. This PR adds the image reference for the 1.19 version.
**Notes**:

fix: add csi-secrets-store image-ref for 1.19

---

parts/k8s/addons/1.14/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.15/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.17/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.18/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-metrics-server-deployment.yaml
pkg/engine/templates_generated.go

Adds `priorityClassName: system-cluster-critical` to metrics-server pods so they are less likely to evicted under load.
**Notes**:
cc: @MichaelSinz

feat: give metrics-server system-cluster-critical priority

---

cmd/upgrade.go
test/e2e/test_cluster_configs/base.json

This PR enables Windows VMSS node pools to be upgraded.
Prior to this change, the upgrade code path uses a Linux-specific VMSS instance naming convention check to determine whether or not the VMSS is an aks-engine-created VMSS instance. Because aks-engine uses an entirely different naming schema for Linux and Windows, this means that `aks-engine upgrade` always thinks that Windows VMSS are not participating in the aks-engine-created Kubernetes cluster, and thus doesn't include them for upgrade.
Fixes #3017 
**Notes**:

fix: don't skip Windows VMSS node pools during upgrade

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1181
**Notes**:

feat: add support for Kubernetes 1.18.2

---

test/e2e/test_cluster_configs/everything.json

Adding to the list of PRs that we're trying to fix! Now fixes cruft from:
https://github.com/Azure/aks-engine/pull/3094
https://github.com/Azure/aks-engine/pull/3070
**Notes**:

test: really fix bad distro value in everything cluster config

---

pkg/api/addons_test.go
pkg/api/const.go

The kubernetes-dashboard implementation is stale and [not considered compatible](https://github.com/kubernetes/dashboard/releases/tag/v1.10.1) with current versions of Kubernetes, so this change disables it by default. It can still be turned on if desired by enabling it explicitly in a cluster config (apimodel).
Fixes #3021
**Notes**:
Users can try out the new pre-release versions by following the [current documentation for Kubernetes Dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/).

feat: disable dashboard addon by default

---

.gitattributes

Overrides the default language detection for `github-linguist` so Go template files aren't identified as Raku or Perl.
Before:
```
91.54%  Go
2.79%   Raku
2.61%   Shell
1.99%   PowerShell
0.90%   Perl
0.14%   Makefile
0.03%   Python
0.00%   Batchfile
```
After:
```
95.22%  Go
2.61%   Shell
1.99%   PowerShell
0.14%   Makefile
0.03%   Python
0.00%   Batchfile
```
**Notes**:
I realize this is entirely trivial, but it's the kind of thing that bothers me.

style: override linguist's default language detection

---

pkg/api/vlabs/types.go

Trying to fix #2839, I ran `golangci-lint` with the default linters enabled and couldn't ignore these typos. But I wonder if this could create actual backward-compatibility issues if the previous annotations weren't being honored as expected.
**Notes**:

fix: typos in JSON annotations caught by staticcheck

---

parts/k8s/addons/coredns.yaml
pkg/engine/templates_generated.go

coredns-autoscaler was evicted to a Windows node during an upgrade in https://upstream.jenkins.azure-containers.io/blue/organizations/jenkins/k8s-create-cluster-matrix/detail/k8s-create-cluster-matrix/141/pipeline/271/, causing the test to fail. It looks like it's deployed without a node selector.
**Notes**:

fix: add nodeSelector for coredns-autoscaler

---

examples/networkpolicy/README.md
parts/k8s/addons/antrea.yaml
parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/api/addons.go
pkg/api/addons_test.go
pkg/api/common/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/network_policy/antrea_azure.json

In this mode antrea will enforce network policies using OVS and azure cni will take care of networking.
Azure CNI will be deployed in transparent mode in which veth pair will be created for each POD. Antrea will move veth pair host namespace leg to OVS and update host route table accordingly.

feat: Enable Antrea in NetworkPolicyOnly mode with Azure CNI

---

parts/k8s/addons/1.19/azure-cni-networkmonitor.yaml
parts/k8s/addons/1.19/ip-masq-agent.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-aci-connector-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-azure-npm-daemonset.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-calico-daemonset.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-flannel-daemonset.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-heapster-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-kube-dns-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-kube-proxy-daemonset.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-metrics-server-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-smb-flexvolume-installer.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-tiller-deployment.yaml
pkg/api/common/versions.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-alpha1
**Notes**:
There is a problem building 1.19.0-alpha.2 currently in the Azure Pipeline. I will update this PR when we have it fixed. cc: @sozercan

feat: add support for Kubernetes 1.19.0-alpha.2

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/mountetcd.sh
pkg/engine/templates_generated.go

This PR includes "retry etcd disk volume mount" when starting etcd systemd service as the systemd service launch depends upon the disk mount.
Fixes #3125 
**Notes**:

fix: idempotent systemd + disk mount for etcd

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsinstallopensshfunc.ps1
parts/k8s/windowskubeletfunc.ps1
pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
pkg/engine/templates_generated.go
scripts/collect-windows-logs.ps1
test/e2e/test_cluster_configs/no_outbound.json
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt

Upgrade Windows VHD image to April release 17763.1098.200409
**Notes**:
cherry-pick below commits from v0.49.0:
chore: adding azure-cni v1.0.33 artifacts to VHDs (#2790)
chore: update Azure CNI to v1.0.33 (#2825)
feat: collect Windows CSE logs during log collection (#2858)
fix: Windows no outbound fixes (#2883)
fix: fixing nssm logging in windows CSE (#2890)
fix: Get WindowsVersion from registry instead of calling Get-ComputerInfo (#2954)
feat: Updating AKS to use April 2020 Windows VHDs by default (#3060)
feat: adding windows defender process exclusions #2967
Co-authored-by: Mark Rossetti marosset@microsoft.com
Co-authored-by: Jaeryn 13284103+jaer-tsun@users.noreply.github.com
Co-authored-by: Kalya Subramanian …

Upgrade Windows VHD image to April release 17763.1098.200409

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

* feat: add support for Kubernetes 1.18.1
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1180
* ci: test PRs with k8s 1.18
(cherry picked from commit 66ff61c13443ef4b675f866251ff0335b69d3591)
**Notes**:

feat: add support for Kubernetes 1.18.1 (#3045)

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsinstallopensshfunc.ps1
parts/k8s/windowskubeletfunc.ps1
parts/k8s/windowsnodereset.ps1
pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
pkg/engine/const.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
scripts/collect-windows-logs.ps1
test/e2e/test_cluster_configs/no_outbound.json
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1158.200421.txt

Update Windows VHD image to April release 4B 17763.1158.200421
**Notes**:
1. Cherry-pick below 1 commits from v0.50.0
5c4e4a7f8a2dca5313f8827985010891659e664f: feat: Updating Windows VHDs with 4B patches
2. Cherry-pick below 9 commits from v0.49.0
8be700023c7cbc64f11634299f1fef0445e5cbc0: feat: Adding WindowsNodeReset.ps1 script to reset/cleanup state for nodes
056484d45638f0c31e13ae776e3d0b104d3462dd: chore: adding azure-cni v1.0.33 artifacts to VHDs
b2420d1f789d46cfc59a9d0b340ead88160274ff: chore: update Azure CNI to v1.0.33
96c8c3ee0190da85377d9a17a46353b41f156ba2: feat: collect Windows CSE logs during log collection
414015252d65948ee13948aa38da9e3771eb2e54: fix: Windows no outbound fixes …

Update Windows VHD image to April release 4B 17763.1158.200421

---

pkg/api/k8s_versions.go

Kubernetes 1.18.x was using the latest release of cluster-autoscaler, v1.18.1, but Kubernetes 1.19 was left behind on v1.18.0.
**Notes**:

chore: update cluster-autoscaler version for k8s 1.19

---

test/e2e/config/config.go
test/e2e/engine/template.go

This PR adds defaults for all environment variable configuration values interpreted by the E2E runner.
- changed `CLEANUP_IF_FAIL` default to false
- changed `STABILITY_ITERATIONS` default to 3
- changed `SKIP_LOGS_COLLECTION` default to true
- changed `GINKGO_FAIL_FAST` default to true (because the skip/focus configs don't work otherwise)
**Notes**:

test: rationalize E2E env defaults

---

pkg/engine/artifacts.go

s/Source/Destination
Tested on a local cluster with the `scheduled-maintenance` addon enabled:
```shell
azureuser@k8s-master-26399701-0:~$ ls /etc/kubernetes/addons/
audit-policy.yaml                     coredns.yaml                         pod-security-policy.yaml
azure-cloud-provider-deployment.yaml  ip-masq-agent.yaml                   scheduled-maintenance-deployment.yaml
azure-cni-networkmonitor.yaml         kube-metrics-server-deployment.yaml  secrets-store-csi-driver.yaml
blobfuse-flexvolume-installer.yaml    kube-proxy-daemonset.yaml
azureuser@k8s-master-26399701-0:~$ kubectl get po -A
NAMESPACE          NAME                                                READY   STATUS    RESTARTS   AGE
drainsafe-system   drainsafe-controller-manager-f5dd84c94-4q7pt …
```

fix: correct destination filename for scheduled maintenance addon

---

docs/topics/clusterdefinitions.md
parts/k8s/cloud-init/artifacts/kubelet.service
parts/k8s/cloud-init/masternodecustomdata.yml
pkg/api/common/const.go
pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
pkg/engine/templates_generated.go

This PR unwinds some weirdness in the implementation of `--register-with-taints`, especially for masterProfile configuration.
Also addressed some strange `--register-node` configuration.
**Notes**:

refactor: enable generic --register-with-taints and --register-node

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowscontainerdfunc.ps1
parts/k8s/windowskubeletfunc.ps1
pkg/engine/templates_generated.go

This PR replaces updates how the pause image is specified for both containerd and docker on windows (containerd was previously hardcoded) to now use values from kubeclusterconfig.json.
For reference here is how the values are expected in other kubeclusterconfig files:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/kubeadm/v1.16.0/Kubeclusterbridge.json
**Notes**:

fix: don't hardcode pause image for containerD on Windows

---

parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

The "--register-schedulable" kubelet configuration is deprecated. See:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
Note: I am not aware that expressing this as an env var to the runtime is even being interpreted at all.
**Notes**:

chore: remove deprecated KUBELET_REGISTER_SCHEDULABLE

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

It's not clear what the purpose of the `KUBELET_IMAGE` systemd env var is doing for pre-1.17 Kubernetes versions of kubelet. This env var doesn't seem to be documented as runtime configuration input for the kubelet binary, and it's not used in `/opt/azure/containers/kubelet.sh`.
**Notes**:

chore: remove KUBELET_IMAGE kubelet systemd env var

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This is follow-on work to go template-related cloud-init data reduction. Standardizes the cloud-init specs to use `{{-` where appropriate to ensure that no unnecessary add'l newlines result.
**Notes**:

chore: standardize to {{- for go template expressions

---

parts/k8s/addons/1.16/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.17/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.18/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/1.19/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/artifacts/untaint-nodes.service
parts/k8s/cloud-init/artifacts/untaint-nodes.sh
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/common/const.go
pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
pkg/engine/armvariables.go
pkg/engine/armvariables_test.go
pkg/engine/const.go
pkg/engine/engine.go
pkg/engine/engine_test.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

This PR introduces an aad-pod-identity-specific taint when the aad-pod-identity addon is enabled, and then adds systemd-enforced reconciliation to remove that taint after the `nmi` daemonset has been scheduled successfully onto a node (and thus the node is ready for schedulable, aad-pod-identity-enforced workloads).
**Notes**:

chore: aad-pod-identity taint

---

.pipelines/vhd-builder-windows.yaml
vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-vhd-builder.json

This PR adds support to the existing Windows VHD packer/scripts to install containerd and use containerd to perform image pulls.
A new environment variable `CONTINAINER_RUNTIME` is used to target either docker or containerd as the container runtime configured in the windows VHDs.
**Note:** docker is still installed when using containerd because there is additional cleanup that is needed in the Windows CSE scripts to not assume docker is installed.
This will get addressed in separate PRSs
**Notes**:

feat: Create Windows containerd VHDs

---

parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go

In an aad-pod-identity cluster configuration, access to IMDS from nodes is proxy'd by the aad-pod-identity nmi daemonset running on each node. This PR introduces an explicit iptables rule that blocks access to IMDS for aad-pod-identity + VMSS configurations when using msi. Because instances in a VMSS share a common msi, we want to prevent a pod container getting a VMSS-scoped msi token between the time that a node comes online and before the nmi daemonset can write its own iptables rules to re-route IMDS to the aad-pod-identity componentry.
Fixes #3135 
**Notes**:

feat: block imds from VMSS nodes if aad-pod-identity + msi

---

docs/topics/clusterdefinitions.md
parts/k8s/cloud-init/artifacts/kubelet.service
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
pkg/engine/templates_generated.go

This PR dusts off the cobwebs from the kubelet systemd implementation. Specifically:
- moves bash block statements out from single line systemd `ExecStartPre` strings into the pre-existing `/opt/azure/containers/kubelet.sh` script (a `ExecStartPre` dependency)
- enables the following containerd kubelet configuration to be overridden via api model:
- `--container-runtime`
- `--runtime-request-timeout`
- `--container-runtime-endpoint`
- removes iptables output from start of kubelet logs
**Notes**:

refactor: simplify kubelet systemd service

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

This PR introduces a stdout warning message when AKS Engine template generation observes an empty "location" value in the input api model. We want to tell folks pro-actively that AKS Engine will treat that empty string significantly, and that the resultant ARM templates will work *exclusively* for public cloud regions.
Addresses part of #3170
**Notes**:

feat: add warning message for empty Location string

---

.golangci.yml
cmd/addpool.go
cmd/deploy.go
cmd/generate.go
cmd/get_logs.go
cmd/rotate_certs.go
cmd/scale.go
cmd/upgrade.go
pkg/api/convertertoagentpoolonlyapi.go
pkg/api/defaults.go
pkg/api/types.go
pkg/armhelpers/azureclient.go
pkg/armhelpers/azurestack/azureclient.go
pkg/armhelpers/azurestack/converter.go
pkg/armhelpers/azurestack/deploymentError.go
pkg/armhelpers/converter.go
pkg/armhelpers/deploymentError.go
pkg/engine/armvariables.go
pkg/engine/customfiles.go
pkg/engine/engine.go
pkg/engine/transform/apimodel_merger.go
pkg/helpers/pki.go
pkg/operations/kubernetesupgrade/upgradecluster.go

Ignoring an error returned from a func can be a dangerous thing in go, so enabling the errcheck linter is good practice. This contains only the changes necessary to main code. See #3183 for changes to test code.
Fixes #1032.
**Notes**:

chore: check all error returns in main code

---

cmd/get_skus_test.go
pkg/helpers/azure_skus_const.go

Adds these new Azure VM SKUs:
- Standard_M192ms_v2
- Standard_M192s_v2
- Standard_M24ms_v2
- Standard_M24s_v2
- Standard_M48ms_v2
- Standard_M48s_v2
- Standard_M96ms_v2
- Standard_M96s_v2
I don't see them listed yet at the [Mv2 series](https://docs.microsoft.com/en-us/azure/virtual-machines/mv2-series) page.
**Notes**:

chore: add new M-series SKUs

---

test/e2e/test_cluster_configs/everything.json

Building a cluster w/ 10 nodes and a "1" min-nodes cluster-autoscaler configuration can yield unpredictable results in tests, as cluster-autoscaler will be scaling down nodes quickly after the cluster has been created. That's not really what we want to test, and it introduces flakes.
**Notes**:

test: reduce node count in E2E "everything" config

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-alpha2
**Notes**:
There were several APIs deprecated with this release, but I think we should defer updating them. See #3196.

feat: add support for Kubernetes 1.19.0-alpha.3

---

parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/artifacts/untaint-nodes.sh
pkg/engine/templates_generated.go

This PR fixes two errata surfaced in 1.14 and 1.15 tests that include aad-pod-identity.
1. move the `ensureTaints` CSE func out of the "is k8s version >= 1.16?" block
2. use the documented `kubectl taint nodes` syntax (remove the `=true` expression after the taint key, which I guess works in 1.16+)
- Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
**Notes**:

fix: aad-pod-identity taints foo works in k8s < 1.16

---

test/e2e/test_cluster_configs/everything.json

This PR delivers a coredns addon configuration so that its autoscale configuration is tuned to be engaged at the first node added to the cluster.
**Notes**:

test: rationalize "everything" E2E config for coredns autoscaler test

---

.golangci.yml
pkg/api/apiloader_test.go
pkg/api/defaults.go
pkg/api/vlabs/validate.go
pkg/armhelpers/azurestack/compute.go
pkg/armhelpers/compute.go
pkg/engine/engine_test.go
pkg/operations/kubernetesupgrade/upgradecluster.go

The `staticcheck` linter is enabled by default in golangci-lint, although AKS Engine has had it disabled. It points out where errors are being assigned but not actually checked, and some other simplifications.
Refs #1032 
**Notes**:

ci: enable staticcheck linter

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go

This is done in the contianerd install scripts provided to us by COSINE (which we aren't currently using) so i'm mimicking the behavior here.
This will prevent unnecessary CPU usage caused by defender scanning containerd or child processes.
**Notes**:

fix: set Windows Defender process exclusion for containerd

---

docs/tutorials/quickstart.md

There are two references to `[upgrade][]` in this doc but they didn't have a URL target.
**Notes**:

docs: add missing link to upgrade doc

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

This PR doesn't throw a validation error for the Kubernetes Version on a Windows-enabled cluster during scale/upgrade contexts.
Fixes #3217
**Notes**:

fix: don't validate Windows version in update scenario

---

vhd/packer/configure-windows-vhd.ps1

Pull cached Azure Stack Windows binaries from shared SA.
Cache Azure Stack binaries for Kubernetes v1.15.10, v1.15.11, v1.15.12, v1.16.8, v1.16.9, v1.17.4, v1.17.5

chore: pull cached Azure Stack Windows binaries from shared SA

---

examples/networkpolicy/README.md

Remove out-of-date note from README regarding:  upgrading from 2+ year old AKS engine v0.17 and older.
n/a
n/a
**Notes**:

docs: remove out of date Calico upgrade note

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR removes the `--server-dry-run=true` option from `kubectl apply` during cluster-init reconciliation.  Strictly speaking, we should not need to validate the entire spec before running `kubectl apply`, as retries of that command should reconcile the spec if < 100% was successful the 1st time around.
Fixes #3234 
**Notes**:

fix: don't dry-run cluster-init spec

---

test/e2e/azure/cli.go

This is a follow-on from #3213, to enable E2E runner usage of `az deployment group create` instead of `az group deployment create`.
**Notes**:

test: az deployment group create in E2E runner

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202005_2020.05.13.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202005_2020.05.13.txt

This PR brings in new Linux VHDs.
Includes the following new pre-downloaded components:
- Azure CNI version 1.1.2
Includes the following pre-installed apt packages:
- linux-headers-5.3.0-1020-azure
- mcr.microsoft.com/oss/kubernetes/dashboard:v2.0.0
- mcr.microsoft.com/oss/kubernetes/metrics-scraper:v1.0.4
- mcr.microsoft.com/containernetworking/azure-npm:v1.1.2
- mcr.microsoft.com/oss/nvidia/k8s-device-plugin:1.0.0-beta6
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.19.0-alpha.3
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.19.0-alpha.3
- mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.19.0-alpha.3
- mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.19.0-alpha.3
- …

chore: rev Linux VHDs to 2020.05.13

---

parts/k8s/cloud-init/artifacts/mountetcd.sh
pkg/engine/templates_generated.go

This PR modifies the etcd data disk mounting implementation thusly:
- `/etc/fstab` does not have a reference to a static `/dev/sd` device, instead it references the filesystem label `etcd_disk`
- we derive the etcd data disk device target by using the lun0 reference under `/dev/disk/azure/scsi1/` 
Fixes #3246 
Fixes #3185
**Notes**:

fix: resilient etcd data disk mounting

---

parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/templates_generated.go

This PR removes the "force create" option when we create the etcd_disk filesystem via cloud-init.
If for some reason the device partition we target for etcd_disk already exists as a filesystem, we want cloud-init to throw an error, not forcibly create a new filesystem and ignore the previous state.
Ref:
```
-F     Force mke2fs to create a filesystem, even if the specified device is not a partition on a block special device, or if other parameters do not make sense.  In order to force mke2fs to create a filesystem even if the filesystem appears to be in use or is mounted (a truly dangerous thing to do), this option must be specified twice.
```
**Notes**:

chore: don't force create etcd_disk filesystem

---

parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/scripts/host-os-fs.sh

This PR follows on from #3273 to ensure that `/mnt` is mounted as ext4 filesystem type via cloud-init.
**Notes**:

fix: ensure /mnt is ext4

---

pkg/api/common/const.go
pkg/api/defaults-kubelet_test.go

Kubernetes 1.18 has the best Azure experience, especially for clusters at scale using cluster-autoscaler. Let's ship this as the default version for folks who don't specify otherwise.
**Notes**:

chore: make 1.18 the default Kubernetes version

---

parts/k8s/addons/azure-cloud-provider.yaml
pkg/engine/templates_generated.go

#3277 regressed the azure-cloud-provider yaml go template representation of the spec, doing the improper whitespace trimming.
Because we are putting the `{{end}}` *after* (duh) the literal text, separated by a whitespace, we need to use `{{- end}}` to trim that preceding newline.
**Notes**:

fix: whitespace trimming in cloud-provider spec is broken

---

cmd/scale.go
pkg/armhelpers/utils/util_test.go

This PR improves the UX for edge case `aks-engine scale` scenarios against Windows VM nodes that are missing VM tags that help identify the node pool the VM is in.
**Notes**:

fix: prevent panic in Windows scale if no tags

---

test/e2e/kubernetes/kubernetes_test.go

This PR eschews a shorter timeout for using the Kubernetes scheduler for commands that are retried a bunch of time, and instead just uses the standard timeout; this will allow for more flake tolerance. We are still able to use aggressive timeouts for the actual runtimes we're testing (e.g., make a DNS lookup in a container)
**Notes**:

test: use common timeout for repeat tests

---

test/e2e/kubernetes/kubernetes_test.go

This PR disables E2E coverage of azurefile if we're in a containerd + Windows cluster configuration context, because of:
https://github.com/Azure/aks-engine/issues/3315
**Notes**:

test: skip azurefile test if using containerd

---

parts/k8s/addons/pod-security-policy.yaml
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
pkg/engine/const.go
pkg/engine/cse.go
pkg/engine/cse_test.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go

This PR ensures that the PodSecurityPolicy resources are loaded before other addons. This is accomplished by:
- changing the `kube-addon-manager` spec so that it sources from `/etc/kubernetes/addons/init`
- copying the pod-security-policy addon spec to the `/etc/kubernetes/addons/init` directory at runtime
- wait for the `privileged` and `restricted` PodSecurityPolicy resources to be present in the cluster
- change the `kube-addon-manager` spec to source from `/etc/kubernetes/addons`
- delete the active `kube-addon-manager` pod (to force a new reconciliation from the fully populated `/etc/kubernetes/addons` directory
Fixes #1851
**Notes**:

fix: ensure pod-security-policy is the first addon loaded

---

labels.yaml

This VHD label is indented to make it easier to identify PRs relating to building VHDs.
These PRs are of often cherry-picked into aks-release branches and are hard to find currently.
Note:
I'm also investigating what options we have for automatically applying this and other labels to PRs based on file paths.
**Notes**:

Adding VHD label to repo

---

.pipelines/pr-e2e.yaml
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changes-by-kind

feat: add support for Kubernetes 1.19.0-beta.0

---

test/e2e/cleanup.sh
vendor/modules.txt
vhd/packer/vhd-rg-cleanup.sh

This PR enables us to configure a set of "never delete" resource group substrings in the cleanup script.
In this PR we add the "aksimages" reserved exclusion, to ensure that we never accidentally delete these VHD CI-produced image resource group(s).
**Notes**:

ci: enable multiple static resource group exclusions in cleanup script

---

examples/azure-stack/conformance/kubernetes1.17.json

Add cluster definition required to replicate k8s-conformance for v1.17
Related: https://github.com/cncf/k8s-conformance/pull/979

chore: k8s v1.17 conformance model for Azure Stack

---

parts/k8s/addons/cluster-autoscaler.yaml
pkg/engine/templates_generated.go

This PR uses the right nodeSelector for the cluster-autoscaler addon for the version of Kubernetes, so we don't have to wait for systemd to apply labels out of band from a master VM.
Fixes #3326
**Notes**:

fix: use right nodeSelector for cluster-autoscaler addon

---

parts/k8s/cloud-init/artifacts/cse_customcloud.sh
pkg/engine/templates_generated.go

Azure CNI is not using encap, no need to reduce MTU on Azure Stack
Related #1346

chore: change MTU only if not Azure CNI on Azure Stack

---

scripts/collect-logs.sh

Collecting vhd install logs will allow support engs to resolve some cases faster. 
**Notes**:

chore: get-logs collects vhd-install.complete

---

pkg/api/common/helper.go
pkg/api/common/helper_test.go
pkg/api/k8s_versions.go
pkg/api/types_test.go
pkg/engine/template_generator_test.go
vhd/packer/install-dependencies.sh

This PR updates the pause image to 1.3.1 for Linux nodes.
Fixes #3368
**Notes**:

chore: rev pause image to 1.3.1

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202005_2020.05.29.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202005_2020.05.29.txt

This PR revs Linux VHDs to the `2020.05.29` image.
Includes the following pre-downloaded components:
- etcd v3.2.2
- Azure CNI v1.1.3
- mcr.microsoft.com/oss/kubernetes/dashboard:v2.0.1
- mcr.microsoft.com/oss/kubernetes/pause:1.3.1
- mcr.microsoft.com/oss/kubernetes/coredns:1.6.9
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.19.0-beta.0
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.19.0-beta.0
- mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.19.0-beta.0
- mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.19.0-beta.0
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.18.3
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.18.3
- …

chore: rev Linux VHDs to 2020.05.29

---

test/e2e/kubernetes/kubernetes_test.go

This PR ensures we print podsecuritypolicy resource state during E2E runs.
**Notes**:

test: print podsecuritypolicy resources during E2E

---

docs/topics/clusterdefinitions.md
parts/k8s/addons/1.15/calico.yaml
parts/k8s/addons/calico.yaml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/network_policy/calico.json
test/e2e/test_cluster_configs/network_policy/calico_azure.json

This PR introduces configurable logging verbosity for the calico addon. E.g.:
```
...
"kubernetesConfig": {
"addons": [
...
{
"name": "calico",
"enabled": true,
"config": {
"logSeverityScreen": "error"
}
}
...
]
}
...
```
In addition, the calico addon spec has been changed to `EnsureExists` to better enable folks to customize the configuration on their cluster over time.
Fixes #2111 
**Notes**:

feat: configurable calico logging verbosity

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200603.txt

This PR brings in a new Windows VHD.
Includes the following new component versions:
- Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.317.411.0)
- Azure CNI 1.1.3
Includes pre-downloaded builds for the following Kubernetes versions:
- v1.16.10
- v1.17.6
- v1.18.3
- v1.19.0-beta.0
No longer includes these Kubernetes version builds:
- v1.14.7
- v1.14.8
- v1.16.7
- v1.17.3
- v1.18.0
- v1.19.0-alpha.3
**Notes**:

chore: rev Windows VHD to 17763.1217.200603

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

We use the `BlockOutboundInternet` feature flag for various "air gap" E2E testing scenarios. To better ensure that CSE on master nodes can run to completion, we should connect to the apiserver locally rather than via the public IP address.
**Notes**:

chore: use local kubeconfig if no outbound

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-beta0

feat: add support for Kubernetes 1.19.0-beta.1

---

pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/types.go

We need to set SinglePlacementGroup default value only when it is not set even node count > 100.
**Notes**:

fix: Set spg only when spg is not set 

---

test/e2e/kubernetes/kubernetes_test.go

Adding an E2E test that downloads a file big enough to expose misconfigured network interfaces MTUs.
Related to #3367

test: expose misconfigured interfaces by downloading large-enough files

---

docs/community/running-tests.md
test.mk

I was doing e2e test walk through on fresh git pull.  Had not run any other commands so ginko was not pulled.
Also made the readme easier to see all variables in example command.
Note this file has CLRF line endings. When copying command to terminal in ubuntu it has extra lines.  I could fix line ending but didn't want to slam you with wall of red.  Let me know if I should push a fix for this.
**Notes**:
cc: @marosset

fix: Enable e2e to install ginko if required

---

parts/k8s/addons/aad-pod-identity.yaml
pkg/engine/templates_generated.go

This PR updates the aad-pod-identity spec so that the `mic` component is only scheduled onto Linux nodes.
Fixes #3288 
**Notes**:

fix: only schedule mic on Linux nodes

---

parts/k8s/kubeletstart.ps1
pkg/engine/templates_generated.go

Original `$global:VolumePluginDir` is actually empty value and FlexVolume is broken on Windows
```
$KubeletArgList += "--volume-plugin-dir=$global:VolumePluginDir"
```
**Notes**:

fix: FlexVolume broken issue on Windows

---

docs/topics/clusterdefinitions.md
pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go
test/e2e/test_cluster_configs/everything.json

This PR allows users to enable the `--anonymous-auth` apiserver flag, now that RBAC support is statically enabled for all clusters.
**Notes**:

feat: enable configurable apiserver --anonymous-auth

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/node/node.go

This PR improves the way we're validating `top nodes` in E2E tests.
**Notes**:

test: generic async top nodes interface for E2E

---

parts/k8s/kubeletstart.ps1
parts/k8s/kubeproxystart.ps1
parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsazurecnifunc.ps1
parts/k8s/windowsnodereset.ps1
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/virtualmachinescalesets_test.go

This PR adds dual stack support for azure cni windows cluster as like linux cluster. V4 Ips will be in vnet and v6 IPs will be in non-vnet. Non lifting validation check for windows dualstack until windows team release OS support. This PR also fixes creating multiple v6 configs per nic as its not supported.
**Notes**:

feat: Dualstack support for Windows containers

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-beta1

feat: add support for Kubernetes v1.19.0-beta.2

---

test/e2e/cluster.sh

This PR ensures that we don't pass an empty string to the test runner for the `STABILITY_ITERATIONS` env var.
**Notes**:

test: assign default stability iterations in cluster.sh

---

pkg/api/defaults.go
pkg/api/defaults_test.go

When provision or update VMAS cluster, AKS RP will first call deployTemplateWithoutAgentPool.
When call deployTemplateWithoutAgentPool, it will follow the below calling trace and AKS-Engine changes the managed cluster's OrchestratorVersion silently.
deployTemplateWithoutAgentPool =>
GenerateTemplate() => 
SetPropertiesDefaults() =>
setOrchestratorDefaults() =>
o.OrchestratorVersion = common.GetValidPatchVersion(
o.OrchestratorType,
o.OrchestratorVersion, isUpdate, a.HasWindows())
This is out of the expectation of AKS RP behavior, we should not adjust the MC's OrchestratorVersion if already given one.
**Notes**:

fix: Do not mutate OrchestratorVersion when set default

---

test/e2e/kubernetes/kubernetes_test.go

We have other tests that validate DNS resolver responsiveness, for the basic functional test we should allow for a higher timeout tolerance.
**Notes**:

test: use regular timeout for functional DNS test

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

AKS requires two ports to be exposed beyond 443. These ports are used for tunnelfront to connect to tunnelend and when customers block them (firewall etc.) it causes clusters to fail
**Notes**:
Looks to me like the apiserver connection check is sectioned to aks only since it is for hosted master but if that is wrong and aks-engine clusters could also trigger this code then please let me know as these ports are only needed for aks clusters

feat: ensure all AKS required ports on api-server are exposed

---

cmd/scale.go

This PR addresses three errors observed:
- `printScaleTargetEqualsExisting` convenience func doesn't return at the right time when it can't print
- retry calling the VM API when looking for nodes in the case where the call produces no matching VMs
- don't rely on tags being present on Windows VMs to correlate VMs w/ node pools, because in practice tags just sometimes aren't there :(
Fixes #3489 
**Notes**:

fix: scale + AvailabilitySet errata

---

examples/e2e-tests/kubernetes/release/default/definition.json
parts/k8s/addons/azure-policy-deployment.yaml
parts/k8s/addons/kubernetes-dashboard.yaml
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go

This PR ensures that we perform azure-policy namespace and label bootstrapping prerequisites before we load the gatekeeper spec via kube-addon-manager.
We also load the kubernetes-dashboard namespace prior to the spec to ensure we always create the namespace first.
Also adds a fix to ensure the change in #3313 actually happens, and that addons order loading is strictly enforced. Debugging azure-policy teased out this gap. Specifically, kube-addon-manager needs the `ADDON_PATH` env var to tell it where to source addons from. In our case we want to launch kube-addon-manager w/ a `ADDON_PATH=/etc/kubernetes/addons/init` so that it loads only the manifests thereunder at bootstrap time.
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/kube …

fix: addons bootstrapping errata

---

pkg/api/k8s_versions.go

This PR brings in metrics-server hotfixes for Windows builds of Kubernetes 1.18.4, 1.17.7, and 1.16.11.
**Notes**:

fix: use hotfix Windows builds for 1.18.4, 1.17.7, and 1.16.11

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

Make sure nvidia utility and compute bins can be mounted into container as documented in nvidia-container-runtime readme.
https://github.com/Azure/aks-engine/pull/3029
NVIDIA utility/compute bins are not mounted into containers when they're required in container env variable as NVIDIA_DRIVER_CAPABILITIES=compute,utility
**Notes**:

fix: Make sure nvidia utility and compute bins can be mounted into container

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR adds foo at node bootstrapping time to ensure that the cron systemd spec includes Restart=always.
Fixes #3503 
**Notes**:

fix: ensure cron systemd job restarts

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.22.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.22.txt

Updates Linux VHD references to the 2020.06.22 vintage.
- k8s.gcr.io/metrics-server-amd64:v0.3.6
- mcr.microsoft.com/oss/kubernetes/metrics-server:v0.3.6
- k8s.gcr.io/kube-addon-manager-amd64:v9.1.1
- mcr.microsoft.com/oss/kubernetes/kube-addon-manager:v9.1.1
- mcr.microsoft.com/oss/kubernetes/pause:1.4.0
- mcr.microsoft.com/containernetworking/azure-npm:v1.1.4
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.19.0-beta.2
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.19.0-beta.2
- mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.19.0-beta.2
- mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.19.0-beta.2
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.18.4
- …

chore: rev Linux VHDs to 2020.06.22

---

pkg/api/vlabs/validate.go

This PR tweaks the validation logic a bit so we don't unnecessarily force folks to explicitly specify "VirtualMachineScaleSets" in the input api model (because that's the default).
**Notes**:

chore: improve vmss validation now that vmss is default

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR standardizes the CSE bootstrapping script to always evaluate `[ -f /var/run/reboot-required ]` (does the file exist?) to determine whether or not we need to reboot.
In addition, in the case where we *want* to reboot, we touch that file, which as far as I can tell is a safe tactic as `/var/run` is tmpfs and files therein will be reliably removed upon reboot. Cf:
```
azureuser@k8s-master-31453872-1:~$ ls -la /var/run
lrwxrwxrwx 1 root root 4 Nov 13  2019 /var/run -> /run
azureuser@k8s-master-31453872-1:~$ df -h /run
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           796M  1.2M  795M   1% /run
```
Fixes #3533
**Notes**:

fix: always use /var/run/reboot-required

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/windowskubeletfunc.ps1
pkg/api/azenvtypes.go
pkg/api/k8s_versions.go
pkg/engine/templates_generated.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200625.txt

**Notes**:
1. cherry-pick commit from master branch: chore: updating windows VHD used by aks-engine to include June k8s packages (#3550)
2. use hotfix Windows builds for 1.18.4, 1.18.2, 1.17.7, 1.16.11, 1.16.10 and 1.15.12: from master branch:
1. fix: use hotfix Windows builds for 1.18.4, 1.17.7, and 1.16.11 (#3510)
1. fix: add windows hotfix overrides for 1.18.2, 1.16.10, 1.15.12 for AKS (#3528)
1. fix: updating hotfix packages used for windows to include hyperkube and iptables fixes (#3539)
3. Update PauseImage to 1.4.0 for Windows: from master branch:
chore: Updates the pause image to 1.4.0 (#3516)

chore: updating windows VHD used by aks-engine to include June k8s packages

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.25.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.25.txt

This PR updates the Ubuntu 16.04-LTS and 18.04-LTS VHDs to `2020.06.25`
Includes the following, newly added pre-downloaded components:
- moby v3.0.13
Includes the following, newly added pre-downloaded container images:
- mcr.microsoft.com/oss/kubernetes/hyperkube:v1.16.11-azs
- mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.16.11
**Notes**:

chore: rev Linux VHDs to 2020.06.25

---

parts/k8s/addons/aci-connector.yaml
parts/k8s/addons/azure-policy-deployment.yaml
parts/k8s/addons/cilium.yaml
parts/k8s/addons/container-monitoring.yaml
parts/k8s/addons/kubernetes-dashboard.yaml
parts/k8s/addons/secrets-store-csi-driver.yaml
parts/k8s/addons/smb-flexvolume.yaml
pkg/engine/templates_generated.go

Addon manifests that set `imagePullPolicy: Always` wont be functional (`ImagePullBackOff`) after upgrading an air-gaped environment, even if the required image is in the upgrade VHD.
Switching to `IfNotPresent` will prevent this problem.
**Notes**:

fix: change addons image pull policy to IfNotPresent

---

test/e2e/kubernetes/daemonset/daemonset.go
test/e2e/kubernetes/pod/pod.go

This PR enables more convenient daemonset testing, as well as retrieving pods by label, which is a common way of deterministically correlating a pod from its originating daemonset spec.
**Notes**:

test: enable daemonset E2E test conveniences

---

parts/k8s/addons/azure-cni-networkmonitor.yaml
parts/k8s/addons/azure-network-policy.yaml
pkg/engine/templates_generated.go

Our air-gap validations show that the `azure-cni-networkmonitor` pods running on control-plane nodes do not reach the `Running` state after an upgrade operation (AKSe v0.48+K8s v1.15 to v1.16). Switching `updateStrategy.type` to `RollingUpdate` (from default `OnDelete`) fixes the problem.
**Notes**:
Should we update all addons `updateStrategy`?

chore: set update strategy for the azure-cnms addon

---

cmd/upgrade.go
pkg/armhelpers/azurestack/kubeclient.go
pkg/armhelpers/interfaces.go
pkg/armhelpers/kubeclient.go
pkg/armhelpers/mockclients.go
pkg/operations/kubernetesupgrade/upgradecluster.go
pkg/operations/kubernetesupgrade/upgrader.go
test/e2e/kubernetes/daemonset/daemonset.go
test/e2e/kubernetes/kubernetes_test.go

Added an extra step in between control-plane and agent upgrades to delete the kube-proxy daemon if the upgrade version is 1.16.
Fixes #3557
**Notes**:
This extra step will fail silently otherwise it would break test "Should not fail if a Kubernetes client cannot be created" (upgradecluster_test.go)

fix: kube-proxy upgrade from v1.15 to v1.16

---

docs/topics/windows-provisioning-scripts.md
scripts/validate-windows-provisioning-scripts.sh

The pr #3441 added signing of the powershell scripts for China Cloud but the validation script was not update to reflect the change.
**Notes**:

fix: validate signed powershell packages in Azure and China Cloud

---

test/e2e/cluster.sh

The previous e2e test was failing on Azure Stack ADFS environment, as there was no --identity-system parameter in the `aks-engine scale` and `aks-engine upgrade` commands.
BTW: the documentation about scale and upgrade may need an update as well.
**Notes**:

test: e2e driver pass identity system to upgrade and scale commands

---

docs/topics/clusterdefinitions.md
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/const.go
pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

…(#3556)
Co-authored-by: Li Ma <lima2@microsoft.com>
**Notes**:

enable /etc/hosts config agent for AKS private cluster BYO DNS

---

.pipelines/e2e-step-template.yaml
parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

Update moby verison.
N/A
**Notes**:
This is the same as 3.0.13, except the new versioning to match upstream
and things are packaged differently (e.g. containerd is now managed with
systemd instead of by dockerd).
The packaging/build changes are fairly significant, but the underlying
moby commits are the same.

chore: Use moby 19.03.x packages

---

test/e2e/kubernetes/pod/pod.go

This PR addresses observed E2E flakes: we should not return from `GetAllRunningByLabelWithRetry` *solely* in a non-err context, because a `kubectl get pods` with an empty set is a non-err result.
**Notes**:

test: don't return from GetAllRunningByLabelWithRetry until we have pods

---

pkg/api/azenvtypes.go

Changes the base URL for the Azure CNI networkmonitor component to `mcr.azk8s.cn` from `dockerhub.azk8s.cn`.
Fixes #3580
**Notes**:

fix: use mcr.azk8s.cn for Azure CNI networkmonitor in China cloud

---

cmd/scale.go

This PR updates the "does this VMSS name correlate with my Windows node pool?" implementation so it actually does that correctly. The prior implementation was using tags, and then falling back to a VMAS-specific string comparison for Windows. This change simply compares the VMSS name using the canonical string munging foo that converts friendly node pool strings down to the concise (unfriendly) VMSS name for Windows pools.
Fixes #3522
**Notes**:

fix: use correct VMSS name comparison during Windows scale

---

pkg/api/azenvtypes.go

Update VHD version to 2020.07.16. Note we use quarter based SKU from now on.
Also remove GPU VHDs since they are not used any more (GPU dedicated VHD is now always SIG)

feat: Update VHD version 2020.07.16 and remove GPU VHDs

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR adds additional defaults enforcement for landing on MCR during upgrade, especially for old clusters that don't have newer api model data properties.
Fixes #3618 
**Notes**:

fix: reinforce MCR migration during upgrade for older clusters

---

test/e2e/kubernetes/kubernetes_test.go

This PR updates the E2E test runner so that the "validate kubelet comes back up after restart" test doesn't run if SSH access is blocked.
**Notes**:

test: don't run kubelet restart test if ssh is blocked

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.07.24.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.07.24.txt

This PR updates the Linux ubuntu VHDs to 2020.07.24
Includes an upgraded Ubuntu 18.04-LTS kernel:
- Linux version 5.3.0-1032-azure (buildd@lgw01-amd64-039) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #33~18.04.1-Ubuntu SMP Fri Jun 26 15:01:15 UTC 2020
Includes an upgraded Ubuntu 16.04-LTS kernel:
- Linux version 4.15.0-1091-azure (buildd@lcy01-amd64-002) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #101~16.04.1-Ubuntu SMP Fri Jun 26 01:14:12 UTC 2020
Includes the following, additive pre-downloaded components:
- moby v19.03.12
Includes the following, additive pre-downloaded container images:
- mcr.microsoft.com/oss/kubernetes/dashboard:v2.0.3
- mcr.microsoft.com/oss/kubernetes/coredns:1.7.0
- …

chore: rev Linux VHDs to 2020.07.24

---

pkg/api/const.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/workloads/validate-windows-logging.yaml

This updates docker to 19.03.11 which has the fix for log rotation.
#3573
**Notes**:
I ran this test against 19.3.05 and if failed consistently.  It passed consistently on new docker version
I also evaluated creating this tests as an upstream test but the container runtime is outside the scope upstream k8s tests.

fix: update windows docker version to fix log rotation error

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

This PR changes the "install moby|containerd" CSE implementation so that we only do the "remove all other CRI" operations if we actually need to install either moby or containerd. In the event that we detect that the desired version is already installed, we can return immediately.
**Notes**:

fix: only remove CRI if re-installing

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-rc2
**Notes**:

feat: add support for Kubernetes 1.19.0-rc.3

---

vhd/packer/install-dependencies.sh

This PR clarifies some errata in the manuallly curated list of CSE-installed apt packages during VHD CI output, and also adds a list of all apt packages installed.
**Notes**:

ci: clarify apt packages installed during VHD CI

---

.pipelines/vhd-builder-windows.yaml
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1190-rc3
**Notes**:
The Azure k8s artifacts are still building, so this will fail at first.

feat: add support for Kubernetes 1.19.0-rc.4

---

docs/topics/clusterdefinitions.md

This PR fixes documentation errata for the `sysctldConfig` interface.
Fixes #3681
**Notes**:

docs: fix misleading sysctldConfig examples

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.19.0
and https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.6
and https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.15.7
**Notes**:

chore: update cluster-autoscaler to latest patch versions

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

Makes load balancer type validation agree that "basic" and "Basic" are both ok.
In making this trivial fix, I noticed there was already a test case that specified "basic", but that was passing. It turns out that set of tests was ignoring any `err` return, so I fixed that so the UT will actually prevent this behavior from regressing.
Fixes #3661
**Notes**:

fix: validate "basic" LB and fix related unit tests

---

pkg/armhelpers/azurestack/kubeclient.go
pkg/armhelpers/interfaces.go
pkg/armhelpers/kubeclient.go
pkg/armhelpers/mockclients.go
pkg/operations/kubernetesupgrade/upgrader.go

Metrics-server upgrade fails from v1.15 to 1.16 as the addon mode is EnsureExists for pre-v1.16 cluster.
Similar to #3570 
**Notes**:

fix: metrics-server upgrade from v1.15 to v1.16

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

Workaround an issue seen on 1.15 to 1.16 upgrade on Azure Stack disconnected scenario where the CSE will timeout on deleting the addon manager pods; the pods go into terminating state and are not deleted unless force delete is invoked.
**Notes**:

chore: force delete addon manager when addon manager pods get stuck on terminating state

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go

Use latest `pod-infra-container-image` on both `deploy` and `upgrade` operations.
Fixes #3686
**Notes**:
WIP while running validations.

feat: cluster upgrade operations upgrade pause image

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/armvariables_test.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go

This PR ensures that we don't wait for a pod-security-policy yaml spec during cluster bootstrapping if the pod-security-policy addon has been explicitly disabled.
To be clear, explicitly disabling that addon will result in a non-working cluster, as privileged escalation capabilities won't be allowed, which various kube-system components require. But this PR will allow folks to deliver their own equivalent PodSecurityPolicy configs if they wish and still return from CSE.
Fixes #3656 
**Notes**:

fix: don't wait for pod-security-policy spec if disabled

---

pkg/api/azenvtypes.go

This PR updates the Windows VHD reference to version `17763.1339.200718`, which will enable new cluster operations with Windows node pools.
Related to #3700 
**Notes**:

fix: use new Windows VHD image version

---

pkg/api/azenvtypes.go

This PR updates the Windows VHD reference to version latest version, which will enable new cluster operations with Windows node pools.
Related to #3700
**Notes**:
/assign @jackfrancis

fix: update v0.53.0 to new 17763.1339.200718

---

pkg/api/azenvtypes.go

This PR updates the Windows VHD reference to the latest available version, which will enable new cluster operations with Windows node pools.
Related to #3700
**Notes**:

fix: update v0.52 to new 17763.1282.200626

---

pkg/api/azenvtypes.go

This PR updates the Windows VHD reference to the latest available version, which will enable new cluster operations with Windows node pools.
Related to #3700
**Notes**:

fix: update v0.51 to new 17763.1217.200514

---

parts/k8s/addons/cloud-node-manager.yaml
pkg/engine/templates_generated.go

Add rbac rules for nodes/status in cloud-node-manager.yaml.
**Notes**:

fix: add rbac rules for nodes/status in cloud-node-manager.yaml

---

pkg/api/k8s_versions.go
vhd/packer/configure-windows-vhd.ps1

1. Patch v1.15.11, v1.15.12, v1.16.10, v1.16.13, v1.17.7, v1.17.9 for Windows CPU usage issue
2. Patch v1.18.4 v1.18.6 for CVE
**Notes**:

fix: Patch v1.15.11, v1.15.12, v1.16.10, v1.16.13, v1.17.7, v1.17.9, v1.18.4 v1.18.6

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Related to https://github.com/Azure/aks-engine/issues/3668#issuecomment-674305778
Seeing some clusters fail with exit 36 recently where CSE failed to get the addon-manager pod as part of ensureAddons().
```
+ for i in $(seq 1 $retries)
+ timeout 30 /usr/local/bin/kubectl --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n kube-system
+ '[' 120 -eq 120 ']'
+ echo Executed '"/usr/local/bin/kubectl' --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n 'kube-system"' 120 times
Executed "/usr/local/bin/kubectl --kubeconfig=/home/azureuser/.kube/config get pods -l app=kube-addon-manager -n kube-system" 120 times
```
This PR might not fix the underlying root cause but we should not be getting/restarting pods when the …

fix: do not restart addon-manager if a reboot is required

---

pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/k8s_versions.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/workloads/validate-windows-logging.yaml
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.200820.txt

1. fix: update windows docker version to fix log rotation error (#3641) 
2. fix: Patch v1.16.10, v1.16.13, v1.17.7, v1.17.9 for Windows CPU metrics issues
3. Update Windows VHD to `17763.1397.200820`: 2020-08 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB4565349)
#3573: Docker log rotation stops after reaching limit on Windows nodes
[82195](https://github.com/kubernetes/kubernetes/issues/82195): CRI pod CPU metrics incorrect for pods with 20+ CPUs 
[83507](https://github.com/kubernetes/kubernetes/pull/83507): Prevent returning invalid usageNanoCores value when cpuacct is reset in a live container #83507
**Notes**:

chore: Update Windows VHD to 8B with hotfixes for Windows CPU metrics

---

cmd/get_skus_test.go
pkg/helpers/azure_skus_const.go

80 new SKUs were picked up by the `aks-engine get-skus` dev command. This adds them to the allowed list and to unit tests.
<details><summary>List of new SKUs</summary>
- Standard_D16_v4
- Standard_D16d_v4
- Standard_D16ds_v4
- Standard_D16s_v4
- Standard_D2_v4
- Standard_D2d_v4
- Standard_D2ds_v4
- Standard_D2s_v4
- Standard_D32_v4
- Standard_D32d_v4
- Standard_D32ds_v4
- Standard_D32s_v4
- Standard_D48_v4
- Standard_D48d_v4
- Standard_D48ds_v4
- Standard_D48s_v4
- Standard_D4_v4
- Standard_D4d_v4
- Standard_D4ds_v4
- Standard_D4s_v4
- Standard_D64_v4
- Standard_D64d_v4
- Standard_D64ds_v4
- Standard_D64s_v4
- Standard_D8_v4
- Standard_D8d_v4
- Standard_D8ds_v4
- Standard_D8s_v4
- Standard_E16-4ds_v4
- Standard_E16-4s_v4
- Standard_E16-8ds_v4
- Standard_E16-8s_v4
- …

chore: add new Azure VM SKUs

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/kubernetesparams.t
pkg/api/components_test.go
pkg/api/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
pkg/versions/compare.go
pkg/versions/compare_test.go
vhd/packer/install-dependencies.sh

Since moby packages now depend on a separate containerd package, we should specify which version of the containerd package should be picked up so that we don't accidentally introduce regressions for new installs/upgrades due to `apt-get` picking the latest containerd (which may include major version bumps).
This also enables testing aks-engine with different versions of containerd (such as the newly released 1.4) since the api model now allows specifying a containerd version when the moby version is >= 19.03.
N/A
**Notes**:

chore: specify containerd version to install with moby-engine package

---

pkg/operations/kubernetesupgrade/upgrader.go

This PR replaces the static 3 hour upgrade timeout with a "per-node" timeout. We calculate a a sum 20 mins per node for every node-to-be upgraded, and allow the aks-engine binary that much total time before throwing a general `aks-engine upgrade` operation timeout error.
For small clusters (less than 9 nodes including control plane nodes), this has the practical effect of reducing the total timeout tolerance for `aks-engine upgrade` operations. For larger clusters (10 or more total nodes), this has the practical effect of increasing the timeout tolerance. For really large clusters, that timeout tolerance becomes quite large.
In summary, the observed ~5 mins per-node upgrade time means that clusters with > 30 nodes cannot be upgraded in one operation successfully: …

feat: variable upgrade timeout based on num nodes

---

pkg/api/addons.go
pkg/api/addons_test.go

Something like this #2806 is required again to successfully deploy K8s 1.15 on air-gapped Azure Stack environments.
**Notes**:

fix: use cached v1.15-azs kube-proxy on Azure Stack

---

parts/k8s/cloud-init/artifacts/health-monitor.sh
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This PR ensures that Restart=always is configured for the docker systemd service, and that the included monitor script for both docker and kubelet has a fail-safe "start the systemd service" if the systemd job spec doesn't do so itself.
**Notes**:

fix: Restart=always docker systemd service

---

.pipelines/e2e-job-template.yaml
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/scripts/systemd-validate.sh

This PR adds a systemd validation test for kubelet and docker, to ensure that they are restarted after the processes are killed.
**Notes**:

test: validate kubelet and docker systemd during E2E

---

test/e2e/cleanup.sh
vhd/packer/vhd-rg-cleanup.sh

This PR ensures that cleanup scripts are able to login, and if not, exits 1.
**Notes**:

fix: ensure cleanup scripts can login w/ sp

---

pkg/engine/virtualmachinescalesets.go
vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2019-12-01/compute/models.go

fix: Fix availabilityZones value in template to read from parameter
The availability zone of virtualMachineScaleSets is specified directly in the template file instead of reading from the parameter file.
Fixes #3762 
fix: Bug Fixes 🐞
**Earlier:**
**Now:**

fix: availabilityZones value in template to read from parameter

---

parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
parts/k8s/addons/azurefile-csi-driver-deployment.yaml
pkg/engine/templates_generated.go

The version of CSI livenessprobe are different from AzureDiskFile CSI Drivers and Secret Store CSI Drivers currently. Tested the AzureDiskFile CSI Drivers with CSI livenessprobe v2.0.0. They worked well. So here make a change that has the minimum impact on the code. 
Later I will update the CSI livenessprobe version in AzureDiskFileCSI Drivers repo.
/cc @feiskyer  @andyzhangx 
**Notes**:

fix: update the flag due to using higher version of csi livenessprobe

---

parts/k8s/addons/1.15/calico.yaml
parts/k8s/addons/calico.yaml
parts/k8s/addons/flannel.yaml
parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/engine.go
pkg/engine/engine_test.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/network_policy/calico.json
test/e2e/test_cluster_configs/network_policy/calico_azure.json

This PR removes some of the sed tomfoolery for calico and flannel addons specs and instead uses go templating for more easier maintenance.
Also modified the E2E test cluster configs so that the "calico" test uses kubenet for IPAM, and the "calico_azure" test config uses Azure CNI.
**Notes**:

chore: simplify addons config for calico and flannel

---

parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
pkg/engine/templates_generated.go

This PR mounts the `/etc/kubernetes/certs` directory into the apiserver pod so that it can locally source them.
Fixes some of #3637, need to verify if it fixes everything
**Notes**:

fix: mount certs directory in apiserver pod

---

parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
pkg/engine/templates_generated.go

This PR mounts `/etc/ssl/certs` for the apiserver container so that it can access root CA certs.
May fix #3637 #3042
**Notes**:

fix: mount /etc/ssl/certs for apiserver

---

parts/k8s/addons/secrets-store-csi-driver.yaml
pkg/engine/templates_generated.go

Make sure that the secrets store addon is able to pull Key Vault entries from air-gapped clouds. 
Fixes #3786
**Notes**:

feat: secrets store addon can pull from custom env

---

parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
pkg/engine/templates_generated.go

In our haste to unblock AAD scenarios, we added an unnecessary `/etc/kubernetes/certs` `mountPath` to the apiserver spec. In fact, the needed mount was at `/etc/ssl/certs`, added in https://github.com/Azure/aks-engine/pull/3800.
We are already mounting `/etc/kubernetes`, and thus have access to `/etc/kubernetes/certs` recursively. E.g. from a cluster built with this changeset:
```
azureuser@k8s-master-20163450-0:~$ kubectl exec -it kube-apiserver-k8s-master-20163450-0 -n kube-system -- /bin/sh
total 80
drwxr-xr-x 2 root root 4096 Sep  9 16:50 .
drwxr-xr-x 6 root root 4096 Sep  9 16:50 ..
-rw-r--r-- 1 root root 6404 Sep  9 16:50 apiserver.crt
-rw------- 1 root root 3243 Sep  9 16:49 apiserver.key
-rw-r--r-- 1 root root 1720 Sep  9 16:48 ca.crt
-rw------- 1 root root …
```

chore: remove apiserver /etc/kubernetes/certs mount

---

parts/k8s/cloud-init/artifacts/etcd.service
pkg/engine/templates_generated.go

This PR addresses observed systemd failures to guarantee the etcd mount dependency upon `/var/lib/etcddisk` via the `RequiresMountsFor` configuration option. In the real world, the systemd `RequiresMountsFor` implementation is unable to detect the specified mount points despite the volume being mounted on the host, and thus blocks the start operation of the service indefinitely.
All credit to @Michael-Sinz :)
Fixes #3807
**Notes**:

fix: more resilient etcd systemd

---

pkg/api/common/versions.go
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md/#changelog-since-v1190
**Notes**:
~1.19.1 artifacts are not yet published by Azure, so this will fail for now.~

feat: add support for Kubernetes 1.19.1

---

parts/k8s/windowsazurecnifunc.ps1
pkg/engine/templates_generated.go

fix: Allow to add more than one VNetCIDR to the exception list

---

test/e2e/cluster.sh

Bug was introduced in https://github.com/Azure/aks-engine/pull/3747. When the uploaded ssh in e2e test was renamed to match the naming format of "${$RESOURCE_GRPUP}.ssh", the $PRIVATE_SSH_KEY_FILE no longer exist.
**Notes**:

test: set correct ssh private key for e2e get-logs

---

pkg/api/defaults-custom-cloud-profile.go

Distributing a fix for #3817 to air-gapped Azure Stack Hub clusters requires a new Linux VHD.
The proposed solution is to force, for Azure Stack clouds only, a different Linux base OS that contains the patched cloud provider images. 
This PR is meant to serve as a one-time fix that specifically targets release v0.55.x. 
Fixes #3817 
**Notes**:

fix: update Azure Stack's Linux VHD to 2020.09.14

---

pkg/api/azenvtypes.go
pkg/api/defaults-custom-cloud-profile.go
pkg/armhelpers/support_validator.go

Update an Azure Stack only validation that makes sure that the required OS images are in the Platform Images Repository (PIR). In this case, the Azure Stack only validation should look up `AzureStackAKSUbuntu1604OSImageConfig` instead of `AKSUbuntu1604OSImageConfig`.
This PR is meant to serve as a one-time fix that specifically targets release v0.55.x.
**Issue Fixed:**
Related to #3828
**Notes**:

chore: validate Azure Stack's Linux VHD is in PIR

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-vhd-builder.json

Reverts Azure/aks-engine#3801
We're seeing DNS failures after applying 9B / Sept 2020 updates on Windows Server 2019

revert: "chore: targeting sept updates for Windows 2019 VHD"

---

cmd/root.go
cmd/root_test.go
cmd/scale.go
cmd/update.go
cmd/updated_test.go
docs/community/developer-guide.md
test/e2e/cluster.sh
test/e2e/test_cluster_configs/base.json

This PR introduces the new CLI feature `aks-engine update --node-pool <node pool name>` to update VMSS node pools on existing cluster via AKS Engine ARM template generation.
tl;dr With a new version of AKS Engine compared to the version used to build your cluster, and/or with changes to the agentPoolProfiles definition in the generated `apimodel.json` output, you use `aks-engine update` to essentially push a new VMSS model to your node pool. Subsequent scale out operations against that VMSS will therefore use the updated VMSS model.
Some real-world examples:
- change the VM SKU
- change the OS distro
- change other AKS Engine-exposed OS configuration (e.g., sysctld)
In practice the implementation essentially re-uses `aks-engine scale`, giving that preëxisting …

feat: update VMSS node pools

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1191
**Notes**:

feat: add support for Kubernetes v1.19.2

---

.pipelines/e2e-job-template.yaml

This PR allows 30 more mins of E2E total time allowed tolerance, in response to observations of some tests exceeding the timeout, especially when testing versions of Kubernetes before they're able to be pre-downloaded into a VHD.
**Notes**:

test: add more E2E timeout tolerance

---

parts/k8s/addons/azure-cloud-provider.yaml
parts/k8s/addons/pod-security-policy.yaml
pkg/engine/templates_generated.go

Since AKS Engine already supports only Kubernetes v1.15.x or later, these template conditionals have no effect.
Refs #3751 
**Notes**:
Thanks to @jadarsie for noticing the off-by-one error in #3751, which implies this cleanup.

chore: remove no-op 1.15 version checks in templates

---

test/e2e/cluster.sh

This PR fixes a scoping bug in the cluster.sh script used to simulate E2E operations.
**Notes**:

fix: E2E scale scenario broken if update is false

---

vhd/publishing/add-image-version-to-sku.sh

Maketplace has a VHD media name length, which should be under 63 characters.
This change check the media name length before the vhd is published to Marketplace.
**Notes**:

chore: check VHD media name length before being published to Marketplace

---

parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh
pkg/engine/templates_generated.go

This PR adds the needed `#EOF` sentinel chars to the custom search domains script so that the CSE file wait func will properly detect its arrival on disk via cloud-init.
Fixes #3859 
**Notes**:

fix: add #EOF sentinel chars to custom search file

---

.pipelines/vhd-builder-windows.yaml
packer.mk
vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2004-vars.json
vhd/packer/windows-2019-vars.json
vhd/packer/windows-vhd-builder.json

feat: Updating Windows VHD build files to support building for multiple OS versions

---

cmd/rotate_certs.go
parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

`apiserver.crt` is distributed to agent nodes even though it is not needed by any agent node component or addon.
**Notes**:

chore: distribute apiserver.crt to control plane nodes only

---

cmd/rotate_certs.go

This PR marks the `rotate-certs` functionality as experimental, as recent tests suggest it's not in a working state.
**Notes**:

docs: mark rotate-certs command as experimental

---

test/e2e/config/config.go
test/e2e/kubernetes/kubernetes_test.go

- E2E test for kube-proxy version validation failed for k8s 1.15 as the hyperkube image for Azure Stack have a different suffix
- E2E test for akse 0.48.0 upgrade scenario on Azure Stack hit certificate issue as `python -v` command didn't return the expected information for python 2
**Notes**:

test: fix Azure Stack E2E cluster provisioner

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This PR moves the initial creation of `/etc/kubernetes/azure.json` entirely to CSE. This is to ensure that OS images derived from a running Kubernetes node can be re-used to create new nodes.
tl;dr
- CSE exits 0 immediately if it's already been run
- We don't want cloud-init to blow away stuff that's been mutated by CSE (`/etc/kubernetes/azure.json` is created by CSE)
See #2849 for the initial implementation of "no azure.json" functionality.
**Notes**:

chore: create azure.json via CSE

---

test/e2e/engine/template.go

This PR fixes a logical bug introduced in #3857. Many of our test configs don't declare a `kubernetesConfig` object in the input API model, which means environment variable-derivd service principal injection will be skipped. That's not what we want!
**Notes**:

test: not nil defense broke logic

---

test/e2e/cluster.sh

Fixing a test issue on E2E scale tests, the loop iterating the node pools needs to stop when the index is less than the total of agent pool profiles; currently the fix causes an additional call to scale with node poll set to null
+ (( ++i ))
+ (( i <= 1 ))
++ jq -r --arg i 1 '. | .properties.agentPoolProfiles[$i | tonumber].name'
+ nodepool=null
+ '[' '' = true ']'
Related to changes made in this PR: https://github.com/Azure/aks-engine/pull/3830
**Notes**:

test: E2E fix scale test indexing out of bounds

---

parts/k8s/windowscontainerdfunc.ps1
pkg/engine/templates_generated.go

On Windows kubelet computes CPU shares based on number of CPUs available on the host and passes that to the container runtime. When using Hyper-V isolated VMs the UVM the containers run in may have a different number of CPUs. Adding this flag instructs containerd to inspect the host and UVM CPU count and scale CPU limit values appropriately.
**Notes**:

feat: add ScaleCPULimitsToSandbox for hyperv runtimeclasses

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Reverts Azure/aks-engine#3864
Azure CNI 1.1.7 breaks container configurations: when nodes reboot, pod containers are not successfully recreated.

Revert "chore: update azure cni to 1.1.7"

---

parts/k8s/addons/aad-pod-identity.yaml
parts/k8s/addons/secrets-store-csi-driver.yaml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/engine/templates_generated.go
test/e2e/kubernetes/pod/pod.go

This PR ensures that aad-pod-identity and csi-secrets-store-driver addons don't open up listeners on the same port, as both are hostNetwork daemonsets.
**Notes**:

fix: ensure addon hostNetwork ports don't conflict

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR changes the CRI update warning in docker config scenarios so that it only logs on scale or upgrade, matching the log implementation of the containerd flow.
**Notes**:

fix: don't warn about CRI update on cluster create

---

parts/k8s/cloud-init/jumpboxcustomdata.yml
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This fixes two issues with custom data run command:
1) retrycmd_if_failure no longer exists, replaced with retrycmd
2) executing the cse helpers script as a shell script causes errors like `/var/lib/cloud/instance/scripts/runcmd: 11: /opt/azure/containers/provision_source.sh: [[: not found` in cloud init logs because `[[` is a bash builtin. Use `source` instead.
**Notes**:

fix: fix jumpbox custom data

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR allows VHD-like CSE flows, regardless of the "distro" value. So long as `/opt/azure/vhd-install.complete` exists on the underlying filesystem when CSE runs, it will assume that all required artifact dependencies are present, and skip those installation steps (e.g., apt-get install).
**Notes**:

chore: enable VHD re-use in no outbound scenarios

---

.pipelines/pr-e2e.yaml
examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
test/e2e/engine/template.go

This PR removes the custom VNET configuration declarations from the PR-configured E2E jobs for containerd, and fixes a nil panic vector in the E2E runner API model injection logic.
**Notes**:

ci: E2E fixes to allow more containerd tests

---

parts/k8s/addons/secrets-store-csi-driver.yaml
pkg/engine/templates_generated.go

Daemonsets are needed to run on all nodes but in a busy cluster with dynamic scaling, it is possible to have enough pending pods from replica sets that a new node fills up before the daemonset pod is ready to be scheduled.  Without priority classes, this can cause daemonsets to be pending to the pod they are bound to and can not run elsewhere.
In this change I added a priority class and use it in the daemonsets.  We could look at using the priority class system-node-critical which is reserved for kubernetes system daemonsets.  I don't think it is valid to use that here.
Just having a priority higher than 0 will usually address this as 99.99% of all workload pods are 0 (or below zero for the easily evicted buffer pods and such) …

Set the csi-secrets-store to have a priority class

---

pkg/api/defaults.go
pkg/api/defaults_test.go

Clear the deprecated MCR image base if upgrading an Azure Stack cluster.
An AzureStack-specific MCR repository was referenced by clusters created using older AKS Engine releases. 
New pause images wont be pushed to that repo.
Related work #3689
**Notes**:

fix: Azure Stack upgrade operations clear old MCR ImageBase

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json

This PR removes some enabled addons from the containerd test configs, because the containerd cluster config carries a slightly higher cloud-init payload, and those addons are contributing to PR test errors due to too many bytes. :/
**Notes**:

ci: reduce addons area for containerd config tests

---

parts/k8s/cloud-init/artifacts/kubelet.service
pkg/engine/templates_generated.go

This PR adds a dependency upon the containerd or docker services (as appopriate) to the kubelet systemd service definition, as strictly speaking we should not start up the kubelet systemd service without the CRI service.
**Notes**:

chore: kubelet systemd job depends on CRI service

---

parts/k8s/addons/metrics-server.yaml
pkg/engine/templates_generated.go

Following the guidance from this issue, setting metrics-server DNS resolution to `InternalIP`:
https://github.com/kubernetes-sigs/metrics-server/issues/131
**Notes**:

fix: use InternalIP for metrics-server DNS resolution

---

docs/tutorials/quickstart.md

-> run `aks-engine deploy` example script contains unwanted (") at Line number 84 of Quickstart.md, which causes syntax error. I have tried the script after truncating " and  it runs successfully.
run `aks-engine deploy` example script contains unwanted (") at Line number 84 of Quickstart.md, which causes syntax error. I have tried the script after truncating " and  it runs successfully.
Cosmetic changes in the Quickstart.md
- [X ] No
- [X ] No
- [ X] includes documentation
**Notes**:

docs: Remove double quotes(") at quickstart.md

---

pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go

Bug fix
Generated custom cloud profile does not contain resource identifiers even when set in API model.
It may cause unexpected application behavior for those programs relying on these values
**Notes**:

fix: resource identifier not pass to custom cloud profile

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
test/e2e/test_cluster_configs/flatcar/flatcar.json

This PR ensures that new flatcar node pool-enabled clusters use transparent mode if using Azure CNI, as that's proven to be the only working Azure CNI implementation w/ flatcar.
No upgrade foo added here; we'll see if folks desire that, but for now, this is a cleaner change that doesn't try to be too tricky in "converting" existing clusters that were built w/ bridge mode prior to the systemd change that broke it.
Fixes #3920 
**Notes**:

fix: ensure flatcar configs use transparent Azure CNI

---

cmd/upgrade.go

**Notes**:
Set 60 minutes cordonDrainTimeout for Azure Stack Cloud to give it enough time to move around resources during Node Drain, especially disk detach/attach operations.
We still honor the user's input.

chore: longer default cordonDrainTimeout for Azure Stack Cloud

---

Jenkinsfile
test/e2e/cluster.sh

This PR ensures that various entry points into `cluster.sh`'s `make test kubernetes` invocation set a bool value to `VALIDATE_CPU_LOAD`, to avoid errors like this:
```
Error while trying to parse configuration: envconfig.Process: assigning CONFIG_VALIDATE_CPU_LOAD to ValidateCPULoad: converting '' to type bool. details: strconv.ParseBool: parsing "": invalid syntax
```
**Notes**:

test: Jenkinsfile bool vars

---

.pipelines/vhd-builder-windows.yaml
test/e2e/engine/template.go
vhd/packer/sysprep.ps1
vhd/packer/windows-vhd-builder.json

This PR unblocks the Windows VHD scripts by doing two things:
- Removes Azure VM agents from the sysprep process 
- this fixes an issue where there was a missing DLL on recent upgrade of the Azure VM agents that caused sysprep to fail: `azure-arm: IMAGE_STATE_UNDEPLOYABLE - missing VMAgentDisabler.dll.`  The VM agent doesn't do anything during sysprep so it is ok to remove it. If the image is deployed to Azure as a VM the agent will redeployed. 
- Fixes the e2e tests during the VHD build using `USE_MANAGED_IDENTITY=false`
**Notes**:

ci: Windows VHD pipeline tests

---

test/e2e/kubernetes/node/node.go
test/e2e/runner/cli_provisioner.go

PR tests were failing occasionally #3974 
**Notes**:

test: Retry label when cluster first comes online

---

test/e2e/engine/template.go
test/e2e/test_cluster_configs/vmss_master.json

This PR explicitly configures `useManagedIdentity` to false in the VMSS masters test cluster configuration, to ensure that no other CI foo sets it to true.
**Notes**:

test: "useManagedIdentity": false for VMSS masters

---

examples/e2e-tests/kubernetes/release/default/definition.json
pkg/api/const.go
pkg/api/defaults.go
pkg/api/defaults_test.go
test/e2e/test_cluster_configs/everything.json

This PR changes the Azure CNI implementation to use "transparent" mode by default, rather than using a bridge interface. This change is due to an observed reduction in UDP edge cases, specifically intermittent high DNS lookup latency when the resolver is an IP address that sits in front of a distributed set of resolvers (DNAT). In the Kubernetes context, this is reproduced if there are more than one coredns pods in the cluster.
Fixes #3955
**Notes**:

chore: use transparent mode for Azure CNI

---

cmd/get_locations_test.go
cmd/get_skus_test.go

Locally we've noticed two test cases may fail. This seems to be because there are no required arguments to the `get-locations` and `get-skus` commands if `cli` auth is working.
To meet test expectations, I explicitly added a bogus command-line argument to ensure these tests see an expected error in any case.
**Notes**:

test: fix two UTs to work with "cli" auth

---

parts/k8s/cloud-init/artifacts/cse_customcloud.sh
parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
pkg/engine/templates_generated.go

This change sets the go sdk log level to INFO for clusters in Azure Stack. Info level logs request information made to ARM by the cloud provider; the extra info is needed to correlate cloud provider operations with Azure Stack service logs when investigating issues in cloud provider.
**Notes**:

chore: set go sdk log level for Azure Stack clusters

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.18.3
and https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.17.4
and https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.7
and #3996
**Notes**:

chore: update cluster-autoscalers to latest patches

---

.pipelines/pr-windows-signed-scripts.yaml
staging/provisioning/windows/cleanupnetwork.ps1
staging/provisioning/windows/kubeletstart.ps1
staging/provisioning/windows/windowsnodereset.ps1

First step in refactoring shared logic in startup and windows node reset.  We learned in 10c update (#3956) adds a breaking change  that requires `Get-HnsPolicyList | Remove-HnsPolicyList` to be removed before HNS-Network. We also need turn off kubeproxy while doing this.  
This also adds removed containerd images during the kubelet startup.
We should be able to have a follow up with a change that shares logic between startup and windowsnodereset.  This needs a little more consideration so is not included here.
**Notes**:
Requires signed scripts before kicking off …

fix: Re-ordering HNS policy removal due to 10c change in behavior and consolidating logic in Windows cleanup scripts 

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go
test/e2e/engine/template.go
test/e2e/test_cluster_configs/dualstack.json

- dhcpv6 systemd unit is only required for ubuntu `16.04`
**Notes**:

fix: enable dhcpv6 only for ubuntu 16.04

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/workloads/dns-loop.yaml

This PR adds a simple, one-time stress test to validate that a bunch of curls to a well-known external URL are responsive.
Nominally these checks actually do a curl, which relies upon the entire HTTP stack, but in practice they will surface high DNS lookups, which we've observed in the past.
**Notes**:

test: add dns-loop (actually curl) stress test

---

pkg/engine/transform/transform.go
pkg/engine/transform/transform_test.go
pkg/engine/transform/transformtestfiles/k8s_addpool_vmas.json
pkg/engine/transform/transformtestfiles/k8s_agent_upgrade_template.json
pkg/engine/transform/transformtestfiles/k8s_master_only_upgrade_template.json
pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
pkg/engine/transform/transformtestfiles/k8s_scale_template.json
pkg/engine/transform/transformtestfiles/k8s_template.json
pkg/engine/transform/transformtestfiles/master_resources_scale_temaplate.json
pkg/operations/kubernetesupgrade/upgradeagentnode.go
pkg/operations/kubernetesupgrade/upgrademasternode.go
test/e2e/test_cluster_configs/availabilityset.json

Upgrade fails for VMAS clusters if its VMs own a `roleAssignment` resource.
The problem is that `NormalizeResourcesForK8sMasterUpgrade` is not filtering `roleAssignments` resources and ARM complains because these `roleAssignments` resources depend on missing VM resources. 
stdout message:
```
INFO[0005] Starting ARM Deployment master-20-11-10T15.11.09-1247996574 in resource group upgrade. This will take some time... 
INFO[0006] Error creating upgraded master VM with index: 0 
Error: upgrading cluster: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool-25762572-0' is not defined in …
```

fix: upgrade broken for VMAS + managed identities

---

test/e2e/kubernetes/kubernetes_test.go

This PR disentangles the E2E test runner logic that determines whether or not cluster-autoscaler is engaged from the "skip ssh tests" context.
It's possible that there's a good reason for coupling those two config contexts, this PR E2E CI will tell us.
**Notes**:

test: re-engage cluster-autoscaler tests if no ssh

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Perhaps in the past the `ensureEtcd` func was unnecessary and not reliable in the non-VHD 18.04 scenario, but without it we don't start the etcd-monitor systemd job, which we want to do always.
**Notes**:

fix: always ensure etcd on control plane vms

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go
test/e2e/kubernetes/scripts/time-sync-validate.sh
vhd/packer/install-dependencies.sh

Use chrony + host-based time sync which is a recommended way and also work in airgap clouds.
All Azure Ubuntu 18.04 stock images already come with chrony enabled as well.
https://github.com/Azure/aks-engine/issues/2552
**Notes**:
Reference: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

feat: Enable chrony and host-based time sync by default on Ubuntu 18.04

---

cmd/addpool.go
cmd/scale.go
cmd/update.go
pkg/api/converterfromapi.go
pkg/api/convertertoapi.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
test/e2e/cluster.sh
test/e2e/test_cluster_configs/availabilityset.json
test/e2e/test_cluster_configs/base.json

This PR adds a new `VMSSName` property to the `AgentPoolProfile` type struct, to persist the definitive VMSS name (when the node pool is VMSS) for future cluster operations.
The VMSS name is a computed property that depends in part upon the particular index value of the pool in the API model `agentPoolProfiles` array at the time of cluster creation; but over time that order may change (for example a pool may be removed, introducing a "hole" in the sequence, and effectively decrementing each pool's index by one). This solution continues to rely upon this undesirable solution (let's not throw away the baby with the bath water), but it does so only one time during a cluster operation when the API model data structure is stable, and once the property is computed it is …

fix: persist VMSS name in API model

---

pkg/api/common/versions.go

We saw test failures with 1.17.14 and have a fix for the next patch release at kubernetes/kubernetes#96623.
See also https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v11713
**Notes**:
This PR contains a temporary testing commit that should be discarded before merging.
The Azure Pipeline for the 1.17.14 build has not completed successfully yet, so the artifacts are not published.

chore: mark Kubernetes 1.17.14 as disabled

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json

This PR ensures we're testing w/ more than one coredns pod on all E2E tests (containerd tests currently re-use the no-vnet cluster config)
**Notes**:

ci: use 3 replicas for no-vnet E2E jobs

---

cmd/deploy.go
cmd/scale.go
cmd/upgrade.go

Completing work started in #2342. This change blocks an upgrade operation if any required OS image is not available in the target Azure Stack Hub PIR (Platform Image Repository).
**Notes**:

chore: validate VHD availability before upgrade/scale on Azure Stack Hub

---

test/e2e/engine/template.go

The default `true` value of `useManagedIdentity` adds additional unsupported KubernetesConfig to Azure Stack API model, this is causing failure of Azure Stack E2E runs.
**Notes**:

test: disable useManagedIdentity default value on Azure Stack

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
test/e2e/kubernetes/workloads/dns-liveness.yaml

This PR addes the `ExecProbeTimeout=false` feature gate to 1.20 and later Kubernetes, to prevent livenessProbe timeout enforcement, which defaults to 1 second, from being introduced to an upgrade Kubernetes cluster suddenly.
**Notes**:

feat: disable livenessProbe timeout enforcement

---

parts/k8s/addons/aad-pod-identity.yaml
parts/k8s/addons/antrea.yaml
parts/k8s/addons/azure-cni-networkmonitor.yaml
parts/k8s/addons/azure-network-policy.yaml
parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
parts/k8s/addons/azurefile-csi-driver-deployment.yaml
parts/k8s/addons/blobfuse-flexvolume.yaml
parts/k8s/addons/calico.yaml
parts/k8s/addons/cilium.yaml
parts/k8s/addons/cloud-node-manager.yaml
parts/k8s/addons/container-monitoring.yaml
parts/k8s/addons/flannel.yaml
parts/k8s/addons/ip-masq-agent.yaml
parts/k8s/addons/keyvault-flexvolume.yaml
parts/k8s/addons/node-problem-detector.yaml
parts/k8s/addons/nvidia-device-plugin.yaml
parts/k8s/addons/scheduled-maintenance-deployment.yaml
parts/k8s/addons/secrets-store-csi-driver.yaml
parts/k8s/addons/smb-flexvolume.yaml
pkg/engine/templates_generated.go

Updating the `rollingUpdate` strategy of addon daemonsets to `maxUnavailable: 50%` in order to speed up `aks-engine rotate-certs`.
Fixes #4088
**Notes**:

chore: faster rolling updates for daemonset addons

---

pkg/operations/kubernetesupgrade/upgradecluster.go

Corrects a typo I noticed while running upgrade unit tests.
**Notes**:

fix: typo in upgrade log message

---

pkg/api/defaults-kubelet_test.go
pkg/api/defaults.go
pkg/api/defaults_test.go

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
fixes #4112
**Notes**:

fix: honor user-defined feature gates before applying defaults

---

parts/k8s/cloud-init/artifacts/docker-monitor.service
parts/k8s/cloud-init/artifacts/kubelet.service
parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This PR ensures we are waiting for the correctly named CRI service name in various systemd definitions.
**Notes**:

fix: ensure we wait for the right CRI service name

---

staging/provisioning/windows/kubeletstart.ps1
staging/provisioning/windows/kubeproxystart.ps1
staging/provisioning/windows/run-process.cs

This should help address many customer reported issues we have been seeing where kubelet get starved of CPU cycles when node is running under high CPU load.
I tried creating the Process object in native powershell but saw some pretty horrible lag processing the OutputDataReceived/ErrorDataReceived events so I think this is probably the most performant thing to do.
**Note**: Once kubelet/kube-proxy both have flags to set the process priority we can remove / undo this code.
**Notes**:

feat: Updating kubelet/kube-proxy to run with as high priority processes

---

staging/provisioning/windows/kubeproxystart.ps1

fix that kubeproxy cannot parse featuregates
**Notes**:
I set `provisioningScriptsPackageURL` in `examples/windows/kubernetes-windsr.json` to `https://testxx3e.blob.core.windows.net/akswindows/signedscripts-v0.0.7.zip` and below test passed.
```
CLUSTER_DEFINITION="examples/windows/kubernetes-windsr.json" SUBSCRIPTION_ID="xxx" CLIENT_ID="xxx" CLIENT_SECRET="xxx" TENANT_ID="xxx" LOCATION="westus2" CLEANUP_ON_EXIT=false make test-kubernetes
```
Result
```
------------------------------
JUnit report was created: /aks-engine/test/e2e/kubernetes/junit.xml
Ran 45 of 65 Specs …
```

fix: fix that kubeproxy cannot parse featuregates

---

pkg/api/const.go
pkg/api/defaults.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
vhd/packer/configure-windows-vhd.ps1

We should be setting a default containerd package for Windows nodes if we plan on making containerd be the default container runtime for aks-engine.
This package contains **signed** versions of upstream containerd/containerd release binaries to comply with Azure SysLock policies.
**Notes**:

feat: setting a default containerd package for Windows

---

pkg/engine/cse.go
pkg/engine/cse_test.go

The prow jobs occasionally fail due to long provisioning times for Windows nodes.  In the prow jobs we use a [second Extension](https://github.com/kubernetes-sigs/windows-testing/blob/master/extensions/master_extension/v1/win-e2e-master-extension.sh) which in turn calls `timeout`. When a timeout occurs the return code is 124 (see `man timeout`).  
The prow job https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-20-windows/1345819398920736768 is an example:
```
\\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n        
\\\"message\\\": \\\"VM has reported a failure when processing extension 'cse-master-0'. Error message: 
\\\\\\\"Enable failed: failed to execute command: command …
```

fix: update error code for vhd not found

---

pkg/api/azenvtypes.go
pkg/api/common/versions.go

Update new VHD and k8s patch versions

chore: Update VHD 2021.01.06 and k8s patch versions

---

scripts/collect-windows-logs.ps1
staging/provisioning/windows/cleanupnetwork.ps1
staging/provisioning/windows/kubeletstart.ps1
staging/provisioning/windows/windowsnodereset.ps1

* Fixes issue when calling cleanupnetwork.ps1 as a stand-alone script
* Fixes issue when running kubeletstart.ps1 from a directory other than c:\k
* Fixes issue where 'azure' network is not re-created after network cleanup because logs weren't deleted (logs ended up in c:\windows\system32 due to issue where containerd not setting working directory) 
**Notes**:

fix: fix network cleanup code on windows for contianerd nodes

---

examples/dualstack/README.md
examples/dualstack/kubernetes-iptables.json

- Adds `iptables` api model for dual-stack
- Updates dual-stack docs
**Notes**:
/cc @lachie83

docs: add dual-stack iptables api model

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/workloads/hostport-test.yaml
test/e2e/kubernetes/workloads/httpbin.yaml

Inspired by this AKS issue report, this PR brings a new E2E test that validates basic hostPort functionality:
https://github.com/Azure/AKS/issues/2070
**Notes**:

test: ensure hostPort routing

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

AKS-Engine clusters on containerd + kubenet currently do not support hostPort mapping to a podSpec's containerPort
See: Azure/AKS#2070
We confirmed this issue also applies to AKS-Engine clusters
- [x ] No
**Notes**:

fix: update nodecustomdata to enable portmapper for kubenet+containerd

---

.devcontainer.json
.github/workflows/nightly-build.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
makedev.ps1
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

This PR updates the standard dev container image to deis/go-docker-dev v1.29.0
See: https://github.com/deis/docker-go-dev/releases/tag/v1.29.0
**Notes**:

ci: update dev image to deis/docker-go-dev v1.29.0

---

test/e2e/kubernetes/kubernetes_test.go

This PR fixes a dangling, unnecessary `err` check, and tests the arrival of a Running daemonset against the prior (pre-vmss-prototype) baseline, rather than requiring an aggressive sub-10 second metric.
**Notes**:

test: kamino E2E errata

---

test/e2e/kubernetes/kubernetes_test.go

This PR corrects some misleading language in the kamino + vmss-prototype E2E test scenario.
**Notes**:

test: correct E2E message during vmss-prototype test

---

test/e2e/kubernetes/kubernetes_test.go

This PR prints the helm command to stdout invoked to test vmss-prototype, in order to more easily see what is being tested.
**Notes**:

test: print helm command for vmss-prototype test

---

test/e2e/kubernetes/pod/pod.go

This PR adds time stamp data to the printed pod logs invocations (via the standard `--timestamps` `kubectl logs` argument).
**Notes**:

test: add timestamps to E2E pod logs output

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/node/node.go
test/e2e/kubernetes/workloads/kured-annotations.yaml

This PR incorporates alpha kured + node annotations functionality to support automatically choosing a node candidate to use in the kamino vmss-prototype test flow.
**Notes**:

test: incorporate kured + auto mode into kamino vmss-prototype tests

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/engine/templates_generated.go

This PR explicitly ensures that container-originating TCP traffic bound for the reserved Azure IP + TCP 80 endpoint is dropped.
**Notes**:

chore: block container traffic to 168.63.129.16

---

test/e2e/kubernetes/kubernetes_test.go

We regularly see it take longer than 4 hours for SIG images to be published and ready. :/
E.g.:
https://github.com/jackfrancis/kamino/pull/60/checks?check_run_id=1824243337
**Notes**:

test: tolerate long SIG image publication times for vmss-prototype test

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Fixes perf issue https://github.com/microsoft/Windows-Containers/issues/22.  See release for more details: https://docs.docker.com/engine/release-notes/19.03/
**Notes**:
/cc @marosset @AbelHu

chore: update windows dockeree version to 19.03.14

---

test/e2e/azure/cli.go
test/e2e/remote/ssh.go

Whoops we were using the wrong select/case pattern to handle continual async message passing for a few go routines used by the E2E test runner. Specifically, we're doing a "run a command once then sleep" pattern, which in the context of a select/case that also handles messages from async channels means that after we return from sleep we want to process any messages first (because those messages tell us whether or not we need to actually re-run the command again).
The fix is to put the periodic command invocation in the `default` block, so that we will always "fall through" the case statements (order not guaranteed). In this case the only order we care about is invoking the command last, so doing it inside of `default` accomplishes that.
**Credit …

test: go routine errata

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go

Replicating https://github.com/Azure/aks-engine/pull/4206 for the Windows CSE
**Notes**:

fix: add retry when downloading files in windows CSE

---

test/e2e/azure/cli.go
test/e2e/kubernetes/deployment/deployment.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/networkpolicy/networkpolicy.go
test/e2e/kubernetes/pod/pod.go
test/e2e/runner/cli_provisioner.go

This PR fixes some observed flakes in E2E tests:
- Retry create VNET calls
- Don't print pod logs for docker rotate logs test
**Notes**:

test: E2E resilience

---

test/e2e/test_cluster_configs/availabilityset.json
test/e2e/test_cluster_configs/base.json

We don't want to run the "DNS liveness" test on a long-lived cluster that has transitioned via an `aks-engine upgrade` operation as that can introduce temporarily downtime that can trigger a DNS liveness failure.
**Notes**:

ci: skip dns liveness test after upgrade

---

cmd/rotate_certs.go
hack/tools/go.mod

An `ARMClient` should be instantiated after `apimodel` is loaded.
**Notes**:

fix: rotate-certs on custom clouds

---

parts/k8s/addons/cilium.yaml

Fixes duplicate "labels" annotation inside the cilium.yaml addon file
**Notes**:
Although this addon may not be used anymore, I was experimenting around with this setup and noticed problems using it due to duplicate label annotation.

fix: remove duplicate labels for cilium-operator

---

parts/k8s/cloud-init/masternodecustomdata.yml
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/types.go
pkg/api/types_test.go
pkg/engine/armvariables.go
pkg/engine/armvariables_test.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/everything.json
vhd/packer/packer_source.sh
vhd/packer/vhd-image-builder-ubuntu-gen2.json
vhd/packer/vhd-image-builder.json

This PR changes the VHD configuration so that auditd rules are not put onto the VM filesystem as part of VHD creation. Also includes required ARM template composition changes due to the fact that there is no VHD context related to the need for these cloud-init requirements.
**Notes**:

chore: don't include auditd rules in Linux VHDs

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This PR changes the way we pre-pull container images during VHD CI so that both docker (moby) and containerd runtime configurations can use them.
**Notes**:

chore: ensure containerd has image cache on VHDs

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

This PR removes one version from each minor release from the supported versions list for Azure public cloud. In practice this means the following:
- aks-engine will only support patch version (the most recent to be validated) of Kubernetes per minor release; for example, for 1.17, the most recent, known-working version will be supported, and no other 1.17 patch releases will be supported
- because we only currently test one patch version per minor release (again, the most recently known-working one), this has the effect of improving the test fidelity across Kubernetes versions
This PR makes no changes to the Azure Stack Hub versions configuration, because in practice Azure Stack Hub already only supports one patch version per minor release.
**Credit …

chore: support only latest, tested versions of Kubernetes

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

This PR standardizes to 2 the number of Azure CNI versions to pre-download into the VHDs. We'll always use the latest, plus the one before that.
**Notes**:

chore: keep two versions of Azure CNI in VHD

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1203
**Notes**:
~~This will fail for the time being, as we are still working out a build issue on the Azure Pipeline for k8s.~~
v1.20.3 was superceded by v1.20.4 due to a conformance test fix.

feat: add support for Kubernetes v1.20.4

---

.pipelines/e2e-step-template.yaml
.pipelines/pr-windows-signed-scripts.yaml
.pipelines/vhd-builder-windows-template.yaml
test/e2e/cluster.sh
test/e2e/engine/template.go
test/e2e/kubernetes/kubernetes_test.go

This PR ensures that any usage of the E2E test runner invoked `az` with the suppression of non-error output.
See:
https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/HISTORY.rst#230
Also, two tweaks to the vmss-prototype tests based on observations:
- If we're configured to test the vmss-prototype functionality, we automatically set `RunUnattendedUpgradesOnBootstrap` to false in the `LinuxProfile`
- retry the kured daemonset creation
**Notes**:

test: use AZURE_CORE_ONLY_SHOW_ERRORS when running E2E

---

vhd/publishing/new-sku-and-add-image-version.sh

AKS publishes SKUs starting with aks- and if AKS publishes a SKU first the logic in this script will not create a new non-AKS sku so I'm fixing that.
**Notes**:

ci: make sure sku is exact match when deciding to create or reuse sku  for publishing Windows VHDs

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR ensures that when we're using the "block outbound internet access" test feature flag, we don't try to run unattended-upgrade as a blocking CSE operation (which will never finish due to default apt servers not being reachable).
**Notes**:

chore: don't run unattended upgrade if using "no outbound" test feature

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

test: Add Feb security patch

---

README.md

Clarifying that the project is maintained, and use for Azure Stack Hub
Some refinement about project status is needed to avoid confusion
**Notes**:

docs: refine message about aks-engine project status

---

cmd/get_skus.go
cmd/get_skus_test.go
pkg/api/common/helper.go
pkg/helpers/azure_skus.go
pkg/helpers/azure_skus_const.go

Since a VM's storage type is calculable from its name, there's no need to maintain a static lookup table. This is a minor simplification to ensure there's only one code path for finding storage type.
(This is also the only separable change that came out of my work on #4277 so far.)
Refs #4277
**Notes**:

refactor: remove storage type from SKU lookup table

---

docs/topics/clusterdefinitions.md
pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/workloads/pod-projected-svc-token.yaml

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
Fixes test failure in https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd, specifically the following test case:
```
Kubernetes e2e suite.[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
```
Got the following error when executing that test case:
```
2021/02/11 20:32:47 Get "kubernetes.default.svc/.well-known/openid-configuration": unsupported protocol scheme ""
```
I manually [updated some of the API models](https://github.com/kubernetes-sigs/windows-testing/pull/247) used for testing and looks like we need explicitly set the protocol by prepending `https://` in the service-account-issuer flag to …

fix: prepend https:// in service-account-issuer flag

---

pkg/api/azenvtypes.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

March patch tuesday
**Notes**:

chore: March 2021 patch updates for Windows

---

vhd/packer/configure-windows-vhd.ps1

mcr.microsoft.com/oss/kubernetes/pause:3.4.1 has support for Windows Server Ver 20H2
**Notes**:

chore: Adding mcr.microsoft.com/oss/kubernetes/pause:3.4.1 to Windows VHD

---

pkg/api/converterfromapi.go
pkg/api/convertertoapi.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/api/vlabs/types_test.go
pkg/engine/virtualmachinescalesets.go

allow setting read only cache
we've observed several issues with the performance of write caching on azure, including stalls on the whole disk when fsync'ing a single file, and allowing the cache to accept IO requests in excess of what the the device can handle. the former directly degrades performance and the latter indirectly degrades it by decreasing the ability of the linux kernel to counteract using e.g. io request merging (since everything passes through to azure as if there were no traffic). 
we're working with storage on mitigating those issues but in the meantime we'd like to allow changing this value to ReadOnly for OS disk. This is the only other allowed value (None for OS Disk will be overridden internally, refer to the doc link on the API type).
**Issue …

feat: allow setting read only cache

---

parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowskubeletfunc.ps1
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1

1. Remove docker as not used when containerD is used. Also mixing docker and containerD may hide potential errors of containerD by docker
2. cx may get confused by the docker CLI output on a containerD-enabled node for devops
**Notes**:

fix: disable docker when containerD is specified

---

parts/k8s/windowscontainerdfunc.ps1
pkg/engine/templates_generated.go

fix: specify correct pause image in containerd config for Windows 20h2

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1204
**Notes**:

feat: add support for Kubernetes v1.20.5

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1

Fixes an issue where curl.exe can fail silently on Windows.
Fixes the issue discussed at https://github.com/Azure/aks-engine/pull/4319#discussion_r590888988
**Notes**:

fix: Checking return code of curl.exe on Windows

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go

The test was checking the date which wasn't in the last 20 lines because the log output is too verbose.  This checks further back in the output to ensure we always have a date stamp
**Notes**:

ci: Fix flaky docker rotate e2e test

---

pkg/armhelpers/mockclients.go
pkg/operations/kubernetesupgrade/upgradecluster_test.go

Some unit test code was naively calculating the prior Kubernetes version by decrementing the minor but leaving the major and patch versions intact. This will fail when Kubernetes 1.18.18 comes out next week, since it will supply "1.17.18" which doesn't and won't exist.
Instead let's reuse the `RationalizeReleaseAndVersion` func to get the latest patch for the previous minor release correctly.
Prevents a test bug that will arise next Wednesday [when v1.18.18 drops](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#118).
**Notes**:

test: fix prior k8s minor version in mocks and upgrade test

---

.devcontainer.json
.github/workflows/nightly-build.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
hack/tools/Makefile
makedev.ps1
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

See https://github.com/deis/docker-go-dev/releases/tag/v1.30.0
and https://github.com/golang/go/issues?q=milestone%3AGo1.15.11+label%3ACherryPickApproved
**Notes**:

chore: update Go toolchain to v1.15.11

---

docs/topics/clusterdefinitions.md
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/api/addons.go
pkg/api/addons_test.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/everything.json
test/e2e/test_cluster_configs/gpu.json

This PR makes a change so that nvidia drivers are not installed if the nvidia-device-plugin addon is disabled.
Additionally, because the known-working drivers that CSE installs don't work with containerd, we don't change the addons default flow so that the nvidia-device-plugin addon is disabled if containerd is the CRI.
The practical outcome of this is that you may use containerd with N series VM SKUs, and no nvidia drivers will be installed. The nvidia gpu-operator implementation solves this, see:
https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/
A new E2E scenario has been added for N series + containerd configurations, which installs the nvidia-curated gpu-operator helm chart, and then validates using the existing CUDA …

feat: don't install nvidia drivers if nvidia-device-plugin is disabled

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Ran into this in CI where I'm trying to test new packages.
runc that's already installed in the vm image is older than the minimum
version of the new package, as such the package installation fails and
cluster provisioning errors out.
apt has functionality to fix dependency problems found while using
`dpkg`.
This adds a helper function to replace `dpkg install` with one that
basically calls `apt-get update && apt-get install -f` after a failed
install (update is required as well, otherwise the package list is out
of date).
**Notes**:

fix: Fix installer for custom package URL's.

---

vhd/packer/configure-windows-vhd.ps1

chore: Adding April 2021 security updates to Windows VHD

---

parts/k8s/addons/metrics-server.yaml
pkg/engine/templates_generated.go

`rbac.authorization.k8s.io/v1beta1` is deprecated, and will be removed in the 1.22 release.
This PR uses the current `rbac.authorization.k8s.io/v1` API version for metrics-server.
**Notes**:

chore: use rbac.authorization.k8s.io/v1 for metrics-server

---

staging/provisioning/windows/kubeletstart.ps1
staging/provisioning/windows/windowsnodereset.ps1

fix #4351 
**Notes**:
We ran our test > 40 times and do not hit the issue with this change

fix: Force restart kubeproxy to avoid stucking

---

.pipelines/pr-windows-signed-scripts.yaml

ci: treat failures in cleanup tasks for pr-windows-signed-scripts.yaml as warmings not errors

---

test/e2e/cluster.sh

Pushing upstream a few `rotate-certs` e2e fixes we have in place in our own CI.
**Notes**:

test: cluster.sh fixes for rotate-certs

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This PR updates the default versions for both moby and containerd to the current latest builds, and standardizes runc to rc92.
The reason for pinning to runc rc92 is to address this issue which was introduced in rc93:
https://github.com/opencontainers/runc/issues/2865
**Notes**:

chore: update CRI builds

---

cmd/upgrade.go

During upgrade, the ImagePublisherAndOfferMatch function itself is not able to distinguish smalldisk and ctrd image, since they have the same ImageOffer and ImagePublisher. This is causing mixed cluster previously using smalldisk image to always try to upgrade to use ctrd image, since it's the first condition. Adding the identifier for ImageSku to help distinguish these two cases.
**Notes**:

fix: distinguish ctrd and smalldisk windows image in upgrade scenario

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/workloads/dns-liveness.yaml
test/e2e/kubernetes/workloads/exec-liveness-always-fail.yaml
test/e2e/kubernetes/workloads/exec-liveness-assume-1-second-default-timeout.yaml
test/e2e/kubernetes/workloads/exec-liveness-timeout-always-fail.yaml
test/e2e/kubernetes/workloads/exec-liveness-timeout.yaml
test/e2e/kubernetes/workloads/exec-liveness.yaml

This PR removes the `ExecProbeTimeout=false` feature gate protection as a default configuration for 1.20+, and adds E2E test cases to fully validated the functional behaviors of exec livenessProbes.
**Notes**:

feat: enable working, validated exec livenessProbes

---

Dockerfile

This enables cases like `docker build --output=bin/
https://github.com/Azure/aks-engine.git` without having to manually
check out code and everything.
It supports cross compilation so a user can set
`--platform=darwin/amd64` or `--platform=local`, etc. to get a binary
for whatever they need.
**Notes**:

chore: Add Dockerfile for convenient building

---

test/e2e/kubernetes/kubernetes_test.go

This PR tweaks the E2E test implementation so that `/sys/class/net/eth0/mtu` is not validated unless the `LinuxProfile.Eth0MTU` property is present (e.g., kubenet).
**Notes**:

test: only validate MTU if Eth0MTU is present

---

parts/k8s/addons/coredns.yaml
pkg/engine/templates_generated.go

This PR adds graceful shutdown configurations to coredns. 
Currently, if a coredns pod is deleted (due to eviction for example), the container shuts down immediately. This has negative side effects:
1. Some in-flight requests may fail.
2. A transient race where some requests may still be sent to the shutdown instance until this pod's IP address have been removed from the service.
If any of the two happens, we end up with the dreadful 5s timeout/retry latency.
The PR adds [`lameduck` configuration](https://github.com/coredns/coredns/blob/master/plugin/health/README.md) to the `health` plugin such that it would delay shutting down the service until 5 seconds after the readiness probes had failed. This guarantees that both in-flight queries are completed and enough …

fix: Graceful coredns shutdown

---

cmd/addpool.go
cmd/addpool_test.go

Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
This makes flag name in error message consistent with flag required by `addpool` cmd
**Notes**:

chore: updates error msg in addpool cmd

---

.github/workflows/release.yaml

This PR updates the release github action so that it doesn't run kamino vmss-prototype tests, as they don't seem to work with the multi-platform nodepools cluster config that we use to test.
**Notes**:

ci: don't run vmss-prototype tests for release

---

cmd/rotate_certs.go
docs/topics/rotate-certs.md
parts/k8s/cloud-init/artifacts/generateproxycerts.sh
parts/k8s/rotate-certs.sh
pkg/api/types.go
pkg/engine/templates_generated.go

`aks-engine rotate-certs` is not rotating the front-proxy certs.
AKS Engine creates a separate PKI for the front-proxy as part of node bootstrapping process and delivers them to all nodes  through etcd. To effectively reuse this functionality, `rotate-certs` has to replace the certs stored in etcd.
Also, front-proxy certs now expire after 30 years.
Fixes #4463
**Notes**:

fix: front-proxy certs updated by rotate-certs

---

hack/tools/Makefile
scripts/ginkgo.coverage.sh

This PR removes various CI references to the goveralls endpoint for publishing ginkgo coverage data, as we aren't actively using that endpoint anymore.
**Notes**:

ci: remove goveralls references

---

.github/workflows/update-go-mod-vendor.yaml
Makefile
test/e2e/Makefile

This PR standardizes our usage of the vendor directory so that both the aks-engine code itself _and_ the E2E go module store local dependencies in `vendor/`.
Also ships a GitHub Action to regularly maintain go mod vendor, and it replaces the (now no longer needed) hack/tools GitHub Action.
**Notes**:

ci: standardize go mod vendor

---

.github/workflows/create-release-branch.yaml
docs/community/release-checklist.md

This PR updates the release documentation to reflect that the release process is fully automated.
We also add more "no egress" coverage to the first phase in the automation.
**Notes**:

docs: Document automated release process

---

parts/k8s/addons/azure-cloud-provider.yaml
pkg/engine/templates_generated.go

This PR changes the StorageClass api version to `storage.k8s.io/v1` for versions of Kubernetes >= 1.22.0
**Notes**:

chore: use storage.k8s.io/v1 apiVersion for 1.22+

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json

Because the `azure-policy` addon is no longer actively maintained, we should remove it from our E2E test configs to eliminate sources of unexpected failures.
Related to:
https://github.com/Azure/aks-engine/issues/4549
**Notes**:

test: don't include azure-policy addon in E2E cluster configs

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR ensures that worker nodes do not start the kubelet systemd service if they are going to be rebooted by CSE.
Additionally, we clean things up so that control plane node *do* always fully start up, even if they are going to be rebooted. This is because we may need to do one-time (delivered via aks-engine api model) resource bootstrapping, and for that we need a working cluster, which each control plane node during cluster creation essentially represents. This will result in a bit more control plane node readiness thrashing during cluster creation (kubelet may come online and then be rebooted a minute later), but this is not a big problem.
This solves the problem of new nodes coming online after cluster creation (for example, node scale out operations) causing …

 fix: don't start kubelet if reboot is imminent

---

pkg/api/common/const.go
pkg/api/const.go
pkg/api/vlabs/const.go
pkg/api/vlabs/types.go

This PR enables node pools to be up to 1000 at cluster creation time, matching the VMSS instance count maximum.
**Notes**:

feat: enable new clusters w/ 1000 count node pools

---

Makefile

This PR abandons the goal of compressing built binaries using upx. We've experienced reports of non-executable binaries after processing with upx, and it is a known outcome of depending upon upx that updates to the version of golang may require an update to upx. We'd rather optimize our ability to quickly track version movement in golang itself, and not be held back by golang <---> upx affinity.
Fixes #4513
**Notes**:

chore: don't use upx to compress built binaries

---

staging/provisioning/windows/windowssecuretls.ps1

Add windowssecuretls.ps1 in Windows provisioning package. 
- [] No
**Notes**:

chore: Add windowssecuretls.ps1

---

docs/topics/clusterdefinitions.md
pkg/api/const.go
pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go

I think not all users need verbosity level 4 for the apiserver. This logs all requests sent to it and is really quite verbose.
**Notes**:
BREAKING CHANGE: the default apiServer verbosity changes from 4 to 2.

feat: allow setting apiserver verbosity and change default from 4 to 2

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR restores the previous behavior of always installing GPU drivers during bootstrapping. This has the side-effect of no longer supporting "airgap" scenarios, but it appears that simply `apt-get download`'ing the packages during VHD creation is not sufficient for providing that solution. I am speculating that files in `/var/cache/apt/archives/` are regularly cleaned up based on the age of the files, which means that pre-downloaded apt packages in the VHD are only viable for a temporary period of time.
Fixes #4631
**Notes**:

fix: always install GPU drivers during bootstrapping

---

staging/provisioning/windows/kubeproxystart.ps1

Allow setting additional parameters for kubeproxy without changing kubeproxystart.ps1
#4639
**Notes**:

feat: Allow setting Kubeproxy parameters by :ClusterConfiguration.Kubernetes.Kubeproxy.ConfigArgs

---

parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/rotate-certs.ps1
parts/k8s/windowsazurecnifunc.ps1
pkg/engine/templates_generated.go

Use Invoke-WebRequest instead of curl.exe to download files
curl.exe does not retry when failed in handshake.
```
2021-09-08T01:12:44.6532522+00:00: Download kubelet binaries and unzip
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
```
If "Yes," did you notify that project's maintainers …

fix: Use Invoke-WebRequest instead of curl.exe to download files

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

chore: Install sept 2021 security patches in Windows VHDs

---

test/e2e/kubernetes/scripts/vmss-health-check.sh

This PR updates the `vmss-health-check.sh` test script to better deal with recovering non-succeeded VMSS.
**Notes**:

test: better VMSS recovery in vmss-health-check

---

test/e2e/kubernetes/scripts/vmss-health-check.sh

This PR adds the `vmssCSE` resource to our list of `provisioningState` things to validate when running vmss-health-check during E2E.
**Notes**:

test: check vmssCSE resource w/ VMSS health check

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/scripts/vmss-health-check.sh

This PR adds instance extension checks to the VMSS health check script, as well as waiting longer overall for new nodes to join during large cluster tests.
**Notes**:

test: delete failed vmss extensions, wait longer

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/scripts/vmss-health-check.sh

This PR prints the number of nodes if the desired number of post-vmss-prototype-scaled nodes is not ready in time, and also updates the vmss-health-check script to tolerate transient failures in scale up operations after deleting failed instances.
**Notes**:

test: large cluster post-scale errors

---

docs/topics/clusterdefinitions.md

I think there's a bug in the example for the Calico `logSeverityScreen`. The addon name should be `calico-daemonset` as defined by `common.CalicoAddonName`.
Only with this name I could convince aks-engine to include my customized log level into the ARM template.

docs: fix addon name in Calico `logSeverityScreen` example

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Name resolution fails on Ubuntu 18.04 hosts because `/etc/resolv.conf` is not pointing to the correct name server.
Borrowing this fix: https://github.com/Azure/AgentBaker/blob/5018e82018f31f3b1fb9a26332f4c706b2d9f011/parts/linux/cloud-init/artifacts/cse_config.sh#L238-L253
Related to https://github.com/Azure/AKS/issues/2052
**Notes**:

fix: bypass systemd-resolved but use the resolv.conf it generates

---

pkg/engine/networkinterfaces.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/virtualmachinescalesets_test.go

Enable ipforwarding on agent nic for Azure CNI dualstack scenario. In dualstack, azure cni assigns overlay ipv6 addresses to pod and rely on udr for routing. Enabling ipforwarding is required to route traffic between pods. 
**Notes**:

fix: Enable ipforwarding on agent nic for Azure CNI dualstack scenario

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/service/service.go

In response to recent flakes, this change adds retry tolerance to the "create pod from file if not exist" instances in the E2E test runner.
**Notes**:

test: retry create pod from file if not exist

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

This PR addresses the fact that we can't get valid error responses from kubectl get or delete using the --label argument.
Instead we now get the actual pod name of the init'ed kube-addon-manager, and delete it.
**Notes**:

fix: ensure we delete init kube-addon-manager

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This PR removes the installation of apt packages that depend upon https://repo.iovisor.org in reponse to intermittent unavailability of that endpoint. These packages were implemented on behalf of AKS, which no longer uses aks-engine to maintain that requirement.
**Notes**:

chore: remove iovisor apt dependencies

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

This reverts commit 02770e2feca59d67e4d4c0ba9f61f16ec1cb0d95.
This was suppose to fix some cluster provisioning errors we saw in upstream testing. Details here: https://github.com/Azure/aks-engine/pull/4743#issuecomment-969564923
Unfortunately it is not helping (see https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1462885863762432000) and blocks any other workaround that we might be able to use like restarting the addon manager after the cluster starts up in the windows test extensions
**Notes**:

Revert "fix: ensure we delete init kube-addon-manager (#4743)"

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This is a follow-up from #4744, to ensure that if we are using a VHD built w/ the iovisor apt configuration, we delete that configuration at the beginning of our bootstrap scripts.
**Notes**:

fix: ensure iovisor is not present in apt config

---

parts/k8s/windowsconfigfunc.ps1
pkg/engine/templates_generated.go

The fix which reduces dynamic port usage for non-DSR load balancers is shiped with KB4550969 in April 2020
Update the range to [33000, 65535] to avoid that it conflicts with NodePort range (30000 - 32767)
**Notes**:

fix: Update Windows dynamic port range

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

This PR updates the default version of containerd delivered to containerd-enabled clusters to 1.5.8 for Windows nodes and 1.4.11 for Linux nodes.
**Notes**:

chore: update containerd versions

---

docs/topics/azure-stack.md

Correct statement claiming that CSI drivers are not supported on air-gapped Azure Stack Hub.
**Notes**:

docs: clarify CSI support note on air-gapped ASH

---

parts/k8s/cloud-init/artifacts/cse_customcloud.sh
pkg/engine/templates_generated.go
scripts/collect-logs.sh

Provision logs to include whether the custom cloud login endpoint is reachable during cluster creation. Also test this condition when collecting logs.
We saw a few on-prem clusters misbehaving due to their network security configuration blocking the login endpoint.
**Notes**:

chore: check if custom login endpoint is reachable

---

pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go

This flag was removed in 1.24+  https://github.com/kubernetes/kubernetes/commit/9573b4a6b993aaa2238d347419ffe7c4b8005c94 and windows jobs are failing: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1469025482350530560
**Notes**:

Remove api-server --insecure-port for versions greater than 1.20

---

examples/no_outbound.json
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

This PR updates the nvidia pre-download implementation to copy downloaded .deb files to a directory outside of the apt cache repo directory, to prevent apt from deleting it over time as it maintains the data cache.
This will solve the "airgap" GPU solution, and will also protect against any unexpected environmental changes (e.g., if the pre-downloaded files *do* disappear we will re-download the files at runtime).
**Notes**:

feat: only download nvidia drivers if needed

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Windows: Fix a situation where containers were not stopped if HcsShutdownComputeSystem returned an ERROR_PROC_NOT_FOUND error moby/moby#42613
Docker 20.10.8 contains a fix where windows containers can stay around after they get deleted (aka 'zombie pods') which continue to consume host resources.
https://docs.docker.com/engine/release-notes/#20108 -> Windows: Fix a situation where containers were not stopped if HcsShutdownComputeSystem returned an ERROR_PROC_NOT_FOUND error moby/moby#42613
/cc @AbelHu 
**Notes**:

chore: update docker EE to 20.10.9 for Windows

---

pkg/api/defaults.go
pkg/api/defaults_test.go

This PR addresses an edge case from #4689: Windows nodes do not run hostNetwork pods from any of the available addons, and so those nodes may pre-allocate IPs according to the complete max-pods configuration for a ~accurate estimate of always having enough IP addresses as there will be pods running.
**Notes**:

fix: Azure CNI IP address allocation for win nodes

---

test/e2e/kubernetes/kubernetes_test.go

This test case was added to validate issues with log rotation in Moby (https://github.com/Azure/aks-engine/issues/3573)
The test has become flakey and this is not the proper place to do validation, so we'll remove it.
**Notes**:

ci: removing flaky log rotation test for Windows nodes

---

pkg/api/defaults-kubelet.go
pkg/api/defaults-kubelet_test.go
staging/provisioning/windows/kubeletstart.ps1

Some of the recently deprecated kubelet flags were getting set by the powershell script that starts/runs kubelet.exe on Windows nodes.
This PR updates that logic to only set dockershim specific kubelet flags if usinig dockershim.
Note: We'll need to sign these scripts and create another signed provisioning scripts package
**Notes**:

feat: Updating script used to run kubelet to not set docker-specific kubelet args when using containerd

---

pkg/api/vlabs/validate.go

When `validateImageNameAndGroup()` return nil, the current code returns early which can lead to pretty unexpected behaviour.
**Notes**:

fix: validation for agentpool.imageRef

---

parts/k8s/cloud-init/artifacts/label-nodes.sh
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go

This PR updates the way we idempotently enforce `kubernetes.io/role` node labels. Instead of redoing it blindly every minute forever, we only do it if the required labels aren't present.
The key part of the change is the way we filter out nodes (by label) for labeling. As an example:
Was:
- Filter by nodes with label `kubernetes.azure.com/role!=master,kubernetes.io/role!=master`
- This filter will *always* return a set of non-control-plane-labeled nodes.
Now:
- Filter by nodes with label `kubernetes.azure.com/role=agent,kubernetes.io/role!=agent,node-role.kubernetes.io/agent!=`
- This filter returns nodes that have the `kubernetes.azure.com/role=agent` label (delivered via kubelet config args when node joins cluster), but have the missing or incorrect …

chore: only label nodes with kubernetes.io/role if they need it

---

parts/k8s/addons/aad-pod-identity.yaml
parts/k8s/addons/azure-network-policy.yaml
parts/k8s/addons/azure-policy-deployment.yaml
parts/k8s/addons/calico.yaml
parts/k8s/addons/container-monitoring.yaml
parts/k8s/addons/flannel.yaml
parts/k8s/addons/secrets-store-csi-driver.yaml
parts/k8s/addons/tiller.yaml
pkg/engine/engine.go
pkg/engine/templates_generated.go

Update API Versions for Kubernetes resources. This is due to the deprecation of multiple `v1beta1` API versions for Kubernetes version 1.22+ as describe in this doc (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) .
**Notes**:

fix: update APIVersion for Kubernetes resources

---

cmd/rotate_certs.go
cmd/rotatecerts/operations.go
cmd/rotatecerts/operations_test.go

`rotate-certs` command rotates all SA tokens, even those created by workloads.
**Notes**:

fix: rotate-certs recreates all service account tokens

---

docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml

Updates the API version of Deployments and Daemonsets in the calico-3.3.1-cleanup-after-upgrade.yaml resource.
Refs: #3839
This is @jovieir's change from #3839 that somehow was overlooked. Then, when I went to update the commit message and merge it, somehow I managed to overwrite the branch and close that PR.
Apologies @jovieir! And thanks for your contribution, which I've resurrected here.
**Notes**:

fix: Update calico-3.3.1-cleanup-after-upgrade.yaml

---

cmd/scale.go
cmd/scale_test.go

When there are multiple Windows / Linux agent pools, the scale operation is not selecting the correct agent pool.
For Windows agent pools, the code `vmName[:9] == sc.containerService.Properties.GetAgentVMPrefix(sc.agentPool, winPoolIndex)[:9]` will always be true and thus all Windows agent pools will be mixed in scaling and indexing.
For Linux agent pools, for example if one agentpool is named `linuxpool` and the other agentpool is named `linxpool2`, and scale operation targets `linuxpool`, then code `strings.Contains(vmName, sc.agentPoolToScale)` will also consider VMs from `linuxpool2` are in agentpool `linuxpool`.
https://github.com/Azure/aks-engine/issues/1065
Does this change contain code from or inspired by another …

fix: ensure correct agent pool selection in scale operations

---

cmd/upgrade.go
pkg/api/addons.go
pkg/api/components.go
pkg/api/defaults-kubelet.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/testdata/azurestack/kubernetes-ubuntu16.json
pkg/engine/testdata/azurestack/kubernetes.json

Start Kubernetes 1.21, only external cloud provider is supported on Azure Stack cloud. Adding the logic to enforce that for deploy and upgrade operations.
**Notes**:

chore: force external cloud provider for Kubernetes v1.21+ on Azure Stack Hub

---

test/e2e/config/config.go

This PR removes the uksouth region from the list of regions to build Azure infra in for our E2E test runner after observing failures in that region.
**Notes**:

test: exclude uksouth from test infra regions list

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go

Update external cloud provider logic for windows node to retrieve root certificate from SSL certificate of ARM endpoint
**Notes**:

fix: correctly handle multiple root certificates on Azure Stack Hub windows nodes

---

main.go

AKS Engine [is deprecated](https://github.com/Azure/aks-engine#project-status) and will not support Kubernetes 1.25 or later. This prints a yellow warning to stderr reminding users of that whenever `aks-engine` is run:
Fixes #4342
**Notes**:

docs: print deprecation message to stderr

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

Upgraded `runc` to address CVE-2022-29162. While on it, upgraded `moby` and `containerd` to the latest v1.5 patch.
**Notes**:

chore: upgrade container runtimes

---

test/e2e/runner.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>
**Notes**:

delete minor unreachable code caused by log.Fatal

---

staging/provisioning/windows/hnsremediator.ps1
staging/provisioning/windows/windowsnodereset.ps1

To mitigate a known HNS issue where a HNS crash purges DNS policy on the node leading to DNS resolution failures on hosted Pods
Related PR for AKS - https://github.com/Azure/AgentBaker/pull/2085/files
**Notes**:

Feature: Add hnsremediator for hns crash in Windows nodes

---

vhd/packer/init-variables.sh

By default, Azure storage accounts are public.
Microsoft recommends to disallow public access to a storage account unless the scenario requires it. Disallowing public access helps to prevent data breaches caused by undesired anonymous access. More info: https://azure.microsoft.com/en-gb/updates/choose-to-allow-or-disallow-blob-public-access-on-azure-storage-accounts/
**Notes**:

Ensure VHD storage accounts are private

---

pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go

`linuxProfile.enableUnattendedUpgrades` is not honored nor persisted in the output API Model.
By default, `enableUnattendedUpgrades` is set to `true`. In practice, this bug affected those users that set the value to `false`. In that case, the `false` value was ignored and unattended upgrades were not disabled.
This fix should effectively disable unattended upgrades for those customers that would like to disable it (air-gapped environments most likely).
Issue logged here https://github.com/Azure/aks-engine-azurestack/issues/44

fix: enableUnattendedUpgrades not honored

---

.pipelines/vhd-builder.yaml
packer.mk
parts/k8s/cloud-init/artifacts/cis.sh
pkg/engine/templates_generated.go
vhd/packer/vhd-image-builder-20.04.json
vhd/packer/vhd-image-builder.json

This PR adds a Ubuntu 20.04-LTS Linux VHD build job to the existing Linux VHD pipeline.
Going forward our Linux VHD pipeline will build 2 VHD images: one Ubuntu 18.04-LTS image and one Ubuntu 20.04-LTS image.
Because Ubuntu 20.04-LTS ships with python3 by default, a minor change was needed to accommodate; other than that the existing VHD pipeline worked as-is!
Kudos to @Michael-Sinz for implementing the prerequisite CSE foo for enabling that part of the flow to work.
**Notes**:

add 20.04-LTS VHD image pipeline job

---

parts/k8s/rotate-certs.sh
pkg/engine/templates_generated.go

The rotate certs command was failing on 20.04 environments, Output:
```
cp -p /etc/kubernetes/rotate-certs/certs/kubeconfig /root/.kube/config 
cp: cannot create regular file '/root/.kube/config': No such file or directory
```
The fix specifies the user instead of using ~, works on both 20.04 and 18.04
**Notes**:

fix: rotate certs script breaks on Ubuntu 20.04

---

test/e2e/kubernetes/scripts/sshd-config-validate.sh

The sshd config validation test was failing on 20.04 environments. Output: 
```
Unable to load host key: /etc/ssh/ssh_host_rsa_key 
Unable to load host key: /etc/ssh/ssh_host_dsa_key 
Unable to load host key: /etc/ssh/ssh_host_ecdsa_key 
Unable to load host key: /etc/ssh/ssh_host_ed25519_key 
sshd: no hostkeys available -- exiting.
exit 1
```
The fix greps the sshd config file itself, and works on both 20.04 and 18.04
**Notes**:

test: sshd config validation test on 20.04

---

cmd/upgrade.go
pkg/api/defaults.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/armhelpers/httpMockClient.go
pkg/armhelpers/support_validator.go

Only impacts Azure Stack Hub
- force overwrite from docker to containerd for upgrade
- set containerd as default container runtime for deploy/generate
- add unit test
- fix validate windows image on ash stamps
**Notes**:

chore: force containerd runtime for Kubernetes v1.24+ on Azure Stack Hub

---

pkg/api/azenvtypes.go
pkg/api/azenvtypes_test.go

This PR updates the mooncake configuration for nvidia driver image pull downloads to use the default `mcr.microsoft.com` container image registry.
Fixes #5034 
**Notes**:

fix: use mcr.microsoft.com for nvidia in mooncake

---

.pipelines/e2e-job-template.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder.yaml

Updates the `vmImage` used in aks-engine Azure DevOps jobs to Ubuntu 20.04, to avoid warnings (and brownout errors) about 18.04 EOL.
**Notes**:

Update pipeline image to Ubuntu 20.04

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json
examples/kubernetes-gpu/kubernetes.json

This PR replaces Standard_D2_v3 with Standard_B2s for the key cluster configurations that we test using E2E automation.
**Notes**:

use Standard_B2s as baseline SKU for test clusters

---

.pipelines/vhd-build-publish-windows.yaml
.pipelines/vhd-builder-windows.yaml

Docker VHD is deprecated, removes the test build to get rid of failures in PRs
> azure-arm: Find-Package : No match was found for the specified search criteria and package name 'Docker'
**Notes**:

Remove Windows Docker VHD build check

---

.github/workflows/release.yaml
examples/e2e-tests/kubernetes/release/default/definition.json

This is a response to [failures](https://github.com/Azure/aks-engine/actions/runs/6028364459/job/16355530809) in the v0.79.0 release pipeline.

chore: use only v1.24 for release gates
