Azure/aks-engine

pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go
**What this PR does / why we need it**: Ensuring that the Windows implementation of accelerated networking also includes the guards against upgrade and scale, and actually added unit tests.
```
accelerated networking rationalization, with tests
```
=> accelerated networking rationalization, with tests

pkg/helpers/azureconst.go
Parallel PR: https://github.com/Azure/acs-engine/pull/4265/files
=> add support PB6 vm skus

pkg/helpers/azureconst_test.go
Updating azure const unit test to reflect the latest list of VM skus that we support
=> update azure_const unit test

.vsts-ci.yaml
**What this PR does / why we need it**:  https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#hosted-linux-preview-pool-deprecation
```release-note
```
=> VSTS VHD pipeline hosted ubuntu pool

.circleci/config.yml, parts/k8s/artifacts/kubernetesazurekms.service
**What this PR does / why we need it**: Fix issue caused by updating azure.json
Details for the fix: Azure/kubernetes-kms#37
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes Azure/aks-engine#49
```
Fix issue caused by updating azure.json
```
=> Fix issue caused by updating azure.json

parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml, parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
**What this PR does / why we need it**: enables Typha for Calico and also adds a horizontal autoscaler for it
Copied from https://github.com/Azure/acs-engine/pull/4290
```
enable typha and add horizontal autoscaler
```
=> enable typha and add horizontal autoscaler

packer/install-dependencies.sh
**What this PR does / why we need it**: Add back missing unbound variable `DOCKER_ENGINE_REPO`.
```release-note
```
=> Fix docker-engine install in VHD pipeline

packer/install-dependencies.sh
**What this PR does / why we need it**: This got lost in the rebase race to master of all the recent versions.
```
Include 1.11.5 in VHD spec
```
=> Include 1.11.5 in VHD spec

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Includes the addition of k8s 1.11.5 pre-baked into the VHD.
```
update to 2018.12.03 VHDs
```
=> update to 2018.12.03 VHDs

parts/k8s/kubernetesinstalls.sh
**What this PR does / why we need it**: Rather than permissively install latest moby, let's explicitly 
```
install explicit moby version
```
=> install explicit moby version

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Fix missing defauld cloud spec distro for AKSDockerEngine distro. https://github.com/Azure/acs-engine/issues/4347
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #114 
```release-note
```
=> Add AKSDockerEngine default for sovereign clouds

README.md, docs/faq.md
Gotta have a FAQ. This should hopefully address some common questions we've heard during the project transition, in particular.
**Which issue this PR fixes**:
Fixes #96 
```release-note
Add a FAQ and link to it from the README
```
=> Add a FAQ and link to it from the README

docs/kubernetes/k8s-developers.md
Improve docs for k8s/hyperkube testing using aks-engine
=> improve documentation for testing custom hyperkube images on aks-engine

docs/kubernetes/features.md, examples/kubernetes-config/kubernetes-keyvault-encryption.json, parts/k8s/artifacts/kubernetesazurekms.service, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/types.go, pkg/api/vlabs/types.go, pkg/engine/params_k8s.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/Azure/acs-engine/issues/4152
```release-note
Add HSM support for kms encryption, create Premium SKU Key Vault and RSA-HSM type key.
```
=> Add HSM support for kms encryption

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Adds Azure CNI 1.0.15
```release-note
```
=> Update VHD version to 2018.12.12

docs/kubernetes/features.md, examples/kubernetes-config/kubernetes-keyvault-encryption.json, parts/k8s/artifacts/kubernetesazurekms.service, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/types.go, pkg/api/vlabs/types.go, pkg/engine/params_k8s.go
This reverts #128 since the jenkins standardLB e2e tests were failing
=> Revert "Add hsm support for kms plugin (#128)"

.circleci/config.yml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.17.4
Just keeping in sync with AKS which now uses this version, so we avoid linter disagreements mostly.
```release-note
NONE
```
=> Update go-dev tools image

examples/addons/cluster-autoscaler/README.md, parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, pkg/api/addons.go
=> make cluster autoscaler scan interval configurable

docs/faq.md
**What this PR does / why we need it**: Remove text about aks-engine not having a release in preparation for upcoming release.
```release-note
```
=> Update FAQ to account for 0.27.0 release

parts/k8s/kubernetesagentcustomdata.yml, pkg/api/const.go, pkg/api/defaults-kubelet.go, pkg/api/defaults-kubelet_test.go, pkg/api/types.go, pkg/engine/artifacts.go, pkg/engine/template_generator.go
**What this PR does / why we need it**: Enable folks to disable ip-masq-agent and use the previous SNAT implementation
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #160
```
Allow for disabling ip-masq-agent
```
=> Allow for disabling ip-masq-agent

docs/kubernetes/scale.md
This PR adds 2 parameters in the Scale documentation: "auth-method" and "language". It might be useful to know you can specify SP Client ID/Secret or use a Certificate when scaling a cluster.
It also removes a small typo.
```release-note
```
=> Docs: Added auth-method in scale.md and Removed a typo.

packer/install-dependencies.sh
```
add k8s 1.10.12 to vhd
```
=> add k8s 1.10.12 to vhd

pkg/api/azenvtypes.go
**What this PR does / why we need it**: Use the new VHD image that includes k8s v1.10.12
```
2018.12.19 VHD image w/ 1.10.12
```
=> 2018.12.19 VHD image w/ 1.10.12

docs/clusterdefinition.md, docs/custom-vnet.md, examples/addons/cluster-autoscaler/kubernetes-cluster-autoscaler.json, pkg/engine/testdata/addons/kubernetes.json
=> docs: update some docs with the right information

docs/kubernetes/windows.md
FIx the broken link to Kubernetes latest release notes in Windows walkthrough document.
Fixes #150 
**Notes**:
=> docs: Fix Kubernetes release notes broken link

parts/k8s/kubernetesinstalls.sh
Use the latest published version of `img` for the binary we put on the node vms.
**Notes**:
=> feat: update img binary to v0.5.6

README.md
follow-up on #253 based on one of @jackfrancis's feedback that somehow got lost in a rebase. Sorry!
=> docs: add note on AKS-Engine and AKS relationship

.github/config.yml
Adds a bot to welcome new contributors for first issue/PR/commit :) 
**Notes**:
=> chore: add config for welcome bot

docs/README.md
**Reason for Change**: Fix docs link to howto/README.md
**Notes**:
=> docs: Fix docs link to howto/README.md

pkg/api/azenvtypes.go
New VHD includes:
- k8s 1.13.2
- addon-resizer 1.8.4
- etcd 3.2.25
- kube-dns 1.15.0
- heapster 1.5.4
- tiller 2.11.0
- blobfuse-flexvolume 1.0.7
Fixes #288 
**Notes**:
=> feat: update VHD version to 2019.01.11

.chglog/CHANGELOG.tpl.md, .chglog/config.yml
Updates the [`git-chglog`](https://github.com/git-chglog/git-chglog) configuration file to help with producing aks-engine release notes. See [v0.29.0](https://github.com/Azure/aks-engine/releases/tag/v0.29.0) for example.
**Notes**:
=> chore: update git-chglog configuration for releases

parts/k8s/kubernetesmasterresources.t
=> fix: the number of probes is of type int32 and not string

examples/cosmos-etcd/readme.md
Updates cosmos documentation with private preview signup page.
fixes: https://github.com/Azure/aks-engine/issues/329
=> update cosmos link

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
Refer to these links for more info:
https://github.com/deis/docker-go-dev/pull/151
https://groups.google.com/forum/m/#!topic/golang-announce/mVeX35iXuSw
=> chore: use the latest docker go dev image

pkg/api/k8s_versions_test.go
=> test: add k8s components versions test 1.13

examples/README.md
We should keep the `examples/` README short and sweet, so there aren't multiple documentation landing pages we need to maintain that are effectively manually curated TOCs.
**Notes**:
=> doc: fix broken links in examples README

docs/topics/README.md, docs/topics/sgx.md
Adding documentation to already merged feature
"Related to #317, #318"
- [X ] includes documentation
**Notes**:
=> docs: SGX support with Kubernetes

docs/tutorials/deploy.md
=> docs: Fix CLI parameters

parts/k8s/kubernetescustomscript.sh, parts/k8s/kubernetesinstalls.sh
Cleaning up docker images in the background before installing docker can cause a race condition with docker install if we need to change the version of moby installed.
**Notes**:
=> fix: prevent race condition with docker/moby install

pkg/api/azenvtypes.go
New VHD image including K8s 1.11.7, 1.12.5 and 1.13.3.
**Notes**:
=> feat: update VHD image to 2019.02.06

packer/install-dependencies.sh, parts/k8s/artifacts/kubernetesazurekms.service
- Move the kms container image from docker hub to mcr
- Bump version
**Notes**:
=> fix: update kms container image

packer/install-dependencies.sh, pkg/api/addons.go, pkg/api/defaults_test.go
bump version for keyvault-flexvolume
**Notes**:
=> fix: bump version for keyvault-flexvolume

pkg/api/azenvtypes.go
Includes Moby 3.0.4 to help address CVE-2019-5736 (runc container breakout).
**Notes**:
=> feat: update VHD image to 2019.02.12

pkg/api/convertertoapi_test.go
=> ci: fix failing unit test in master

docs/topics/clusterdefinitions.md, pkg/api/defaults-apiserver.go, pkg/api/defaults-apiserver_test.go
Remove `repair-malformed-updates` deprecated flag
Fixes #490 
**Notes**:
=> fix: remove repair-malformed-updates deprecated flag

cmd/doc.go, pkg/api/agentPoolOnlyApi/v20170831/doc.go, pkg/api/agentPoolOnlyApi/v20180331/doc.go, pkg/api/agentPoolOnlyApi/vlabs/doc.go, pkg/api/common/doc.go, pkg/api/doc.go, pkg/api/v20160330/doc.go, pkg/api/v20160930/doc.go, pkg/api/v20170131/doc.go, pkg/api/v20170701/doc.go, pkg/api/v20170930/doc.go, pkg/api/vlabs/doc.go, pkg/armhelpers/doc.go, pkg/engine/doc.go, pkg/i18n/doc.go, pkg/operations/dcosupgrade/doc.go, pkg/operations/kubernetesupgrade/doc.go
Add missing godoc comments on packages where missing
fix #29
=> docs: adding godoc package comments

packer/install-dependencies.sh, pkg/api/addons.go, pkg/api/defaults_test.go
fix: upgrade blobfuse version for bug fix, related bug:
https://github.com/Azure/kubernetes-volume-drivers/issues/9
**Notes**:
fix: upgrade blobfuse version for bug fix
=> fix: upgrade blobfuse version for bug fix

pkg/api/azenvtypes.go
This new VHD image includes 1.10.13 pre-baked
**Notes**:
=> chore: update AKS VHD images to 2019.02.13

pkg/api/types.go
Flannel uses VXLAN encapsulation... so using route table makes no sense...
**Notes**:
Trivial and obvious low hanging fruit.
=> fix: do not create route table when using flannel

pkg/api/types.go
Follow up from #529 
Fixes the `HasZonesForAllAgentPools()` func so that it works in masters-only scenarios
**Notes**:
=> chore: fix HasZonesForAllAgentPools() for masters-only scenarios

.gitignore
Re-adding to `.gitignore` previously ignored file references, to unblock back-compat stories.
E.g.:
- checkout an old commit and compile/generate
- checkout current commit and compile/generate
- this is broken because compile+link detects that there are multiple references, from the previous build generation
See this thread:
https://github.com/Azure/aks-engine/commit/25915938f2c3bccd7fc4dcd4c9185641cbc935cc
**Notes**:
=> chore: ignore artifacts that may be present from prior commits

parts/k8s/kubernetesinstalls.sh
- htop
- iotop
- iftop
- sysstat
=> chore: add administration tools

test/e2e/kubernetes/kubernetes_test.go
We implement the following algorithm when assessing for pod readiness in our E2E tests:
- wait for _n_ Ready reponses
- keep track of non-Ready responses as _f_
- if/when _f_ reaches a count that equals the desired _n_ count before we have tracked the desired Ready responses, return a failure response, as we interpret that to mean that the pod may be thrashing between Ready and non-Ready
(The above algorithm is only implemented if _n_ is greater than 1. If _n_ is 1 then we simply wait for a single Ready response in a given timeout interval.)
In order to eliminate false positive signals due to "normal" operational pod reconciliation, we should wait longer if we get a non-Ready signal, and allow the k8s control plane more time to reconcile the pod into a consistent …
=> test: wait longer when incrementing error count waiting for pod Ready

docs/tutorials/quickstart.md
Explains how macOS users can install AKS Engine with `brew install Azure/aks-engine/aks-engine`.
See also https://github.com/Azure/homebrew-aks-engine
Fixes #227
**Notes**:
=> docs: add how to install aks-engine with Homebrew

parts/k8s/kubernetesinstalls.sh
…by versions if needed
Moby version downgrade scenario is broken currently.
Fixes #568 
**Notes**:
=> Fix: To enable downgrading Moby version from what has been pre-provisioned in the VHD Image

packer/install-dependencies.sh, pkg/api/common/versions.go
Release notes here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#v1126
**Notes**:
=> chore: enable Kubernetes v1.12.6

pkg/api/common/versions.go
Release notes here:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#v1140-beta1
**Notes**:
=> chore: enable Kubernetes v1.14.0-beta.1

cmd/scale.go, pkg/api/defaults_test.go, pkg/api/vlabs/types_test.go, pkg/api/vlabs/validate_test.go, pkg/armhelpers/compute.go, pkg/armhelpers/utils/util_test.go
Align all comments and log message casing from vmss to VMSS
=> chore: align vmss casing to VMSS

pkg/api/azenvtypes.go
Includes Kubernetes v1.12.6 and overlay2fs for docker-engine VHD.
The full functional changeset:
- https://github.com/Azure/aks-engine/commit/9f41e73eb6aab8681e3ab6cceb4eb8c9019d5fb0#diff-62ed5765f6aaf1d428746b3d7b597100
- https://github.com/Azure/aks-engine/commit/1d979960996dd2d07d5f9efd417bc0be8772a32b#diff-62ed5765f6aaf1d428746b3d7b597100
- https://github.com/Azure/aks-engine/commit/e2cf6ae765b63b56610f689a2a6fd0d0082eda48#diff-62ed5765f6aaf1d428746b3d7b597100
- https://github.com/Azure/aks-engine/commit/ffa6556cebe7e4d76747561cc4b6727564644251#diff-62ed5765f6aaf1d428746b3d7b597100
- https://github.com/Azure/aks-engine/commit/9b07e9ac9132b9a9b97e44ba66fee2a773ab850f#diff-62ed5765f6aaf1d428746b3d7b597100
**Notes**:
=> chore: update VHD reference to 2019.02.26

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
Makes the `go-dev` image about 2GB smaller, which should speed up development and CI a bit.
See https://github.com/deis/docker-go-dev/releases/tag/v1.18.6
Related: #603
**Notes**:
=> chore: update go-dev image

pkg/api/azenvtypes.go
Contains Kubernetes 1.11.8, 1.12.6, and 1.13.4 hyperkube images.
**Notes**:
=> chore: update VHD reference to 2019.02.28

pkg/api/common/const.go
=> feat: default to Kubernetes 1.11

pkg/helpers/azureconst_test.go
Add unit tests to increase overall code coverage
=> test: add unit tests for azureconst.go

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
Changes include
i) Go 1.12
ii) Golangci-lint v1.15.0
iii) Kubectl v1.10.13
=> chore: update the deis docker go-dev image to v1.19.1

OWNERS
Add @serbrech to OWNERS file for PR approval.
=> chore: add serbrech to OWNERS

examples/e2e-tests/kubernetes/windows/hybrid/definition.json
We want to default enableAutomaticUpdates to false for Windows agent pools. Updating the api model we use to run regular PR tests will give us some test signal as to any unintended side-effects of doing so.
**Notes**:
=> chore: update hybrid api model to "enableAutomaticUpdates": false

README.md
Add PR E2E pipeline status badge to README.
**Notes**:
=> ci: add E2E pipeline status to README

docs/topics/upgrade.md
Documents the new `--force` flag for the upgrade command
documentation for #522 #525 
=> docs: upgrade --force

pkg/armhelpers/utils/util.go, pkg/engine/doc.go, pkg/engine/transform/doc.go, pkg/helpers/doc.go, pkg/operations/doc.go, pkg/test/util.go
Improve package documentation of aks-engine.
=> docs: add more package documentation for aks-engine's godoc

docs/community/developer-guide.md
Include a reference to the new "comment to trigger the pipeline" feature soon to be enabled on the E2E pipeline.
**Notes**:
=> docs: update E2E pipeline process in developer docs

packer/install-dependencies.sh
#630 went in yesterday around the same time that release notes got added, adding the package to list of installs.
**Notes**:
=> chore: add systemd/xenial-proposed to list of installed packages in VHD notes

README.md
Finally a green badge on our README 🍏 
**Notes**:
=> chore: add go report card badge to README

README.md
Change the status badge to the AKS Engine CI E2E pipeline since we separated pipelines into pr-e2e and ci-e2e
**Notes**:
=> ci: update build status badge to ci pipeline

parts/k8s/kubernetesinstalls.sh
When using "ubuntu" distro the systemd/proposed install of the following version isn't working:
`229-4ubuntu21.17`
Deployments yield:
```
Error from deployment for kubernetes-southcentralus-76873 in resource group kubernetes-southcentralus-76873:exit status 1
2019/03/06 19:42:35 Command Output: ERROR: Deployment failed. Correlation ID: e80bf0f6-b582-4161-bf55-8ca50b22bb33. {
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"details": [
{
"code": "VMExtensionProvisioningError",
"message": "VM has reported a failure when processing extension 'vmssCSE'. Error message: \"Enable failed: failed to execute command: command terminated with exit …
```
=> fix: enable systemd proposed implementation for non-VHD scenario

pkg/engine/virtualmachinescalesets_test.go
Follow-up from #684
**Notes**:
=> test: fix template refactor unit tests

pkg/engine/armvariables.go, pkg/engine/cosmosdb.go, pkg/engine/cosmosdb_test.go, pkg/engine/masterarmresources.go
No_template implementation of CosmosDB Etcd
=> fix: implement cosmosEtcd no_template

Makefile, releases/Dockerfile.linux, releases/README.Dockerfile.md
Adds `make build-container` to simplify running the command in releases/README.Dockerfile.md and does some minor cleanup of the Dockerfile.
**Notes**:
Yes, I know this makes the **image**, not the **container**. But `make build-image` sounded too ambiguous, and I didn't want to mention Docker specifically. Suggestions welcome.
=> build: add "build-container" target

pkg/api/apiloader.go, pkg/api/apiloader_test.go
=> test: add unit tests for pkg/api/LoadDefaultContainerServiceProperties()

docs/topics/gpu.md
Updating GPU doc, #634 updated the driver version
=> docs: update docs for NVIDIA driver version

docs/tutorials/quickstart.md
Explains how to install `aks-engine` with the Windows package manager Chocolatey. All thanks goes to @synax for maintaining and publishing this!
Fixes #652
**Notes**:
=> docs: add how to install aks-engine with Chocolatey

cmd/scale.go
=> fix: fix the typo in the scale cmd logs

pkg/api/vlabs/validate.go
=> style: add some golint style simplications to validate.go

pkg/api/apiloader.go, pkg/api/apiloader_test.go, pkg/api/types_test.go
add failure condition unit test for LoadContainerServiceFromFile and tests for DeserializeContainerService
**Notes**:
=> test: more apiloader unit tests

pkg/engine/artifacts.go, pkg/engine/params_k8s.go
Removes remaining elb artifacts in private cluster. Related to: #487 .
**Notes**:
=> fix: removed unnecessary elb artifacts when PrivateCluster is enabled

packer/install-dependencies.sh, parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesinstalls.sh, parts/k8s/kubernetesmastercustomdata.yml
systemd systemd 229-4ubuntu21.17 has graduated and the systemd/xenial-proposed package no longer exists. https://launchpad.net/ubuntu/+source/systemd/229-4ubuntu21.17. Reverts #630.
This is the output from a freshly built Ubuntu 16.04 VM (without the proposed systemd install):
```
sudo dpkg -l | grep systemd
ii  libpam-systemd:amd64                 229-4ubuntu21.17                           amd64        system and service manager - PAM module
ii  libsystemd0:amd64                    229-4ubuntu21.17                           amd64        systemd utility library
ii  python3-systemd                      231-2build1                                amd64        Python 3 bindings for systemd
ii  systemd                              229-4ubuntu21.17 …
```
=> revert: remove systemd/xenial-proposed install

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1140-beta1
**Notes**:
=> chore: enable Kubernetes v1.14.0-beta.2

pkg/engine/armtype.go
Adding godoc to the publicly exposed types :).
=> style: add godoc to the armtype structs used in the template refactor

pkg/engine/armresources.go, pkg/engine/armresources_test.go, pkg/engine/virtualmachinescalesets.go
=> test: add more unit tests for no_template refactor

pkg/engine/engine.go, pkg/engine/engine_test.go
More unit tests for the `engine` package.
=> test: add unit tests for engine.go

pkg/engine/engine.go, pkg/engine/engine_test.go
=> Revert "test: add unit tests for engine.go"

.circleci/config.yml, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.19.2
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.1
**Notes**:
I enabled this version in Jenkins CI already.
=> chore: update go toolchain to 1.12.1

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604-201903_2019.03.15.txt, releases/vhd-notes/aks-ubuntu-1604-docker-engine_2019.03.15.txt
This VHD contains a new release of walinuxagent.
**Notes**:
=> chore: update AKS distro version to 2019.03.15

cmd/get_versions.go, cmd/orchestrators.go, cmd/scale.go, cmd/upgrade.go, pkg/api/agentPoolOnlyApi/v20170831/validate.go, pkg/api/agentPoolOnlyApi/v20180331/validate.go, pkg/api/agentPoolOnlyApi/vlabs/validate.go, pkg/api/orchestrators.go, pkg/api/strictjson_test.go, pkg/api/types.go, pkg/api/v20170701/validate.go, pkg/api/vlabs/validate.go, pkg/armhelpers/utils/util.go, pkg/engine/armvariables.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/params.go, test/e2e/config/config.go, test/e2e/engine/template.go, test/e2e/kubernetes/pod/pod.go, test/e2e/metrics/metrics.go
Increases the legibility of some code.
The [`gocritic`](https://github.com/go-critic/go-critic) linter suggests a lot of refactorings I don't think we would want to pursue, so I didn't enable it in our golangci-lint configuration.
**Notes**:
=> style: refactorings suggested by the gocritic linter

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1140-beta2
**Notes**:
=> chore: enable Kubernetes v1.14.0-rc.1

docs/topics/upgrade.md
Fixing language on upgrade docs
=> docs: Fix language on upgrade.md

pkg/engine/armvariables.go, pkg/engine/masterarmresources.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachinescalesets.go
More nil checks! One can never be too safe!
=> fix: add more kubernetesConfig nil checks to account for more resilience

pkg/engine/params_k8s.go
Holding onto dear life with nil checks
=> fix: add nil checks before accessing the service principal profile

pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
=> style: fix some linting issues in api/validate

pkg/engine/systemroleassignments.go, pkg/engine/systemroleassignments_test.go
Missing "right paren" in ARM expression results in ARM template validation error.
Fixes #868
**Notes**:
=> fix: add missing right paren in ARM expression

parts/k8s/kubernetescustomscript.sh, pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604-201903_2019.03.25.txt, releases/vhd-notes/aks-ubuntu-1604-docker-engine_2019.03.25.txt, releases/vhd-notes/aks-ubuntu-1804-201901_2019.03.25.txt
Enable new VHD image. See release notes for details.
Fixes #761
**Notes**:
=> chore: enable 2019.03.25 VHD image

pkg/engine/systemroleassignments.go, pkg/engine/systemroleassignments_test.go
This fixes a discrepancy between the old template and refactor versions for VMAS masters.
=> fix: user contributor role for Master VMAS role assignments

OWNERS
It has truly been a pleasure :).
=> chore: remove tariq1890 from the OWNERS list

packer/vhd-image-builder.json, parts/k8s/kubernetescustomscript.sh
=> fix: remove packer user

docs/tutorials/quickstart.md
fixed type -> change _ to - in filename
**Notes**:
=> fixed typo

docs/topics/windows.md
docs: cleans up example docs
**Notes**:
=> docs: Cleaned up examples

docs/tutorials/quickstart.md
Follows up #914 to make the script have the same name locally as it does in the repository.
**Notes**:
=> docs: rename local download script name to match remote

parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetescustomscript.sh, parts/k8s/kubernetesinstalls.sh, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/kubernetesprovisionsource.sh
- Remove apt locks with unattended-upgrade
- Upgrade OS at first boot
- Improve CSE execution duration
Fixes #869
=> perf: improve CSE script

examples/kubernetes-releases/kubernetes1.13.json
Added 1.13 example to match the rest of the examples
**Notes**:
=> Added Kubernetes 1.13

examples/windows/README.md
Those files don't exist anymore and appear to be rolled into the windows.md
**Notes**:
=> Removed dead links

docs/community/release-checklist.md
Improve release process docs
**Notes**:
=> docs: generate all shasum strings with a one-liner

packer/install-dependencies.sh, pkg/api/const.go
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.18
**Notes**:
=> chore: update Azure CNI version to v1.0.18

test/e2e/kubernetes/kubernetes_test.go
=> test: skip dns-liveness restarts check for k8s 1.14

examples/largeclusters/README.md
Cleans up old example documentation referencing DC/OS and Swarm and fixes a link to the api model.
Fixes #932
**Notes**:
=> docs: fix reference to large cluster api model

examples/windows/README.md
#929 removed the link to the windows binary doc because the link didn't exist anymore. Re-add the guide we correct updated link.
**Notes**:
=> docs: re-add windows binaries doc link

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/workloads/pvc-standard.yaml
This enables non-premium VM SKUs to use this test spec
**Notes**:
=> test: use managed-standard storage class for pvc test

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.03.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.03.txt
This VHD enables GPU + moby scenarios.
**Notes**:
=> chore: enable 2019.04.03 VHD versions

.pipelines/e2e-job-template.yaml, .pipelines/e2e-step-template.yaml
This is to allow re-running individual jobs without the published artifact names colliding.
**Notes**:
=> ci: add timestamp to artifact names

parts/k8s/kubernetesconfigs.sh
AKS will have to integrate changes from #454 distinctly. This PR will enable AKS to do so.
**Notes**:
=> chore: only use new calico CSE config for AKS Engine

packer/install-dependencies.sh
Removes an apparently redundant command from the VHD builder script.
**Notes**:
=> style: remove extra pullContainerImage command

scripts/azure-const.sh
Double quote to prevent globbing.
=> refactor: avoid shell globbing

pkg/operations/kubernetesupgrade/upgradeagentnode.go, pkg/operations/kubernetesupgrade/upgradecluster.go, pkg/operations/kubernetesupgrade/upgradecluster_test.go, pkg/operations/kubernetesupgrade/upgrademasternode.go, pkg/operations/kubernetesupgrade/upgrader.go
=> fix: handle uppercase letters in VM names in upgrade

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1140
**Notes**:
=> feat: add support for Kubernetes 1.14.1

.pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.21.0
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.2
**Notes**:
I already set this go-dev image as the default in our Jenkins instance. 🤞
=> chore: update go toolchain to 1.12.2

docs/community/release-checklist.md
`git clean -fdx` is more destructive than necessary before building release artifacts, so use `make info` as a sanity check instead.
**Notes**:
=> docs: use "make info" as preflight release check

cmd/deploy.go, cmd/scale.go, cmd/upgrade.go, parts/k8s/kubernetesagentcustomdata.yml, parts/k8s/kubernetesmastercustomdata.yml, parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml, pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/converterfromapi.go, pkg/api/convertertoapi.go, pkg/api/defaults-custom-cloud-profile.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/types.go, pkg/api/types_test.go, pkg/api/vlabs/const.go, pkg/api/vlabs/types.go, pkg/api/vlabs/types_test.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/testdata/azurestack/kubernetes.json
feat: retrieve endpoints from metadata endpoint for Azure Stack
**Notes**:
=> feat: retrieve endpoints from metadata endpoint for Azure Stack

.pipelines/pr-e2e.yaml, examples/ubuntu-1804/kubernetes.json
Add a job in pr-e2e for ubuntu 18.04 to ensure we don't regress 18.04 functionality in PRs.
**Notes**:
=> test: add ubuntu 18.04 job to pr-e2e

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.08.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.08.txt
This VHD adds k8s 1.14.1 and revs nvidia drivers to 418.40.04
**Notes**:
=> chore: enable 2019.04.08 VHD versions

examples/kubernetes-zones/README.md
=> docs: fix a command

docs/topics/sgx.md, parts/k8s/kubernetescustomscript.sh
Added documentation for supporting Ubuntu 18.04 on DC-series VMs (ACC)
Cleaned up driver installation steps
Related to #317
**Notes**:
=> docs: add documentation for ACC agent pools running Ubuntu 18.04

cmd/root.go, pkg/api/types.go, pkg/api/types_test.go, pkg/armhelpers/azurestack/compute.go, pkg/armhelpers/azurestack/compute_test.go, pkg/armhelpers/azurestack/deployment_test.go, pkg/armhelpers/azurestack/disk_test.go, pkg/armhelpers/azurestack/graph.go, pkg/armhelpers/azurestack/httpMockClient.go, pkg/armhelpers/azurestack/msi.go, pkg/armhelpers/azurestack/network_test.go, pkg/armhelpers/azurestack/resultPageClient.go, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/template_generator.go
Fix issue #963
#963
**Notes**:
=> refactor: return error instead of invoking log.Fatal

pkg/engine/armvariables.go
Follow-up from #996, fixes a post-rebase bug.
**Notes**:
=> fix: GetKubernetesB64ConfigsCustomCloud rebase errata

parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh
Run `apt-get dist-upgrade` after `apt-get update` on "full install" scenarios (e.g., VHD or base image)
Fixes #974
**Notes**:
=> chore: run apt-get dist-upgrade during VHD or for base OS image distro

cmd/deploy.go, cmd/scale.go, cmd/upgrade.go, pkg/api/defaults-custom-cloud-profile.go, pkg/api/defaults_test.go
fix generate command for Azure Stack
**Notes**:
=> fix: fix generate command for Azure Stack

packer/cleanup-vhd.sh, packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cis.sh
CIS 4.2.4 Ensure permissions on all logfiles are configured 
Fixes #1012 
**Notes**:
=> chore(CIS): Ensure permissions on all log files are configured

parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
This saves > 25% against the payload of this yaml
Also includes a reference to `docker.io/cilium/operator:v1.4` instead of `docker.io/cilium/operator:latest` as per @skinny 
**Notes**:
=> chore: remove comments from cilium addons spec

parts/k8s/cloud-init/artifacts/kubelet.service, test/e2e/kubernetes/scripts/net-config-validate.sh
Reverts Azure/aks-engine#1073
Fixes #1092
=> revert: "fix: make conntrack more liberal on packets"

parts/k8s/cloud-init/artifacts/modprobe-CIS.conf, test/e2e/kubernetes/scripts/modprobe-config-validate.sh
Adds additional modprobe blacklisting for non-essential file systems.
Fixes #965
**Notes**:
=> chore(CIS): kernel module hardening for non-essential filesystem types

parts/k8s/cloud-init/artifacts/cis.sh, test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Harden grub.cfg file permissions
Fixes #979
**Notes**:
=> chore(CIS): harden grub.cfg file permissions

.pipelines/pr-e2e.yaml
In practice the coreos E2E tests are rather flaky, so let's test them out-of-band instead of as a gate in front of PR progress to master.
**Notes**:
=> test: disable coreos scenario as PR E2E gate

parts/k8s/cloud-init/artifacts/etc-issue, parts/k8s/cloud-init/artifacts/etc-issue.net
Add newlines to make things look nicer. From:
```
$ ssh -A -i _output/kubernetes-westus2-70830-ssh azureuser@kubernetes-westus2-70830.westus2.cloudapp.azure.com
Authorized uses only. All activity may be monitored and reported.Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1041-azure x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
Get cloud support with Ubuntu Advantage Cloud Guest:
http://www.ubuntu.com/business/services/cloud
0 packages can be updated.
0 updates are security updates.
New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```
To:
```
$ ssh -A -i _output/kubernetes-westus2-17862-ssh …
```
=> chore: add newlines to login banner message

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
Adds the same "check google.com in case" functionality for Windows outbound test to match the Linux outbound test.
**Notes**:
=> test: fallback google.com check for Windows outbound test

docs/community/developer-guide.md
=> docs: add makedev.ps1 to doc

docs/topics/features.md
fixed a limit that changed over time
Docs: https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#azure-resource-manager-virtual-networking-limits
**Notes**:
=> docs: fix IPs per vnet limit documented

parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh
Remove the installs for containerd and clear containers during CSE when that cluster does not need them. These are pre-installed as part of the VHD.
Fixes #1091 
**Notes**:
=> chore: clean up containerd and cc-runtime when unused

parts/k8s/cloud-init/nodecustomdata.yml
fix: set correct master FQDN for Azure Stack
**Notes**:
=> fix: set correct master FQDN for Azure Stack

packer/vhd-image-builder.json, parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/profile-d-cis.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/const.go, test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Enforces more secure umask by default
Fixes #1021
**Notes**:
=> chore(CIS): set umask to 027 for ubuntu

packer/vhd-image-builder.json, parts/k8s/cloud-init/artifacts/pam-d-common-auth, parts/k8s/cloud-init/artifacts/pam-d-common-password, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/const.go, test/e2e/kubernetes/scripts/cloud-init-files-validate.sh
Enforces CIS password recommendations:
- Ensure lockout for failed password attempts is configured
- Ensure password reuse is limited
Fixes #1017 Fixes #1018
**Notes**:
=> chore(CIS): pam.d password enforcement

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml
\t is messing up unit tests
**Notes**:
=> fix: replace \t with nothing

docs/topics/calico-3.3.1-cleanup-after-upgrade.yaml, docs/topics/features.md
Add guides for calico cleanup after upgrading to v3.5.
Fixes #908.
**Notes**:
=> docs: Add guides for calico cleanup after upgrading to v3.5

Makefile
`make clean` by tradition should clean up all generated and temporary files. This adds some droppings that were missed.
**Notes**:
=> fix: clean generated and unit test helper files

.codecov/codecov.yml
Adds some mock implementations and test code to codecov's exclusion list.
**Notes**:
=> ci: exclude some test files from coverage report

parts/k8s/cloud-init/artifacts/cis.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, test/e2e/kubernetes/scripts/cloud-init-files-validate.sh, test/e2e/kubernetes/scripts/pwquality-validate.sh
Enable opinionated password expiration configuration:
- password max days expiration = 90 days
- password minimum days requirement = 7 days
- inactive passwords locked at 30 days
Enforce `0600` file mode configuration for cron-related files.
Fixes #1019
Fixes #1014 
Fixes #1020
**Notes**:
=> chore(CIS): password expiration, cron file mode enforcement

pkg/api/azenvtypes.go, test/e2e/kubernetes/kubernetes_test.go
Includes the introduction of some new tests to validate recently introduced CIS-related configuration built into the VHD.
**Notes**:
=> chore: enable 2019.04.24 VHD images

pkg/engine/vmextensions_test.go
Follow up from #1133, use the master branch to get the extension templates for unit tests now that the apiversion changes have merged to master.
**Notes**:
=> test: use master branch as root URL in extensions unit test

pkg/operations/kubernetesupgrade/upgradeagentnode.go
When upgrade, if the newly added node is not ready, it will fail the upgrade attempt but that node will be kept. However, in the next upgrade attempt, another working node will be deleted, which ends up with a cluster with less than specified number of working nodes.
Here the fix is to remove the newly added node if it reports not ready.
**Notes**:
=> fix: delete vm if node is not ready after upgrade.

releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.24.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.24.txt
Follow-up from #1165
**Notes**:
=> chore: add 2019.04.24 VHD release notes

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#v1150-alpha2
**Notes**:
=> feat: add support for Kubernetes v1.15.0-alpha.2

test/e2e/kubernetes/kubernetes_test.go
Skip "ssh into master" tests for multi-vmss master scenarios (there is not currently an ssh'able vector for these clusters)
**Notes**:
=> test: can’t ssh into master vmss master vms

test/e2e/kubernetes/kubernetes_test.go
Follow-up from #1188, this is the correct way to determine if you can ssh into a master vm
**Notes**:
=> test: hasSSHAbleMaster returns false if master vmss

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.04.30.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.04.30.txt, test/e2e/kubernetes/kubernetes_test.go
Includes pre-pulled components for Azure Stack.
**Notes**:
=> chore: update VHD version to 04.30.2019

parts/k8s/cloud-init/artifacts/cse_config.sh, scripts/validate-shell.sh, test/cluster-tests/kubernetes/test.sh
Suggests replacing `echo | sed` usages with the hidden powers of `bash` [parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html).
See https://github.com/koalaman/shellcheck/wiki/SC2001
Refs #953
**Notes**:
=> style: bash parameter expansion replaces "echo | sed"

pkg/engine/vmextensions_test.go
Adds a unit test to validate the "don't run outbound internet" CSE option. Also adds a similar test for Azure Stack.
**Notes**:
=> test: add no outbound CSE unit test

Makefile
Standardizing syntax in makefile as per our discussion in previous PR. 
**Notes**:
=> style: standardize makefile syntax

test/e2e/kubernetes/kubernetes_test.go
for some reason long-named deployments are getting pods w/ truncated pod names
**Notes**:
=> test: reduced name for ilb curl deployment

docs/community/developer-guide.md, docs/community/example-launch.json
Adds a more complete example `launch.json` file to help developers debug AKS Engine. 
**Notes**:
=> docs: add a more complete VS Code debug configuration

pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go
This adds validation for non-support of the prometheus extension for Windows nodes
Refers to #727 
**Notes**:
=> fix: add validation for non-support of prometheus extension for Windows

pkg/engine/artifacts.go, pkg/engine/artifacts_test.go
Follow-up from #1265, adds Azure Stack specific unit tests for addons related to managed/non-managed disk
**Notes**:
=> test: add storage + Azure Stack addons unit tests

docs/community/example-launch.json
Updates the example `launch.json` file for VS Code after I used it more and found some bugs.
**Notes**:
=> docs: fix typos in launch.json debug example

pkg/engine/templates_generated.go
Running `make generated` in master produced these changes, that I assume are a relic of PRs not having been rebased off of #1088.
**Notes**:
=> chore: update templates_generated.go

test/e2e/kubernetes/kubernetes_test.go
The SSH port was hardcoded to `22` which isn't compatible with VMSS, change to use the correct port.
**Notes**:
=> test: fix auditd E2E for master VMSS

extensions/windows-patches/README.md
This better explains the use cases for `extensions/windows-patching` and that using it to install pre-release private patches also enables test signing as a prerequisite.
**Notes**:
=> docs: Clarify terminology around patches and use of windows-patches extension

test/e2e/kubernetes/kubernetes_test.go
Attempt # 2 to fix master VMSS auditd e2e...
**Notes**:
=> test: add masterSSHPort to auditd E2E SCP

pkg/engine/artifacts.go, pkg/engine/artifacts_test.go
Add unit test coverage for convenience funcs that contribute to k8s manifest data payload composition
**Notes**:
=> test: unit tests for kubernetesManifestSettingsInit

.golangci.yml, cmd/deploy.go, cmd/deploy_test.go, cmd/generate.go, cmd/generate_test.go, cmd/scale.go, cmd/upgrade.go, pkg/api/convertertoapi_test.go, pkg/api/orchestrators.go, pkg/api/vlabs/validate.go, pkg/armhelpers/azurestack/converter.go, pkg/engine/engine.go, pkg/engine/params.go, pkg/engine/params_test.go, pkg/engine/template_generator.go, pkg/engine/vmextensions.go, test/aks-engine-test/promote/promote.go
Enables the `unparam` linter to check that Go functions don't have unused parameters. This led to interesting results.
**Notes**:
=> style: check for unused parameters

docs/topics/features.md, parts/k8s/containeraddons/kubernetesmasteraddons-calico-daemonset.yaml, pkg/api/addons.go, pkg/api/defaults_test.go
Update calico to v3.7.2
**Notes**:
=> chore: Update calico to v3.7.2

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.05.16.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.05.16.txt
See release notes files for details.
**Notes**:
=> chore: update VHD image to 2019.05.16

pkg/engine/templates_generated.go
=> chore: fix templates_generated.go

docs/topics/windows.md
More accurate with the names even though hard coded. Would be easy to understand the example and relate. 
#1258 
**Notes**:
=> docs: update group name and corresponding output folder names

examples/azurestack/kubernetes-azurestack-adfs.json, examples/azurestack/kubernetes-azurestack-azure-ad.json
add example cluster definition for Azure Stack
**Notes**:
=> chore: add example cluster definition for Azure Stack

docs/tutorials/custom-vnet.md
resolves - https://github.com/Azure/aks-engine/issues/1267
Fixes #1267 
**Notes**:
=> docs: update tutorial docs to use kubernetes instead of swarm

pkg/api/types.go
ensure that `GetKubernetesLabels` sorts its key/val label string so that we can unit test it deterministically
**Notes**:
=> test: sorted GetKubernetesLabels method for deterministic unit tests

pkg/engine/artifacts.go
=> fix: correction of file/path inversion args for custom yaml manifests

.prowci/README.md, .prowci/deck.yaml, .prowci/hook.yaml, .prowci/plugins.yaml, .prowci/tide.yaml
=> docs: update prow docs

parts/k8s/cloud-init/artifacts/cse_install.sh
Fixes #1387
Fixes #1387
- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ n/a] includes documentation
**Notes**:
=> fix: Update Kata download URL

pkg/engine/templates_generated.go
follow up for #1390 
**Notes**:
=> chore: update generated files

pkg/api/defaults_test.go
Improve the addons image unit test.
**Notes**:
=> test: refactor addons default image test

pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json
test: update unit test payload for Azure Stack
**Notes**:
=> test: update unit test payload for Azure Stack

.chglog/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Add `security` as a commit title option in the changelog config.
Fixes #1415 
**Notes**:
=> chore: add security to changelog commit titles

.gitignore
#1397 added junit.xml generation for e2e. Add it to gitignore to make sure it doesn't get committed.
**Notes**:
=> chore: ignore junit.xml from e2e

pkg/api/defaults_test.go
Parallelize and reduce code surface overhead of validating defaults addons image for create/update.
**Notes**:
=> test: quicker “defaults addons image” unit test

pkg/engine/templates_generated.go
master code is out-of-sync with generated output
**Notes**:
=> fix: reconcile templates_generated.go

examples/azure-stack/kubernetes-azurestack.json
Revert to Standard_D2_v2 because Standard_D2_v3 does not work on Azure Stack
**Notes**:
=> chore: move azure stack example VM SKUs from Standard_D2_v2 to Standard_D2_v3

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.08.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.08.txt
Includes pre-downloaded artifacts of the following:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.14.3
- k8s.gcr.io/hyperkube-amd64:v1.14.3
- k8s.gcr.io/cloud-controller-manager-amd64:v1.13.7
- k8s.gcr.io/hyperkube-amd64:v1.13.7
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.13.5-azs
- k8s.gcr.io/cloud-controller-manager-amd64:v1.12.9
- k8s.gcr.io/hyperkube-amd64:v1.12.9
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.12.9-azs
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.12.8-azs
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.11.10-azs
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.11.9-azs
- mcr.microsoft.com/k8s/azurestack/core/pause-amd64:3.1
- k8s.gcr.io/cluster-autoscaler:v1.12.5
- …
=> chore: enable 2019.06.08 VHD

parts/k8s/cloud-init/masternodecustomdata.yml, pkg/api/common/helper.go, pkg/api/common/helper_test.go, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/engine_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go, test/e2e/engine/template.go, test/e2e/kubernetes/kubernetes_test.go
```
"GetKubernetesMasterPreprovisionYaml",
"GetKubernetesAgentPreprovisionYaml",
"GetMasterSwarmCustomData",
"GetAgentSwarmCustomData",
"GetSwarmAgentPreprovisionExtensionCommands",
"GetLocation",
"GetWinAgentSwarmCustomData",
"GetWinAgentSwarmModeCustomData",
"GetKubernetesWindowsAgentFunctions",
"GetMasterSwarmModeCustomData",
"GetAgentSwarmModeCustomData",
"WrapAsVariable",
"WrapAsParameter",
"WrapAsVerbatim",
```
**Notes**:
=> test: getTemplateFuncMap unit tests part 5

pkg/engine/templates_generated.go
Generated files are out of sync
**Notes**:
=> chore: reconcile generated files

parts/k8s/cloud-init/artifacts/cse_helpers.sh
This must have been a copy/paste typo in a previous PR, `apt_update_output` should be `apt_dist_upgrade_output`.
**Notes**:
=> fix: fix missing variable in CSE

test/e2e/kubernetes/kubernetes_test.go
Enable DNS liveness checks for calico-enabled clusters.
**Notes**:
=> test: enable DNS liveness test for calico-enabled clusters

parts/k8s/addons/1.15/kubernetesmasteraddons-pod-security-policy.yaml, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/engine/artifacts.go, pkg/engine/artifacts_test.go, pkg/engine/templates_generated.go
Use PodSecurityPolicy to implement privileged auth for 1.15.0-beta.1 and greater.
Fixes #1453 
**Notes**:
=> feat: enable PSP w/ privileged ClusterRoleBinding for 1.15

pkg/api/addons_test.go, pkg/api/common/helper_test.go, pkg/api/common/versions_test.go, pkg/api/orchestrators_test.go, pkg/api/types_test.go, pkg/engine/templates_generated.go
Run tests in parallel as appropriate.
**Notes**:
=> test: parallelize tests part 1

docs/topics/azure-stack.md, pkg/api/common/versions.go
=> revert: remove k8s 1.12.9 support

.github/ISSUE_TEMPLATE/bug_report.md
Suggest adding apimodel to repro steps in bug reports.
**Notes**:
=> chore: add note about apimodel in issue template

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.12.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.12.txt
Includes the following changes:
- `Linux version 4.15.0-1046-azure` for Ubuntu 16.04-LTS
- `k8s.gcr.io/cluster-autoscaler:v1.15.0` container image pre-baked
**Notes**:
=> chore: update VHD to 2019.06.12

docs/topics/azure-stack.md
Update to Azure Stack doc page. List pre-pulled images for private preview users.
=> docs: list pre-pulled versions for Azure Stack

.pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.6
**Notes**:
=> chore: update go toolchain to 1.12.6

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.18.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.17.txt
- Addresses cve-2019-11477 for azure Linux kernel
Per https://usn.ubuntu.com/4017-1/ :
18.04: linux-image-4.18.0-1020-azure - 4.18.0-1020.20~18.04.1
16.04/14.04: linux-image-4.15.0-1047-azure - 4.15.0-1047.51
- 1.14.1 for Azure Stack
- pre-pull correct flannel image
**Notes**:
=> security: new VHD images with kernel patch

docs/topics/azure-stack.md
Document marketplace pre-requisites when deploying to Azure Stack
=> docs: add marketplace prerequisites for Azure Stack

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.20.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201904_2019.06.20.txt
Adds the following pre-downloaded container images for Ubuntu 16.04-LTS:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.0
- k8s.gcr.io/hyperkube-amd64:v1.15.0
Adds the following pre-downloaded container images for Ubuntu 18.04-LTS:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.0
- k8s.gcr.io/hyperkube-amd64:v1.15.0
**Notes**:
=> chore: enable VHD 2019.06.20

scripts/get-akse.sh
Fixes some assumptions in `scripts/get-akse.sh` so it works in Azure Cloud Shell.
Fixes #1518
**Notes**:
=> fix: download aks-engine in Azure Cloud Shell

packer/install-dependencies.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json, pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json, pkg/engine/templates_generated.go, pkg/engine/testdata/key-vault-certs/kubernetes.json
New version of moby for CVE-2018-15664
N/A
**Notes**:
I've kind of blindly updated all the occurrences of moby 3.0.5.
=> chore: Update to MS Moby 3.0.6

.devcontainer.json
VSCode Insiders has a new (awesome) feature which allows you to develop inside a container, with all of the benefits of local development. Here's [a great explanation](https://www.hanselman.com/blog/VisualStudioCodeRemoteDevelopmentMayChangeEverything.aspx). This PR adds the necessary config to use the same docker container as `make dev`.
**Notes**:
This is my first time doing this, and I partially did it for learning.! If there's better practice to follow, please let me know.
=> feat: Add vscode containerized development config

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201904_2019.06.26.txt
This 16.04-LTS VHD was built from the `patch-release-v0.37.4` branch and will be included in that release.
Additive differences compared to the 16.04-LTS VHD currently in master:
- k8s.gcr.io/cluster-autoscaler:v1.1.2
- k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.7
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.14.3-azs
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.13.7-azs
- k8s.gcr.io/cloud-controller-manager-amd64:v1.9.11
- k8s.gcr.io/hyperkube-amd64:v1.9.11
- k8s.gcr.io/cloud-controller-manager-amd64:v1.9.10
- k8s.gcr.io/hyperkube-amd64:v1.9.10
The addition of k8s 1.9-vintage container images is because the 1.9 deprecation was not cherry-picked into the v0.37.4 branch. That deprecation will be included in the v0.38.0 release, before which a …
=> chore: enable VHD 2019.06.26 for 16.04-LTS

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
Closes #1551
**Notes**:
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> fix: use correct path for monitor script in monitor units

test/e2e/kubernetes/kubernetes_test.go
This test case was failing and didn't have enough logging. It wasn't clear which pods were crashing. Ideally none of them should, but what we've seen is that sometimes they restart a few times due to race conditions then stabilize later. It is failing when we're testing private vnets because some kube-system pods had 3 crashes before stabilizing. If 5 isn't enough, maybe this should move up to 10. Otherwise, we could rely on the test case "should have core kube-system componentry running" and cut this one.
It was also marked Windows only, which wasn't needed. There's nothing Windows specific about this test. I also moved it up to the top next to the test case that makes sure the right kube-system pods are running.
=> test: improve crashing kube-system pod check

docs/topics/clusterdefinitions.md, parts/k8s/addons/kubernetesmasteraddons-scheduled-maintenance-deployment.yaml, pkg/engine/artifacts.go, pkg/engine/artifacts_test.go, pkg/engine/const.go, pkg/engine/templates_generated.go
- adds drainsafe addon under scheduled maintenance name, repo has further details
- addon source code is at https://github.com/awesomenix/drainsafe, will be moved under azure in future
- currently the image is hosted in quay, hopefully will be moved to mcr
**Notes**:
=> feat: add scheduled maintenance addon, by default disabled

pkg/api/const.go, pkg/api/defaults.go, pkg/api/defaults_test.go
See https://github.com/Azure/aks-engine/issues/1590
https://github.com/Azure/aks-engine/issues/1590
**Notes**:
=> feat: change windows profile defaults for Azure Stack

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
Ensure that we wait for apt-locks before running apt-get purge. Also remove dependency packages and remove cc from apt sources.
Addresses #1580
**Notes**:
=> fix: improve clear containers clean up

examples/addons/cluster-autoscaler/README.md
Helps to solve the problem when including this example directly from the README.md otherwise you can get the following error:
```
Error: validating generateCmd: specified api model does not exist (kube-autoscaler.json) 
```
**Notes**:
=> docs: fix typo in examples/addons/cluster-autoscaler

parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
This PR brings various CoreOS provisioning fixes and improvements, utilizing cloud-init capabilities.
It also fixes issue with rebooting master node on cluster running CoreOS.
Closes #1576.
**Notes**:
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> fix: CoreOS improvements and fixes

packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
Stop gap solution to address registry reqs
Fixes: #1625
=> feat: pre-pull docker distribution for Azure Stack

docs/topics/azure-stack.md, packer/install-dependencies.sh
See
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#downloads-for-v1151 
Fixes #1647 
**Notes**:
Waiting for PR https://github.com/cncf/k8s-conformance/pull/661 to get merge before we checkin the changes.
=> feat: add support for Kubernetes 1.15.1 on Azure Stack.

docs/topics/azure-stack.md, packer/install-dependencies.sh
=> Revert "feat: add support for Kubernetes 1.15.1 on Azure Stack."

.devcontainer.json, .pipelines/pr-e2e.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.22.4
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.7
**Notes**:
I updated Jenkins to use this image already.
=> chore: update go toolchain to 1.12.7

packer/install-dependencies.sh, parts/k8s/containeraddons/kubernetesmasteraddons-azure-npm-daemonset.yaml, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/const.go, pkg/api/converterfromapi_test.go, pkg/api/defaults_test.go, pkg/engine/const.go, pkg/engine/templates_generated.go
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.24
**Notes**:
```None```
=> chore: Update Azure CNI and NetworkPolicy to v1.0.24

examples/dualstack/README.md, examples/dualstack/kubernetes.json
Add docs for creating dualstack cluster with aks-e.
**Notes**:
=> docs: add docs for dualstack

pkg/api/azenvtypes.go
Changing a distro value, which deprecates the old value, should include a back-compat story for continued usages of that distro value. This PR adds an equivalent map value reference for the deprecated distro keys.
Fixes #1652
**Notes**:
=> fix: add back-compat support for deprecated distro vals

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201907_2019.07.25.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201907_2019.07.25.txt
This VHD delivers the following:
- restored k8s 1.12.7 artifacts
- adds 1.14.4 artifacts
- adds 1.15.1 artifacts
- adds 1.13.8 artifacts
And the following components:
- gcr.io/google-containers/ip-masq-agent-amd64:v2.3.0
- k8s.gcr.io/ip-masq-agent-amd64:v2.3.0
- k8s.gcr.io/kube-addon-manager-amd64:v8.9.1
**Notes**:
=> chore: update VHD to 2019.07.25

examples/dualstack/kubernetes.json
CIDR value of `/82` is not supported until my ip-masq-agent PR is merged. So updating to a more reasonable cidr value thats supported for phase1.
**Notes**:
=> docs: Update ipv6 cidr for dualstack

test/e2e/runner.go
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
**Notes**:
=> fix: honour CLEANUP_IF_FAIL in test runner

pkg/engine/transform/transform.go, pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
…ncer during upgrade
Fixes #1624
**Notes**:
=> fix: omit NSG rules created by LoadBalancer during upgrade

pkg/engine/transform/transform.go, pkg/engine/transform/transformtestfiles/k8s_master_upgrade_template.json
=> Revert "fix: omit NSG rules created by LoadBalancer during upgrade"

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201907_2019.07.29.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201907_2019.07.29.txt
Built from this branch to include more provisioning artifacts pre-built:
https://github.com/Azure/aks-engine/pull/1684
In addition includes the following component changes:
- Updates 16.04 kernel to `4.15.0-1052-azure`
- adds Azure CNI `v1.0.24`
- adds Kubernetes components
- `k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.15.4`
- `k8s.gcr.io/cluster-autoscaler:v1.15.1`
- `k8s.gcr.io/cluster-autoscaler:v1.14.4`
- `k8s.gcr.io/cluster-autoscaler:v1.13.6`
- `k8s.gcr.io/cluster-autoscaler:v1.12.7`
- adds Azure Stack versions
- `mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.15.1-azs`
- `mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.14.4-azs`
- `mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.13.8-azs`
- removes deprecated versions
- …
=> chore: rev VHD to 2019.07.29

examples/dualstack/README.md
Add prerequisites to IPv6 enabled Azure virtual networks
**Notes**:
=> docs(dual-stack): Add prerequisites

examples/dualstack/kubernetes.json
Update api model example in dual-stack docs.
**Notes**:
=> docs: fix feature flags location in dual-stack example

parts/k8s/windowscnifunc.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go, scripts/build-windows-k8s.sh
This replaces the deprecated plugin with win-bridge
**Notes**:
=> fix: Change win-cni to win-bridge binaries and config

test/e2e/kubernetes/node/node.go
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
**Notes**:
=> chore: fix error message not displayed when binary not found

examples/azure-stack/kubernetes-azurestack.json
=> docs: increase master node count in Azure Stack template

packer/install-dependencies.sh, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/const.go, pkg/api/converterfromapi_test.go, pkg/api/defaults_test.go
Updates to the latest release of Azure CNI and NetworkPolicy:
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.25
Fixes #1773 
**Notes**:
=> chore: update Azure CNI and NetworkPolicy to v1.0.25

OWNERS
Welcome to the club @devigned 
**Notes**:
=> docs: Add devigned as owner

pkg/engine/transform/transform_test.go, pkg/engine/transform/transformtestfiles/master_resources_scale_temaplate.json
Added unit test for NormalizeMasterResourcesForScaling function
Fixes #1645
=> feat: Added unit test for NormalizeMasterResourcesForScaling function

docs/topics/features.md
=> docs: fix the feature table

.pipelines/vhd-builder-windows.yaml, packer.mk, packer/configure-windows-vhd.ps1, packer/windows-vhd-builder.json, packer/write-release-notes-windows.ps1
There is a desire to produce Windows VHDs curated by the AKS Engine team for use with AKS-Engine and AKS.
This packer build definition produces a Windows VHD that can be used be AKS-Engine without modification to any of the custom script extensions but also allows precise control over version of Windows Server 2019 (including patches) is used.
This work supports https://github.com/Azure/container-compute-upstream/issues/49
**Notes**:
=> feat: Windows VHD build pipeline

docs/community/release-checklist.md
Simplifies the AKS Engine release instructions now that [`gofish`](https://gofi.sh) package manager updates are automated.
**Notes**:
=> docs: gofish updates are automated now for AKS Engine releases

parts/k8s/containeraddons/1.16/kubernetesmasteraddons-metrics-server-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml, pkg/engine/templates_generated.go
Fix the deployment for v0.3.3 of metrics-server
Fixes #1707 
=> fix: metrics server cluster role

pkg/engine/armresources.go
Skip creation of SLB when `isHostedMaster`
fixes #1834 
**Notes**:
=> fix: skip creating slb for hostedmaster

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.08.21.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.08.21.txt
Adds the following pre-baked Kubernetes versions for AKS and Azure Stack:
- 1.15.3
- 1.14.6
- 1.13.10
And removes:
- 1.15.1
- 1.14.4
- 1.13.8
**Notes**:
=> chore: rev VHD image references to 2019.08.21

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/scripts/host-os-dns-validate.sh
We're not retrying UDP-based lookups, which leads to flakes.
**Notes**:
=> test: add retries to host OS DNS E2E tests

pkg/api/common/const.go
As Kubernetes upstream is no longer actively patching the 1.12 release channel, let's deliver 1.13 by default if no version is specified by the api model.
**Notes**:
=> feat: update default Kubernetes version to 1.13

test/e2e/kubernetes/kubernetes_test.go
A few things:
- use the new common ssh connection instance to do remote ssh execution
- the implementation was not doing what it said it was doing, which was to connect to the dashboard on any one node, it was actually trying to connect to the dashboard on all nodes
- remove the duplicated "verify custom addons configuration is applied" checks
- remove the logic to deal with non-https connection on pre-1.9 versions (no longer supported in aks-engine) of Kubernetes
- don't gate on clusters that have windows pools, simply only validate on linux nodes only
**Notes**:
=> test: improve dashboard e2e tests

packer/configure-windows-vhd.ps1, packer/windows-vhd-builder.json
New Windows Server images with August patches have been released.
**Notes**:
=> chore: Targeting August updates for Windows VHD

test/e2e/kubernetes/kubernetes_test.go, test/e2e/runner/cli_provisioner.go
Certain E2E tests that enumerate across all nodes are not appropriate for low-priority VMSS scenarios, as the vms that underlie those nodes may (and do) disappear suddenly and unexpectedly.
**Notes**:
=> test: e2e accommodations for low-pri vmss configurations

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go
Allow up to 5 mins for host vm DNS records to be created.
**Notes**:
=> test: check DNS before scp’ing

examples/addons/cluster-autoscaler/README.md
=> docs: fix invalid link

packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
This package includes _htpasswd_
=> chore: add apache2-utils as an apt dependency

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
Retry pod get requests to account for flakes in the I/O and Kubernetes application layer.
**Notes**:
=> test: retry pod get

test/e2e/kubernetes/pod/pod.go
Follow-up from #1879, my git UI fooled me, there was a final bit of the changeset that I didn't stage for commit. This is that final bit.
**Notes**:
=> test: printing wrong err

packer/install-dependencies.sh, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/const.go, pkg/api/converterfromapi_test.go, pkg/api/defaults_test.go
Updates to the latest release of Azure CNI and NetworkPolicy:
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.27
**Notes**:
=> chore: update Azure CNI and Azure-NPM to v1.0.27

parts/k8s/containeraddons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, pkg/engine/templates_generated.go
Update rbac settings for cluster autoscaler.
=> fix: Update rbac settings for cluster autoscaler

.pipelines/vhd-builder-windows.yaml, packer/windows-vhd-builder.json
Updating the windows VHD build pipeline definition and also adding an optional task to copy the VHD to classic storage for future publishing
**Notes**:
=> ci: Running e2e tests as part of windows VHD build

Jenkinsfile, test/e2e/test_cluster_configs/base.json, test/e2e/test_cluster_configs/container_monitoring.json, test/e2e/test_cluster_configs/everything.json, test/e2e/test_cluster_configs/network/cilium.json, test/e2e/test_cluster_configs/network_policy/calico.json, test/e2e/test_cluster_configs/network_policy/calico_azure.json, test/e2e/test_cluster_configs/no_outbound.json, test/e2e/test_cluster_configs/not_in_vhd.json, test/e2e/test_cluster_configs/storage_profile.json, test/e2e/test_cluster_configs/vmss_master.json, test/e2e/test_cluster_configs/windows/accellerated_networking.json, test/e2e/test_cluster_configs/windows/custom_image.json, test/e2e/test_cluster_configs/windows/custom_vnet.json, test/e2e/test_cluster_configs/windows/image_reference.json, test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json, test/e2e/test_cluster_configs/windows/shared_image_gallery.json, test/e2e/test_cluster_configs/windows/vhd_url.json
Not all of the tests were migrated over from the old Jenkins. This should complete the migration of the existing jobs into the new Jenkins Pipeline.
TODO for future improvement:
- add apiModelPath to the test configurations to point to examples configurations and documentation.
=> chore: add windows, monitoring and base test configs

Makefile, pkg/engine/const.go, pkg/engine/params_k8s.go, pkg/engine/testdata/azurestack/kubernetes.json, scripts/build-windows-k8s.sh
Add build and deploy windows zip file support on Azure Stack
Fixes #1887 
**Notes**:
=> feat: add build and deploy windows zip file support on Azure Stack

pkg/api/common/versions.go, test/e2e/kubernetes/service/service.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#v1160-beta2
**Notes**:
=> feat: add support for Kubernetes 1.16.0-beta.2

docs/topics/clusterdefinitions.md, pkg/api/const.go
Deploy & test August patch tuesday image
=> chore: Update Windows to version  17763.678.1908092216

Jenkinsfile
Add parallel upgrade and scale Jenkins support. This change will allow for a job to specify a range of jobs and then the build script will determine the highest next version to upgrade and run the E2E tests on the upgraded cluster. The build script / pipeline also supports scaling the cluster via job parameters.
**Notes**:
=> chore: add upgrade and scale parallel jobs

test/e2e/engine/template.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/hpa/hpa.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/node/node.go, test/e2e/kubernetes/persistentvolume/persistentvolume.go, test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go, test/e2e/kubernetes/pod/pod.go, test/e2e/kubernetes/service/service.go, test/e2e/kubernetes/storageclass/storageclass.go
This PR began as:
"We shouldn't be intolerant towards ephemeral errors in "wait for state" tests."
And it evolved into a wholesale cleanup of background/async/retry go func usage patterns:
- No longer holding open unnecessary channels for goroutine state communication (e.g., we were commonly holding open a distinct error channel, and a distinct "response" channel.
- Converged lots of "do this then do this if not err then do this if not err" into simpler "do stuff and err immediately" wrapped inside simpler "tolerate errs and retry until timeout" funcs.
- Cleaned up some var naming so that it's clear we're doing "retry" and then "time out" implementations (e.g., rename the ill-worded `duration` var to `timeout`
- Various, targeted retry/timeout changes in response to …
=> test: E2E: goroutine and err response cleanup

test/e2e/kubernetes/pod/pod.go
E2E `pod.WaitOnSucceeded` func unnecessarily accepts a simple substring "prefix" when it is only being used to wait for distinct pod Succeeded states.
**Notes**:
=> test: pod WaitOnSucceeded against distinct pod

docs/topics/clusterdefinitions.md, packer/windows-vhd-builder.json, pkg/api/const.go
New Windows Server images with Sept 2019 patches have been released.
**Notes**:
=> chore: Updating windows image references to target Sept updates

test/e2e/test_cluster_configs/gpu.json
Seeing this error in tests:
```
10:23:28  Error from deployment for kubernetes-southcentralus-78634 in resource group kubernetes-southcentralus-78634:exit status 1
10:23:28  2019/09/17 17:23:26 Command Output: ERROR: Deployment failed. Correlation ID: 0fe233f4-ed9e-4bf0-9fae-daa71d7694dc. {
10:23:28    "status": "Failed",
10:23:28    "error": {
10:23:28      "code": "ResourceDeploymentFailure",
10:23:28      "message": "The resource operation completed with terminal provisioning state 'Failed'.",
10:23:28      "details": [
10:23:28        {
10:23:28          "code": "AllocationFailed",
10:23:28          "message": "Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation …
```
=> test: run gpu tests in westus2

examples/kubernetes-releases/kubernetes1.16.json
Add example Kubernetes 1.16 example api model in preparation for 1.16.0 final release.
**Notes**:
=> docs: add 1.16 api model example

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.16.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.16.txt
`2019.09.16` brings in the following for both 16.04-LTS and 18.04-LTS VHD images:
- k8s.gcr.io/metrics-server-amd64:v0.3.4
**Notes**:
=> chore: rev VHD images to 2019.09.16

parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
Deleting hyperkube images in close proximity to bringing the kubelet online may trick the kubelet into thinking that it has a local image, which if it suddenly doesn't a few ticks later, puts that scheduling operation into an unrecoverable state.
This PR moves container image cleanup to the beginning of the CSE implementation, prior to the bootstrapping of the Kubernetes application layer, to prevent races between Kubernetes container scheduling and underlying container runtime image manipulation.
The time to do these image cleanup operations can be up to 30 seconds, and so we will continue to send the `docker rmi` processes to the background. By moving the commencement of execution to the beginning of CSE we will eliminate *most* of the flaky symptoms due to the …
=> fix: delete hyperkube images before starting kubelet

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#v1147
**Notes**:
=> feat: add support for Kubernetes 1.14.7

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#v11311
**Notes**:
=> feat: add support for Kubernetes 1.13.11

test/e2e/kubernetes/workloads/validate-dns-linux.yaml
We shouldn't test just one FQDN for DNS resolution during E2E
**Notes**:
=> test: run DNS validation against more than one query

test/e2e/test_cluster_configs/flannel/containerd.json, test/e2e/test_cluster_configs/network/cilium.json, test/e2e/test_cluster_configs/network_policy/calico.json, test/e2e/test_cluster_configs/network_policy/calico_azure.json, test/e2e/test_cluster_configs/network_policy/cilium.json, test/e2e/test_cluster_configs/rbac_disabled.json, test/e2e/test_cluster_configs/windows/network_plugin/kubenet.json
An iteration to remove unnecessary k8s version restrictions from E2E test configs.
**Notes**:
=> test: update Jenkins test configs for k8s versions

packer/install-dependencies.sh
standardize to spaces over tabs in an `install-dependencies.sh` block, was a mix of tabs/spaces before
**Notes**:
=> ci: consistent whitespace

test/e2e/kubernetes/kubernetes_test.go, test/e2e/remote/ssh.go
Retry ssh remote execution commands in E2E
**Notes**:
=> test: retry remote ssh commands

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.19.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.19.txt
Includes the following new pre-pulled container images:
- k8s.gcr.io/hyperkube-amd64:v1.16.0
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.4
- k8s.gcr.io/hyperkube-amd64:v1.15.4
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.15.4-azs
- k8s.gcr.io/cloud-controller-manager-amd64:v1.14.7
- k8s.gcr.io/hyperkube-amd64:v1.14.7
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.14.7-azs
- k8s.gcr.io/cloud-controller-manager-amd64:v1.13.11
- k8s.gcr.io/hyperkube-amd64:v1.13.11
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.13.11-azs
No longer pre-pulling the following container images:
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.2
- k8s.gcr.io/hyperkube-amd64:v1.15.2
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.15.2-azs …
=> chore: rev VHD images to 2019.09.19

test/e2e/test_cluster_configs/windows/accelerated_networking.json
typo in E2E cluster config
**Notes**:
=> test: s/Standard_D2_3/Standard_D2_v3

test/e2e/test_cluster_configs/ubuntu_distro.json
Ensure we test the "non-VHD-installed" moby path for "not in VHD" test cluster scenario, and add a non-VHD scenario.
**Notes**:
=> test: update not in vhd config, add ubuntu distro

test/e2e/kubernetes/workloads/dns-liveness.yaml
Validate DNS against more than one external URL to more reliably determine that our external DNS resolution is really broken.
**Notes**:
=> test: dns-liveness against more than one URL

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.09.24.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.09.24.txt
These new VHDs are pre-baked with valid nvidia apt certificates.
**Notes**:
=> chore: rev VHD to 2019.09.24

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, examples/kubernetes.json, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.23.3
and https://github.com/golang/go/issues?q=milestone%3AGo1.12.10
**Notes**:
=> chore: update go toolchain to 1.12.10

Jenkinsfile
We need to account for a `null` `opts` object.
**Notes**:
=> e2e: fix missing null coalescing operator

docs/community/developer-guide.md, makedev.ps1
Fixes #2012
https://github.com/Azure/aks-engine/issues/2012
**Notes**:
=> fix: verify LCOW in makedev.ps1

test/e2e/test_cluster_configs/everything.json
eastus, westeurope, southeastasia, and westus2 are known to offer availability zones support, so let's restrict test configs that validate AZ to only those regions
**Notes**:
=> test: availability zones not available in all regions

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsazurecnifunc.ps1, parts/k8s/windowsconfigfunc.ps1, parts/k8s/windowsinstallopensshfunc.ps1, pkg/engine/templates_generated.go
For total disconnected case we don't want docker install flow to be trigger again when its already installed on windows vhd.
Fixes #2051 
**Notes**:
=> feat: Skip installing docker if already installed on windows vhd

cmd/scale.go, cmd/upgrade.go, pkg/api/azenvtypes.go, pkg/api/converterfromapi.go, pkg/api/converterfromapi_test.go, pkg/api/convertertoapi.go, pkg/api/convertertoapi_test.go, pkg/api/defaults-custom-cloud-profile.go, pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/api/vlabs/azenvtypes.go, pkg/engine/armresources.go, pkg/engine/deployment.go, pkg/engine/deployment_test.go
Configures a different Telemetry Tracking PID during scale, upgrade and deploy scenarios
- [] includes documentation
**Notes**:
=> feat: enable azurestack telemetry for scale and upgrade scenarios

packer/install-dependencies.sh, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/const.go, pkg/api/converterfromapi_test.go, pkg/api/defaults_test.go
Updates to the latest release of Azure CNI and NetworkPolicy:
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.28
**Notes**:
=> chore: Updating Azure CNI and Azure NPM to v1.0.28

docs/topics/features.md
=> fix: correcting spelling in documentation

docs/topics/features.md
=> fix: cleaning up features.md

packer/configure-windows-vhd.ps1, parts/k8s/windowsconfigfunc.ps1, pkg/api/const.go, pkg/engine/templates_generated.go
New versions of docker have been released.
**Notes**:
=> chore: Windows update to docker 19.03.2

docs/community/README.md
channel name has been updated
**Notes**:
=> fix: correcting documentation

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201908_2019.10.03.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201908_2019.10.03.txt
Pre-pulls new hyperkube images:
- k8s.gcr.io/hyperkube-amd64:v1.16.1
- mcr.microsoft.com/k8s/azurestack/core/hyperkube-amd64:v1.16.0-azs
Pre-downloads Azure CNI 1.0.28
- (no longer pre-downloads Azure CNI 1.0.25)
Pre-pulls a newer version of tiller:
- gcr.io/kubernetes-helm/tiller:v2.13.1
Pre-pulls new versions of cluster-autoscaler:
- k8s.gcr.io/cluster-autoscaler:v1.16.1
- k8s.gcr.io/cluster-autoscaler:v1.15.2
- k8s.gcr.io/cluster-autoscaler:v1.14.5
- k8s.gcr.io/cluster-autoscaler:v1.13.7
- k8s.gcr.io/cluster-autoscaler:v1.12.8
**Notes**:
=> chore: rev VHD images to 2019.10.03

packer/install-dependencies.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json, pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json, pkg/engine/templates_generated.go
Updates Microsoft's build of Moby (Docker) to 3.0.7.
Fixes #2113
No CVE, just general bug fixes from upstream. 
**Notes**:
=> chore: update to MS Moby 3.0.7

docs/tutorials/containermonitoringaddon.md
correcting grammar and markdown mistakes as I see them
**Notes**:
=> [wip] docs: correcting grammatical mistakes

test/e2e/runner.go
With retries create or delete operations that are expected to fail during "soak cluster rebuild" scenarios take a long time.
**Notes**:
=> test: faster fail during soak test re-build

packer/vhd-rg-cleanup.sh
=> fix: fix deployment cleanup in cleanup script

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/api/common/helper.go, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/templates_generated.go, test/e2e/kubernetes/job/job.go, test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/workloads/sgx-test.yaml, test/e2e/test_cluster_configs/sgx.json
Adds an api model entry for sgx, to enable e2e tests for sgx on AKS. 
**Notes**:
=> test: Add api model entry for sgx

test/e2e/test_cluster_configs/sgx.json
ntp time sync is a known flake at present w/ 18.04-LTS
**Notes**:
=> test: skip time sync for 18.04-backed sgx test

test/e2e/test_cluster_configs/windows/custom_vnet.json
We don't need a non-default addons configuration, or > 1 master node, to test *just* Windows + custom VNET.
**Notes**:
=> test: minimal Windows custom VNET cluster config

test/e2e/config/config.go, test/e2e/kubernetes/kubernetes_test.go
Let's make the "log all the things after E2E tests" optional. In practice these are like 20 MB of stdout :/
**Notes**:
=> test: make AfterSuite log output optional

packer/windows-vhd-builder.json, pkg/api/azenvtypes.go
Use WindowsServer VHDs with Oct patches
**Notes**:
=> chore: Use WindowsServer VHDs with Oct patches

examples/azure-stack/kubernetes-windows.json
Add Windows api model example file
Fixes #2168 
**Notes**:
=> chore: Add Azure Stack Windows api model example file

packer/configure-windows-vhd.ps1
Adding collectlogs.ps1 script to windows AKS VHD so it won't need to be pulled from the internet.
**Notes**:
=> chore: Adding collectlogs.ps1 to windows AKS VHD

pkg/api/azenvtypes.go, releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.805.191016.txt
Updating windows VHDs used by default in aks-engine
**Notes**:
=> chore: Updating aks-engine to use oct windows aks vhd

parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
There's a bunch of bug workarounds in the Windows setup scripts. Document them.
/hold
=> chore: document some bug workarounds

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go
Follow-up from #1783. Actually use the configurable cloudprovider write limits!
**Notes**:
=> fix: actually use cloudprovider write rate limits

docs/topics/kubernetes-developers.md, pkg/api/defaults.go, pkg/api/defaults_test.go, test/e2e/kubernetes/kubernetes_test.go
Set the distro to "ubuntu" by default so `customHyperkubeImage` scenarios don't have to do that manually.
**Notes**:
=> chore: default to ubuntu distro for customHyperkubeImage

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, pkg/engine/templates_generated.go
Make log collection scripts available for all windows nodes so users do not need to download them from the internet when needed.
**Notes**:
=> feat: Adding steps to get log collection scripts for windows nodes

test/e2e/test_cluster_configs/everything.json, test/e2e/test_cluster_configs/network_policy/azure.json, test/e2e/test_cluster_configs/network_policy/calico.json, test/e2e/test_cluster_configs/sgx.json
Confirmed that these test configs don't (yet) work in 1.17
**Notes**:
=> test: cluster configs that don't work in 1.17

test/e2e/kubernetes/kubernetes_test.go
- Set `longRunningApacheDeploymentName` in BeforeSuite even if `blockSSHPort` is true as it's used by tests that don't use ssh.
- Skip `should be able to access the dashboard` as it requires ssh connection. 
**Notes**:
=> test: skip tests when block ssh port enabled

test/e2e/azure/cli.go
Remove some command print statements to avoid printing connections strings in soak test logs.
**Notes**:
=> test: remove soak test log statements with connection string

packer/install-dependencies.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/armhelpers/azurestack/httpMockClientData/deployVMRequest.json, pkg/armhelpers/azurestack/httpMockClientData/deployVMResponse.json, pkg/engine/templates_generated.go
Updates Microsoft's build of Moby (Docker) to 3.0.8.
**Notes**:
=> chore: update to MS Moby 3.0.8

test/e2e/kubernetes/kubernetes_test.go
#2100 merged after #2187 went in, applying the changes to new e2e case it added.
**Notes**:
=> test: skip cloudprovider config test in no ssh scenario

scripts/collect-windows-logs.ps1
This script will collect all known troubleshooting info from a Windows node. It's intended to be used from this repo for troubleshooting, and may be built into VHDs later.
/assign @marosset
=> chore: Adding a log collection script for Windows

scripts/collect-windows-logs.ps1
If you run this script on a non-AKS deployed machine then it crashes because some of the log paths don't exist. Make a best effort to collect the logs that it can even if some are missing.
=> chore: log collection bugfix around some nonexistant paths

examples/addons/azure-policy/README.md
Update Azure policy add on README doc
=> docs: update azure-policy add-on README doc

.pipelines/vhd-builder.yaml, packer.mk, packer/install-dependencies.sh, packer/vhd-image-builder.json
Paying down some tech debt in the vhd pipeline
**Notes**:
=> feat: Copy linux release notes out of VHD instead of parsing console output

Makefile
Add go module export to the makefile so that in GOPATH builds will default to use modules.
**Notes**:
=> fix: add go module export

.codecov/codecov.yml
https://codecov.io/gh/Azure/aks-engine/commit/e6cc2d61ec6c5e2cff7c3caf4de67aa48d080e6f#diff-cGtnL2VuZ2luZS90ZW1wbGF0ZXNfZ2VuZXJhdGVkLmdv
We shouldn't be tracking generated files in codecov.
**Notes**:
=> ci: ignore generated file in codecov

packer/configure-windows-vhd.ps1, packer/windows-vhd-builder.json
=> feat: Adding more debug files to windows VHD

pkg/operations/kubernetesupgrade/upgrader.go
Assume that during the upgrade of a master the recreation fails after the delete then if you run the upgrade again it will upgrade the next master before trying to recreate the one which is missing.
If your 2nd upgrade fails you will end up with 1 master left (in case you have 3 masters).
Starting by recreating missing masters before continuing upgrading the next ones ensures you are not left with too few masters, if not none.
**Notes**:
=> refactor: recreate missing masters before upgrading

parts/k8s/addons/coredns.yaml
Currently coreDNS is set to auto-reconcile and any customization such as override parameters or stub zone proxy customization will not work in AKS-Engine as the Corefile is reset to default config map settings. Adding the import additional parameters can be added by using a coredns-custom config map with the following parameters:
i.e. Rewrite DNS
```
apiVersion: v1
kind: ConfigMap
metadata:
name: coredns-custom
namespace: kube-system
data:
test.server: |
<domain to be rewritten>.com:53 {
errors
cache 30
rewrite name substring <domain to be rewritten>.com default.svc.cluster.local
forward .  /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10
}
```
i.e. CoreDNS Hosts plugin using overrride
```apiVersion: v1
kind: ConfigMap
metadata: …
```
=> fix: Modified coredns.yaml to include import parameters

parts/k8s/cloud-init/artifacts/setup-custom-search-domains.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, parts/k8s/kubernetesparams.t, parts/k8s/manifests/1.17/kubernetesmaster-kube-apiserver.yaml, parts/k8s/manifests/1.17/kubernetesmaster-kube-controller-manager.yaml, parts/k8s/manifests/1.17/kubernetesmaster-kube-scheduler.yaml, parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml, parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml, parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml, parts/k8s/manifests/kubernetesmaster-kube-controller-manager-custom.yaml, parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml, parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml, pkg/api/common/helper.go, pkg/api/common/helper_test.go, pkg/api/defaults-apiserver.go, pkg/api/defaults-apiserver_test.go, pkg/engine/engine_test.go, pkg/engine/params.go, pkg/engine/params_k8s.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
Rather than delivering manifest specs w/ incomplete references and then sed replacing them via kubelet systemd, we will simply render the appropriate data based on the cluster configuration context.
This PR leverages go template interpretation for all cloud-init-delivered `/etc/kubernetes/manifests/`-bound files.
A related, targeted refactor of sed usage is also included in this PR:
- custom search domain script no gets its data injection via go template instead of at runtime via kubelet systemd shell script sed replacement
In addition to making the various cloud-init file sources more maintainable, this PR allows us to reduce the number of ARM parameters.
This PR includes a new UT for `engine.getContainerServiceFuncMap`, w/ coverage for the effected/new funcs. This …
=> refactor: render manifest specs at template generation time

pkg/api/defaults-kubelet.go, pkg/api/defaults.go, pkg/api/defaults_test.go
Simplify the defaults enforcement flow given the fact that there are order-of-operations "race conditions" between the following:
- `OrchestratorProfile` (defaults depend upon various configurations in `MasterProfile` and `AgentPoolProfiles` pools)
- `MasterProfile` (defaults depend upon various configurations in `OrchestratorProfile`)
- `AgentPoolProfiles` pools (defaults depend upon various configurations in `OrchestratorProfile`)
This PR introduces the following flow changes:
1. Set "IaaS" defaults
1. MasterProfile
2. AgentPoolProfiles defaults
3. Storage defaults
2. Set "app layer" defaults
1. Kubernetes (OrchestratorProfile) defaults
3. Set AKS (HostedMasterProfile) defaults
There is some follow-up work to re-order the WindowsProfile defaults enforcement (given …
=> refactor: rationalize defaults enforcement order

pkg/api/defaults.go, pkg/api/defaults_test.go, pkg/engine/template_generator_test.go
For some reason lint errors passed PR E2E only to land on master E2E as red. :(
**Notes**:
=> fix: lint errors

docs/topics/sgx.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Adds SGX device plugin installation details so that the Kubernetes schedule may be used to schedule workloads to hardware that supports the creation of Trusted Execution Environment (enclaves)
**Notes**:
=> (docs/sgx): Add SGX Device plugin installation details

docs/topics/sgx.md
=> docs: Update sgx device plugin image name

docs/topics/sgx.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Doc updates
**Notes**:
=> (docs/sgx): Add TOC and update device plugin docs

test/e2e/test_cluster_configs/everything.json
Forcing function to uncover what isn't working in 1.17
**Notes**:
=> test: enable "everything" cluster config test for 1.17

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201911_2019.11.18.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201911_2019.11.18.txt
Update VHD reference to 2019.11.18
These new Linux VHDs includes the following:
- `Linux version 4.15.0-1063-azure` for Ubuntu 16.04-LTS
- `Linux version 5.0.0-1025-azure` for Ubuntu 18.04-LTS
Updates the following built-in components:
- moby v3.0.8
- updated from v3.0.7
Includes the addition of the following pre-downloaded components:
- Azure CNI v1.0.29
No longer includes the following pre-downloaded components:
- Azure CNI v1.0.27
Includes the addition of the following pre-downloaded container images:
- mcr.microsoft.com/containernetworking/azure-npm:v1.0.28
- mcr.microsoft.com/containernetworking/azure-vnet-telemetry:v1.0.29
- mcr.microsoft.com/containernetworking/azure-vnet-telemetry:v1.0.28
- mcr.microsoft.com/k8s/core/azure-cloud-controller-manager:v0.3.0
- …
=> chore: rev Linux VHD images to 2019.11.18

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
A more resilient "run a command in a pod" for E2E. And let's use it for our flaky curl tests.
**Notes**:
=> test: add RunWithRetry to E2E, use for curl tests

docs/topics/kubernetes-developers.md
Follow-up PR for https://github.com/Azure/aks-engine/pull/2333.
**Notes**:
=> docs: update kubernetes-developers.md

test/e2e/kubernetes/scripts/net-config-validate.sh
=> test: re-enable E2E test for inotify max_user_watches

pkg/api/types.go, pkg/engine/virtualmachines.go, pkg/engine/virtualmachines_test.go, pkg/engine/virtualmachinescalesets.go, pkg/engine/virtualmachinescalesets_test.go
cherry-pick for https://github.com/Azure/aks-engine/pull/2238/files to aks-release branch
**Notes**:
=> feat: support using existing identity for addons (#2238)

packer/windows-vhd-builder.json
Including Nov patches in Windows VHD
**Notes**:
=> feat: Updating Windows VHD build def to container Nov patches

packer/configure-windows-vhd.ps1, packer/write-release-notes-windows.ps1
Adding a unique ID file to Windows VHDs so we can correlate telemetry from Windows node setup extensions to a specific VHD image
**Notes**:
=> feat: Adding a unique id to Windows VHDs for telemtry correlation

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.25.0
and https://golang.org/doc/devel/release.html#go1.13
**Notes**:
=> chore: update go toolchain to 1.13.5

packer/configure-windows-vhd.ps1
=> feat: caching application insights bins in windows vhd

pkg/api/azenvtypes.go, pkg/engine/template_generator_test.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201912_2019.12.09.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201912_2019.12.09.txt
Updates Ubuntu VHDs to `2019.12.09`, which includes the following changes:
- Adds pre-downloaded Kubernetes 1.17 components:
- k8s.gcr.io/kube-apiserver:v1.17.0
- k8s.gcr.io/kube-controller-manager:v1.17.0
- k8s.gcr.io/kube-proxy:v1.17.0
- k8s.gcr.io/kube-scheduler:v1.17.0
- k8s.gcr.io/cluster-autoscaler:v1.17.0
- Adds the following pre-downloaded container images:
- k8s.gcr.io/coredns:1.6.5
- mcr.microsoft.com/k8s/csi/azuredisk-csi:v0.4.0
- mcr.microsoft.com/k8s/csi/azurefile-csi:v0.3.0
- quay.io/k8scsi/csi-attacher:v1.0.1
- quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
- quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
- quay.io/k8scsi/csi-provisioner:v1.0.1
- quay.io/k8scsi/livenessprobe:v1.1.0
- k8s.gcr.io/node-problem-detector:v0.8.0
- No longer includes …
=> chore: rev Linux VHDs to 2019.12.09

pkg/api/azenvtypes.go, pkg/engine/template_generator_test.go, releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.864.191209.txt
=> chore: releasing new Windows VHD with Nov 2019 patches/updated bins

Jenkinsfile
Now that 1.12 is no longer supported we need to disable it from the jenkins allow list.
**Notes**:
=> test: stop testing 1.12

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#changelog-since-v1149
**Notes**:
I'll collect the VHD-related changes into a separate PR so we can focus discussion on those changes.
=> feat: add support for Kubernetes 1.14.10

test/e2e/cluster.sh
Some variables were missed during #2438 
**Notes**:
=> ci: fix some Jenkins variables

pkg/api/azenvtypes.go, releases/vhd-notes/aks-windows/2019-datacenter-core-smalldisk-17763.864.191211.txt
=> chore: releasing Windows VHD with 1.16.4, 1.15.7 k8s packages

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-201912_2019.12.11.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-201912_2019.12.11.txt
Includes the following additive pre-downloaded container images:
- k8s.gcr.io/hyperkube-amd64:v1.16.4
- k8s.gcr.io/hyperkube-amd64:v1.15.7
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.7
**Notes**:
=> chore: rev Linux VHDs to 2019.12.11

test/e2e/cluster.sh
Before switching branches we need to ensure no generated code artifacts (i.e., dirty git status).
**Notes**:
=> test: ensure clean local git before switching branches

packer/configure-windows-vhd.ps1, packer/install-dependencies.sh, pkg/api/const.go, pkg/api/converterfromapi_test.go
Updates to the latest release of Azure CNI
**Notes**:
=> chore: Updating Azure CNI to v1.0.30

test/e2e/test_cluster_configs/everything.json
Anecdotal evidence that availability zones are capacity constrained in westus2.
**Notes**:
=> test: use uksouth instead of westus2 for AZ tests

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsazurecnifunc.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
=> feat: Move creation of 'ext' HNS network into cse for Windows

pkg/engine/images.go, pkg/engine/images_test.go
=> fix: hard-coding hyper-v generation when using VHD URls as a quick unblock

pkg/api/types.go
fix lint error that got to master :/
**Notes**:
=> chore: lint

examples/kubernetes.json
Unintended change to `examples/kubernetes.json` landed in master
**Notes**:
=> test: revert change to default kubernetes.json api model example

docs/community/developer-guide.md, docs/topics/architecture.md, docs/topics/extensions.md, docs/tutorials/custom-vnet.md, examples/disks-storageaccount/README.md, examples/keyvaultcerts/README.md, examples/kubernetes-config/README.md, examples/networkpolicy/README.md, examples/vnet/vnetarmtemplate/deploy.ps1, extensions/hello-world/README.md, extensions/hello-world/v1/supported-orchestrators.json, releases/README.Dockerfile.md
Cleans up the remaining citations of DC/OS, Swarm, and such in documentation and examples.
Refs #2500
**Notes**:
=> docs: remove mentions of old orchestrators

packer/windows-vhd-builder.json
=> chore: Targeting dec patches for windows VHD

pkg/api/common/versions.go
=> chore: add the 1.13.12/1.14.8/1.15.5 back.

pkg/helpers/helpers.go, pkg/helpers/helpers_test.go
cherry-pick  #2509 into aks-release
**Notes**:
cherry-pick  #2509
=> fix: add "Standard_DS3_v2" to "AcceleratedNetworking" supported list (#2509)

test/e2e/runner.go
This PR restores log collection for E2E runs.
**Notes**:
=> ci: collect logs during E2E runs

parts/k8s/addons/1.16/kubernetesmasteraddons-aci-connector-deployment.yaml, parts/k8s/addons/1.17/kubernetesmasteraddons-aci-connector-deployment.yaml, parts/k8s/addons/1.18/kubernetesmasteraddons-aci-connector-deployment.yaml, parts/k8s/addons/kubernetesmasteraddons-aci-connector-deployment.yaml, pkg/engine/templates_generated.go
The region configuration is not being passed into the aci-connector addon spec.
Fixes #2523 
**Notes**:
=> fix: aci-connector region is ignored

test/e2e/kubernetes/workloads/dns-liveness.yaml
This is more resilient across clouds, e.g., china
**Notes**:
=> test: use vanilla busybox image for E2E tests

packer/install-dependencies.sh
The AKS tunnel images in VHD are out-of-date, we need to bake new images in the VHD
**Notes**:
=> perf: upgrade AKS tunnel image in VHD

.pipelines/vhd-builder-windows.yaml, packer.mk, packer/generate-windows-vhd-publishing-info.sh
Updating the windows vhd build pipeline to produce a json file with information needed for publishing to be used in future build/release pipeline steps
**Notes**:
=> feat: create windows vhd publishing file in build pipeline

.pipelines/marketplace-sku.yaml
When i was testing the pipeline in my personal azure devops instance i wasn't using secret variables :(
**Notes**:
=> fix: marketplace-sku.yaml - fix for secret variables

vhd/publishing/add-image-version-to-sku.sh
Part 3 of changes needed to automate VHD publishing to azure marketplace as described in #2528
**Notes**:
=> feat: Win vhd release pipeline

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, pkg/engine/templates_generated.go
=> feat: Cse tracing for windows nodes

test/e2e/kubernetes/kubernetes_test.go
Follow up from #2547, ensure that all E2E tests trying to connect to a static node are disabled if the node is running in a Spot VMSS pool configuration.
**Notes**:
=> test: don't run ssh tests on spot vmss pools

test/e2e/test_cluster_configs/availabilityset-standard-lb.json
This PR adds an E2E cluster configuration scenario for `AvailabilitySet` (i.e., not VMSS) and Standard Load Balancer.
**Notes**:
=> ci: add AvailabilitySet + SLB E2E scenario

packer/install-dependencies.sh, pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#changelog-since-v1170
**Notes**:
=> feat: add support for Kubernetes 1.17.1

pkg/api/azenvtypes.go, releases/vhd-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.10.txt, releases/vhd-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.10.txt, test/e2e/test_cluster_configs/no_outbound.json
new VHD contains images required by AKS, e. g.
coredns1.6.6
hcp-tunnel 3.0.11
**Notes**:
=> chore: update VHD references to 2020.01.10 (#2564)

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/util/util.go, test/e2e/kubernetes/workloads/pod-pvc.yaml, test/e2e/kubernetes/workloads/pvc-azuredisk.yaml, test/e2e/test_cluster_configs/availabilityset.json, test/e2e/test_cluster_configs/sgx.json
=> fix: Fix e2e test failure

pkg/api/azenvtypes.go, vhd/release-notes/aks-ubuntu-1604/aks-ubuntu-1604-202001_2020.01.15.txt, vhd/release-notes/aks-ubuntu-1804/aks-ubuntu-1804-202001_2020.01.15.txt
This PR updates Ubuntu 16.04-LTS and 18.04-LTS VHD references to version `2020.01.15`.
Includes the following additive pre-downloaded artifacts:
- apmz v0.4.0
- k8s.gcr.io/kube-apiserver:v1.17.1
- k8s.gcr.io/kube-controller-manager:v1.17.1
- k8s.gcr.io/kube-proxy:v1.17.1
- k8s.gcr.io/kube-scheduler:v1.17.1
- mcr.microsoft.com/k8s/csi/azuredisk-csi:v0.5.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v1.2.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-cluster-driver-registrar:v1.0.1
- mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.1.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v1.4.0
- mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v1.1.0
- …
=> chore: update VHD references to 2020.01.15

vhd/packer/windows-vhd-builder.json
=> feat: Updating aks-windows vhd to to include jan patches

vhd/packer/configure-windows-vhd.ps1
=> chore: Adding 1.17.1 package to windows vhd

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.18.md#changelog-since-v1180-alpha1
**Notes**:
=> feat: add support for Kubernetes 1.18.0-alpha.2

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, pkg/engine/templates_generated.go, vhd/packer/configure-windows-vhd.ps1
=> feat: fetching collect-windows-logs.ps1 during windows CSE

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, hack/tools/Makefile, makedev.ps1
See https://github.com/deis/docker-go-dev/releases/tag/v1.25.2
Specifically updates `golangci-lint` to v1.23.1 and go itself to 1.13.6.
**Notes**:
=> chore: update go-dev tools image

test/e2e/cluster.sh
This PR adds foo to our standard E2E upgrade scripts to change the Master VM SKU prior to upgrade, to simulate how one could use `aks-engine upgrade` to vertically scale his/her control plane compute.
**Notes**:
=> test: modify vm sku during e2e upgrade tests

test/e2e/test_cluster_configs/cloud_controller_manager_zones.json
Restrict CCM + Zones test config to regions that we know have availability zones support.
**Notes**:
=> test: zones aren't available everywhere

.devcontainer.json, .pipelines/pr-e2e.yaml, .pipelines/vhd-builder.yaml, Makefile, hack/tools/Makefile, makedev.ps1
This reverts commit 7cff5e4dcc219bfd49a18148a01860bc18ac24c0.
**Notes**:
=> revert: "chore: update go-dev tools image (#2534)"

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.973.200123.txt
=> feat: updating aks-engine to use jan windows images by default

parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/defaults_test.go, pkg/engine/templates_generated.go, vhd/packer/install-dependencies.sh
Update moby to 3.0.9
**Notes**:
=> chore: Bump moby to 3.0.10

cmd/scale.go
This PR will make Windows scaling actually work. The current scaling implementation uses an incorrect substring parsing implementation to derive the "pool index suffix", which is used at cluster creation time to compose the name of a Windows VMSS resource. Ultimately, this incorrect parsing has two bad side-effects:
- it prevents the scale operation from correctly identifying the VMSS resource when the `--node-pool` argument value is the pool name of a Windows node pool
- the above has the side-effect of creating a *new* Windows node pool with the desired `--new-node-count`, instead of failing the scale operation
Additionally, this PR fixes a bug which was causing VHD-backed Linux node pools from entering the first bad side-effect above, and logging a spuriuos error …
=> fix: make Windows scaling work

README.md
This PR adds a note about project support on the homepage readme, making it easier for users to discover how to engage the project maintainers for help with issues.
**Notes**:
=> docs: add support note to main readme

parts/k8s/addons/1.11/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.12/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.13/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.14/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.15/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.16/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.17/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/1.18/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml, parts/masteroutputs.t, pkg/api/const.go, pkg/api/mocks.go, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/armoutputs.go, pkg/engine/armvariables.go, pkg/engine/armvariables_test.go, pkg/engine/engine.go, pkg/engine/engine_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
pre-refactor refactor: separating all non related changes in #2651 to make reviews easier and reverting possible if necessary.
**Notes**:
=> refactor: cleanup duplicate functions and move apiversions to consts

test/e2e/kubernetes/pod/pod.go
Observed some flakery on soak tests that we can avoid by deleting pre-existing pods:
```
STEP: Ensuring we can create a curl pod to connect to the service
2020/02/01 21:58:31 Error trying to deploy curl-to-ilb [byrnedo/alpine-curl] in namespace default:Error from server (AlreadyExists): pods "curl-to-ilb" already exists
```
**Notes**:
=> test: delete pod if exists in run pod scenario

.prowci/deck.yaml, .prowci/hook.yaml, .prowci/tide.yaml
=> fix: #2667 change apiVersion of deployments from v1beta2 to v1

Jenkinsfile, test/e2e/test_cluster_configs/base.json
This PR runs scale and upgrade (in addition to addpool) tests against the base E2E cluster configuration
**Notes**:
=> test: enable scale/upgrade for base E2E cluster config

parts/k8s/addons/antrea.yaml, pkg/api/k8s_versions.go, pkg/engine/templates_generated.go
Release note covers the changes
https://github.com/vmware-tanzu/antrea/releases/tag/v0.3.0
**Notes**:
=> feat: Updating Antrea version to v0.3.0

parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsconfigfunc.ps1, pkg/engine/templates_generated.go
=> fix: raising dynamic port range for windows to better support clusters with 200+ services

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/pod/pod.go
This PR adds an additional "stability" test using the curl client.
**Notes**:
=> test: curl as a stability test client

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, pkg/engine/templates_generated.go
=> feat: read vm size from instance metadata service for windows cse telemetry

hack/tools/tools.go, pkg/api/defaults_test.go
saw another flaky lint error on master
**Notes**:
=> chore: gofmt to avoid lint errors

vhd/packer/configure-windows-vhd.ps1
=> feat: adding mcr.microsoft.com/oss/kubernetes/pause:1.3.0 to windows VHD

README.md
If a Microsoft open source project or release has source code that enables Microsoft to collect data/telemetry, you must place in the README a notice.
This PR satisfies our community and legal requirement.
fixes #2673 
**Notes**:
=> docs: add data collection (telemetry) notice to readme

pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1172
**Notes**:
=> feat: add support for Kubernetes 1.17.3

.pipelines/vhd-builder-windows.yaml
=> chore: use k8s 1.17 for e2e tests in windows vhd pipeline

pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#changelog-since-v1166
**Notes**:
=> feat: add support for Kubernetes 1.16.7

pkg/telemetry/telemetry.go
=> fix: remove requirement for ldflags or make test

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.973.200213.txt
=> feat: updating windows VHD for Feb k8s versions

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowskubeletfunc.ps1, parts/k8s/windowsnodereset.ps1, pkg/api/defaults_test.go, pkg/engine/const.go, pkg/engine/template_generator.go, pkg/engine/templates_generated.go
=> feat: Adding WindowsNodeReset.ps1 script to reset/cleanup state for nodes

docs/topics/azure-stack.md
This is GA now right?
**Notes**:
=> docs: remove references to "Public Preview" from Azure Stack page

pkg/api/common/versions.go, test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/kubernetes_test.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1180-alpha2
**Notes**:
=> feat: add support for Kubernetes 1.18.0-alpha.3

vhd/packer/windows-vhd-builder.json
=> chore: update image base for windows vhd

pkg/api/common/versions.go
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1180-alpha3
**Notes**:
=> feat: add support for Kubernetes 1.18.0-alpha.5

vhd/packer/configure-windows-vhd.ps1
=> chore: installing Docker EE 19.03.5 by default in Windows VHD

pkg/api/addons_test.go
Fixing some more fun lint leakage.
**Notes**:
=> chore: latent lint

examples/kubernetes-containerd.json, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/kubernetesparams.t, pkg/api/const.go, pkg/api/vlabs/validate.go, pkg/api/vlabs/validate_test.go, pkg/engine/templates_generated.go, vhd/packer/install-dependencies.sh
Fixes #2370
**Notes**:
This is a POC.
Looking for feedback on the implementation.
Also need tests to run, currently having issues deploying things.
=> chore: use azure containerd packages

pkg/api/addons_test.go
Lint, it gets everywhere.
**Notes**:
=> chore: more lint!

parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go, vhd/packer/configure-windows-vhd.ps1
=> feat: update pause image to 1.3.0 (includes 1903 and 1909 support)

test/e2e/kubernetes/deployment/deployment.go, test/e2e/kubernetes/kubernetes_test.go
This PR introduces deployments into the stability test implementation so that we can test replicas across all nodes to ensure all nodes are consistently healthy across the test matrix.
**Notes**:
=> test: add deployment stability tests

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
=> fix: support Azure containerd install in Debian

test/e2e/kubernetes/kubernetes_test.go
This PR re-orders E2E tests so they go from foundational upwards, from host to container runtime to core k8s components to addons to higher order Kubernetes cluster behaviors.
**Notes**:
=> test: reorder E2E tests

vhd/packer/install-dependencies.sh
This PR brings the VHD spec up-to-date.
**Notes**:
=> chore: rationalize AKS Engine VHD config

vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
=> chore: adding azure-cni v1.0.33 artifacts to VHDs

OWNERS
=> Adding Kalya to OWNERS

pkg/api/azenvtypes.go, pkg/api/const.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1039.2000220.txt
- Feb 2020 security patches for windows
- update to docker EE 19.03.5
**Notes**:
=> feat: Feb windows updates

pkg/api/common/versions.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md/#v1180-beta1
**Notes**:
=> feat: add support for Kubernetes 1.18.0-beta.1

vhd/packer/configure-windows-vhd.ps1
=> chore: Adding 2C patches to windows VHD which addresses some networking issues

parts/k8s/cloud-init/masternodecustomdata.yml, pkg/engine/templates_generated.go
Some of the old values are deprecated, also updates to use the runc (and
kata) v2 containerd shim. The runc v2 shim will be default in containerd
1.4 anyway.
N/A
**Notes**:
=> chore: Update the containerd config

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
Makes sure the URL parsing in `installCNI` and `installAzureCNI` align with `downloadCNI` and `downloadAzureCNI`.
**Notes**:
=> fix: fix the CNI temp file URL parsing in CSE

parts/k8s/cloud-init/artifacts/kubelet.service, pkg/engine/templates_generated.go, test/e2e/kubernetes/scripts/net-config-validate.sh
Cherry pick to 0.47.0-1 release 
**Notes**:
=> [AKS] apply large ipv3 neigh GC settings to nodes of all sizes

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1075.200227.txt
=> feat: release Windows VHD with 2C updates

docs/howto/kubernetes-large-clusters.md
Small fix to the large clusters doc page
=> docs: fixed large clusters doc page

pkg/api/const.go, pkg/api/converterfromapi_test.go
Contains the latest changes in the v1.0.33 Azure CNI release
https://github.com/Azure/azure-container-networking/releases/tag/v1.0.33
**Notes**:
=> chore: Updating Azure CNI to v1.0.33

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1075.200227.txt
**Notes**:
cherry-pick from master branch.
=> feat: release Windows VHD with 2C updates (#2809)

parts/k8s/addons/kubernetesmasteraddons-omsagent-daemonset.yaml, pkg/api/addons.go, pkg/api/addons_test.go, pkg/api/defaults_test.go, pkg/engine/templates_generated.go, pkg/engine/testdata/key-vault-certs/kubernetes.json, test/e2e/test_cluster_configs/container_monitoring.json
February 2020 release changes for Containermonitoring addon -
feat: GPU metrics collection
feat: Support for user assigned msi
feat: Query kubelet to get limits
Complete set of changes here - https://github.com/microsoft/Docker-Provider/blob/ci_feature_prod/README.md
=> feat: update containermonitoring addon for february 2020 release

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
This PR addresses three observed issues w/ the Azure-curated containerd implementation:
- Ensure that we are using the v2 configuration on agent as well as master nodes
- Ensure that we configure iptables for IP forwarding
- Ensure that we configure (via sysctl) the IPv4 stack for IP forwarding
**Notes**:
=> fix: address containerd errata

parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
Restore the `cracklib-runtime` apt installation library.
**Notes**:
=> fix: install cracklib-runtime on ubuntu

test/e2e/kubernetes/workloads/busybox-master.yaml
Until we fix #662 we can't test master-scheduled-pod --> apiserver connectivity because that is not functional in multi-master configurations.
**Notes**:
=> test: remove apiserver from master test

test/e2e/kubernetes/kubernetes_test.go
This is hacky, but moving the validate node labels test to the bottom gives more time for systemd to do its automated thing, removing flakes from E2E.
**Notes**:
=> test: run node labels test later

test/e2e/kubernetes/kubernetes_test.go
Remove the superflous node count test in the "check if nodes have the right labels" test.
**Notes**:
=> test: don't count nodes, just look for labels

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/workloads/policies/backend-policy-deny-egress.yaml
Add egress rule e2e test for network policy. 
E2E test didn't cover egress network policy. Add a default deny all egress policy to the E2E test.
Lack of egress network policy E2E test.
- [ X] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [X ] tested upgrade from previous version
=> test: Add default deny egress test for net work policy.

test/e2e/engine/template.go
This PR allows us to more easily test containerd + Windows scenarios.
**Notes**:
=> test: working Windows containerd URLs

vhd/packer/install-dependencies.sh
Probably just a typo or other human error.
**Notes**:
=> chore: pre-install the version of apmz in CSE

parts/k8s/windowskubeletfunc.ps1, pkg/engine/templates_generated.go
nssm.exe output when captured in powershell contains null characters which mangle the log files.
This PR removes the null characters before they get logged.
**Notes**:
=> fix: fixing nssm logging in windows CSE

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
This is a housekeeping PR to remove unnecessary bytes from CSE rendered payloads, to prevent data limit threshold exceptions.
**Notes**:
=> chore: optimize CSE payload

vhd/packer/configure-windows-vhd.ps1
=> chore: updating windows VHD to include 3B patches + march k8s packages

.pipelines/e2e-step-template.yaml
Surface interesting data about tests into DevOps.
None
**Notes**:
We were already generating the files just need to publish them.
=> build: publish junit test results

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200315.txt
=> feat: Updating AKS to use March 2020 Windows VHDs by default

docs/topics/azure-stack.md
Remove reference to raw Ubuntu from Azure Stack doc
=> docs: remove reference to raw Ubuntu from Azure Stack doc

pkg/armhelpers/httpMockClient.go, pkg/armhelpers/support_validator.go, pkg/armhelpers/support_validator_test.go
I updated the image validation code flow to take into account the new windows vhd details
**Notes**:
=> fix: add validation for new AKS engine Windows Version

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/namespace/namespace.go, test/e2e/kubernetes/networkpolicy/networkpolicy.go
Functions created in network policy specific file for tests to consume. Increase code reusablity.
test: Testing 💚 
- [X ] tested upgrade from previous version
**Notes**:
=> test: create functions in network policy specific file and let tests call it.

test/e2e/runner/cli_provisioner.go
This PR properly skips tests if configured to.
**Notes**:
=> test: better skip test implementation

test/e2e/test_cluster_configs/base.json
This PR skips waiting for deleted nodes to be terminally removed from the node list after scale down in E2E tests that include scale down.
**Notes**:
=> test: skip node ready test after scale down

pkg/api/azenvtypes.go, vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202003_2020.03.16.txt, vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202003_2020.03.16.txt
This PR updates Linux VHD references to `2020.03.16`.
Includes the following pre-downloaded artifacts:
- apmz v0.5.1
- replaces v0.5.0
- moby v3.0.11
- replaces v3.0.10
- k8s.gcr.io/cluster-autoscaler:v1.18.0
- k8s.gcr.io/kube-apiserver:v1.17.4
- k8s.gcr.io/kube-controller-manager:v1.17.4
- k8s.gcr.io/kube-proxy:v1.17.4
- k8s.gcr.io/kube-scheduler:v1.17.4
- k8s.gcr.io/hyperkube-amd64:v1.16.8
- k8s.gcr.io/hyperkube-amd64:v1.15.11
- k8s.gcr.io/cloud-controller-manager-amd64:v1.15.11
No longer pre-downloading these container images:
- k8s.gcr.io/kube-apiserver:v1.17.2
- k8s.gcr.io/kube-controller-manager:v1.17.2
- k8s.gcr.io/kube-proxy:v1.17.2
- k8s.gcr.io/kube-scheduler:v1.17.2
- …
=> chore: rev AKS Engine Linux VHDs to 2020.03.16

test/e2e/test_cluster_configs/availabilityset.json
This PR delivers a simpler cluster configuration for validating AvailabilitySet node pool configuration.
**Notes**:
=> test: simplified availabilityset E2E cluster config

test/e2e/kubernetes/kubernetes_test.go, test/e2e/kubernetes/networkpolicy/networkpolicy.go, test/e2e/kubernetes/workloads/policies/backend-policy-allow-egress-pod-label.yaml, test/e2e/kubernetes/workloads/policies/backend-policy-allow-egress-pod-namespace-label.yaml
Add network policy tests which target pod and namespace selector specifically. 
- [X ] tested upgrade from previous version
**Notes**:
=> test: add egress tests which target pod and namespace.

docs/topics/clusterdefinitions.zh-CN.md, docs/tutorials/quickstart.zh-CN.md
Fix broken links for examples in zh docs.
Only small fixes for doc.
**Notes**:
=> docs: update examples location for zh docs

.pipelines/vhd-builder-ubuntu-gen2.yaml, packer.mk, vhd/packer/vhd-image-builder-ubuntu-gen2.json
This PR adds a new Azure DevOps pipeline spec for building Generation 2 Ubuntu VHDs.
**Notes**:
=> ci: new VHD pipeline definition for Ubuntu + gen2 images

pkg/api/common/helper.go
These skus are allowed in the list of VM, but missing from the driver install list.
**Notes**:
=> fix: add NVv3 series to NVidia driver install list

.pipelines/e2e-job-template.yaml, .pipelines/pr-e2e.yaml, examples/e2e-tests/kubernetes/release/default/definition.json
This PR reduces the number of cluster configurations to test per-PR.
**Notes**:
=> test: reduce PR E2E cluster jobs

pkg/api/common/helper.go
(cherry picked from commit 3ea0881252e86d36ec517b3126a8eedbbb919417)
**Notes**:
=> fix: add NVv3 series to NVidia driver install list (#2959)

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go, pkg/engine/vmextensions.go
=> chore: don't re-run provision.sh if already called.  (#2843)

.pipelines/pr-e2e.yaml
This PR uses Kubernetes 1.17 to test run aks-engine E2E against PRs.
**Notes**:
=> test: use 1.17 for E2E

docs/topics/azure-stack.md
Call out limits of using the Basic LB SKU.
**Notes**:
=> docs: include Basic LB SKU limitations in Azure Stack page

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go
This PR removes the mlocate apt package if auditd is not enabled (auditd configuration depends upon mlocate)
Fixes #2971 
**Notes**:
=> chore: remove mlocate if auditd disabled

docs/topics/csi-proxy-windows.md, parts/k8s/windowscsiproxyfunc.ps1, parts/k8s/windowskubeletfunc.ps1, parts/k8s/windowsnodereset.ps1, pkg/engine/templates_generated.go
The csi-proxy binary name has been modified in the upstream. After decompression of the latest archive, the path has been changed. 
https://kubernetesartifacts.azureedge.net/csi-proxy/master/binaries/csi-proxy.tar.gz
**Notes**:
=> chore: change csi-proxy binary name

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/api/types.go, pkg/api/types_test.go, pkg/engine/template_generator.go, pkg/engine/template_generator_test.go, pkg/engine/templates_generated.go
This PR moves some CSE funcs around a bit to further optimize shell script omissions that can be applied via go templating. Specifically, because cse_install.sh is interpreted literally by VHD CI (not yet supported for go template interpretation), we move more funcs out of that shell script into cse_config.sh, where those funcs can as appropriate be included only if the cluster configuration needs it.
**Notes**:
=> refactor: cse_install.sh for VHD reqs

parts/k8s/addons/antrea.yaml, pkg/api/k8s_versions.go, pkg/engine/templates_generated.go
Release note covers the changes
https://github.com/vmware-tanzu/antrea/releases/tag/v0.5.0
**Notes**:
=> feat: Updating Antrea version to v0.5.1

docs/tutorials/deploy.md, docs/tutorials/quickstart.md
aks-engine version to fetch the new output:
```
Version: v0.48.0
GitCommit: 44a35c00c
GitTreeState: clean
```
Bring the output of `ask-engine deploy` tutorial up to date, which previously indicate `resource-group` unspecified by mistake.
**Notes**:
=> docs: update `ask-engine deploy` example output

parts/k8s/cloud-init/artifacts/cse_main.sh, parts/k8s/cloud-init/masternodecustomdata.yml, parts/k8s/cloud-init/nodecustomdata.yml, pkg/engine/templates_generated.go
Signed-off-by: Sylvain Rabot <s.rabot@lectra.com>
**Notes**:
=> fix: disable unattended upgrades during CSE execution

parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go
In case of validation err(for now api server connection issues), we still want the script to complete. There are edge cases CSE will run before reimaging, we want to short circuit that.
**Notes**:
=> fix: In case of api server connection error, still complete script

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, parts/k8s/cloud-init/artifacts/cse_main.sh, pkg/engine/templates_generated.go, vhd/packer/install-dependencies.sh
This PR is inspired by @andyliuliming's work here:
https://github.com/Azure/aks-engine/pull/3018
(Liming did all the hard work).
Essentially, this PR adds proper retry tolerance to the actual, last-mile nvidia drivers installation. E.g.:
```
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 418.40.04............................................................................................................................................................................................................................................................................................................................................................................................................................................................................ …
```
=> refactor: retry nvidia drivers installation

parts/k8s/cloud-init/artifacts/cse_config.sh, parts/k8s/cloud-init/artifacts/cse_helpers.sh, parts/k8s/cloud-init/artifacts/cse_install.sh, pkg/engine/templates_generated.go
=> fix: do some clean up before retry to install the gpu driver.

pkg/api/azenvtypes.go
=> bump the vhd version which contains the route table hotfix.

pkg/api/agentPoolOnlyApi/v20170831/types.go, pkg/api/agentPoolOnlyApi/v20180331/types.go, pkg/api/agentPoolOnlyApi/vlabs/types.go, pkg/api/types.go, pkg/api/vlabs/types.go
the os disk size restriction is changed to 2048 now in Azure.
**Notes**:
=> fix: the os disk size restriction is changed in azure.

pkg/api/azenvtypes.go, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt
=> feat: Updating AKS to use April 2020 Windows VHDs by default

pkg/api/azenvtypes.go
=> fix: switch to use the 04.13 image which contains the cve patch.

pkg/api/azenvtypes.go
=> feat: Update NPM from v1.0.33 to v1.1.0 for aks ubuntu images

test/e2e/test_cluster_configs/everything.json
https://github.com/Azure/aks-engine/pull/3070 introduced a bad distro value to the "everything" E2E cluster config
**Notes**:
=> test: fix bad distro value in everything cluster config

.pipelines/pr-e2e.yaml, cmd/generate_test.go, examples/kubernetes-non-vhd-distros.json, pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/defaults-kubelet_test.go, pkg/api/defaults.go, pkg/api/types.go, pkg/api/types_test.go, pkg/api/vlabs/const.go, pkg/api/vlabs/types.go, pkg/api/vlabs/types_test.go, pkg/api/vlabs/validate_test.go, pkg/armhelpers/support_validator.go, pkg/engine/armvariables_test.go
Cherry-pick gen2 config settings to AKS release branch
**Notes**:
=> test: add test config to use gen2 images for agent pools (#2893)

docs/design/get-logs.md
Proposal to discuss features, scope and command interface.
=> docs: get-logs proposal

pkg/api/const.go, pkg/api/converterfromapi_test.go, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh
1. Azure CNI IPVS Support Linux
2. Azure CNI Dualstack Support Linux - vnet v4 ips and non-vnet v6 ips
3. Bug fixes
**Notes**:
=> chore: updating azure cni version to v1.1.0

docs/community/release-checklist.md
Syncs up the AKS Engine release doc with package management reality.
See #653
**Notes**:
=> docs: remove docker package and choco caveat from release docs

docs/community/README.md
The [Community](https://github.com/Azure/aks-engine/blob/master/docs/community/README.md#community) doc didn't get updated after the [#aks-engine-users](https://kubernetes.slack.com/archives/CU3N85WJK) Kubernetes Slack channel was created.
**Notes**:
=> docs: join the #aks-engine-users Slack channel (not #provider-azure)

vhd/packer/configure-windows-vhd.ps1, vhd/packer/windows-vhd-builder.json
April patches for windows are released
https://support.microsoft.com/en-us/help/4549949
**Notes**:
=> chore: updating Windows VHD to include April patches

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, parts/k8s/windowsinstallopensshfunc.ps1, parts/k8s/windowskubeletfunc.ps1, pkg/api/azenvtypes.go, pkg/api/const.go, pkg/api/converterfromapi_test.go, pkg/engine/templates_generated.go, scripts/collect-windows-logs.ps1, test/e2e/test_cluster_configs/no_outbound.json, vhd/packer/configure-windows-vhd.ps1, vhd/packer/install-dependencies.sh, vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1098.200409.txt
Upgrade Windows VHD image to April release
**Notes**:
Cherry-pick below 7 commits from v0.49.0:
762984105d1df1b5a49f8ba3e6c9366bb4e2bc7f
From <https://github.com/Azure/aks-engine/commit/762984105d1df1b5a49f8ba3e6c9366bb4e2bc7f> 
9a78964a74df305e2a2f17c141e05d4dbf660787
From <https://github.com/Azure/aks-engine/commit/9a78964a74df305e2a2f17c141e05d4dbf660787> 
44e353debf213d1d4757130c2c32e261f1817470
From <https://github.com/Azure/aks-engine/commit/44e353debf213d1d4757130c2c32e261f1817470> 
414015252d65948ee13948aa38da9e3771eb2e54
From <https://github.com/Azure/aks-engine/commit/414015252d65948ee13948aa38da9e3771eb2e54> 
96c8c3ee0190da85377d9a17a46353b41f156ba2
From <https://github.com/Azure/aks-engine/commit/96c8c3ee0190da85377d9a17 …
=> Upgrade Windows VHD image to April release

parts/k8s/cloud-init/artifacts/cse_config.sh, pkg/engine/templates_generated.go
This PR fixes  @bug introduced by this PR #2862. It checks for string in condition check instead of boolean
**Notes**:
=> fix: Fixed bug in condition check for dualstack

parts/k8s/kuberneteswindowsfunctions.ps1, parts/k8s/kuberneteswindowssetup.ps1, pkg/engine/templates_generated.go
cherry-pick 54c975605347ff07b8a65fb786aa5eab58050400 from v0.49.0
**Notes**:
cherry-pick 54c975605347ff07b8a65fb786aa5eab58050400 from v0.49.0
=> feat: adding kubelet and csi-proxy-server as windows defender excluded processes (#2967)

pkg/api/azenvtypes.go, vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202004_2020.04.21.txt, vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202004_2020.04.21.txt
This PR revs Linux Ubuntu 18.04-LTS and 16.04-LTS VHDs to `2020.04.21`.
Includes the following additive pre-downloaded artifacts:
- Azure CNI version 1.1.0
No longer includes the following:
- Azure CNI version 1.0.29
Includes the following additive pre-installed apt packages:
- linux-headers-5.0.0-1036-azure
No longer includes the following:
- linux-headers-5.0.0-1035-azure
Includes the following additive pre-downloaded images:
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.18.2
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.18.2
- mcr.microsoft.com/oss/kubernetes/kube-proxy:v1.18.2
- mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.18.2
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.17.5
- …
=> chore: rev Linux VHDs to 2020.04.21
