pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1158.200421.txt

Including April security updates in the windows VHD
**Notes**:

feat: Updating Windows VHDs with 4B patches

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

containerd was moved to our prod repos, so let's use that.
**Notes**:

chore: Use prod repos for containerd.

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go

fix: don't hardcode csi enableproxy in kubeclusterconfig.json

---

test/e2e/test_cluster_configs/base.json

This PR skips individual E2E tests after "add pool", "scale in", and "upgrade" for the base cluster config test, to ensure that the entire E2E run finishes more quickly.
**Notes**:

test: faster base config test

---

parts/k8s/windowsnodereset.ps1
pkg/engine/templates_generated.go

Correct wrong file name in the logs
Fixes #3137
**Notes**:

fix: Correct wrong file name in the logs

---

pkg/api/azenvtypes.go

feat: update aks-ubuntu vhd version to 2020.04.23

---

docs/tutorials/day2-operations.md

Fix typos in day2-operations.md
**Notes**:

docs: fix typos in day2-operations.md

---

vhd/packer/install-dependencies.sh

build: fetch k8s node binaries from kubernetesartifacts storage

---

docs/topics/azure-stack.md
examples/azure-stack/kubernetes-azurestack.json
examples/azure-stack/kubernetes-windows.json

docs: supported versions for disconnected Azure Stacks using VHD 2020.03.19

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go

Expose error details in Windows CSE for better troubleshooting 
Fix #3156
**Notes**:

fix: Expose error details in Windows CSE

---

.pipelines/e2e-step-template.yaml

Disables the artifact publishing steps for now, so PR e2e jobs have a hope of going green. 💚 
**Notes**:

ci: disable artifact publishing

---

pkg/engine/engine_dcos.go

This has unintended side-effects, and doesn't appear to do what it was originally intended for (remove from test coverage calculations)
**Notes**:

chore: remove //+build !test pragma

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

Going forward Intel is changing its format of the checksum file to *.cfg. This PR updates the sgx driver installation to reflect that.
**Notes**:

fix: update dcap checksum file

---

scripts/validate-go.sh

This shell hackery is no longer necessary now that golangci/golangci-lint#276 is fixed.
**Notes**:

refactor: simplify golangci-lint invocation

---

.devcontainer.json
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
hack/tools/Makefile
makedev.ps1

See https://github.com/deis/docker-go-dev/releases/tag/v1.27.0
Updates some tools, specifically golangci-lint.
**Notes**:

chore: update go-dev image to v1.27.0

---

vhd/packer/configure-windows-vhd.ps1

mcr.microsoft.com/oss/kubernetes/pause:1.3.1 has signed versions of pauseloop.exe and wincat.exe
**Notes**:

chore: Updating Windows VHD build to use mcr.microsoft.com/oss/kubernetes/pause:1.3.1

---

README_zh-CN.md
docs/community/e2e-output-example.log
docs/topics/windows.md
docs/tutorials/custom-vnet.md
docs/tutorials/day2-operations.md
docs/tutorials/quickstart.md
test/e2e/cleanup.sh
vhd/packer/vhd-rg-cleanup.sh

Silences deprecation warnings about the `az group deployment` command.
Fixes #2968.
**Notes**:

refactor: use newer "az deployment group" CLI syntax

---

pkg/api/azenvtypes.go

Update AKS VHD version to 2020.05.06

update: Update AKS VHD version

---

cmd/get_logs.go
scripts/collect-logs.sh

Linux log collection script renames a few files, adds headers and collects some more data if Azure Stack.

chore: get-logs command on Azure Stack

---

examples/addons/azure-policy/README.md
pkg/api/k8s_versions.go

Updates GK to 3.1 beta 8
Updates Policy addon to `prod_20200505.1`
**Notes**:

chore: Update Policy addon versions

---

docs/topics/sgx.md

1. Fixed typo in DCsv2 SKU references 
2. Added documentation about labels before k8s v1.17
3. Removed references to the device plugin as optional/alpha
4. Fixed the public repo to the 1.0 release
**Notes**:

docs: update sgx plugin docs

---

docs/tutorials/quickstart.md

Scoop is a good tool for install packages. By this PR https://github.com/ScoopInstaller/Main/pull/1010 , scoop can install aks-engine. Scoop will help user to download the aks-engine from Github release and it is secure for users. 
None
**Notes**:

docs: Update quickstart.md to add scoop install guide

---

pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Upgrading cni to v.1.1.2. 
1. Has minor fixes
3. Windows CNI dualstack support
**Notes**:

chore: updating cni to v1.1.2

---

vhd/packer/configure-windows-vhd.ps1

May 2020 Windows updates were released
**Notes**:

chore: update Windows VHD to use May 2020 updates

---

test/e2e/test_cluster_configs/containerd.json

fix: Add Windows node pool to containerd tests

---

parts/k8s/cloud-init/artifacts/init-aks-custom-cloud.sh
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/types.go
pkg/engine/armvariables.go
pkg/engine/const.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/vmextensions.go

AKS custom cloud setup

---

.pipelines/marketplace-sku.yaml

#3239 updated new-windows-sku.sh to expect a CONTAINER_RUNTIME env var.
This PR sets passes the pipeline variable to the dev container executing the script.
**Notes**:

ci: passing container runtime var to new-windows-sku.sh

---

parts/k8s/kuberneteswindowssetup.ps1
parts/k8s/windowsazurecnifunc.ps1
pkg/engine/templates_generated.go

This PR only adds the `"environment": "mas"` Azure CNI config if we're in an Azure Stack custom cloud profile context.
**Notes**:

fix: custom cloud Azure CNI config for Windows

---

docs/topics/README.md
docs/topics/proxy-servers.md

This PR contains a few considerations and guidance about the use of proxy servers in connected and disconnected scenarios of Azure and Azure Stack Hub. This applies to AKS-engine as well as (at least partially) to AKS and Kubernetes in general.
- no issues addressed in this PR
**Notes**:

docs: AKS-engine (on Stack) considerations around the use of proxy servers

---

pkg/api/azenvtypes.go

update vhd version to 2020.05.13

feat: Update vhd version 2020.05.13

---

docs/topics/sgx.md

1. Fix capitalization in reference to SGX 
**Notes**:

docs: fix capitalization

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1217.200513.txt

feat: Updating Windows VHDs to include May patches

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1

mcr.microsoft.com/oss/kubernetes/pause:1.3.1 contains signed windows binaries
**Notes**:

chore: update Windows pause image

---

pkg/armhelpers/support_validator.go
pkg/armhelpers/support_validator_test.go

The image validation for raw Windows image on Azure Stack Hub should be based on image information from api model only.
**Notes**:

fix: update Windows image validate on Azure Stack Hub

---

pkg/engine/template_generator.go

Last revert change removed generateUserAssignedIdentityClientIDParameterForWindows
**Notes**:

fix: Fix last revert change

---

pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

chore: cherry pick c7109ed99 to get the latest azure cni versions

---

parts/k8s/kubeletstart.ps1
pkg/engine/templates_generated.go

fix: fix issue provisioning windows nodes with kubenet

---

parts/k8s/addons/azurefile-csi-driver-deployment.yaml
pkg/engine/templates_generated.go

This fixes a typo in the azurefile CSIDriver spec.
**Notes**:

fix: addon-manager definition should be under "labels"

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

Cherry-pick of https://github.com/Azure/aks-engine/pull/3293 and #3294.
Fix: increase apiserver connection timeout for private apiserver.
**Notes**:

fix: increase apiserver connection timeout for private apiserver

---

parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

fix: ensure ERR_K8S_API_SERVER_DNS_LOOKUP_FAIL is returned when DNS check fails.
It also increase timeouts for apiserver DNS check.
**Notes**:

fix: ensure ERR_K8S_API_SERVER_DNS_LOOKUP_FAIL is returned when DNS check fails

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/init-aks-custom-cloud.sh
pkg/api/types.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/vmextensions.go

fix: Fix initAKSCustomCloud script; use customized outbound test url

---

pkg/api/azenvtypes.go

feat: Update ASK VHD to 2020.05.21

---

pkg/engine/vmextensions.go

fix: Fix VMAS cse

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

This PR updates the AKS Engine-provided version of coredns to v1.6.9. See:
https://github.com/coredns/coredns/releases/tag/v1.6.9
**Notes**:

chore: update coredns to 1.6.9

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

This PR updates the version of kube-dashboard delivered w/ the `kubernetes-dashboard` addon to v2.0.1. See:
https://github.com/kubernetes/dashboard/releases/tag/v2.0.1
**Notes**:

chore: update kube-dashboard addon to v2.0.1

---

test/e2e/test_cluster_configs/everything.json

This PR ensures we always run the "everything" E2E cluster configuration against all versions of Kubernetes.
**Notes**:

test: run everything E2E config against all cluster versions

---

pkg/api/const.go
vhd/packer/install-dependencies.sh

This PR updates the core CNI binaries to v0.8.6
See:
https://github.com/containernetworking/plugins/releases/tag/v0.8.6
**Notes**:

chore: update CNI binary to 0.8.6

---

vhd/notice/notice_windows.txt
vhd/packer/windows-vhd-builder.json

chore: add legal notice for Windows VHD

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

fix: Sync downloadAzureCNI

---

pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

This PR upgrades cni to v1.1.3. CNI has fixes for
1. disabling ra for interfaces created by CNI
2.  fix for TCP lb scenario where nodepool acts as router/proxy
**Notes**:

chore: upgrade cni to v1.1.3

---

test/e2e/test_cluster_configs/sgx.json

This PR enables testing of SGX-enabled scenarios across all supported Kubernetes versions.
**Notes**:

test: remove Kubernetes version restrictions from sgx tests

---

pkg/api/azenvtypes.go
pkg/api/common/helper.go
pkg/api/const.go
pkg/api/defaults.go
pkg/armhelpers/support_validator.go

Add image config for GPU VHD, also make NvidiaEnabledSKUs accessible publicly so RP can use it to generate error message.

feat: add support for GPU VHD

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

New moby patch release
N/A
**Notes**:

chore: Bump moby version to 3.0.12

---

pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/defaults.go
pkg/armhelpers/support_validator.go

Add gen2 GPU SKU and OS config

feat: Add gen2 GPU SKU and OS config

---

examples/windows/kubernetes-windows-1909.json
test/e2e/engine/template.go

Update to the testing function was required to run tests again 1909 correctly.
#2385
**Notes**:
cc: @marosset

test: Add test support for windows server 1909

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202006_2020.06.02.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202006_2020.06.02.txt

This PR updates Linux VHDs to 2020.06.02.
Includes a new Linux kernel version for 18.04-LTS:
- `Linux version 5.3.0-1022-azure (buildd@lcy01-amd64-001) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #23~18.04.1-Ubuntu SMP Mon May 11 11:55:56 UTC 2020`
Includes a new Linux kernel version for 16.04-LTS:
- `Linux version 4.15.0-1083-azure (buildd@lcy01-amd64-028) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #93~16.04.1-Ubuntu SMP Thu May 7 18:39:44 UTC 2020`
Includes the following new component versions:
- moby v3.0.12
Includes the following additive Azure Stack container images:
- mcr.microsoft.com/oss/kubernetes/kube-apiserver:v1.17.6-azs
- mcr.microsoft.com/oss/kubernetes/kube-controller-manager:v1.17.6-azs
- …

chore: rev AKS Engine VHDs to 2020.06.02

---

pkg/api/azenvtypes.go

feat: update AKS VHD to 2020.05.31

---

parts/k8s/addons/azure-cni-networkmonitor.yaml
parts/k8s/addons/cluster-autoscaler.yaml
parts/k8s/addons/coredns.yaml
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go

Standardizes nodeSelector
Fixes #3351
**Notes**:

chore: standardize nodeSelectors

---

docs/tutorials/containermonitoringaddon.md
parts/k8s/addons/container-monitoring.yaml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/api/defaults_test.go
pkg/engine/templates_generated.go
pkg/engine/testdata/key-vault-certs/kubernetes.json

Updated api versions for cluster role and cluster role binding
Adding permissions for nodes/proxy
Updating agent image version to ciprod05262020

feat: Update container monitoring addon for may omsagent release 

---

test/e2e/test_cluster_configs/windows/sac/sac-1903.json
test/e2e/test_cluster_configs/windows/sac/sac-1909.json

adds e2e tests for 1903/1909 windows versions
**Notes**:
cc: @marosset

test: add sac test configs

---

parts/k8s/addons/kubernetes-dashboard.yaml
parts/k8s/addons/metrics-server.yaml
parts/k8s/addons/nvidia-device-plugin.yaml
pkg/engine/templates_generated.go

This is a simple PR that changes a few (working) non-standard (as compared to other addons) nodeSelector declarations so that it's 100% consistent.
**Notes**:

chore: standardize nodeSelector declarations in addons

---

docs/topics/clusterdefinitions.md
parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
pkg/api/defaults-apiserver.go
pkg/engine/templates_generated.go
pkg/engine/testdata/key-vault-certs/kubernetes.json

Disables deprecated apiserver insecure-port
**Notes**:

fix: disable apiserver insecure-port

---

docs/topics/upgrade.md
examples/cosmos-etcd/readme.md
pkg/api/common/versions.go
test/e2e/config/config.go

This PR removes the clumsy and insensitive "whitelist" shortcut terminology in favor of more expressive documentation, improving clarity and cultural empathy.
**Notes**:

docs: remove references to "whitelist"

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

fix: Fix cleanup container image

---

parts/k8s/kubeletstart.ps1
pkg/engine/templates_generated.go

ported from https://github.com/Azure/aks-engine/pull/3426/
**Notes**:

fix: FlexVolume broken issue on Windows

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
pkg/engine/templates_generated.go

fix: add retry for the image clean up.

---

test/e2e/test_cluster_configs/network_policy/azure.json

This PR ensures we're testing Azure NetworkPolicy addon against all versions of Kubernetes.
**Notes**:

test: test Azure NetworkPolicy against all Kubernetes versions

---

parts/k8s/cloud-init/artifacts/cse_install.sh

export the missing functions.

---

pkg/engine/templates_generated.go

fix: forgot to do the templates generation.

---

docs/topics/sgx/device-plugin-before-k8s-1-17.yaml
docs/topics/sgx/device-plugin.yaml

Updated the security context related configs of the sgx device plugin to be more restrictive.
**Notes**:

fix: make security context configs more restrictive

---

parts/k8s/kuberneteswindowsfunctions.ps1
pkg/api/common/helper.go
pkg/api/common/helper_test.go
pkg/api/k8s_versions.go
pkg/api/types_test.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Fresh off the presses from Azure Pipelines: "fixes a bug in the CDPX and release build." Specifically, Windows binaries are now properly signed.
cc: @jchauncey 
**Notes**:

chore: update pause image to 1.3.2

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200610.txt

cherry-pick Jame's commit to update Windows VHD image to `17763.1282.20061`
**Notes**:

chore: Add June Patches

---

pkg/api/azenvtypes.go

feat: use 2020.06.10 VHD for AKS

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200610.txt

Adds release notes and updates default windows image to use June's patches
**Notes**:
CC: @AbelHu

chore: Add June Windows Patches

---

vhd/packer/configure-windows-vhd.ps1

These images will be used by CSI Drivers.
**Notes**:
/cc @andyzhangx @xuto2

chore: add csi windows related images

---

test/e2e/kubernetes/workloads/busybox-master.yaml

Use the full toleration to match the taint on control plane nodes.
**Notes**:

test: use full toleration for testing scheduling to control plane

---

test/e2e/kubernetes/kubernetes_test.go

This PR allows 3 retries for E2E pod scheduling tests to accommodate occasional flakes.
**Notes**:

test: retry pod scheduling attempts

---

test/e2e/test_cluster_configs/everything.json

This PR skips running the "stability" tests for the "test the kitchen sink of features" cluster config, as the primary objective of testing that cluster configuration is to validate functionality.
**Notes**:

test: skip stability tests for "everything" E2E cluster config

---

parts/k8s/addons/calico.yaml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/network_policy/calico.json
test/e2e/test_cluster_configs/network_policy/calico_azure.json

This PR enables configurable usageReportingEnabled for users of the calico addon. See here for more info:
https://docs.projectcalico.org/reference/felix/configuration
**Notes**:

feat: enable configurable usageReportingEnabled in calico addon

---

pkg/api/types.go

Current code will report client error when customer inputs some careless case-insensitive parameter. This is annoying to customers. It may also have a bad impact on system QoS. We're making our RP code case-insensitive. 
**Notes**:

fix: change string comparison way to remove case-sensitive for customer input.

---

vhd/packer/configure-windows-vhd.ps1

Including hotfixed Windows k8s binaries with fixes to metrics/stats if pods use init contianers.
**Notes**:

chore: add 1.16.11, 1.17.7, 1.18.4 hotfix packages to Windows VHD

---

pkg/api/azenvtypes.go

feat: Use VHD 2020.06.18

---

test/e2e/test_cluster_configs/windows/sac/sac-1903.json
test/e2e/test_cluster_configs/windows/sac/sac-1909.json
test/e2e/test_cluster_configs/windows/sac/sac-2004.json

Adds Windows SAC 2004 e2e test.  This should have been a part of #3516 but the file was missing.
**Notes**:

test: Add Windows SAC 2004 e2e

---

pkg/api/k8s_versions.go

fix: add windows hotfix overrides for 1.18.2, 1.16.10, 1.15.12 for AKS

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

Testing moby 3.0.13
**Notes**:

chore: bump moby to 3.0.13

---

scripts/collect-logs.sh

Include audit logs to the list of files collected by `get-logs`.
**Notes**:

chore: get-logs collects audit logs

---

docs/howto/troubleshooting.md
docs/topics/azure-api-throttling.md

This PR adds a document to help aid Azure API throttling situations that can be helped with a newer cloudprovider version.
**Notes**:

docs: add Azure API throttling doc

---

parts/k8s/addons/kube-proxy.yaml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/api/k8s_versions.go
pkg/api/k8s_versions_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

Use kube-proxy image instead of hyperkube for 1.16.
Fixes #3529.
**Notes**:

fix: use kube-proxy image instead of hyperkube for 1.16

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

fix: downgrade blobfuse to 1.1.1 since there is breaking change on 1.2.3
more details could be found here: https://github.com/Azure/kubernetes-volume-drivers/issues/66#issuecomment-649188681
**Notes**:

fix: downgrade blobfuse to 1.1.1 since there is breaking change on 1.2.3

---

pkg/api/common/versions.go

feat: Add support for 1.15.12/1.16.10/1.17.7/1.18.4

---

pkg/api/vlabs/validate_test.go

This PR fixes UT following from #3544 
**Notes**:

test: fix UT

---

docs/topics/azure-api-throttling.md

The original version of this document incorrectly stated that the kubelet systemd service was able to stop the controller-manager process. These updates provide working examples of how to actually stop kube-controller-manager (and/or cloud-controller-manager) during Azure API throttling events.
**Notes**:

docs: update throttling doc

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
test/e2e/cluster.sh
test/e2e/engine/template.go

This PR allows us to pass in a custom kube-proxy image as environment variable to the E2E test runner, which will allow us to test an arbitary kube-proxy build across a matrix of cluster configurations.
**Notes**:

test: enable CustomKubeProxyImage override

---

pkg/api/azenvtypes.go
pkg/api/common/versions.go

feat: use AKS VHD 2020.06.25

---

docs/topics/clusterdefinitions.md

Ensure the calico addon docs have the correct heading name.
**Notes**:

docs: fix incorrect calico addons section heading

---

test/e2e/kubernetes/daemonset/daemonset.go
test/e2e/kubernetes/deployment/deployment.go
test/e2e/kubernetes/job/job.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/storageclass/storageclass.go

This PR ensures we retry kubectl apply and related commands during E2E tests.
**Notes**:

test: ensure all resource creation attempts are retried

---

pkg/api/types.go

feat: Add aks custom cloud env

---

docs/topics/clusterdefinitions.md
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/const.go
pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go
pkg/api/defaults.go
pkg/api/defaults_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

This pr is required by AKS private cluster BYO DNS scenario. Since this pr also changes the api model, the pr need to be merged into master.
For AKS BYO DNS, we'll config the /etc/hosts file on all agent nodes so we can resolve the private dns without azure private dns zone.
**Notes**:

feat: reconcile private hosts for AKS BYO DNS

---

pkg/api/azenvtypes.go

Add AKS VHD version 2020.06.30

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1282.200702.txt

Adds VHD with the signed powershell scripts #3441 
**Notes**:

chore: add VHD with signed powershell scripts

---

test/e2e/cluster.sh

This PS assigns a default value to the `IDENTITY_SYSTEM` variable in the cluster.sh test script so that test runners not passing that value in can still work.
**Notes**:

test: set default IDENTITY_SYSTEM

---

pkg/api/azenvtypes.go

switch to use the new 07 vhd.

---

pkg/api/azenvtypes.go

chore: switch to use the 07 vhd for gpu too.

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Updates the signed powershell package to include new file introduced in #3572 
**Notes**:
/cc @AbelHu  @feiskyer 
Follows update procedure from https://github.com/Azure/aks-engine/blob/master/docs/topics/windows-provisioning-scripts.md#updates

chore: Update the signed powershell package version

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-vhd-builder.json

Adds release notes and updates default windows image to use July's patches
**Notes**:

chore: July 2020 windows patches

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/dashboard/releases/tag/v2.0.3
**Notes**:

chore: update Dashboard addon to v2.0.3

---

pkg/api/azenvtypes.go
pkg/api/k8s_versions.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-aks-17763.1339.200717.txt

**Notes**:
chore: Cherrypick July patches to v0.53.0 (#3610)
chore: Add Windows VHD with 7B

chore: Add Windows VHD with 7B

---

pkg/armhelpers/support_validator.go

remove GPU image config in support_validator.go

chore: remove more GPU image config

---

pkg/api/common/versions.go

feat: Add K8s1.16.13/1.17.9/1.18.6 for AKS

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-aks-17763.1339.200717.txt

This sets the default vhd built with July patches off the cherry picks to this branch for AKS
See #3610
**Notes**:
/assign @AbelHu

chore: Release v0.53.0 update vhd with July patches

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1339.200716.txt

July VHD with latest patches and hotfixes
**Notes**:

chore: update Windows default VHD for July

---

test/e2e/kubernetes/kubernetes_test.go

In response to a test flake that resulted from a Windows node not being able to schedule pods (but the test results not showing that explicitly), this PR adds a discrete "should be able to schedule a pod to a Windows node" test, and does all pod scheduling tests before running other tests that in fact depend upon pod scheduling.
**Notes**:

test: run pod schedule tests first

---

test/e2e/kubernetes/kubernetes_test.go

This PR fixes a dumb error courtesy of yours truly that assigns variable values into the wrong lexical scope in the E2E test runner.
**Notes**:

test: move E2E global vars out of "not block ssh port" conditional block

---

pkg/engine/params.go
pkg/engine/params_test.go

The PR https://github.com/Azure/aks-engine/pull/2725 was merged on Feb 20 but aks-engine v0.47.0 was released on Feb 19. So the aks-engine branch used by AKS does not contain this fix. We need to apply the fix in the aks-engine branch used by aks.
**Notes**:

feat: Set vnetCidr by the address space of the vnet

---

pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

updated cni version to latest release - 1.1.6.
**Notes**:

chore: Upgrade CNI to v1.1.6

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go

chore: Only use Windows telemetry client when enableTelemetry is true
**Notes**:

chore: Only use Windows telemetry client when enableTelemetry is true

---

pkg/api/azenvtypes.go
pkg/api/defaults-custom-cloud-profile.go
pkg/api/defaults.go
pkg/helpers/helpers.go
pkg/helpers/helpers_test.go

feat: add aks custom cloud in GetTargetEnv
Add CSIProxyURL
**Notes**:

feat: Add aks custom cloud and CSIProxyURL

---

pkg/api/defaults-custom-cloud-profile.go
pkg/helpers/helpers.go

fix: Support USNat and USSec

---

pkg/api/defaults-custom-cloud-profile.go

chore: Remove one duplicated line
**Notes**:

chore: Remove one duplicated line

---

examples/service-mesh/README.md
examples/service-mesh/istio.json

I had to deploy Istio 1.6 recently and figured I may as well share what I learnt. 
I am not expert at all, so please feel free to correct anything odd-looking.
**Notes**:

docs: update stale Istio page and example

---

pkg/api/types.go

GPU distros were not added to some funcs.

fix: Fix distro related change

---

pkg/api/types.go
pkg/helpers/helpers.go

feat: Support AKS custom cloud
**Notes**:

feat: Support AKS custom cloud

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/api/types.go
pkg/engine/templates_generated.go

fix: Generate AzureStackCloud.json for akscustomcloud
**Notes**:

fix: Generate AzureStackCloud.json for akscustomcloud

---

pkg/api/azenvtypes.go

feat: Set AKS VHD to 2020.08.06

---

docs/topics/sgx.md

docs: update the SGX DCAP version mentioned in the sgx instructions

---

vhd/packer/configure-windows-vhd.ps1

As part of #3641 the default for the api model was moved to docker 19.3.11 and the update for the VHD was missed. 
**Notes**:

chore: Update  docker version in VHD to fix log rotation issue

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-vhd-builder.json

August 11 patches for windows are released
https://support.microsoft.com/en-us/help/4565349
**Notes**:

chore: update Windows VHD to include 8B patches

---

pkg/api/azenvtypes.go

feat: Set AKS VHD version to 2020.08.13

---

pkg/api/azenvtypes.go

fix: Set windows VHD version to 17763.1339.200718

---

OWNERS

docs: adding James to OWNERS

---

pkg/api/azenvtypes.go

This PR updates the Windows VHD reference to the latest available version for the sku for this release, which will enable new cluster operations with Windows node pools.
Related to #3700
**Notes**:

fix: update v0.50 to new 17763.1158.200422

---

examples/dualstack/README.md

docs: update limitations in dualstack docs

---

pkg/api/azenvtypes.go

feat: update aks vhd to 20200819

---

parts/k8s/windowscontainerdfunc.ps1
pkg/engine/templates_generated.go
scripts/collect-windows-logs.ps1

Enables and Adds log collection for containerd hyperv for debugging tests and support purposes. 
**Notes**:

feat: collect hyperv containerd logs

---

docs/topics/features.md
examples/windows/kubernetes-hybrid.azure-containerd.json
examples/windows/kubernetes-hybrid.kubenet-containerd.json
test/e2e/engine/template.go
test/e2e/test_cluster_configs/containerd.json

ci: use 1.4.0 containerd release for windows in CI

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.08.24.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.08.24.txt

This PR updates Ubuntu 18.04-LTS and Ubuntu 16.04-LTS VHDs to version `2020.08.24`. See release notes for the full description of included artifacts.
**Notes**:

chore: rev Linux VHDs to 2020.08.24

---

test/e2e/test_cluster_configs/everything.json

This PR removes the azure-arc-onboarding addon from the "everything" test cluster config, because there is already a test cluster config dedicated to validating that addon.
**Notes**:

test: disable azure-arc-onboarding addon in everything cluster config

---

test/e2e/kubernetes/scripts/systemd-validate.sh

The "kill docker and validate that systemd restarts it" shouldn't be run if using containerd.
**Notes**:

test: don't try to kill docker if using containerd

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/engine/templates_generated.go

This PR ensures that containerd install flows always get moby-runc
**Notes**:

chore: always install moby-runc

---

docs/topics/azure-stack.md
examples/azure-stack/kubernetes-azurestack.json
examples/azure-stack/kubernetes-windows.json

Update azure stack doc for aks-engine v0.55.0
**Notes**:

doc: update azure stack doc for aks-engine v0.55.0

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/masternodecustomdata.yml
pkg/engine/armresources_test.go
pkg/engine/const.go
pkg/engine/masterarmresources_test.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/virtualmachinescalesets_test.go
pkg/engine/vmextensions.go
pkg/engine/vmextensions_test.go

This PR improves the CSE error handling due to the control plane being unable to connect to the cluster apiserver.
Specifically, this PR makes the following changes:
- validate basic apiserver connectivity and cluster functionality (via `kubectl cluster-info`) *before* validating "init" addons, because being able to connect to the cluster apiserver endpoint is a precondition of validating "init" addons
- remove the non-working "validate that kube-addon-manager pods" are present check, prefer the concrete check of waiting for specific init addon outcomes:
- the arrival of PodSecurityPolicy-provided resources, if the pod-security-policy addon is enabled
- the arrival of the kubernetes-dashboard namespace, if the kubernetes-dashboard addon is enabled
- the arrival of …

fix: validate k8s control plane before addons

---

parts/k8s/kubernetesparams.t
pkg/api/defaults_test.go
pkg/engine/templates_generated.go

fix: update template for moby version validation

---

pkg/api/const.go
vhd/packer/install-dependencies.sh

See https://github.com/containernetworking/plugins/releases/tag/v0.8.7
**Notes**:

chore: update CNI plugins to v0.8.7

---

examples/ipv6/README.md
examples/ipv6/kubernetes.json

- Adds example api model for IPv6 clusters
- Adds docs for IPv6 
**Notes**:

docs: add doc and example api model for IPv6

---

examples/e2e-tests/kubernetes/release/default/definition.json

This PR removes the tiller (helm v2) addon from the PR E2E cluster config, as we don't want to suggest that we recommend using helm v2 over helm v3.
**Notes**:

test: remove tiller addon from PR E2E cluster configuration

---

cmd/upgrade.go

fix: Enable Windows VHD version update in aks-engine upgrade scenario

---

hack/tools/Makefile
hack/tools/go.mod
hack/tools/go.sum
vhd/publishing/add-image-version-to-sku.sh

Updates to a version of pub that supports categoryMap fields.
https://github.com/devigned/pub/pull/24
**Notes**:

ci: updating pub to v0.2.6 to address publishing issues

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-vhd-builder.json

chore: targeting sept updates for Windows 2019 VHD

---

parts/k8s/windowsazurecnifunc.ps1
pkg/engine/templates_generated.go

feat: Add ACL rules for Windows

---

parts/windowsparams.t
pkg/engine/params.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachines.go
pkg/engine/virtualmachinescalesets.go

feat: Generate ARM template for Windows agent pool for different VHD images
**Notes**:

feat: Generate ARM template for Windows agent pool for different VHD images

---

docs/topics/gpu.md
parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go

> The current NVIDIA driver version is 418 with Ubuntu 18.04 and the latest version from NVIDIA is 450. 418 doesn't support a lot of current frameworks, like pytorch. Also needed to support CUDA.
fix #3814
**Notes**:

fix: update GPU driver to 450.51.06 (#3814)

---

cmd/upgrade.go

Checks if the windows profile exists before accessing in upgrade windows VHD
fixes #3819 
**Notes**:

fix: check if windows profile exists in upgrade

---

README.md
SUPPORT.md

Microsoft suggested a standard support policy format for open source projects. It's not set in stone yet, but this implements the current suggestion.
**Notes**:

docs: clarify project support policy in SUPPORT.md

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Generated a new package of signed powershell scripts which include https://github.com/Azure/aks-engine/pull/3822
**Notes**:

chore: update signed powershell script package to include azure CNI fixes

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.09.14.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.09.14.txt

This PR updates the Linux VHDs to version `2020.09.14`.
**Notes**:

chore: rev Linux VHDs to 2020.09.14

---

.github/PULL_REQUEST_TEMPLATE.md

Encourages pull requests to verify that their content does or does not contain code from elsewhere, and that required attribution has been added.
Fixes #3755.
This wording is inspired by our friends at the [Open Service Mesh](https://github.com/openservicemesh/osm/blob/main/.github/pull_request_template.md) project, but does not require formal attribution.
**Notes**:

docs: add required attribution reminder to PR template

---

vhd/packer/configure-windows-vhd.ps1

Follow up to https://github.com/Azure/aks-engine/pull/3816
**Notes**:

chore: adding 1.19.1 bits to Windows VHD

---

README.md
docs/faq.md

This PR removes the mention in the landing page README.md about AKS Engine being a library for AKS.
Historically, this was true, but more and more any AKS Engine usage by AKS is more or less piecemeal, and not obvious to the public, so we should stop suggesting otherwise.
**Notes**:

docs: remove mention about library for AKS

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.200917.txt

chore: updating Windows VHD with new cached artifacts

---

pkg/engine/params.go

After the PR https://github.com/Azure/AgentBaker/pull/333 for Linux is merged, I will merge this PR and vendor aks-engine to agentbaker and then vendor them both into AKS.
The PR https://github.com/Azure/aks-engine/pull/3812 for Windows was merged.
**Notes**:

fix: Set all ip address ranges in vnetCidr

---

pkg/api/azenvtypes.go

feat: update VHD version to 2020.09.17

---

docs/howto/troubleshooting.md
docs/topics/azure-stack.md
examples/azure-stack/kubernetes-azurestack.json
examples/azure-stack/kubernetes-windows.json

Include v0.55.4 to supported Azure Stack versions table
**Notes**:

docs: add v0.55.4 to supported Azure Stack versions

---

pkg/api/common/versions.go
pkg/operations/kubernetesupgrade/upgradecluster_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1188
**Notes**:

feat: add support for Kubernetes v1.18.9

---

OWNERS

This PR updates the OWNERS file, welcoming @jadarsie, and thanking @brendandburns and @PatrickLang ❤️ 
**Notes**:

ci: update OWNERS

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/dashboard/releases/tag/v2.0.4
**Notes**:

chore: update Dashboard addon to v2.0.4

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Update to the latest Azure CNI 1.1.7 for bug fixes
No github issues though we have a customer report VIVEK AGGARWA believes will be fixed by this release. 
**Notes**:

chore: update azure cni to 1.1.7

---

test/e2e/cluster.sh

Run `aks-engine rotate-certs` before `make test-kubernetes` if `ROTATE_CERTS` flag is set
`ROTATE_CERTS` should default to `false` as `rotate-certs` has regressed.
**Notes**:

test: E2E optionally validates rotate-certs

---

pkg/api/azenvtypes.go

update vhd release

---

docs/topics/update.md
docs/tutorials/cli-overview.md

This PR adds more documentation clarification that `aks-engine update` can't be used to update the control plane.
**Notes**:

docs: clarify that update is for node pools only

---

pkg/engine/params.go
pkg/engine/virtualmachines.go
pkg/engine/virtualmachinescalesets.go

Support ImageRef and CustomImage in WindowsProfile.
**Notes**:

fix: Support ImageRef in WindowsProfile

---

pkg/helpers/azureconst.go

feat: Add Dv4 and DSv4 series SKU

---

.pipelines/e2e-job-template.yaml
.pipelines/pr-e2e.yaml
examples/e2e-tests/kubernetes/release/default/definition.json
test/e2e/engine/template.go

This PR adds containerd configuration to the PR E2E jobs, so that we test containerd scenarios before merging changes.
**Notes**:

ci: add containerd PR E2E tests

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1397.201006.txt

feat: Target new windows VHD with new K8s binaries (1.19.2, 1.18.9, etc)

---

.github/workflows/nightly-build.yaml

Add CI for adding a nightly build/release of aks-engine.
This will help increase test velocity for various upstream projects that rely on aks-engine for testing.
**Notes**:

ci: adding github actions to create nightly builds

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.10.06.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.10.06.txt

This PR updates the Linux VHDs to version `2020.10.06`.
**Notes**:

chore: rev Linux VHDs to 2020.10.06

---

pkg/engine/networksecuritygroups.go

These NSG rules were added specifically for Azure Stack regarding a previous bug. Now the bug on Azure Stack has been fixed, these NSG rules can be removed.
**Notes**:

fix: remove NSG rules for AzureStack

---

test/e2e/test_cluster_configs/flatcar/flatcar.json

until #3920 is fixed we aren't able to test flatcar node configurations
**Notes**:

test: skip tests for flatcar cluster config

---

pkg/engine/virtualmachinescalesets.go
test/e2e/test_cluster_configs/vmss_master.json

This PR fixes a regression introduced in #3767. And adds E2E test coverage so we'll know when we break it next time. :/
Fixes #3910 
**Notes**:

fix: VMSS control plane + availability zones

---

pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

updated cni version to latest release - 1.1.8.
**Notes**:

chore: Upgrade CNI to v1.1.8

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/cloud_controller_manager.json

This PR disables system-assigned identity (MSI) in the cloud-controller-manager test config so that we can test azurefile scenarios. Also, updates the test so it doesn't run if user-assigned identity is enabled.
**Notes**:

test: CCM + azurefile + MSI test scenarios

---

parts/agentparams.t

remove static sku validation so we can rely on the sku api in RP

remove static sku validation

---

pkg/api/azenvtypes.go

2020.10.04 AKS Windows VHD update
**Notes**:

chore: 2020.10.04 AKS Windows VHD update

---

pkg/api/azenvtypes.go

feat: Add VHD 2020.10.15

---

pkg/api/azenvtypes.go

chore: update windows image version to 17763.1554.201021

---

pkg/api/azenvtypes.go

chore: update VHD 2020.10.21

---

pkg/armhelpers/azurestack/resultPageClient.go

**Notes**:
Fix Azure Stack DiskListPageClient NotDone() logic bug.

fix: page not done logic bug

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1192
**Notes**:
~~Publishing is not yet complete, so tests will fail for the time being.~~

feat: add support for Kubernetes v1.19.3

---

pkg/operations/cordondrainvm.go

When method `evictPods` returns in whichever cases (normal return or timeout), we need to send a signal to the goroutines to stop and return, otherwise, it may be problematic because it will keep trying to evict the Pods forever (based on my observation in my tests)
Use `context` to send signals to goroutines to stop and return when the method `evictPods` returns.
**Notes**:
Cancel the Pod Eviction jobs when timeout. Otherwise, it may fall into an infinite loop.

fix: cancel Pod Eviction jobs when timeout

---

pkg/api/common/versions.go
pkg/api/vlabs/validate_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v1189
**Notes**:

feat: add support for Kubernetes v1.18.10

---

.devcontainer.json
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
go.mod
hack/tools/Makefile
makedev.ps1

See https://github.com/deis/docker-go-dev/releases/tag/v1.28.4
**Notes**:

chore: update go toolchain to v1.15.3

---

.pipelines/pr-e2e.yaml
examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json
test/e2e/engine/template.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/everything.json

This PR adds azure-kms-provider E2E coverage.
**Notes**:

test: ensure azure-kms-provider E2E coverage

---

pkg/api/azenvtypes.go

feat: add AKS linux VHD 2020.10.28

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200-alpha3
**Notes**:

feat: add support for Kubernetes v1.20.0-beta.0

---

cmd/get_logs.go
cmd/get_logs_test.go
cmd/root.go
docs/topics/get-logs.md
pkg/api/types.go
pkg/api/types_test.go
pkg/helpers/ssh/scp.go
pkg/helpers/ssh/ssh.go
pkg/helpers/ssh/types.go
pkg/kubernetes/interfaces.go

Increasing test coverage of `get_logs.go` and removing some code duplication noticed while working on `rotate-certs`. 
**Notes**:

refactor: move ssh-related funcs to its own package

---

docs/topics/clusterdefinitions.md
pkg/api/defaults-apiserver.go
pkg/api/defaults-apiserver_test.go

This adds soon-to-be-required apiserver config args in anticipation of this upstream PR:
https://github.com/kubernetes/kubernetes/pull/95896
**Notes**:

feat: set apiserver tokenRequest flags in 1.20+

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200-beta0
**Notes**:

feat: add support for Kubernetes v1.20.0-beta.1

---

.pipelines/pr-windows-signed-scripts.yaml
scripts/build-windows-provisioning-scripts.sh
test/e2e/engine/template.go

ci: Adding CI pipeline to verify windows provisioning script content BEFORE it gets check in

---

examples/e2e-tests/kubernetes/release/default/definition.json

So that Azure cloud-init is happy!
**Notes**:

ci: remove node-problem-detector addon from PR E2E

---

vhd/packer/configure-windows-vhd.ps1

chore: Adding csi-proxy-v0.2.2 to Windows VHD

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Updates powershell scripts to new version with changes from #4002 for 10c updates in #3956
**Notes**:

chore: update powershell signed scripts

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

chore: Install Windows Server 2019 10C updates in Windows VHD

---

.pipelines/pr-windows-signed-scripts.yaml
docs/topics/windows-provisioning-scripts.md

…
Default value is 
examples/e2e-tests/kubernetes/windows/hybrid/definition.json
This will help us test updates to the windows provisioning scripts for even more use cases
**Notes**:

ci: Updating pr-windows-signed-scripts.yaml to allow for overriding cluster definition

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2020.10.30.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2020.10.30.txt

This PR updates the Ubuntu 16.04 and 18.04 VHDs to the `2020.10.30` version.
**Notes**:

chore: rev Linux VHDs to 2020.10.30

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1554.201109.txt

chore: Add Windows 10c image as default (August optional patches) 

---

vhd/packer/configure-windows-vhd.ps1

Adds November Windows Patches 
**Notes**:

chore: Windows November Patches (11b)

---

pkg/api/azenvtypes.go

update azenvtypes for 20201111 VHD release

---

pkg/api/azenvtypes.go
pkg/api/const.go

chore: Update Windows image version

---

scripts/collect-windows-logs.ps1

fix: Adding csi-proxy logs locked file list to prevent access denied errors

---

pkg/api/azenvtypes.go

Update Windows image version to the latest.

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1577.201112.txt

Adds November image.
**Notes**:

chore: Use Windows November(11b) updates as default vhd

---

test/e2e/test_cluster_configs/flannel/containerd.json

This PR restricts the Kubernetes version test validation for the legacy flannel + containerd config. We will not test this config after 1.19.
**Notes**:

test: only test flannel + containerd thru k8s 1.19

---

docs/topics/addpool.md

Fix up some json formatting in the markdown
**Notes**:

chore: format some json in addpool.md

---

docs/topics/azure-stack.md

Small fixes to ASH topic page
**Notes**:

docs: fixed broken link in Azure Stack topic page

---

test/e2e/test_cluster_configs/container_monitoring.json

This PR configures the omsagent-enabled test cluster config to bypass the rotate docker logs test, which regularly fails.
**Notes**:

test: skip rotate docker log tests if omsagent

---

parts/k8s/cloud-init/artifacts/cse_config.sh
pkg/api/const.go
pkg/api/converterfromapi_test.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

chore: Upgrade CNI to v1.2.0

---

pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go

This PR removes MasterProfile warnings for update/scale/upgrade.
**Notes**:

chore: only warn about master stuff during create

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/api/azenvtypes.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
pkg/api/defaults.go
pkg/api/mocks.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/const.go
pkg/api/vlabs/types.go
pkg/api/vlabs/types_test.go
pkg/api/vlabs/validate_test.go
pkg/armhelpers/support_validator.go
pkg/engine/const.go
pkg/engine/engine.go
pkg/engine/engine_test.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
pkg/engine/virtualmachines.go
pkg/engine/virtualmachines_test.go
pkg/engine/virtualmachinescalesets.go
pkg/engine/virtualmachinescalesets_test.go
test/e2e/kubernetes/scripts/time-sync-validate.sh
test/e2e/kubernetes/scripts/ubuntu-installed-packages-validate.sh

This PR removes dead code, the result of an audit of `pkg/api/types.go`. Plenty of indirection happened and various parts of the codebase were pruned, but the main story was culling through the type library for no-longer relevant stuffs.
**Notes**:

chore: cleanup dead code

---

examples/azure-stack/conformance/kubernetes1.18.json

Adding 1.18 sample file in preparation to run compliance tests for 1.18 on Azure Stack
**Notes**:

chore: k8s v1.18 conformance model for Azure Stack

---

pkg/engine/systemroleassignments.go
pkg/engine/systemroleassignments_test.go

This PR allows system-assigned identity-configured clusters to work w/ `aks-engine upgrade`. The `Microsoft.Authorization/roleAssignments` definition needs to use the computed `sub(variables('masterCount'), variables('masterOffset'))` solution to inform its copy/loop implementation in order to work w/ the current upgrade implementation, which does one master at a time by using its offset value and a `masterCount` value of the offset + 1.
**Notes**:

fix: make system role assignments work w/ upgrade

---

test/e2e/kubernetes/workloads/dns-liveness.yaml

This PR modifies the E2E dns-liveness spec accordingly:
- uses the strongly-versioned busybox:1.31.1 image, matching other tests
- adds the `-type=A` option to nslookup to ensure a quick response
**Notes**:

test: dns-liveness livenessProbe tweaks

---

test/e2e/test_cluster_configs/base.json

This PR changes the base test config to use 3 control plane VMs so that we test upgrade in that configuration scenario.
**Notes**:

test: use 3 control plane VMs for base test config

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200-beta2
**Notes**:

feat: add support for Kubernetes v1.20.0-rc.0

---

pkg/api/azenvtypes.go

chore: Update VHD 2020.12.01

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1577.201202txt

Build new Windows image with latest packages in prep for release
**Notes**:
cc: @marosset @AbelHu @jackfrancis

chore: Update Windows image

---

examples/dualstack/README.md
examples/dualstack/kubernetes.json

- Updates dualstack docs to use `1.20`
**Notes**:

docs: update dualstack docs to 1.20

---

vhd/packer/configure-windows-vhd.ps1

chore: Installing Dec 2020 cumulative updates for Windows VHDs

---

Jenkinsfile
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1190
**Notes**:

feat: add support for Kubernetes v1.20.0

---

pkg/api/azenvtypes.go

feat: Aks linux vhd 20201209

---

test/e2e/config/config.go
test/e2e/kubernetes/daemonset/daemonset.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/node/node.go
test/e2e/kubernetes/pod/pod.go
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

This PR adds a configurable option to test the VMSS Node Prototype implementation here:
https://github.com/jackfrancis/kamino
**Notes**:

test: enable configurable node prototype tests

---

.github/workflows/nightly-build.yaml

ci: add manual dispatch trigger to nightly build

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1637.2012040632.txt

feat: Updating Windows VHDs to include Dec 2012 patches

---

hack/tools/go.sum
parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

A few releases recently, this brings aks-engine up to speed.
**Notes**:

chore: Update moby/containerd versions

---

README.md

Indicating that aks-engine is a legacy ARM-based project, and pointing users to CAPZ
Making it clear to users that aks-engine is a stable project, and that new use cases are enabled through Cluster API on Azure with CAPZ
**Notes**:

Added references to capz

---

README.md

Clarify that AKS Engine is the tool for Azure Stack Hub as CAPZ does not yet work there
**Notes**:

Clarify with respect to AZH

---

pkg/api/k8s_versions.go

This PR updates metrics-server to v0.4.1. See:
https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.4.1
**Notes**:

chore: rev metrics-server to v0.4.1 for all k8s versions

---

hack/tools/go.mod
hack/tools/go.sum
test/e2e/go.mod
test/e2e/go.sum

This PR delivers an updated vendor directory as a result of running `make vendor`.
**Notes**:

chore: update vendor deps

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Adding a critical fix to azure transparent mode CNI for mitigating intitial latency issue
**Notes**:

Chore: updating Az CNI to v1.2.0_hotfix

---

pkg/api/azenvtypes.go

feat: Aks linux vhd 20201215

---

docs/topics/windows-dsr.md
examples/windows/kubernetes-windsr.json
parts/k8s/kuberneteswindowsfunctions.ps1
parts/k8s/kuberneteswindowssetup.ps1
pkg/api/converterfromapi.go
pkg/api/converterfromapi_test.go
pkg/api/convertertoapi.go
pkg/api/convertertoapi_test.go
pkg/api/types.go
pkg/api/types_test.go
pkg/api/vlabs/types.go
pkg/api/vlabs/types_test.go
pkg/engine/template_generator.go
pkg/engine/template_generator_test.go
pkg/engine/templates_generated.go
staging/provisioning/windows/kubeproxystart.ps1

Fixes #4079
- [] includes documentation
- [] tested upgrade from previous version

feat: Add WinDSR support

---

vhd/packer/configure-windows-vhd.ps1

Fix for regression introduced in #4129 
**Notes**:

fix: Fixing URl for azure-cni v1.20_hotfix package in Windows VHD

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1200
**Notes**:

feat: add support for Kubernetes v1.20.1

---

docs/topics/features.md

Fix outdated content for Custom VNet.
Fix #4098 
**Notes**:

Fix: features.md

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Contains updates to powershell code used to start kubelet for kube-proxy
- feat: Updating kubelet/kube-proxy to run with as high priority processes (#4073)
- feat: Add WinDSR support (#4104)
- fix: fix that kubeproxy cannot parse featuregates (#4145)
**Notes**:

chore: Use signed scripts v0.0.8 for Windows deployments

---

pkg/api/const.go
pkg/api/types.go

update IsVHDDistro check

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2021.01.08.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2021.01.08.txt

This PR updates the standard Linux VHDs in preparation for the next release.
**Notes**:

chore: rev Linux VHDs to 2021.01.08

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1637.210111.txt

chore: release Windows VHD for v0.59.0 aks-engine release

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Update signed scripts package to include
- fix: fix network cleanup code on windows for contianerd nodes #4154
**Notes**:

chore: Use signed scripts package 0.0.9 on Windows nodes

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

chore: bump kms keyvault to v0.0.10

---

vhd/packer/configure-windows-vhd.ps1

chore: install Jan 2021 security updates in Windows VHD

---

staging/provisioning/windows/windowsnodelabelsync.ps1

The explanation of adding this script has been explained in https://github.com/Azure/aks-engine/pull/4157. This PR is for new signed script before we enable this periodical task
**Notes**:

chore: Add windowsnodelabelsync.ps1

---

docs/topics/aad.md

This PR fixes a broken link in the aad docs.
**Notes**:

docs: fix broken link in AAD docs

---

docs/topics/aad.md

Fix AAD docs and its support on Azure Stack Hub
**Notes**:

doc: aad not supported on Azure Stack Hub

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Update Azure CNI to v1.2.2.
The fix [Write to intermediate file before moving to state file](https://github.com/Azure/azure-container-networking/commit/98f838ef1b7fc1a6ef0a3f1b34b81840d703469e) in v1.2.2 is very important for Windows.
Please see more details in Azure CNI v1.2.2 release notes:
https://github.com/Azure/azure-container-networking/releases/tag/v1.2.2
**Notes**:

chore: Update Azure CNI to v1.2.2

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Signed-off-by: Mark Rossetti<marosset@microsoft.com>
Including [chore: Add windowsnodelabelsync.ps1 #4163](https://github.com/Azure/aks-engine/pull/4163) in signed scripts package
Fixes #4173
**Notes**:

chore: updating windows provisioing scripts to v0.0.10

---

pkg/api/azenvtypes.go
pkg/api/common/versions.go

revert 01.13 vhd and add 1.20.2

chore: revert 01.13 vhd and add 1.20.2

---

.pipelines/pr-e2e.yaml
examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json
parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_main.sh
parts/k8s/cloud-init/artifacts/kms-keyvault-key.service
parts/k8s/cloud-init/artifacts/kms-keyvault-key.sh
parts/k8s/cloud-init/masternodecustomdata.yml
pkg/api/const.go
pkg/engine/armvariables.go
pkg/engine/armvariables_test.go
pkg/engine/const.go
pkg/engine/keyvaults.go
pkg/engine/keyvaults_test.go
pkg/engine/masterarmresources.go
pkg/engine/params_k8s.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
test/e2e/test_cluster_configs/kms.json

- Create KMS key as part of cluster boostrap
- This is the first step to making the kms key version mandatory for the kms plugin pod.
- This will also allow BYOK configuration with KMS with the next KMS release.
- Deterministic behavior instead of relying on runtime for key creation.
- Fixes using `premium` sku with user-assigned managed identity
**Notes**:
cc @ritazh

feat: create kms key as part of cluster bootstrap

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1201
**Notes**:

feat: add support for Kubernetes 1.20.2

---

test/e2e/test_cluster_configs/everything.json

This PR removes the KMS config from the "everything" cluster config, in order to get back cloud-init data overhead.
**Notes**:

ci: remove KMS test from everything cluster config

---

test/e2e/cluster.sh
test/e2e/kubernetes/kubernetes_test.go
test/e2e/test_cluster_configs/kamino.json

This PR updates the kamino vmss-prototype E2E tests, and adds a cluster config so that we can regularly test this integration.
**Notes**:

test: updated kamino vmss-prototype integration E2E

---

test/e2e/kubernetes/kubernetes_test.go

Left in a `fmt.Println()` from an E2E debug session.
**Notes**:

test: remove dangling fmt.Println

---

go.mod
go.sum
test/e2e/go.sum
vendor/github.com/Azure/go-autorest/autorest/adal/token.go
vendor/github.com/Azure/go-autorest/autorest/adal/token_1.13.go
vendor/github.com/Azure/go-autorest/autorest/adal/token_legacy.go
vendor/modules.txt

Updating adal package version to fix a parsing issue on ADFS Azure Stack.
https://github.com/Azure/go-autorest/pull/599
**Notes**:

chore: update adal to v0.9.10

---

test/e2e/kubernetes/kubernetes_test.go

Unfortunately it regularly takes longer than 2 hours for a SIG image publication to complete.
**Notes**:

test: increase timeout tolerance for vmss-prototype SIG publishing

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.1697.210129.txt

chore: update aks-engine VHD Windows VHD

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-engine-ubuntu-1604/aks-engine-ubuntu-1604-202007_2021.01.28.txt
vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2021.01.28.txt

This PR freshens Linux VHD images.
**Notes**:

chore: rev Linux VHDs to 2021.01.28

---

cmd/get_skus_test.go
pkg/api/types_test.go
pkg/helpers/azure_locations.go
pkg/helpers/azure_locations_test.go
pkg/helpers/azure_skus_const.go

This PR updates Azure consts, enabling more recent VM SKUs.
**Notes**:

chore: add new Azure VM SKUs, brazilsoutheast, westus3 regions

---

pkg/api/azenvtypes.go

weekly AKS VHD update

---

test/e2e/test_cluster_configs/availabilityset.json

Until we address this bug:
https://github.com/Azure/aks-engine/issues/4236
We can't reliably test 1.21
**Notes**:

test: don't test availability sets + 1.21

---

pkg/api/vlabs/validate_test.go

This PR fixes a side-effect of two colliding PRs merging to master out of order.
**Notes**:

fix: func arity mismatch in validate_test.go

---

vhd/packer/install-dependencies.sh

This PR removes a bunch of images from VHD configuration that we don't need to pre-pull in order to meet "default" configuration requirements.
**Notes**:

chore: prune non-default images from VHD config

---

vhd/packer/install-dependencies.sh

This PR removes all GCR-sourced container images from the Linux VHDs.
**Notes**:

chore: don't include gcr-sourced images in Linux VHDs

---

pkg/api/common/helper.go

chore: add T4 GPU as Nvidia GPUs
Allow T4 GPUs to be treated as Nvidia GPUs, so it can be used on Azure Stack Hub.
Fixes #4242 
**Notes**:

chore: add T4 GPU as Nvidia GPUs

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1210-alpha2
**Notes**:

feat: add support for Kubernetes 1.21.0-alpha.3

---

pkg/engine/templates_generated.go

This housekeeping PR updates generated code.
**Notes**:

chore: generated code

---

pkg/api/azenvtypes.go

chore: update vhd 2021.02.10

---

pkg/api/const.go
vhd/packer/install-dependencies.sh

This PR updates the CNI plugins implementation to the latest:
https://github.com/containernetworking/plugins/releases/tag/v0.9.1
**Notes**:

chore: update CNI plugins to v0.9.1

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1210-alpha3
**Notes**:

feat: add support for Kubernetes 1.21.0-beta.0

---

.devcontainer.json
.github/workflows/nightly-build.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
makedev.ps1
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

See https://github.com/deis/docker-go-dev/releases/tag/v1.29.2
and https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved
**Notes**:

chore: update Go toolchain to v1.15.8

---

docs/topics/aad.md

Improves the AAD documentation
**Notes**:

docs: Update AAD documentation for Azure Stack and UI changes to Azure

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1697.210223.txt

chore: Updating Windows VHDs for v0.61.0 release

---

docs/topics/azure-stack.md

Doc was not update when the PR (https://github.com/Azure/aks-engine/pull/3394) was merged, thus making the change.
**Notes**:

docs: update get-verions section of Azure Stack documentation

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Update provisioning scripts version.
**Notes**:

chore: update windows provisioing scripts to v0.0.11

---

docs/topics/azure-stack.md

Include v0.60.1 to supported Azure Stack versions table
**Notes**:

docs: add v0.60.1 to Azure Stack topic page

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

fixes issue with azure cni when passing acl policies with containerd: https://github.com/Azure/azure-container-networking/releases/tag/v1.2.7
https://github.com/Azure/aks-engine/pull/3833
**Notes**:

chore: update azurecni to 1.2.7

---

docs/topics/azure-stack.md

Update Azure Stack topic documentation to add CSI driver information.
**Notes**:

docs: add CSI driver instructions for Azure Stack

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1

Hsn fix for 2c+
If multiple LB policies are included for same endpoint then HNS hangs. this fix forces an error  so restarts to HNS are not required.
https://github.com/Azure/AgentBaker/pull/628
/cc @AbelHu @mainred
**Notes**:

chore: Hsn fix for 2c+

---

test/e2e/kubernetes/workloads/kured-annotations.yaml

This PR updates to a newer kured build for testing kamino via E2E.
**Notes**:

test: update kured image to use during kamino tests

---

pkg/api/common/versions.go
test/e2e/engine/template.go
test/e2e/test_cluster_configs/containerd.json
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1210-beta0
**Notes**:

feat: add support for Kubernetes 1.21.0-beta.1

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.1817.210317.txt

Signed-off-by: Mark Rossetti<marosset@microsoft.com>
**Notes**:

chore: Update default Windows VHDs to include 3B patches

---

pkg/api/common/versions.go

Add 1.18.17/1.19.9/1.20.5

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

chore: Update Windows provisioning scripts to 0.0.12

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1210-beta1
**Notes**:

feat: add support for Kubernetes v1.21.0-rc.0

---

Jenkinsfile
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1200-1
**Notes**:

feat: add support for Kubernetes v1.21.0

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.1879.210414.txt
vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.1879.210414.txt

chore: Updating default windows VHDs

---

test/e2e/test_cluster_configs/no_outbound_containerd.json

This PR adds a containerd "no outbound" test scenario to validate pre-pulled VHD artifacts prior to release.
**Notes**:

test: add containerd no outbound test scenario

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1205
**Notes**:

feat: add support for Kubernetes v1.20.6

---

.pipelines/pr-e2e.yaml

This PR ensures that only appropriate CI env vars are passed to the appropriate jobs.
**Notes**:

ci: clear out unnecessary env vars

---

docs/topics/gpu.md
parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go
test/e2e/kubernetes/workloads/cuda-vector-add.yaml

Upgrade the Nvidia drivers for GPU machine to 450.80.02. 
This version of the drivers is the same used in AzureML based images since April 2021. This change will add compatibility with newer version of CUDA (11.1,11.2,11.3). Reference https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html 
None. It adds support to run docker images based on CUDA >= 11.1
**Notes**:
Should be pretty safe since it is a minor version upgrade.

chore: Upgrade nvidia drivers to 450.80.02

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

chore: Update Windows provisioning scripts to 0.0.13

---

examples/azure-stack/conformance/kubernetes1.19.json
examples/azure-stack/conformance/kubernetes1.20.json
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Adding support for K8s versions 1.18.18, 1.19.10, and 1.20.6 on Azure Stack.
**Notes**:

feat: add Azure Stack support for k8s 1.18.18, 1.19.10, and 1.20.6

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/cloud-init/nodecustomdata.yml
pkg/api/addons.go
pkg/api/addons_test.go
pkg/engine/template_generator.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This greatly simplifies what's required to install gpu drivers since the
packages no longer depend on docker-ce.
Older nvidia packages required docker-ce packages.
This is no longer a problem with the v3 drivers and greatly simplifies the install process.
**Notes**:
Still need to actually allow the driver installation when containerd is used.

chore: Update nvidia runtime

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1210
**Notes**:

feat: add support for Kubernetes v1.21.1

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1206
**Notes**:

feat: add support for Kubernetes v1.20.7

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
Reflects https://github.com/kubernetes/kubernetes/commit/25f3cf55509acdd3bd31bc9ca028c5d5a3bd22b0 in the latest kube-addon-manager image.
**Notes**:

chore: bump kube-addon-manager to v9.1.5

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

This PR ensures that all nvidia drivers are downloaded during VHD creation, and installed from local files during CSE.
**Notes**:

chore: download nvidia drivers during VHD

---

vhd/publishing/new-sku-and-add-image-version.sh

Publishing with pub causes an error currently.  This workaround enables us to publish to marketplace
**Notes**:

ci: workaround image publishing errors

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.1935.210520.txt
vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.1935.210520.txt

chore: Add Windows May 2021 images

---

parts/k8s/cloud-init/artifacts/cse_config.sh
parts/k8s/cloud-init/artifacts/cse_helpers.sh
parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/template_generator.go
pkg/engine/templates_generated.go

This PR addresses errors in the nvidia + containerd scenarios uncovered during VHD testing.
**Notes**:

fix: nvidia + containerd errata

---

pkg/engine/availabilitysets.go

missed this one the first time around 
-______________-

fix: vmas with ephemeral os should use aligned AS sku

---

parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
parts/k8s/addons/azurefile-csi-driver-deployment.yaml
pkg/engine/templates_generated.go

There is a failure in some cases of https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-serial
Following is the detail error log from CSI controller.
```
I0521 06:16:31.327041       1 azure_armclient.go:430] Received error in put.send: resourceID: /subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-p9qac7rm/providers/Microsoft.Compute/disks/pvc-919384c7-e152-4819-84ae-21dfaad82307, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client '4eef356b-d1ce-4a7a-83f6-5c4c26edbf6b' with object id '4eef356b-d1ce-4a7a-83f6-5c4c26edbf6b' does not have authorization to perform action …
```

fix: Run CSI controller driver on master node

---

.devcontainer.json
.github/workflows/nightly-build.yaml
.github/workflows/release.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
docs/community/release-checklist.md
examples/no_outbound.json
makedev.ps1
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

This PR introduces a new release action to make aks-engine releases automated.
The process, in brief:
1. create a new release branch
2. add a releases/CHANGELOG-<version>.md file with release notes
3. push a new tag that matches the version to be released (e.g., `v0.64.0`)
Upon pushing the tag, the new github action will run various E2E against that commit, and then conditionally create a new release w/ notes from the versioned CHANGELOG file.
**Notes**:

ci: automated release using github actions

---

releases/CHANGELOG-v0.64.0.md

This delivers the proposed v0.64.0 changelog.
**Notes**:

ci: v0.64.0 changelog

---

.github/workflows/release.yaml

Use go 1.16 in release build pipeline
**Notes**:

ci: use go 1.16 to build release artifacts

---

.github/workflows/release.yaml

We don't want to manually `go get` the ginkgo library during release CI, as that will mutate the `go.mod` and produce vendoring pathologies. The current `make` targets (`build-binary` and `test`) do everything we need.
🥇 to @devigned for the pro tip
**Notes**:

ci: don't install ginkgo

---

docs/topics/gpu.md
parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go

This is needed in order to support CUDA 11 which supports some large
model memory leak fixes.
Needed for latest CUDA version
Fixes #4464 

Update to the nVidia 460.32.03 drivers

---

pkg/api/defaults-controller-manager.go
pkg/api/defaults-controller-manager_test.go

Signed-off-by: Ernest Wong <chuwon@microsoft.com>
Fixes test failure in https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-master
**Notes**:

fix: stop using ServiceNodeExclusion feature gate after it is GA

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1207
**Notes**:

feat: add support for Kubernetes v1.20.8

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1211
**Notes**:

feat: add support for Kubernetes 1.21.2

---

pkg/api/azenvtypes.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

Adds June patch images to build VHD
**Notes**:

chore: use Azure June release images for base images

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.1999.210622.txt
vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.1999.210622.txt

Sets default aks-e vhds to June patches
**Notes**:

chore: June Windows VHDs

---

.chglog/config.yml
.github/semantic.yml
docs/community/release-checklist.md

This PR addresses some longstanding issues w/ git-chglog, and updates the release notes accordingly.
**Notes**:

release: git-chglog changes with docs

---

.github/workflows/generate-release-changelog.yaml

This PR adds a github action to automatically generate a release CHANGELOG
**Notes**:

release: add CHANGELOG generation ci

---

.github/workflows/generate-release-changelog.yaml

Tweaks to generate changelog github action
**Notes**:

release: ensure all tags are fetched, reset go.mod

---

.github/workflows/create-release-branch.yaml

This PR adds a github action to automatically create a release candidate branch.
**Notes**:

release: add create release branch workflow

---

.github/workflows/create-release-branch.yaml

Tested that this regex works on ubuntu
**Notes**:

release: compatible regex for ubuntu

---

.github/workflows/release.yaml
.github/workflows/tag-release-branch.yaml

This PR adds a github action to automatically tag a release when the CHANGELOG is merged to the release branch.
**Notes**:

release: add github action for creating release tag

---

.github/workflows/create-release-branch.yaml

This PR fixes some github action variables errata.
**Notes**:

release: use the right release env

---

.github/workflows/release.yaml

This PR fixes the way the release tag is sourced in the "release" github action.
**Notes**:

release: use github.ref to source release tag

---

.github/workflows/release.yaml

Another tweak to derive the correct version substring after the tag has been pushed.
**Notes**:

release: derive release version from git branch

---

.github/workflows/release.yaml

This PR changes the release github action so that it just fires on a tag. Working through this issue:
https://github.com/softprops/action-gh-release/issues/20
**Notes**:

release: just release on tag

---

.github/workflows/release.yaml

This PR updates the release github action so that it derives the release version string from the tag.
**Notes**:

release: use git describe --tags to derive release version

---

.github/workflows/tag-release-branch.yaml

This PR uses a PAT to tag the release branch in a github action, so that another github action may be triggered.
**Notes**:

release: use PAT to tag release branch

---

.github/workflows/release.yaml

This PR creates a local (temporary) release tag before running `make dist` to produce release artifacts, so that the artifacts are named meaningfully.
**Notes**:

release: add local tag before running make dist

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

chore: Update Azure CNI to 1.4.0
**Notes**:

chore: Update Azure CNI to 1.4.0

---

.github/workflows/generate-azure-consts.yaml

This PR adds a github action that will generate Azure consts every day, and create a new PR if they are detected.
**Notes**:

ci: automate generate Azure consts

---

.github/workflows/generate-azure-consts.yaml

Iterating on generate Azure consts github action
**Notes**:

ci: automate generate Azure consts part deux

---

.github/workflows/generate-azure-consts.yaml

Still iterating on a generate Azure const action
**Notes**:

ci: automate generate Azure consts part trois

---

.github/workflows/generate-azure-consts.yaml

Fingers crossed this is the last iteration...
**Notes**:

ci: automate generate Azure consts part quatre

---

.github/workflows/generate-azure-consts.yaml

need to commit the right files
**Notes**:

ci: automate generate Azure consts part cinq

---

.github/workflows/generate-azure-consts.yaml

Maybe the pull request action is the only one we need...
**Notes**:

ci: automate generate Azure consts part six

---

.github/workflows/generate-azure-consts.yaml

Still seeing the go.mod leftovers...
**Notes**:

ci: automate generate Azure consts part sept

---

.github/workflows/generate-azure-consts.yaml

Only run if new consts are generated
**Notes**:

ci: automate generate Azure consts part huit

---

.github/workflows/generate-azure-consts.yaml

This PR fixes double-quote usage inside if github actions job if conditions, which doesn't parse.
**Notes**:

ci: use single quotes for equality comparison

---

.github/workflows/update-go-mod-vendor.yaml

A couple copy/pasta fixes.
**Notes**:

ci: go mod vendor action tweaks

---

Makefile
test/e2e/Makefile

This PR unwinds the introduction of a vendor directory in `test/e2e/`. That experiment was useful to prove out automated GitHub Action runs, but adds unnecessary complexity/overhead in the long term.
**Notes**:

ci: undo test/e2e vendor

---

CODEOWNERS
OWNERS

This PR adds a CODEOWNERS file. We can fine-tune this over time. Added some targeted ownership assignments.
For more info:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
**Notes**:

ci: add CODEOWNERS file

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Update Windows docker version to 20.10.5 which is the latest docker version in DockerMsftProvider 
Fix https://github.com/microsoft/Windows-Containers/issues/106
**Notes**:

chore: Update Windows docker version to 20.10.5

---

.pipelines/pr-windows-signed-scripts.yaml
.pipelines/vhd-builder-windows-template.yaml

This PR uses the more idiomatic `build` make target to build aks-engine code during Windows VHD CI.
**Notes**:

ci: use make build in Windows VHD build CI

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1

This PR updates the installed version of containerd to 1.4.6.
**Notes**:

chore: update containerd to 1.4.6

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220-alpha3
Closes #4439
Closes #4447
**Notes**:

feat: add support for Kubernetes v1.22.0-beta.0

---

parts/k8s/cloud-init/artifacts/cse_install.sh
parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/engine/templates_generated.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

This PR updates the default moby (docker) version to 20.10.7 for both Linux and Windows.
**Notes**:

chore: update moby/docker, and runc for linux only

---

.github/workflows/generate-azure-consts.yaml
.github/workflows/nightly-build.yaml
.github/workflows/update-go-mod-vendor.yaml

This PR configures the various automated GitHub Action jobs so that they don't run on forks. (GitHub Actions do that by default, oy!)
See:
- https://github.community/t/stop-github-actions-running-on-a-fork/17965/2
**Notes**:

ci: don't run automated github actions on forks

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220-beta0
**Notes**:

feat: add support for Kubernetes 1.22.0-beta.1

---

.github/workflows/create-release-branch.yaml

This PR updates the "create-release-branch" GitHub Action to manually create a new release branch from the checked out branch, because `peterjgrainger/action-create-branch@v2.0.1` is always creating the branch from `master`.
**Notes**:

release: create branch manually

---

.github/workflows/create-release-branch.yaml

This PR uses the full "git push to remote" command, which may or may not work with the `actions/checkout@v2` GitHub Action. Printing out the remote list to verify, in case we need to continue iterating on this.
**Notes**:

release: create branch by pushing to origin remote

---

CODEOWNERS

This PR adds @jsturtevant and @marosset to CODEOWNERS
**Notes**:

ci: add jsturtevant and marosset to CODEOWNERS

---

vhd/packer/configure-windows-vhd.ps1

WS 2019 July 2021 patches: https://support.microsoft.com/en-us/topic/july-13-2021-kb5004244-os-build-17763-2061-d2b763cb-fad4-4b0a-a67f-4e184e277b99
**Notes**:
cc @marosset @jackfrancis

chore: WS 2019 July 2021 patches for vhd

---

.github/workflows/release.yaml

This PR ensures that GitHub Action-generated releases fail if our build steps produce a dirty git status outcome.
**Notes**:

release: verify clean git status before building release artifacts

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220-beta1
**Notes**:

feat: add support for Kubernetes v1.22.0-beta.2

---

.devcontainer.json
.github/workflows/nightly-build.yaml
.github/workflows/release.yaml
.pipelines/pr-e2e.yaml
.pipelines/vhd-builder-ubuntu-gen2.yaml
.pipelines/vhd-builder.yaml
Makefile
hack/tools/Makefile
makedev.ps1
pkg/armhelpers/azurestack/resultPageClient.go
test/e2e/kubernetes/workloads/large-container-daemonset.yaml

See https://github.com/deis/docker-go-dev/releases/tag/v1.32.3
**Notes**:

chore: update Go toolchain to 1.16.6

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1208
**Notes**:

feat: add support for Kubernetes v1.20.9

---

.github/workflows/release.yaml

This PR ensures that our built release binaries won't be marked as dirty, but includes some stdout information to help find out why that may have been happening.
**Notes**:

release: tolerate dirty git status while we debug

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2061.210716.txt
vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.2061.210716.txt

Sets July's VHD's as the default images
**Notes**:

chore: Windows July 2021 VHDs

---

docs/community/release-checklist.md

Fixed `Create Release Branch` fields description.
**Notes**:

docs: release checklist update

---

vhd/packer/install-dependencies.sh

A recent PR omitted an update to the VHD installation spec for containerd:
https://github.com/Azure/aks-engine/pull/4561
This PR updates the Linux VHD installation spec so that 1.4.6 is pre-installed.
**Notes**:

chore: pre-install containerd 1.4.6 on Linux VHD

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml
examples/kubernetes-gpu/kubernetes.json

This PR ensures that we validate well-known GPU scenarios before we cut a release.
**Notes**:

release: validate GPU scenarios

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR ensures we can run the more interesting E2E tests to validate gpu during release CI.
**Notes**:

release: SSH_AUTH_SOCK in CI so we can run E2E

---

Jenkinsfile
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1210
Ckoses #4593 
**Notes**:

feat: add support for Kubernetes v1.22.0

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1209
**Notes**:

feat: add support for Kubernetes v1.20.10

---

pkg/api/apiloader_test.go
pkg/api/const.go
pkg/api/converterfromapi_test.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Upgrade default Azure CNI to latest release and remove old CNI version from VHD.

chore: upgrade Azure CNI to 1.4.9

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1220
**Notes**:
**Notes**:

feat: add support for Kubernetes v1.22.1

---

.github/workflows/test-cluster-config.yaml

This PR adds a GitHub action to allow on-demand testing of particular cluster config types. Initially we ship a "gpu" type.
**Notes**:

ci: add on-demand cluster config GitHub Action

---

parts/k8s/kuberneteswindowssetup.ps1
pkg/engine/templates_generated.go

**Notes**:
Permissions **before** changes:
```cmd
c:\k NT AUTHORITY\Authenticated Users:(I)(M)
NT AUTHORITY\Authenticated Users:(I)(OI)(CI)(IO)(M)
NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
BUILTIN\Administrators:(I)(OI)(CI)(F)
BUILTIN\Users:(I)(OI)(CI)(RX)
c:\k\nssm.exe NT AUTHORITY\Authenticated Users:(I)(M)
NT AUTHORITY\SYSTEM:(I)(F)
BUILTIN\Users:(I)(RX)
BUILTIN\Administrators:(I)(F)
```
```cmd
Permissions **after** changes:
c:\k BUILTIN\Administrators:(OI)(CI)(F)
BUILTIN\Users:(OI)(CI)(RX)
NT …
```

fix: Remove 'NT AUTHORITY\Authenticated Users' write permissions on files in c:\k

---

parts/k8s/addons/azuredisk-csi-driver-deployment.yaml
parts/k8s/addons/azurefile-csi-driver-deployment.yaml
pkg/api/k8s_versions.go
pkg/api/vlabs/validate.go
pkg/api/vlabs/validate_test.go
pkg/engine/templates_generated.go

fix: make Azure Disk & File CSI drivers work on 1.22
**Notes**:

fix: make Azure Disk & File CSI drivers work on 1.22

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

Update Windows provisioning signed package to v0.0.15
**Notes**:

chore: Update Windows provisioning signed package to v0.0.15

---

.github/workflows/large-cluster-test.yaml

This PR cleans up some cruft from the large cluster test GitHub Action spec.
**Notes**:

ci: fix large-cluster-test errata

---

test/e2e/kubernetes/kubernetes_test.go

This PR updates the E2E test implementation to print stdout from vmss-health-check after E2E runs.
**Notes**:

test: print vmss-health-check stdout at E2E end

---

test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/pod/pod.go

This PR changes the vmss-prototype E2E tests so that when there are multiple VMSS they run in parallel for each VMSS.
**Notes**:

test: parallel vmss-prototype jobs when multiple VMSS

---

test/e2e/kubernetes/kubernetes_test.go

This PR modifies the E2E tests so that it correctly detects the number of nodes and large container daemonset pods when using vmss-prototype across multiple VMSS.
**Notes**:

test: detect node count when adding vmss-prototype nodes

---

examples/largeclusters/kubernetes.json
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/node/node.go
test/e2e/kubernetes/scripts/vmss-health-check.sh

This PR brings in changes to large cluster testing that have proven working.
**Notes**:

test: known-working 5k node test

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

Azure CNI v 1.4.12 containers fixes for Windows node names that end in an upper-case letter when used in clusters with IPv6/dualstack support.
**Notes**:

chore: Update Azure CNI to v.1.4.12

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1221
**Notes**:

feat: add support for Kubernetes v1.22.2

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230-alpha1
**Notes**:

feat: add support for Kubernetes v1.23.0-alpha.2

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2183.210922.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2183.210922.txt

chore: Update default Windows VHDs to Sept 2021 images

---

vhd/packer/configure-windows-vhd.ps1

chore: Install 9C patches for Windows Server 2019 which contains fixes for accelerated networking

---

test/e2e/config/config.go
test/e2e/kubernetes/kubernetes_test.go

This PR allows convenient testing of any local kured chart when using vmss-prototype tests.
**Notes**:

test: support local kured chart

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-smalldisk-17763.2213.210927.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2213.210927.txt

chore: New Windows VHD with 9C patches

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json
pkg/engine/testdata/azurestack/kubernetes-ubuntu16.json
pkg/engine/testdata/key-vault-certs/kubernetes.json

Ubuntu 16.04-LTS has been EOL for some time, and we've logged warning messages discouraging customers from using it.
As such, let's stop testing 16.04 node pools with every E2E run.
**Notes**:

test: stop testing Ubuntu 16.04-LTS

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230-alpha3
**Notes**:

feat: add support for Kubernetes v1.23.0-alpha.4

---

examples/networkpolicy/README.md
parts/k8s/addons/antrea.yaml
pkg/api/k8s_versions.go
pkg/engine/templates_generated.go

Signed-off-by: Rahul Jain <reachjainrahul@gmail.com>
Upgrading Antrea version to v1.3.0. Also fixed documentation
links.
**Notes**:

feat: Update Antrea version to v1.3.0

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230-alpha4
**Notes**:

feat: add support for Kubernetes v1.23.0-beta.0

---

.github/workflows/release.yaml

This PR ensures that we delete untracked git files before generating the `aks-engine version` output, so that our releases aren't ever marked as "dirty".
**Notes**:

release: remove untracked files before building release binaries

---

.github/workflows/release.yaml

This PR ensures that we don't cut a release w/ an association to a pre-existing tagged commit.
**Notes**:

release: validate tag doesn't exist before releasing

---

pkg/api/k8s_versions.go
vhd/packer/install-dependencies.sh

This PR updates the delivered version of metrics-server to the most recently released version:
https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.2
**Notes**:

chore: update metrics-server to v0.5.2

---

parts/k8s/kubernetesparams.t
pkg/api/const.go
pkg/api/defaults_test.go
pkg/engine/templates_generated.go
vhd/packer/install-dependencies.sh

This PR updates the default Linux moby packages to `20.10.11` for cluster backed by docker.
**Notes**:

chore: update moby Linux packages to 20.10.11

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230-beta0
**Notes**:

feat: add support for Kubernetes v1.23.0-rc.0

---

pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

https://github.com/Azure/azure-container-networking/releases/tag/v1.4.16
82f4b39 feat: [CNI] Enable DSR policy for windows singletenancy (AKS) by default (#1116)
**Notes**:

chore: update cni to v1.4.16

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

chore: use Nov 2021 as Windows Server 2019 VHD base

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml
.github/workflows/test-cluster-config.yaml
Jenkinsfile
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230-rc1
Closes #4778
**Notes**:

feat: add support for Kubernetes v1.23.0

---

pkg/api/azenvtypes.go
vhd/packer/windows-2019-vars.json
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2300.211204.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2300.211204.txt

chore: use windows VHDs with Nov 2021 security patches

---

examples/e2e-tests/kubernetes/release/default/definition-no-vnet.json
examples/e2e-tests/kubernetes/release/default/definition.json
parts/k8s/addons/azure-cloud-provider.yaml
pkg/api/k8s_versions.go
pkg/api/types.go
pkg/api/types_test.go
pkg/engine/engine.go
pkg/engine/engine_test.go
pkg/engine/templates_generated.go
test/e2e/kubernetes/kubernetes_test.go
test/e2e/kubernetes/util/util.go
vhd/packer/install-dependencies.sh

This PR updates the relevant out-of-tree cloud-provider-azure components, including CSI components (which we test in common with out-of-tree). References:
- https://github.com/kubernetes-sigs/cloud-provider-azure/releases
- https://github.com/kubernetes-sigs/azurefile-csi-driver/releases
- https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases
In addition, we will now test the out-of-tree scenarios against PRs in preparation for making that the default configuration going forward.
Finally, I observed that the "holistic" CCM implementation that you get when using the `"useCloudControllerManager": true,` configuration exceeds the Azure-allowed cloud-init data limits. In order to get good tests against this scenario, we need to disable the cluster-autoscaler …

chore: update out-of-tree cloudprovider releases

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2300.211214.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2300.211214.txt

chore: Windows VHD for v0.68.0 release

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1230
N/A
**Notes**:

feat: add support for Kubernetes v1.23.1

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

This PR updates the nvidia-container-runtime to the recently released 3.6.0:
- https://github.com/NVIDIA/nvidia-container-runtime/releases/tag/v3.6.0
Fixes #4792 
**Notes**:

chore: update nvidia-container-runtime to 3.6.0

---

parts/k8s/cloud-init/artifacts/cse_install.sh
pkg/engine/templates_generated.go

This PR updates the delivered version of runc to 1.0.2.
**Notes**:

chore: update runc to 1.0.2

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2300.220111.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2300.220111.txt

chore: New Windows VHDs

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR updates the release github actions so that the clusters they build are cleaned up afterwards.
**Notes**:

release: cleanup resource groups during CI

---

.github/workflows/release.yaml

This xargs usage as-is doesn't work w/ the github action container.
**Notes**:

release: use gnu xargs in CI

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1231
N/A
**Notes**:

feat: add support for Kubernetes v1.23.2

---

docs/topics/windows-provisioning-scripts-release-notes.md
pkg/api/const.go
vhd/packer/configure-windows-vhd.ps1

making windows provisioning scripts v0.0.16 the default
**Notes**:

chore: making windows provisioning scripts v0.0.16 the default

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1232
N/A
**Notes**:

feat: add support for Kubernetes v1.23.3

---

.pipelines/vhd-builder.yaml

ci: use 18.04 for Linux VHD job

---

pkg/api/azenvtypes.go
pkg/api/defaults-custom-cloud-profile.go
pkg/armhelpers/support_validator.go

fix: update Azure Stack's Linux VHD to 2022.02.07

---

README.md

Update the project status of AKS-Engine to announce the deprecation of the project and the final version of Kubernetes that will be supported.
To notify prospective users of AKS-Engine that there is a better option for building self-managed Kubernetes clusters on Azure, [Cluster API Provider Azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure), and they should either not adopt this project or determine plans for migrating to a different set of tools for building self-managed clusters.
**Notes**:
/cc @jackfrancis @CecileRobertMichon @mboersma

docs: update AKS-Engine project status to deprecated

---

README.md
SUPPORT.md
docs/faq.md

**Notes**:
This PR updates the README, SUPPORT, and FAQ to point to the updated status. It also rephrases the call-to-action in the Community section of the README, to more accurately reflect the status of the project.

docs: Adding current status updates

---

docs/tutorials/quickstart.md

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
Adds links missing from quickstart.
Fixes https://github.com/Azure/aks-engine/issues/4469
**Notes**:

docs: add missing links

---

.pipelines/pr-e2e.yaml
Jenkinsfile
cmd/generate_test.go
examples/kubernetes-releases/kubernetes1.24.json
pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1240-alpha1
N/A
**Notes**:

feat: add support for Kubernetes v1.24.0-alpha.2

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1240-alpha2
N/A
**Notes**:

feat: add support for Kubernetes v1.24.0-alpha.3

---

docs/topics/azure-stack.md
examples/azure-stack/kubernetes-azurestack.json
examples/azure-stack/kubernetes-windows.json

docs: add linuxProfile section to Azure Stack Hub doc page

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#changelog-since-v1233
N/A
**Notes**:

feat: add support for Kubernetes v1.23.4

---

vhd/packer/windows-2019-vars.json

chore: Using feb 2022 base image for Windows VHDs

---

docs/tutorials/quickstart.md

docs: Update quickstart.md

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2565.220301.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2565.220301.txt

feat: Adding Windows VHDs with Feb 2022 security updates

---

docs/howto/troubleshooting.md

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
Docs updates for [bridge mode](https://github.com/Azure/aks-engine/issues/4595#issuecomment-885082542) and [unattended upgrades](https://github.com/Azure/aks-engine/issues/4595#issuecomment-885090488).
Fixes #4606
**Notes**:
Updates based on GitHub comments by @mboersma.

docs: bridge mode and unattended upgrades

---

test/e2e/kubernetes/workloads/busybox-agent.yaml
test/e2e/kubernetes/workloads/busybox-master.yaml
test/e2e/kubernetes/workloads/dns-liveness.yaml
test/e2e/kubernetes/workloads/exec-liveness-always-fail.yaml
test/e2e/kubernetes/workloads/exec-liveness-assume-1-second-default-timeout.yaml
test/e2e/kubernetes/workloads/exec-liveness-timeout-always-fail.yaml
test/e2e/kubernetes/workloads/exec-liveness.yaml
test/e2e/kubernetes/workloads/validate-dns-linux.yaml
vhd/packer/install-dependencies.sh

This PR standardizes the busybox image we use for testing to mcr.microsoft.com/oss/busybox/busybox:1.33.1
Fixes #4864
**Notes**:

test: use mcr.microsoft.com/oss/busybox

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.2565.220407.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.2565.220408.txt

chore: updating windows vhds for v0.70.0

---

.github/workflows/create-release-branch.yaml

This PR updates the "create release branch" GitHub Action so that the `git-chglog` binary is installed via `go install` instead of `go get`.
**Notes**:

release: use go install to build git-chlog

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR updates the release CI configs in response to observing flakes.
**Notes**:

release: use 1.23 for release verification, bypass SSH

---

vhd/packer/windows-vhd-builder.json

We build the Windows VHD in "internal" Azure subs which are subject to some compliance policies.
One such policy is to change how Azure VMs receive defender signature updates.
We need to opt of out this for the VMs used to produce our aks-engine VHDs because it breaks customer scenarios.
**Notes**:

fix: opt out of 'Anitimalware Signatures SDP' extension for Windows VHDs

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1240
**Notes**:

feat: add support for Kubernetes v1.24.1

---

scripts/collect-logs.sh

Include container logs to the list of files collected by get-logs.
**Notes**:

chore: get-logs copies kube-system logs from file system

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1241
**Notes**:

feat: add support for Kubernetes v1.24.2

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

chore: install 2022 7C updates to help validate windows networking fixes

---

cmd/get_locations.go
cmd/get_locations_test.go
pkg/helpers/azure_locations.go

This PR manually adds the pre-GA `qatarcentral` region so that qualified Azure subscriptions are able to use aks-engine with it.
**Notes**:

chore: add qatarcentral region

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR updates the release CI configuration to use `westus3` instead of `westus2` in reponse to:
Error from deployment for kubernetes-westus2-19379 in resource group kubernetes-westus2-19379:exit status 1
[110](https://github.com/Azure/aks-engine/runs/7565146563?check_suite_focus=true#step:9:111)
2022/07/28 17:17:18 Command Output: ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment failed with error: 'The resource with id: '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-poolgpu-39726647-vmss' failed validation with message: 'The requested size for resource '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSets/k8s …

ci: use westus3 for release automation

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR updates the release CI configuration to use `eastus` instead of `westus2` in reponse to:
Error from deployment for kubernetes-westus2-19379 in resource group kubernetes-westus2-19379:exit status 1
[110](https://github.com/Azure/aks-engine/runs/7565146563?check_suite_focus=true#step:9:111)
2022/07/28 17:17:18 Command Output: ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment failed with error: 'The resource with id: '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-poolgpu-39726647-vmss' failed validation with message: 'The requested size for resource '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSets/k8s- …

ci: use eastus for release automation

---

.github/workflows/create-release-branch.yaml

This PR updates one final release CI configuration to use `eastus` instead of `westus2` in reponse to:
Error from deployment for kubernetes-westus2-19379 in resource group kubernetes-westus2-19379:exit status 1
[110](https://github.com/Azure/aks-engine/runs/7565146563?check_suite_focus=true#step:9:111)
2022/07/28 17:17:18 Command Output: ERROR: {"code": "InvalidTemplateDeployment", "message": "The template deployment failed with error: 'The resource with id: '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSets/k8s-poolgpu-39726647-vmss' failed validation with message: 'The requested size for resource '/subscriptions/***/resourceGroups/kubernetes-westus2-19379/providers/Microsoft.Compute/virtualMachineScaleSet …

ci: really use eastus for release automation

---

vhd/packer/configure-windows-vhd.ps1

Updating cloud node manager version in windows vhd

---

.github/workflows/create-release-branch.yaml
.github/workflows/generate-azure-consts.yaml
.github/workflows/large-cluster-test.yaml
.github/workflows/release.yaml
.github/workflows/test-cluster-config.yaml
.github/workflows/update-go-mod-vendor.yaml

This PR ensures that github actions use the same version of go defined in `go.mod`.
**Notes**:

chore: pin github actions go versions to go.mod

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3232.220805.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3232.220805.txt

chore: updating Windows VHDs for next aks-engine release

---

.github/workflows/create-release-branch.yaml

Kubernetes v1.20.n is no longer a supported AKS Engine version, so we need to remove it from the set of release CI requirements.
**Notes**:

ci: remove 1.20 no-egress requirement

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml

This PR removes the 1.24 no-egress requirement in the interest of getting a quicker release out the door.
**Notes**:

ci: remove 1.24 no-egress requirement

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1243
**Notes**:

feat: add support for Kubernetes v1.24.4

---

README.md

Updates the support statement for AKSe on AzSH
Not an open issue
**Notes**:
@bridgetkromhout for awareness

docs: Update README.md support statement for Hub

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1245
**Notes**:

feat: add support for Kubernetes v1.24.6

---

hack/tools/Makefile

chore: Upgrading pub v0.2.6 -> v0.3.2

---

hack/tools/Makefile

Updating to pub v0.3.3 which has a fix for JSON marshalling issues when updating the Windows VHD with pub.
**Notes**:

chore: update to pub v0.3.3

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3232.221003.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3232.221003.txt

chore: prepping new Windows VHDs for the next release

---

docs/topics/azure-stack.md
examples/azure-stack/migratepv.sh

Fix instructions to upgrade from in-tree to out-of-tree for Azure Stack Hub. Storage class should be deleted after the upgrade, to account for add-on manager. 
**Notes**:

docs: explain how to migrate to CSI after upgrade on Azure Stack Hub

---

parts/k8s/cloud-init/artifacts/cse_helpers.sh
pkg/engine/templates_generated.go

This updates the driver to the latest bug fix and CUDA level driver for the datacenter use.
NVIDIA UNIX x86_64 Kernel Module  515.65.01  Wed Jul 20 14:00:58 UTC 2022
NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7
For the next aks-engine update, having the fixed/updated GPU driver will be important
In addition to update to latest driver, this updated driver has some security fixes
I have done basic tests with the driver install and run it on a few SKUs
**Notes**:
No tests need updating - existing tests should cover this situation.

Update NVIDIA GPU driver to 515.65.01

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1246
**Notes**:

feat: add support for Kubernetes v1.24.7

---

docs/topics/windows-provisioning-scripts-release-notes.md
vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

Includes new signed windows provisioning scripts
**Notes**:

chore: Adding v0.0.17 signed windows provisioning scripts to VHD builds

---

pkg/api/common/versions.go

chore: enable Kubernetes v1.23.13 on Azure Stack Hub

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3532.221102.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3532.221102.txt

releasing new Windows vhds

---

.github/workflows/test-cluster-config.yaml

This PR allows user-configurable test cleanup when runing cluster tests.
**Notes**:

ci: enable configurable test cleanup

---

.github/workflows/create-release-branch.yaml
.github/workflows/release.yaml
examples/kubernetes-gpu/kubernetes.json

This PR updates the VM SKU that we use to test GPU workloads to `Standard_NV12s_v3`. This is to unblock of the `515.65.01` nvidia drivers version.
**Notes**:

ci: update gpu test SKU

---

.github/workflows/generate-azure-consts.yaml

Recent const generation automation suggests this process is broken since the update to golang 1.17. Because AKS Engine is deprecated let's disable this ongoing functionality and stick with the current, static set of allowed values until we find out we need to update things.
**Notes**:

ci: disable regular const generation

---

.github/workflows/release.yaml

The latest automated release didn't pick up the tag value when producing the binary, let's invoke `make dist` directly without using a docker run.
**Notes**:

cu: run make dist without go-dev container

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1247
**Notes**:

feat: add support for Kubernetes v1.24.8

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

chore: enable v1.23.14 & v1.22.16 on Azure Stack Hub

---

docs/topics/azure-stack.md

The limit of FE IPs on ASH was increased a long time ago. Removing stale documentation.
**Notes**:

docs: remove Basic LB known issue from ASH doc page

---

vhd/packer/configure-windows-vhd.ps1
vhd/packer/windows-2019-vars.json

Updating the Windows VHDs to the latest patches + enabling some fixes that are gated behind registry keys
These changes are in AKS VHDss - https://github.com/Azure/AgentBaker/blob/ddbf61e7f6f42a0606e8c00b798b08315b32fd04/vhdbuilder/packer/configure-windows-vhd.ps1#L400-L416
**Notes**:

feat: Updating Windows VHD builds to use 2022 11B images and setting reg keys to enable to fixes

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3650.221213.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3650.221213.txt

chore: Updating default Windows VHDs for to include 11B HNS fixes

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1248
**Notes**:

feat: add support for Kubernetes v1.24.9

---

vhd/packer/windows-2019-vars.json

Updating Windows VHD packer job to use Jan 2023 patches
**Notes**:

chore: Updating Windows VHD packer job to use Jan 2023 patches

---

examples/kubernetes-releases/kubernetes1.24.json

This PR updates the 1.24 example api model so that it explicitly declares containerd, a 1.24+ Kubernetes requirement.
Fixes #5039 
**Notes**:

update 1.24 example api model to use containerd

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3887.230110.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3887.230110.txt

chore: updating default windows images - Jan 2023

---

pkg/api/common/helper.go

chore: add A10 GPUs as Nvidia GPUs
Allow A10 GPUs to be treated as Nvidia GPUs.
**Notes**:

chore: add A10 GPUs as Nvidia GPUs

---

pkg/api/common/const.go
pkg/api/common/versions.go

Add 1.23.15 and 1.24.9 on Azure Stack Hub
**Notes**:

chore: enable v1.23.15 & v1.24.9 on Azure Stack Hub

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v1249
**Notes**:

feat: add support for Kubernetes v1.24.10

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3887.230209.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3887.230209.txt

chore: updating Windows VHDs

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v12410
**Notes**:

feat: add support for Kubernetes v1.24.11

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.3887.230306.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.3887.230306.txt

chore: Windows VHDs for March 2023

---

vhd/packer/windows-2019-vars.json

chore: Updating Windows VHD base image to include April 2023 security updates

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.4252.230404.txt
vhd/release-notes/aks-windows/2019-datacenter-core-smalldisk-17763.4252.230414.txt

chore: Updating Windows references for April 2023

---

pkg/api/const.go
vhd/packer/install-dependencies.sh

Bump Azure CNI version to v1.4.39.1

---

pkg/api/common/versions.go
vhd/packer/configure-windows-vhd.ps1
vhd/packer/install-dependencies.sh

See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#changelog-since-v12416
**Notes**:

feat: add support for Kubernetes v1.24.17

---

pkg/api/azenvtypes.go
vhd/release-notes/aks-windows-2019-containerd/2019-datacenter-core-ctrd-17763.4252.230828.txt

chore: use Aug 2023 Windows VHDs

---

releases/CHANGELOG-v0.79.0.md

Add CHANGELOG for upcoming v0.79.0 release

release: v0.79.0 CHANGELOG

---

releases/CHANGELOG-v0.79.0.md

Thanks to all the contributors over the years!

Thanks to all the contributors!
